- packages/cypress/src/integration/howto/read.spec.ts
- src/pages/Howto/Content/HowtoList/HowToCard.tsx
PR Checklist
PR Type
Fixes nesting of elements so that the Username anchor is not nested within a link to the How to item. 
Example of the error logged to the browser console:
> fix: nesting of anchor links

- functions/src/Integrations/firebase-discord.ts
PR Checklist
PR Type
Fixes event accepted firebase discord hook function that was erroring when run.
Closes #
---
> fix: notify event accepted discord hook error

- functions/src/emailNotifications/createEmail.spec.ts
- functions/src/emailNotifications/createEmail.ts
- functions/src/emailNotifications/pk-template.handlebars
- functions/src/emailNotifications/pp-template.handlebars
PR Checklist
PR Type
i was mistakenly using the display name in the url slug instead of the user name. this fixes the issue and updates templates and tests. 
steps to deploy:
Closes #2363 
---
> fix(emails): use userName in links

- CONTRIBUTING.md
PR Checklist
PR Type
Updated the "Join us on Discord" link to a current Discord invite link found [here](https://onearmy.github.io/community-platform/Contributing/start-contributing). 
No current issue open for this.
> fix(docs): updates to the CONTRIBUTING document

- src/pages/common/Header/Menu/Logo/Logo.tsx
PR Checklist
PR Type
Closes #2307
> fix: remove use of theme from logo

- packages/components/src/ImageGallery/ImageGallery.test.tsx
- packages/components/src/ImageGallery/ImageGallery.tsx
- packages/components/src/ResearchEditorOverview/__snapshots__/ResearchEditorOverview.test.tsx.snap
- packages/components/src/tests/utils.tsx
PR Checklist
PR Type
- fix: gracefully fail on undefined/empty props
- chore: snapshot update
- chore: formating
> fix: handling of nullish/undefined props

- src/pages/Settings/content/formSections/ChangeEmail.form.tsx
- src/pages/Settings/content/formSections/ChangePassword.form.tsx
PR Checklist
PR Type
Closes #2308 #2303
> fix: remove use of theme from ChangePassword.form & ChangeEmail.form

- src/pages/Research/Content/ResearchArticle.test.tsx
- src/pages/Research/Content/ResearchArticle.tsx
- src/pages/Research/Content/ResearchDescription.tsx
PR Checklist
PR Type
Adds research contributors to the research description (top of the research article).
Closes #
---
> feat: add contributors to research description

- src/pages/Settings/content/formSections/Workspace.section.tsx
PR Checklist
PR Type
Closes #2309
> refactor: Remove direct usage of Theme from "Workspace.section.tsx"

- src/utils/helpers.test.ts
- src/utils/helpers.ts
PR Checklist
PR Type
Removes a few unused methods and introduces tests for a few used ones. 
---
> chore: remove unused and add tests

- functions/scripts/start.ts
PR Checklist
PR Type
programatically -> programmatically
Closes #
---
> fix: typo in start.ts

- src/pages/Howto/Content/HowtoList/HowToCard.tsx
- src/pages/Howto/Content/HowtoList/HowtoList.tsx
- src/pages/Howto/Content/HowtoList/SortSelect.tsx
- src/stores/Howto/howto.store.test.ts
- src/stores/Howto/howto.store.tsx
- src/test/factories/Howto.ts
PR Checklist
PR Type
- Fixes how-to most useful sort
- Fixes display of useful count on how-to list for cards with long title
Closes #
---
> fix: how-to most useful sort

- packages/components/src/GlobalStyles/GlobalStyles.tsx
- packages/themes/src/common/colors.ts
- packages/themes/src/types/index.ts
- src/common/AuthWrapper.tsx
- src/pages/common/Header/Header.tsx
PR Checklist
PR Type
- Adds border around beta features protected with an AuthWrapper
- Adds 'BETA' icon to header for users with beta-tester role
Closes #
https://github.com/ONEARMY/community-platform/assets/80723794/dd07d62e-c26a-4ff4-9868-9a50e46e82d5
---
> feat: add highlighting of beta features for users with beta-tester role

- src/pages/Research/Content/ResearchListItem.tsx
- src/pages/common/Header/Menu/Profile/ProfileButtons.tsx
PR Checklist
PR Type
Implemented the feedback given on implemented PRs
https://github.com/ONEARMY/community-platform/pull/2448#discussion_r1238351918
https://github.com/ONEARMY/community-platform/pull/2454#issuecomment-1604054969
> chore: font size fixed and cleaned the unnecessary comments

- src/modules/admin/pages/adminApprovals.tsx
- src/pages/Events/Content/EventsCreate/EventsCreate.tsx
- src/pages/Howto/Content/Common/Howto.form.tsx
- src/pages/Howto/Content/Common/HowtoStep.form.tsx
- src/pages/Settings/SettingsPage.tsx
- src/pages/Settings/content/formSections/MemberMapPin.section.tsx
- src/pages/Settings/content/formSections/UserInfos.section.tsx
- src/pages/Settings/content/formSections/WorkspaceMapPin.section.tsx
- src/pages/common/Layout/Main.tsx
PR Checklist
PR Type
I try to remove as many direct usage of Theme as possible
Closes #2294
Closes #2301 
Closes #2290
Closes #2299
> [refactor] Remove direct usage of Theme

- src/modules/admin/admin.routes.tsx
- src/modules/admin/pages/__tests__/adminTags.test.tsx
- src/modules/admin/pages/adminTags.tsx
PR Checklist
PR Type
Add tag viewing/adding/updating to the `/admin_v2` screen
Handles half of #2321 - categories still need to be moved
> feature: add tags admin to admin_v2

- src/common/Form/ImageInput/ImageConverter.tsx
PR Checklist
PR Type
Closes #2288
> refactor: imageConverter general theme removed

- src/modules/admin/admin.routes.tsx
- src/modules/admin/pages/__tests__/adminCategories.test.tsx
- src/modules/admin/pages/adminCategories.tsx
PR Checklist
PR Type
Add category viewing/adding/updating to the /admin_v2 screen
https://github.com/ONEARMY/community-platform/issues/2321
> feat: add categories admin to adminv2

- src/common/Form/ImageInput/ImageInput.tsx
PR Checklist
PR Type
This reverts commit b0fab811bf3d97286e1b5e2177537f6b324e6236.  Commit broke profile image upload in production so reverting and will look at refactor of theme use under a separate pr.
Closes #
---
> Revert "Merge pull request #2458 from jonboiser/fix-imageinput-styles"

- src/common/Form/ImageInput/ImageInput.tsx
PR Checklist
PR Type
Revises #2458 to work with dropzone. 
The proper fix was actually more complicated than just converting from styled components to theme-ui `Box` since one of the refactored components was intended as a dropzone target.
This PR fixes on the previous by wrapping `ImageInputWrapper` in a `React.forwardRef`, in order to receive the `rootRef` value from Dropzone.
cc @AlfonsoGhislieri who reviewed this the first time.
Closes #2285 
Dropzone overlay now appears properly, when clicking the button, and drag-dropping items.
And uploaded photos appear as previews
---
If the PR is working as intended it'll be merged and included in the next …
> refactor: remove direct usage of Theme from "ImageInput.tsx" (works with dropzone)

- packages/components/src/MapMemberCard/MapMemberCard.stories.tsx
- packages/components/src/MapMemberCard/MapMemberCard.tsx
- src/models/maps.models.tsx
- src/pages/Maps/Content/View/Popup.tsx
- src/stores/Maps/generatePins.tsx
- src/stores/Maps/maps.store.ts
- fix: remove last active from Map Pin
- fix: remove last active from Map pin
PR Checklist
PR Type
Closes #
---
> fix: remove last active from map pin

- packages/cypress/src/support/db/firebase.ts
- packages/cypress/src/support/hooks.ts
PR Checklist
PR Type
Closes #
---
> test: remove generated ids

- packages/cypress/src/integration/profile.spec.ts
- src/pages/User/content/UserCreatedDocumentsItem.tsx
PR Checklist
PR Type
This *partially* adds the coverage for changes added in #2428. 
Begins to close #2443
> [test] Coverage for display of how-to and research on member profile

- src/pages/User/content/SpaceProfile.tsx
PR Checklist
PR Type
Remove direct usage of Theme from "SpaceProfile.tsx".
Closes #2297
> [refactor] Remove direct usage of Theme from "SpaceProfile.tsx"

- src/pages/Howto/Content/Howto/HowtoDescription/HowtoDescription.tsx
- src/pages/Research/Content/ResearchDescription.tsx
PR Checklist
PR Type
Adds publish date to how to's
Closes #
---
> feat: add how to publish date

- packages/themes/src/fixing-fashion/styles.ts
PR Checklist
PR Type
Closes #
---
> fix: align ff brand guidelines

- src/pages/Howto/Content/Common/Howto.form.tsx
PR Checklist
PR Type
Adds additional css properties so that sticky display position works and the section highlighted in red stays on screen once the user begins to scroll down the page.
Closes #
---
> fix: make howto guidelines and publish buttons sticky on desktop

- src/stores/User/notifications.store.ts
PR Checklist
PR Type
Adds comment clarifying why we have not refactored userId property which is being updated using a userName property
Closes #
---
> chore: add comment clarifying why userId property has not been refactored

- src/pages/common/Header/Menu/MenuMobile/MenuMobilePanel.tsx
PR Checklist
PR Type
Remove direct usage of Theme from "MenuMobilePanel.tsx".
Closes #2298
> refactor: drop theme and emotion from menu mobile panel

- packages/documentation/docs/Backend Development/firebase-emulators-docker.md
PR Checklist
PR Type
Small update to make it easier to discover more about running functions within an Emulator context.
> docs: add link through to firebase emulator docs

- packages/documentation/docusaurus.config.gh-pages.js
PR Checklist
PR Type
Addresses the following
> docs: update base path and URL to match docs.platform.onearmy.earth

- functions/src/emailNotifications/__snapshots__/createNotificationEmails.spec.ts.snap
- functions/src/emailNotifications/createNotificationEmails.spec.ts
- functions/src/emailNotifications/utils.ts
PR Checklist
PR Type
Follow notifications have been integrated into the platform but not emails. this PR adds code to handle follow notifications in emails. 
Closes #2364 
---
> feat(emails): add follow notifications to emails

- packages/documentation/static/CNAME
PR Checklist
PR Type
Persist CNAME as one of the static assets, this will ensure it is available in the build directory which is moved during deployment to the `gh-pages`. 
Reference: https://stackoverflow.com/questions/53080767/docusaurus-cname-file-is-deleted-after-each-build
> docs: add CNAME record to specific domain

- package.json
- yarn.lock
PR Checklist
PR Type
Removes unused `react-portal` dependency which is only used in the components workspace.
> chore(deps): drop unused react-portal

- package.json
- yarn.lock
PR Checklist
PR Type
Removes unused `cheerio` dependency which is only used in the scripts workspace.
> chore(deps): drop unused cheerio

- package.json
- yarn.lock
PR Checklist
PR Type
Removes unused `sass` dependency.
> chore(deps): drop unused sass

- functions/src/emailNotifications/__snapshots__/createNotificationEmails.spec.ts.snap
- functions/src/emailNotifications/getNotificationEmailTemplate.ts
PR Checklist
PR Type
after we moved off of the email templates in #2507, @davehakkens noticed weird formatting of emails
after some googling i learned that gmail (and other email providers) support a [select number of CSS properties](https://designmodo.com/html-css-emails/) and sometimes react strangely to unsupported CSS. for example, i was using flexbox to center content, which is not supported by gmail. google must've handled this behind the scenes somehow when we were using their firebase template method. 
i updated the HTML to maintain the styling.
Closes #
web:
mobile:
(dark mode not ideal but acceptable for now)
---
If the PR is working as …
> fix(emails): update email styling to be compatible with gmail

- functions/scripts/runtimeConfig/model.ts
- functions/src/alerting/errorAlerting.ts
- functions/src/config/config.ts
- functions/src/emailNotifications/createNotificationEmails.ts
- functions/src/emailNotifications/index.ts
PR Checklist
PR Type
this PR adds discord error alerting for the email notification serverless functions. this will help with the maintenance of these functions and sets a pattern for future function alerting. 
Closes #
tested by deploying to development and the integration worked as expected 
once deployed to master i will set the discord webhook config var in all prod environments  …
> feat(alerts): add error alerting to emails

- functions/src/emailNotifications/__snapshots__/createNotificationEmails.spec.ts.snap
- functions/src/emailNotifications/getNotificationEmailTemplate.ts
PR Checklist
PR Type
updated style for email to match mocks by @davehakkens 
Closes #
desktop
mobile/darkmode
---
> feat: apply new styling to emails

- packages/themes/src/common/index.ts
- packages/themes/src/types/index.ts
- src/pages/Maps/Content/Controls/Controls.tsx
PR Checklist
PR Type
_removes the direct usage of the `theme` in the `Controls.tsx` file_
Closes #2293 
---
> refactor: remove direct usage of theme

- packages/components/src/FieldInput/FieldInput.tsx
PR Checklist
PR Type
Replace TextLimitIndicator in FieldInput with CharacterCount component
Closes #2598
---
> Add character count to field input

- src/pages/Howto/Content/Common/HowtoStep.form.tsx
PR Checklist
PR Type
Displays the character count also for each howto step title 
Closes #
---
> feat: add character count to howto step title

- src/stores/Maps/maps.store.test.ts
- src/stores/Maps/maps.store.ts
PR Checklist
PR Type
Adds support for new users when there is no Map Pin yet associated with the user. 
Original Report:
https://discord.com/channels/586676777334865928/1132066860725182534
> fix: creating map pins

- CONTRIBUTING.md
- packages/documentation/docs/Testing/overview.md
PR Checklist
PR Type
Updates testing overview on documentation website and removes some duplicate information in GitHub Contributing guidelines.  
Partial fix #2646
> docs: update testing information

- packages/components/src/FieldTextarea/FieldTextarea.tsx
- packages/cypress/src/integration/howto/write.spec.ts
- packages/cypress/src/integration/research/write.spec.ts
- src/pages/Howto/Content/Common/Howto.form.test.tsx
- src/pages/Howto/Content/Common/Howto.form.tsx
- src/pages/Howto/Content/Common/HowtoStep.form.tsx
- src/pages/Research/Content/Common/Research.form.tsx
- src/pages/Research/Content/Common/ResearchUpdate.form.tsx
- src/pages/Research/constants.ts
- src/utils/validators.ts
PR Checklist
PR Type
Adds the character counter for all the fields that should have it and implements custom validators to enforce them and give correct errors to the user.
Closes #2655
---
> Fix: implement validation and error messages for form field lengths

- packages/components/src/MapMemberCard/MapMemberCard.stories.tsx
- packages/components/src/MapMemberCard/MapMemberCard.tsx
- packages/cypress/src/integration/map.spec.ts
- src/pages/Maps/Content/View/Popup.tsx
- src/stores/Maps/maps.store.ts
PR Checklist
PR Type
Removes moderation button from Map Pin cards.
Closes #2546
> feat: remove moderation flow from Map Pins

- src/models/maps.models.tsx
PR Checklist
PR Type
As part of #2543 a new moderation status was introduced
for Map Pins. This value is not yet available for other
content types so splitting from the common definition.
> chore: refactor to include etended moderation status

- packages/cypress/src/integration/howto/read.spec.ts
- packages/cypress/src/integration/research/read.spec.ts
- shared/mocks/data/howtos.ts
- shared/mocks/data/research.ts
- src/models/common.models.tsx
- src/models/howto.models.tsx
- src/models/maps.models.tsx
- src/models/research.models.tsx
- src/pages/Howto/Content/EditHowto/EditHowto.tsx
- src/pages/Howto/Content/Howto/Howto.tsx
- src/pages/Howto/Content/Howto/HowtoDescription/HowtoDescription.tsx
- src/pages/Research/Content/CreateUpdate/index.tsx
- src/pages/Research/Content/EditResearch/index.tsx
- src/pages/Research/Content/EditUpdate/index.tsx
- src/pages/Research/Content/ResearchArticle.tsx
- src/pages/Research/Content/ResearchDescription.tsx
- src/stores/Howto/howto.store.test.ts
- src/stores/Howto/howto.store.tsx
- src/stores/Maps/maps.store.ts
- src/stores/Research/research.store.test.ts
- src/stores/Research/research.store.tsx
- src/utils/helpers.test.ts
- src/utils/helpers.ts
PR Checklist
PR Type
Builds on the work from @KungRaseri to make it possible for users to Delete their Research and How to items.
Closes #2391
---
> feat: 2391 allow users to delete content

- packages/components/src/Select/Select.tsx
PR Checklist
PR Type
Adds `cursor: pointer` to both content (default label/value) and options of `oa-components/Select` component. This new behavior can be easily seen on the filter and order dropdowns of  `/research` and `/how-to`. 
Closes #2665
---
> fix: Select: add "cursor pointer" behavior to component content and its options

- src/common/Form/FieldContainer.ts
PR Checklist
PR Type
_removes unused theme from fieldcontainer.ts_
Closes #2289 
---
> refactor: remove unused styled component

- src/common/Form/ImageInput/ImageInput.tsx
PR Checklist
PR Type
Adds a background colour to the delete button so it's possible for users to read the text.
Closes #2699
> fix: add background to imageinput for ux

- commitlint.config.ts
PR Checklist
PR Type
for some reason we've started getting the following error in [Circle CI builds: ](https://app.circleci.com/pipelines/github/ONEARMY/community-platform/5891/workflows/59757a07-b416-43be-9a57-eedc1190d5a0/jobs/44654)
```
/home/circleci/project/commitlint.format.ts:1
import type { Formatter, FormattableReport } from '@commitlint/types'
^^^^^^
SyntaxError: Cannot use import statement outside a module
at internalCompileFunction (node:internal/vm:74:18)
at wrapSafe (node:internal/modules/cjs/loader:1141:20)
at Module._compile (node:internal/modules/cjs/loader:1182:27)
at Module._extensions..js (node:internal/modules/cjs/loader:1272:10)
at Module.load (node:internal/modules/cjs/loader:1081:32)
at Module._load (node:internal/modules/cjs/loader:922:12)
at Module.require …
```
> fix: remove custom formatter

- package.json
- packages/cypress/src/integration/howto/write.spec.ts
- src/common/Form/ImageInput.field.tsx
- src/common/Form/ImageInput/ImageInput.tsx
- src/pages/Howto/Content/Common/HowtoStep.form.tsx
- src/pages/Howto/Content/Common/howtostep.form.test.tsx
- yarn.lock
PR Checklist
PR Type
This adds unit tests for the how-to step form and drops the same testing from the e2e tests (and a couple of performance tweaks), thus speeding up the test suite significantly. On the old machine I'm using, the unit tests add 11 seconds and the e2e removals saves 8 minutes(!)
Part of #2671
> refactor: optimise howto tests

- src/common/Form/ErrorsContainer.test.tsx
- src/common/Form/ErrorsContainer.tsx
- src/common/Form/labels.ts
PR Checklist
PR Type
This is a generic errors component doing all the presentational lifting for the error components that are about to be created for the how-to, research and user settings forms.
Part of #2684
> feat: add generic error rendering component

- .circleci/config.yml
- packages/security-rules/package.json
- yarn.lock
PR Checklist
PR Type
- chore(deps): explicitly add dotenv
- chore(ci): verify security rules in CI
> chore(ci): verify security rules 

- src/pages/Howto/Content/Common/Howto.form.test.tsx
- src/pages/Howto/Content/Common/HowtoFieldTitle.tsx
- src/pages/Research/Content/Common/Research.form.tsx
- src/pages/Research/Content/Common/ResearchUpdate.form.tsx
- src/stores/common/module.store.test.tsx
- src/stores/common/module.store.ts
- src/utils/validators.test.ts
- src/utils/validators.ts
PR Checklist
PR Type
This merge request adds a couple of unit tests and makes small improvements to the code.
Expands on #2315
---
> refactor: remove unnecessary argument and add unit tests

- src/pages/Howto/Content/HowtoList/HowToCard.tsx
- src/pages/Research/Content/ResearchListItem.tsx
PR Checklist
PR Type
Adds tooltips to the research page 
Closes #2728
---
> feat: add tooltips to research and howto cards

- packages/cypress/src/integration/howto/write.spec.ts
- src/common/Form/ErrorsContainer.tsx
- src/common/Form/types.ts
- src/pages/Howto/Content/Common/Howto.form.tsx
- src/pages/Howto/Content/Common/HowtoErrors.test.tsx
- src/pages/Howto/Content/Common/HowtoErrors.tsx
- src/pages/Howto/Content/Common/HowtoFieldFileLink.tsx
- src/pages/Howto/Content/Common/HowtoFieldFileUpload.tsx
- src/pages/Howto/Content/Common/HowtoFieldFiles.tsx
- src/pages/Howto/Content/Common/HowtoFieldStep.tsx
- src/pages/Howto/Content/Common/HowtoFieldStepsContainer.tsx
- src/pages/Howto/Content/Common/HowtoFieldTags.tsx
- src/pages/Howto/Content/Common/index.ts
- src/pages/Howto/Content/Common/utils/index.ts
- src/pages/Howto/Content/Common/utils/transformHowtoErrors.test.ts
- src/pages/Howto/Content/Common/utils/transformHowtoErrors.ts
- src/pages/Howto/labels.ts
PR Checklist
PR Type
Building off #2717 and #2707(!), this adds an error component to the how-to form.
Part of #2684.
> feat: add errors to how-to

- src/pages/common/SortFilterHeader/SortFilterHeader.tsx
- src/stores/Howto/howto.store.test.ts
- src/stores/Howto/howto.store.tsx
- src/stores/Research/research.store.tsx
PR Checklist
PR Type
Pushes the logic for the default sorting values for the research and howto list pages into the stores .
Closes #
---
> refactor: move default sorting filter logic to store

- packages/components/src/ResearchEditorOverview/ResearchEditorOverview.tsx
- packages/components/src/ResearchEditorOverview/__snapshots__/ResearchEditorOverview.test.tsx.snap
- packages/cypress/src/integration/research/write.spec.ts
- src/pages/Research/Content/Common/Research.form.tsx
- src/pages/Research/Content/Common/ResearchErrors.test.tsx
- src/pages/Research/Content/Common/ResearchErrors.tsx
- src/pages/Research/Content/Common/ResearchUpdate.form.tsx
- src/pages/Research/Content/Common/index.ts
- src/pages/Research/labels.ts
- src/test/components/ResearchProvider.tsx
- src/test/components/index.ts
PR Checklist
PR Type
Building off #2717, this adds an errors component to the research forms. It also adds a full e2e test for research updates, which was missing from the suite.
Part of #2684.
> feat: add errors to research

- packages/components/src/MapWithDraggablePin/MapWithDraggablePin.tsx
- packages/themes/src/common/index.ts
- src/pages/Settings/content/formSections/UserInfos.section.tsx
PR Checklist
PR Type
* Introduces new info variant for Alert component.
* Refactors existing instances from Settings area to use component.
> feat: introduce info Alert variant

- packages/components/src/ImageGallery/ImageGallery.test.tsx
- packages/components/src/ImageGallery/ImageGallery.tsx
PR Checklist
PR Type
Introduces tests for the ImageGallery component.
Note. Aside from asserting the Lightbox component appears we are not verifying its state is being managed.
> fix: adds tests for ImageGallery component

- packages/cypress/src/integration/howto/read.spec.ts
- src/stores/Howto/howto.store.tsx
- src/stores/Research/research.store.tsx
- src/stores/common/FilterSorterDecorator/FilterSorterDecorator.ts
- src/stores/common/FilterSorterDecorator/FitlerSorterDecorator.test.ts
PR Checklist
PR Type
Pins a users howtos to the top of the howto list if they are a draft/rejected/awaiting-moderation
Closes #
---
> feat: pin user howtos that require moderation/draft

- packages/cypress/src/integration/howto/read.spec.ts
- packages/cypress/src/integration/research/read.spec.ts
- src/pages/Howto/Content/Howto/HowtoDescription/HowtoDescription.tsx
- src/pages/Research/Content/ResearchDescription.tsx
PR Checklist
PR Type
Closes #2774 
---
> feat: remove back button from descriptions

- src/pages/Howto/Content/Howto/Step/Step.tsx
PR Checklist
PR Type
Closes https://github.com/ONEARMY/community-platform/issues/2763
Based on the work from #2785
> 2763 how to text overflow

- packages/cypress/src/integration/settings.spec.ts
- src/pages/Settings/SettingsPage.tsx
- src/pages/Settings/constants.ts
- src/pages/Settings/content/formSections/AccountSettings.section.tsx
- src/pages/Settings/content/formSections/ChangeEmail.form.tsx
- src/pages/Settings/content/formSections/ChangePassword.form.tsx
- src/pages/Settings/content/formSections/Collection.section.tsx
- src/pages/Settings/content/formSections/EmailNotifications.section.tsx
- src/pages/Settings/content/formSections/Expertise.section.tsx
- src/pages/Settings/content/formSections/Fields/ProfileLink.field.tsx
- src/pages/Settings/content/formSections/Focus.section.tsx
- src/pages/Settings/content/formSections/MemberMapPin.section.tsx
- src/pages/Settings/content/formSections/SettingsError.test.tsx
- src/pages/Settings/content/formSections/SettingsErrors.tsx
- src/pages/Settings/content/formSections/UserInfos.section.tsx
- src/pages/Settings/content/formSections/Workspace.section.tsx
- src/pages/Settings/content/formSections/WorkspaceMapPin.section.tsx
- src/pages/Settings/labels.ts
- src/test/components/SettingsProvider.tsx
- src/test/components/index.ts
PR Checklist
PR Type
Building off #2717, this adds the errors component to the user settings form
Part of #2684
> feat: add errors to user settings

- functions/src/alerting/errorAlerting.spec.ts
- functions/src/alerting/errorAlerting.ts
PR Checklist
PR Type
error alerting channel notified me that an error was being thrown from the email functions
although the alert wasn't extremely helpful (something to work on) it led me to this error
where i realized i did break something in https://github.com/ONEARMY/community-platform/pull/2790
here i fix the offending line of code and add more testing 😇 
Closes #
--- …
> fix: fix error alerting and add test

- functions/src/emailNotifications/__snapshots__/createModerationEmails.spec.ts.snap
- functions/src/emailNotifications/constants.ts
- functions/src/emailNotifications/createModerationEmails.spec.ts
- functions/src/emailNotifications/createModerationEmails.ts
- functions/src/emailNotifications/index.ts
- functions/src/emailNotifications/templates.ts
- functions/src/emailNotifications/utils.ts
- functions/src/emulator/seed/content-generate.ts
PR Checklist
PR Type
see #2791 for the first PR in this stack
depends on #2790 
**This PR (2)**
- trigger this function on moderation status change
- add template and styles for the how to approval email
- add testing for the flow
**PR 3**
- add templates and functions for how to rejected email, map pin approval email, and map pin rejected email
**future work**
- add PP custom footer (see issue)
- add emails for submitted resources
- add emails for research
#2379 
here is a rendering of the how-to approval email:
---
If the PR is working as intended it'll be merged and included in the next platform release, if not changes will be requested and …
> feat(emails): send howto approval email on moderation update

- functions/src/emailNotifications/__snapshots__/createModerationEmails.spec.ts.snap
- functions/src/emailNotifications/__snapshots__/createSubmissionEmails.spec.ts.snap
- functions/src/emailNotifications/createModerationEmails.spec.ts
- functions/src/emailNotifications/createModerationEmails.ts
- functions/src/emailNotifications/createSubmissionEmails.spec.ts
- functions/src/emailNotifications/createSubmissionEmails.ts
- functions/src/emailNotifications/index.ts
- functions/src/emailNotifications/templates.ts
- functions/src/emailNotifications/utils.ts
PR Checklist
PR Type
This PR builds on #2792 to add the following emails:
- map pin approval
- how to submission
- map pin submission
**future work**
- add emails for rejected resources
- integrate moderation feedback work  
- add emails for research
#2379
new templates:
---
> feat(emails): add map pin approval email, submission emails

- README.md
PR Checklist
PR Type
Closes #
---
> docs: corrected good-first-issue link in README

- packages/cypress/package.json
PR Checklist
PR Type
This comments have been stating to-do for 2 years. It seems reasonable
to assume that we shall not be doing them in the near future.
> chore: remove todo comments

- functions/package.json
- functions/src/emailNotifications/README.md
- functions/src/emailNotifications/development/entry-server.mjs
- functions/src/emailNotifications/development/index.html
- functions/src/emailNotifications/development/server.mjs
- functions/src/emailNotifications/index.ts
- functions/src/emailNotifications/supporterBadgeEmails.spec.ts
- functions/src/emailNotifications/supporterBadgeEmails.ts
- functions/src/emailNotifications/templates.ts
- functions/src/emailNotifications/templates/index.ts
- functions/src/emailNotifications/templates/layout.html
- functions/src/emailNotifications/templates/supporter-badge-added.html
- functions/src/emailNotifications/templates/supporter-badge-removed.html
- functions/src/emailNotifications/utils.ts
- yarn.lock
PR Checklist
PR Type
Adds email notification when supporter badge is added or removed.
- feat: adds email notification when supporter badge added/removed
- feat(emails): load HTML template
- chore: add local server for rendering
- feat: move supporter-badge-added to hbs template
- chore(email): add title to preview app
- fix: attempt to override some type warnings
Partial fix #2688
--- …
> feat: email notifications for supporter badge

- packages/cypress/src/integration/howto/write.spec.ts
- shared/mocks/data/categories.ts
- src/pages/Howto/Content/Common/Howto.form.tsx
- src/pages/Howto/Content/Common/HowtoCategoryGuidance.test.tsx
- src/pages/Howto/Content/Common/HowtoCategoryGuidance.tsx
- src/pages/Howto/Content/Common/HowtoFieldCategory.tsx
- src/pages/Howto/Content/Common/HowtoFieldFiles.test.tsx
- src/pages/Howto/Content/Common/HowtoFieldFiles.tsx
- src/pages/Howto/Content/Common/index.ts
- src/pages/Howto/labels.ts
- src/test/factories/Category.ts
PR Checklist
PR Type
This adds guidance for the user on certain how-to categories in which additional context is provided.
Closes #2683
> add guidance to howto form

- functions/src/emailNotifications/createModerationEmails.spec.ts
- functions/src/emailNotifications/createModerationEmails.ts
- functions/src/emailNotifications/development/entry-server.mjs
- functions/src/emailNotifications/templates.ts
- functions/src/emailNotifications/templates/how-to-rejected.html
- functions/src/emailNotifications/templates/index.ts
- functions/src/emailNotifications/templates/map-pin-rejected.html
PR Checklist
PR Type
this PR adds transactional emails for rejected map pins and how-tos
Closes #
---
> feat(emails): add rejected emails for map pin and how to

- packages/components/src/MapMemberCard/MapMemberCard.stories.tsx
- packages/components/src/MapMemberCard/MapMemberCard.test.tsx
- packages/components/src/MapMemberCard/MapMemberCard.tsx
- src/pages/Maps/Content/View/Popup.tsx
PR Checklist
PR Type
* Display moderation comments on MapMemberCard
* Adds component tests for MapMemberCard
Closes #2668
> feat(components): display moderation comments on MapMemberCard

- CONTRIBUTING.md
- packages/documentation/docs/Testing/overview.md
PR Checklist
PR Type
Closes #
---
> docs: update guidance around testing

- functions/src/emailNotifications/index.ts
- functions/src/emailNotifications/templates.ts
- functions/src/emailNotifications/templates/index.ts
- functions/src/emailNotifications/templates/verified-badge-added.html
- functions/src/emailNotifications/verifiedBadgeEmails.spec.ts
- functions/src/emailNotifications/verifiedBadgeEmails.ts
PR Checklist
PR Type
Closes #2688
> feat: adds email notification when verified badge added

- functions/src/emailNotifications/createModerationEmails.spec.ts
- functions/src/emailNotifications/createModerationEmails.ts
- functions/src/emailNotifications/development/entry-server.mjs
- functions/src/emailNotifications/templates.ts
- functions/src/emailNotifications/templates/how-to-needs-improvements.html
- functions/src/emailNotifications/templates/index.ts
- functions/src/emailNotifications/templates/map-pin-needs-improvements.html
PR Checklist
PR Type
adds needs improvements transactional emails with moderator comments
will wait to merge until #2820 
Closes #2668
---
> feat(emails): needs improvements emails

- functions/src/emailNotifications/templates/index.ts
- functions/src/emailNotifications/templates/templates.spec.ts
PR Checklist
PR Type
as discussed in https://github.com/ONEARMY/community-platform/pull/2842#discussion_r1341964565
Closes #
---
> test: add error handling and testing for getEmailTemplate

- functions/src/emailNotifications/createModerationEmails.ts
- functions/src/emailNotifications/index.ts
- functions/src/emailNotifications/templates/index.ts
- functions/src/emailNotifications/utils.ts
PR Checklist
PR Type
saw this error pop up while testing, so bumped the moderation email mem limit
also saw that i was not using the same path convention in #2844, so i updated to be consistent
would like this to merge before next release
Closes #
---
If you need more immediate feedback you can try reaching out on Discord in the [Community Platform `development` channel](https://discord.com/channels/586676777334865928/9387817270175 …
> fix: memory and file path

- src/pages/Howto/Category/CategoriesSelect.tsx
- src/pages/common/SortFilterHeader/SortFilterHeader.tsx
- fix(platform): hides untouched selected option in filter and sort inputs
- chore: apply code formatting
PR Checklist
PR Type
Closes #
---
> fix: updated filter and sort inputs

- .circleci/config.yml
PR Checklist
PR Type
Skips Cypress install during Cloud Functions job
> chore: empty commit

- src/pages/SignUp/SignUp.tsx
- src/utils/helpers.ts
- src/utils/validators.test.ts
- src/utils/validators.ts
PR Checklist
PR Type
- Add a new `noSpecialCharacters` validator along with a `getSpecialCharacters` helper.
- Refactored the SignUp form to use the new validator via `composeValidators`.
Closes #2408 
I also tested the signup flow worked when using a display name without special characters and ran the SignUp Cypress tests locally.
> fix: prevent signup if username contains invalid characters

- functions/src/emailNotifications/development/entry-server.mjs
- functions/src/emailNotifications/development/server.mjs
- functions/src/emailNotifications/templates/index.ts
- functions/webpack.config.ts
PR Checklist
PR Type
After this change the bundle file structure is:
```
functions/dist
├── index.html
├── index.js
├── package.json
└── templates
├── how-to-needs-improvements.html
├── how-to-rejected.html
├── index.ts
├── layout.html
├── map-pin-needs-improvements.html
├── map-pin-rejected.html
├── supporter-badge-added.html
├── supporter-badge-removed.html
├── templates.spec.ts
└── verified-badge-added.html
```
> fix: copy templates directory to built bundle

- src/pages/UserSettings/content/formSections/MemberMapPin.section.tsx
PR Checklist
PR Type
Added visual character limit to map pin.
> feat: add visual character limit to map pin

- package.json
- yarn.lock
PR Checklist
PR Type
Removes unused deps
> chore(deps): remove unused react-table

- src/pages/Maps/Content/View/Sprites.tsx
- src/pages/Password/ForgotPassword.tsx
PR Checklist
PR Type
We should have been using the core logger module here.
> chore: remove usage of workbox

- package.json
- packages/components/package.json
- src/pages/SignUp/SignUp.tsx
- yarn.lock
> chore(deps): upgrade yup to v1.3.2

- yarn.lock
PR Checklist
PR Type
Upgrade caniuse to remove this warning when running locally
```
Browserslist: caniuse-lite is outdated. Please run:
npx update-browserslist-db@latest
Why you should do it regularly: https://github.com/browserslist/update-db#readme
```
> chore(deps): upgrade caniuse

- src/common/ScrollToTop.test.tsx
- src/common/ScrollToTop.tsx
- src/pages/index.tsx
PR Checklist
PR Type
Drop class based component in favour of functional.
> feat: refactor ScrollToTop and introduce tests

- functions/src/emailNotifications/createModerationEmails.spec.ts
- functions/src/emailNotifications/development/entry-server.mjs
- functions/src/emailNotifications/templates/how-to-needs-improvements.html
- functions/src/emailNotifications/templates/map-pin-needs-improvements.html
- src/stores/Howto/howto.store.tsx
PR Checklist
PR Type
right now, moderation comments for howtos are only available to add through the UI. this was added in [this scope of work.](https://github.com/ONEARMY/community-platform/issues/2377) when added, the comments are in this shape:
for map pins, feedback is added in retool and is a string populated in a `comments` field. we should migrate the feedback mechanism for how tos to also use retool (and also consider making it more consistent w map pins). i captured that in this issue: https://github.com/ONEARMY/community-platform/issues/2876
i updated the improvements needed template to accept and render feedback stored in this way on the howto object.
i also updated the moderation status to be `improvements-needed` when comments are present, rather than `rejected` as it was …
> fix(emails): typo and how to moderation comments

- functions/package.json
- yarn.lock
PR Checklist
PR Type
Attempting to upgrade the project to Node v20, bumped into the following limitation: 
https://github.com/firebase/firebase-tools/pull/5837
> fix(functions): upgrade firebase-tools@12.1.0

- src/pages/Research/Content/ResearchListItem.tsx
PR Checklist
PR Type
Before:
After:
> fix: research thumbnail size

- .github/pull_request_template.md
- BOUNTIES.md
- packages/documentation/docs/Contributing/start-contributing.md
PR Checklist
PR Type
Updates readme and other pages
Closes #2897
---
> clarify the monthly call is only for maintainers

- functions/package.json
- packages/security-rules/package.json
- yarn.lock
PR Checklist
PR Type
Bumps `firebase-tools` to the latest version https://github.com/firebase/firebase-tools/releases
> feat(dep): upgrade firebase-tools@12.6.2

- packages/components/scripts/templates/{componentName}.stories.tsx.mst
- packages/components/src/index.ts
PR Checklist
PR Type
Ran into bug when trying to generate a new component, story generation script was not up to date.
Edit: just saw an issue had been raised already by @thisislawatts 
Closes #2860
---
> fix: update story generation script

- packages/documentation/docs/Backend Development/firebase-emulators-docker.md
PR Checklist
PR Type
Closes #2530
---
> docs: add build command

- functions/src/logging/logging.ts
- package.json
- src/config/constants.ts
- src/logger/index.test.ts
- src/logger/index.ts
- src/pages/Howto/Content/Howto/HowToComments/HowToComments.tsx
- src/pages/Research/Content/ResearchComments/ResearchComments.tsx
- src/stores/Theme/theme.store.tsx
- yarn.lock
PR Checklist
PR Type
Introduce a functional logger for the client side context so we can aggregate usage information from users. This information can then be used in a variety of ways; including debugging, monitoring, and auditing.
One of the primary benefits of logging is that it can help developers debug software issues. When a problem occurs, logs can provide valuable information about what went wrong and why. This information can help developers identify and fix bugs more quickly and efficiently.
Logs can also be used to monitor the performance and health of a system. By analyzing log data, developers can identify trends and patterns that may indicate issues such as performance bottlenecks or security vulnerabilities. This information can be used to proactively address issues before …
> feat: adopt tslog

- package.json
- packages/components/package.json
- packages/documentation/docs/Frontend Development/overview.md
- src/pages/PageList.tsx
- src/pages/common/Header/Menu/Profile/ProfileButtonItem.tsx
- src/pages/common/Layout/Main.tsx
- yarn.lock
PR Checklist
PR Type
Removes styled-system
> chore(deps): remove styled-system

- packages/documentation/docs/Maintainers/Onboarding.md
PR Checklist
PR Type
@benfurber let me know if theres anything else you want to add after the call yesterday.
> docs: update onboarding steps for maintainer

- src/pages/UserSettings/labels.ts
- src/stores/User/user.store.test.tsx
- src/stores/User/user.store.ts
PR Checklist
- [x} - Commit [messages are descriptive](https://github.com/ONEARMY/community-platform/blob/master/CONTRIBUTING.md#--commit-style-guide), it will be used in our [Release Notes](https://github.com/ONEARMY/community-platform/releases/)
PR Type
here i set the default email setting to weekly and remove the beta wording from the frequency settings dropdown in the user profile.
i tested this by creating a new account and checking that the frequency was set to weekly. i also added a test for the `registerNewUser` function. 
Closes #2864
---
If the PR is working as intended it'll …
> chore: set default email frequency to weekly and remove beta wording

- .circleci/config.yml
- functions/package.json
PR Checklist
PR Type
We have reached 50% coverage for the `src` and `packages` directories, however we had no coverage being captured by the functions unit tests. Heres hoping this doesn't tank our overall coverage 🤞🏻 (obviously more coverage is _great_ in the longer term)
> chore: add coverage reports to functions

- shared/models/db.ts
- src/models/index.ts
- src/models/question.models.tsx
- src/modules/index.test.ts
- src/modules/index.ts
- src/pages/PageList.tsx
- src/pages/Question/QuestionCreate.tsx
- src/pages/Question/QuestionEdit.tsx
- src/pages/Question/QuestionListing.tsx
- src/pages/Question/QuestionPage.tsx
- src/pages/Question/QuestionSingle.tsx
- src/pages/Question/index.tsx
- src/pages/Question/question.routes.test.tsx
- src/pages/Question/question.routes.tsx
- src/stores/Question/question.store.test.tsx
- src/stores/Question/question.store.tsx
- src/stores/databaseV2/clients/dexie.tsx
- src/stores/index.tsx
- src/test/factories/Question.ts
PR Checklist
PR Type
Introduces router scaffolding for inbound Question module. The intention here is to establish the foundations and then divide the work across multiple tickets for parallelisation. For example:  Create, Edit, Commenting and display work.
This is being introduced as a standalone module. It will be enabled by default for any installs which **do not declare** the modules they use. As all production instances specify their modules with the `REACT_APP_SUPPORTED_MODULES` configuration option this means the new Questions module will not be "leaked" to public sites.
Placeholder Routes
#2859
> feat: adds question module

- .circleci/config.yml
- commitlint.config.js
PR Checklist
PR Type
Switch to published docker image for project for validating commits. Reduces execution time of `Lint commits` task in CI by 20%
> chore(ci): switch to commit lint image

- src/stores/Howto/howto.store.test.ts
- src/stores/Howto/howto.store.tsx
- src/stores/databaseV2/DocReference.tsx
PR Checklist
PR Type
Ensures any data from the existing document will be persisted to the document. 
Closes #2892
> fix: persist existing doc attributes when updating how-to

- functions/src/emailNotifications/createModerationEmails.spec.ts
- functions/src/emailNotifications/development/entry-server.mjs
- functions/src/emailNotifications/templates/how-to-needs-improvements.html
- functions/src/emailNotifications/templates/map-pin-needs-improvements.html
PR Checklist
- [ x - Commit [messages are descriptive](https://github.com/ONEARMY/community-platform/blob/master/CONTRIBUTING.md#--commit-style-guide), it will be used in our [Release Notes](https://github.com/ONEARMY/community-platform/releases/)
PR Type
per discord convo: 
> 1. put a feedback box in the how to retool moderation that writes to a field named moderatorFeedback. it will overwrite whatever is currently in this field. ✅
> 2. remove the feedback input and moderation buttons from CP ✅
> 3. rename the feedback field from comments to moderatorFeedback in the map pin schema for consistency (comments cannot be used in how tos because it is already used to hold the comments array)
> 4. update the map pin moderation UI to read from moderatorFeedback rather than comments
> 5. update …
> fix: use moderatorFeedback in emails

- src/stores/Howto/howto.store.test.ts
- src/stores/Howto/howto.store.tsx
- src/stores/Research/research.store.test.ts
- src/stores/common/incrementDocViewCount.tsx
PR Checklist
PR Type
Similar to https://github.com/ONEARMY/community-platform/pull/2943, moves logic spread across two stores into a reusable function. Note that this approach has been adopted to create composable features rather than adding as method to common store class which would introduce to _all_ derived stores.
> chore: refactor to use shared logic for incrementing view

- src/models/research.models.tsx
- src/stores/Howto/howto.store.test.ts
- src/stores/Howto/howto.store.tsx
- src/stores/Research/research.store.test.ts
- src/stores/Research/research.store.tsx
- src/stores/common/toggleDocUsefulByUser.ts
PR Checklist
PR Type
* Introduce some lower test coverage to verify toggleUseful behaviour.
* Refactor toggleUseful behaviour out to reusable function
> chore: introduce lower level test coverage for vote useful logic

- functions/src/emailNotifications/createModerationEmails.spec.ts
- functions/src/emailNotifications/createSubmissionEmails.spec.ts
- functions/src/emailNotifications/templates/how-to-needs-improvements.html
- functions/src/emailNotifications/templates/how-to-rejected.html
- functions/src/emailNotifications/templates/how-to-submission.html
- functions/src/emailNotifications/templates/map-pin-needs-improvements.html
PR Checklist
PR Type
final round of feedback before beta release! 
from discord: 
```
A few last commnets:
-> Would it be easy to have the comments we set to be in bold? just to make them stand out ?
-> could we have the URL of the HT/map pin in the emails? (as we have for the approval email) 
-> as for the map pin "needs improvements emails, could we include this?  apologies if it was not included in the inital template :/ 
(...)
Please review the following & re-submit your How-to:
retool comments
Make sure you also check the HT guidelines* to review our requirements.
Until you update your information, your HT will remain hidden from the community platform. We hope to see your edits soon, so we can get your HT online as soon as possible 🙂
We are looking forward to hearing back from you. …
```
> fix(transactional-emails): implement feedback

- functions/src/emailNotifications/createModerationEmails.spec.ts
- functions/src/emailNotifications/createModerationEmails.ts
- functions/src/emailNotifications/createSubmissionEmails.spec.ts
- functions/src/emailNotifications/createSubmissionEmails.ts
PR Checklist
PR Type
release transactional emails!
Closes #2861
---
> chore(transactional-emails): remove beta

- src/pages/Question/QuestionEdit.tsx
- src/pages/Question/QuestionPage.tsx
- src/pages/Question/question.routes.test.tsx
PR Checklist
PR Type
- feat: support admin edit
- feat: load Question from store
- feat: support updating items
- feat: add Edit button to individual Question pages
> feat: questions edit flow

- package.json
- yarn.lock
PR Checklist
PR Type
Upgrades library to address defect causing logger to throw Errors. Documented via: https://github.com/fullstack-build/tslog/issues/227
> fix(deps): upgrade ts-log@4.9.2

- packages/components/src/ContentStatistics/ContentStatistics.tsx
- packages/components/src/Icon/Icon.tsx
- packages/components/src/Icon/types.ts
PR Checklist
PR Type
- adds clickable more information component to ContentStatistics component
- adds FaChevronUp and FaChevronDown icons 
Closes #2735
> feat: add clickable more information component

- packages/cypress/src/integration/map.spec.ts
- shared/mocks/data/mappins.ts
- src/stores/Maps/maps.store.ts
PR Checklist
PR Type
Hides member pins on PP.
Closes #2927
> feat: hide member pins on pp only

- .circleci/config.yml
- functions/package.json
- functions/src/admin/getUserEmail.ts
- functions/src/emailNotifications/createModerationEmails.spec.ts
- functions/src/emailNotifications/createSubmissionEmails.spec.ts
- functions/src/emailNotifications/utils.ts
- functions/src/emulator/seed/content-generate.ts
PR Checklist
PR Type
see comments for detailed explanation of changes
tldr:
1. remove unnecessary DB writes in functions tests 
2. do not spin up extension emulator in testing
3. increase container memory in circle ci to avoid 137 OOM error
Closes #
--- …
> fix(emulators): fix functions tests

- .circleci/config.yml
PR Checklist
PR Type
Closes #
---
> test revert

- functions/src/emailNotifications/createSubmissionEmails.ts
- functions/src/emailNotifications/templates.ts
- packages/cypress/src/integration/profile.spec.ts
- src/pages/User/contact/UserContactFieldEmail.tsx
- src/pages/User/contact/UserContactForm.test.tsx
- src/pages/User/contact/UserContactForm.tsx
- src/pages/User/labels.ts
PR Checklist
PR Type
Fixes reported issues:
1. Unclear that using an email address that isn't the users account email address would block sending - fixed with UI change.
2. Emails weren't be sent to reciever - fixed by undoing a last minute change I'd made that I hadn't tested properly.
3. Email header image wasn't showing - now pulling in the right data to the email template.
> fix: contact message issues

- .circleci/config.yml
PR Checklist
PR Type
Closes #
---
> chore(ci): increase resources for unit tests

- package.json
- yarn.lock
PR Checklist
PR Type
Closes #
---
> feat(deps): upgrade react virtualized to 9.22.5

- .github/workflows/pr-preview.yml
PR Checklist
PR Type
Closes #
---
> chore(patreon): update preview deploy with patreon env variable

- src/pages/Question/Content/Common/PostingGuidelines.tsx
- src/pages/Question/Content/Common/index.ts
- src/pages/Question/QuestionCreate.tsx
- src/pages/Question/QuestionEdit.tsx
PR Checklist
PR Type
Updates the question page's sidebar text 
Closes #2965 
---
> feat(question): update sidebar explanation

- src/pages/Question/QuestionCreate.tsx
- src/pages/Question/QuestionEdit.tsx
- src/pages/Question/QuestionListing.tsx
PR Checklist
PR Type
Remove unnecessary padding in Questions page
Closes #3031 
---
> fix: removed unnecessary padding in Questions page

- src/pages/User/contact/UserContactError.tsx
- src/pages/common/Header/Menu/Profile/Profile.tsx
- src/stores/databaseV2/clients/dexie.tsx
PR Checklist
PR Type
There's a few linting overriddes hanging around for no-console which shouldn't be there. One of which allowed a leak of data to sneak through.
> fix: drop unwanted no console overrides

- .circleci/config.yml
- .github/workflows/pr-preview.yml
- firestore.rules
- functions/scripts/runtimeConfig/model.ts
- functions/src/Integrations/index.ts
- functions/src/Integrations/patreon.ts
- functions/src/config/config.ts
- packages/documentation/docs/Backend Development/integrations.md
- packages/security-rules/tests/general.spec.ts
- shared/models/db.ts
- src/config/config.ts
- src/config/constants.ts
- src/models/user.models.tsx
- src/pages/PageList.tsx
- src/pages/Patreon/Patreon.tsx
- src/pages/UserSettings/SettingsPage.tsx
- src/stores/databaseV2/clients/dexie.tsx
PR Checklist
PR Type
this PR sets up a basic "Log in with Patreon" button on the platform
Follows the steps in the docs here: https://docs.patreon.com/#oauth
1. Create keys, set redirect uris to `http(s)://<host>/patreon`
2. Add keys to the firebase config (functions) and env variables (React app) to securely access in app
3. Create button in the user settings page (is this the right place? @davehakkens)
4. Button redirects to patreon's login auth flow
5. Patreon's auth flow redirects back to the platform with the path `/patreon` and URL param with a single use token. React app renders a loading screen while the page sends a HTTP request to our serverless functions with the token sent back from Patreon.
6. The function hits the patreon API auth endpoint with the single-use token. The …
> feat(patreon): set up auth with patreon

- packages/documentation/docs/Design/our-design-system.md
PR Checklist
PR Type
Updates the link to the more up to date design file.
> fix: doc link to public figma file

- packages/components/src/TabbedContent/TabbedContent.tsx
- src/pages/User/contact/UserContactFieldEmail.tsx
- src/pages/User/contact/UserContactFieldMessage.tsx
- src/pages/User/contact/UserContactFieldName.tsx
- src/pages/User/impact/ImpactField.tsx
- src/pages/User/impact/ImpactItem.tsx
PR Checklist
PR Type
Updates the tab design in line with the new impact data feature.
---
> feat: update tab styling

- functions/src/Integrations/patreon.ts
PR Checklist
PR Type
Closes #
---
> fix(patreon): lookup by auth id

- functions/src/Integrations/patreon.ts
- functions/src/consts.ts
- functions/src/emailNotifications/createModerationEmails.ts
- functions/src/emailNotifications/index.ts
- functions/src/emailNotifications/utils.ts
PR Checklist
PR Type
Closes #
---
> fix(patreon): increase memory limits

- src/pages/UserSettings/SettingsPage.tsx
PR Checklist
PR Type
A tiny tweak. The basic user info settings are more important than the map and for members, the map setting isn't a requirement.
> feat: move user info up on settings page

- functions/src/Integrations/patreon.ts
- shared/models/user.ts
- src/models/user.models.tsx
- src/pages/Patreon/Patreon.tsx
- src/pages/UserSettings/SettingsPage.tsx
- src/pages/UserSettings/content/formSections/PatreonIntegration.tsx
PR Checklist
PR Type
this PR adds models for the patreon data we fetch from the API and builds the designed component for the settings page to enable integration.
Closes #
https://github.com/ONEARMY/community-platform/assets/37253846/ec1f89a4-ed8e-4a6a-859d-faf985469bb9
---
> feat(patreon): build frontend integration

- src/models/question.models.tsx
- src/pages/Question/Content/Common/QuestionForm.tsx
- src/pages/Question/QuestionListing.tsx
- src/pages/Question/QuestionPage.tsx
- src/pages/Question/labels.ts
- src/pages/Question/question.routes.test.tsx
- src/stores/Question/question.store.test.tsx
- src/stores/Question/question.store.tsx
PR Checklist
PR Type
- creates and modify a draft question. in case of draft validates only the question title
- added draft icon to question list and question page
- fix: on question update keeps the original _createdBy user
Closes #2966 
---
> feat(question): create draft

- functions/src/emailNotifications/createSubmissionEmails.ts
- functions/src/emailNotifications/templates.ts
- functions/src/emailNotifications/templates/receiver-message.html
- functions/src/emailNotifications/templates/sender-message.html
PR Checklist
PR Type
This tweaks the email templates for consistency and sets the 'reply to' field for the email that goes to the reciever.
Closes #3047
> feat: update message templates for consistency

- shared/models/db.ts
- src/models/question.models.tsx
- src/models/questionCategories.model.ts
- src/pages/Howto/Category/CategoriesSelect.tsx
- src/pages/Question/Content/Common/QuestionForm.tsx
- src/pages/Question/question.routes.test.tsx
- src/stores/QuestionCategories/questionCategories.store.tsx
- src/stores/databaseV2/clients/dexie.tsx
- src/stores/index.tsx
PR Checklist
PR Type
Add categories to questions, like Research and How-To.
⚠️ I think work is required on the firebase side to add the categories, because I don't think there is an administration for the website?
Closes #2963
---
> feat(question): select category

- functions/src/Integrations/patreon.spec.ts
- functions/src/Integrations/patreon.ts
- src/models/user.models.tsx
- src/pages/UserSettings/SettingsPage.tsx
- src/pages/UserSettings/content/formSections/PatreonIntegration.test.tsx
- src/pages/UserSettings/content/formSections/PatreonIntegration.tsx
- src/stores/User/user.store.ts
PR Checklist
PR Type
1. applies the requested changes to the Patreon integration section of the settings page:
2. adds the `supporter: true` badge for users that integrate with Patreon and support a linked tier
3. writes tests!
Closes #3068 
https://github.com/ONEARMY/community-platform/assets/37253846/83278d65-742f-4f9d-a67b-16250f0d41e1
---
If you need more immediate feedback you can try reaching out on Discord in …
> feat(patreon): link to supporter badge and update integration module

- .circleci/config.yml
PR Checklist
PR Type
The Firefox test suite run for cypress is just in the way atm, very flaky and not picking any additional issues up.
> chore: drop firefox e2e test run

- packages/cypress/src/integration/howto/read.spec.ts
- src/pages/Howto/Content/Howto/HowtoDescription/HowtoDescription.tsx
- src/pages/Question/QuestionPage.tsx
- src/pages/Research/Content/ResearchDescription.tsx
- src/pages/common/ContentAuthorTimestamp/ContentAuthorTimestamp.tsx
Question, Research and How-To modules now use the same component to display the author, create and update dates.
PR Checklist
PR Type
- Show update date on questions
- Introduce a new react component to display the author, created and updated dates
Closes #2960
---
> feat(questions): display update date on questions and share component

- packages/components/README.md
- packages/components/scripts/newComponent.ts
- packages/components/scripts/templates/{componentName}.test.tsx.mst
PR Checklist
PR Type
- docs(components): include test file in script output
- chore(packages): include new line char at end of file
- chore: update template test so it passes initially
> chore(packages): update new component docs/scripts

- shared/models/db.ts
- src/models/discussion.models.tsx
- src/models/index.ts
- src/stores/Discussions/discussion.store.test.ts
- src/stores/Discussions/discussions.store.tsx
- src/stores/databaseV2/clients/dexie.tsx
- src/stores/index.tsx
- src/test/factories/Discussion.ts
PR Checklist
PR Type
Introduces new Discussion model and store with basic CRUD operations. This new data structure will be used to host all comment lists going forward. It extends the existing Comment model slightly to support a new property `parentCommentId`. Setting the `parentCommentId` for a comment item creates a Reply.
The comments will be stored as a flat list which allows:
* Simplified Data Management: Handling comments in a flat list simplifies database operations, making it easier to manage and query data without complex hierarchical queries.
* Improved Performance: Flat lists can offer better performance, especially in large-scale applications, as operations like sorting and filtering are generally more efficient compared to nested structures.
* Ease of Pagination: Implementing …
> feat: introduce Discussion model and store for persisting data

- src/pages/UserSettings/SettingsPage.tsx
- src/pages/UserSettings/UserSettings.test.tsx
- src/pages/UserSettings/content/formSections/AccountSettings.section.tsx
- src/pages/UserSettings/content/formSections/ChangeEmail.form.tsx
- src/pages/UserSettings/content/formSections/ChangePassword.form.tsx
- src/pages/UserSettings/content/formSections/Fields/CustomCheckbox.field.tsx
- src/pages/UserSettings/content/formSections/Fields/CustomRadio.field.tsx
- src/pages/UserSettings/content/formSections/Fields/OpeningHoursPicker.field.tsx
- src/pages/UserSettings/content/formSections/Fields/ProfileLink.field.tsx
- src/pages/UserSettings/content/formSections/MemberMapPin.section.tsx
- src/pages/UserSettings/content/formSections/UserInfos.section.tsx
- src/pages/UserSettings/content/formSections/WorkspaceMapPin.section.tsx
PR Checklist
PR Type
Refactors Settings class components to hooks.
> Settings class components to hooks

- src/pages/common/Header/Header.tsx
- src/pages/common/Header/Menu/Logo/Logo.tsx
- src/pages/common/Header/Menu/MenuMobile/MenuMobileExternalLink.tsx
- src/pages/common/Header/Menu/MenuMobile/MenuMobileLink.tsx
- src/pages/common/Header/Menu/MenuMobile/MenuMobilePanel.tsx
- src/pages/common/Header/Menu/Profile/Profile.tsx
- src/pages/common/Header/Menu/Profile/ProfileButtonItem.tsx
- src/pages/common/Header/Menu/ProfileModal/ProfileModal.tsx
PR Checklist
PR Type
Converts header class components to hooks
> refactor: header class components to hooks

- src/common/hooks/useMemberStatistics.ts
- src/pages/User/content/MemberProfile.tsx
- src/pages/User/content/SpaceProfile.tsx
PR Checklist
PR Type
As part of adopting https://www.npmjs.com/package/eslint-plugin-react-hooks in https://github.com/ONEARMY/community-platform/pull/3105, I am merging a subset of fixes as flagged in:
https://app.circleci.com/pipelines/github/ONEARMY/community-platform/7387/workflows/c97aaa26-c1bd-4640-92ff-419d76beee96/jobs/62234
> The react-hooks/exhaustive-deps rule in the ESLint plugin is beneficial as it ensures that all dependencies of React hooks like useEffect, useMemo, and useCallback are correctly specified. This rule helps prevent bugs related to missing dependencies, which can cause unexpected behavior in React components. By enforcing a comprehensive check on the dependencies array, it aids in maintaining the functional integrity and performance of React components, …
> chore: align with standards for naming custom React Hook function

- src/pages/Howto/Content/Common/Howto.form.test.tsx
- src/pages/Maps/Maps.test.tsx
- src/pages/UserSettings/UserSettings.test.tsx
PR Checklist
PR Type
As part of adopting https://www.npmjs.com/package/eslint-plugin-react-hooks in https://github.com/ONEARMY/community-platform/pull/3105, I am merging a subset of fixes required for the tests. 
> The react-hooks/exhaustive-deps rule in the ESLint plugin is beneficial as it ensures that all dependencies of React hooks like useEffect, useMemo, and useCallback are correctly specified. This rule helps prevent bugs related to missing dependencies, which can cause unexpected behavior in React components. By enforcing a comprehensive check on the dependencies array, it aids in maintaining the functional integrity and performance of React components, ensuring that they update correctly in response to state or prop changes.
> For more detailed information, you can refer to the …
> test: refactor to match React naming conventions

- packages/components/src/CommentItem/CommentItem.tsx
- packages/components/src/CommentList/CommentList.tsx
- packages/components/src/ImageGallery/ImageGallery.tsx
- packages/components/src/NotificationList/NotificationList.tsx
- packages/components/src/OsmGeocoding/OsmGeocoding.tsx
PR Checklist
PR Type
As part of adopting https://www.npmjs.com/package/eslint-plugin-react-hooks in https://github.com/ONEARMY/community-platform/pull/3105, I am merging a subset of fixes required for the packages/components directory. 
> The react-hooks/exhaustive-deps rule in the ESLint plugin is beneficial as it ensures that all dependencies of React hooks like useEffect, useMemo, and useCallback are correctly specified. This rule helps prevent bugs related to missing dependencies, which can cause unexpected behavior in React components. By enforcing a comprehensive check on the dependencies array, it aids in maintaining the functional integrity and performance of React components, ensuring that they update correctly in response to state or prop changes.
> For more detailed …
> fix(components): correct deps for all useEffect instances

- src/stores/User/user.store.ts
PR Checklist
PR Type
The user record can be fairly verbose, especially if the user has plenty
of messages or notifications. Reducing the output to cover only the _id
field which is needed for debugging this particular problem.
> chore: reduce log output

- packages/components/src/CommentList/CommentList.stories.tsx
- packages/components/src/CommentList/CommentList.test.tsx
- packages/components/src/CommentList/CommentList.tsx
- packages/components/src/CommentList/createComments.tsx
PR Checklist
PR Type
Introduces tests for `CommentList` in preparation for expanding the behaviour of this component to support Nested Comments and Reply.
> test(components): add some assertations around CommentList

- src/pages/Unsubscribe/Unsubscribe.test.tsx
- src/pages/Unsubscribe/Unsubscribe.tsx
PR Checklist
PR Type
Closes #
---
> test: add coverage to Unsubscribe page

- packages/cypress/src/integration/research/write.spec.ts
- src/common/AuthWrapper.test.tsx
- src/common/AuthWrapper.tsx
- src/common/Form/FileInput/FileInput.tsx
- src/common/Form/ImageInput/ImageConverter.tsx
- src/common/Form/ImageInput/ImageInput.tsx
- src/common/Tags/TagsSelect.tsx
- src/pages/Question/QuestionListing.tsx
- src/pages/Question/QuestionPage.tsx
- src/pages/Question/question.routes.test.tsx
PR Checklist
PR Type
Converts remaining /common components to hooks.
> refactor: common components to hooks

- packages/components/src/ModerationStatus/ModerationStatus.tsx
- src/App.tsx
- src/pages/Howto/Content/Common/Howto.form.tsx
- src/pages/Howto/Content/Common/HowtoFieldStep.tsx
- src/pages/Howto/VirtualizedFlex/VirtualizedFlex.tsx
- src/pages/Maps/Content/Controls/GroupingFilterDesktop.tsx
- src/pages/Maps/Content/Controls/GroupingFilterMobile.tsx
- src/pages/Maps/Content/MapView/Popup.tsx
- src/pages/Research/Content/Common/ResearchUpdate.form.test.tsx
PR Checklist
PR Type
Refactors the remaining class components to hooks.
I didn't migrate the ErrorBoundary component as it's not trivial and there is probably a better way once we have the fullstack framework.
> refactor: remaining class components to hooks

- src/stores/Message/message.store.test.ts
PR Checklist
PR Type
test: add coverage for message.store
> test: add coverage for message.store

- src/pages/SignIn/SignIn.tsx
- src/stores/User/user.store.test.tsx
- src/stores/User/user.store.ts
PR Checklist
PR Type
- chore: refactor user store moving private methods base of class
- chore: refactor to drop unused provider prop
- chore: drop unused method
- test: add coverage to pulic methods
> chore: refactor and tests

- src/pages/Question/QuestionPage.tsx
- src/pages/Question/question.routes.test.tsx
- src/stores/Question/question.store.test.tsx
- src/stores/Question/question.store.tsx
- src/stores/Research/research.store.test.ts
- src/stores/Research/research.store.tsx
- src/stores/common/toggleDocSubscriberStatusByUserName.ts
PR Checklist
PR Type
Adds support for Follow function, note that it will require some further integration work to notify subscribers when new comments are added. 
Closes #2957
> feat: toggle follow state for user

- packages/documentation/docs/Contributing/start-contributing.md
PR Checklist
PR Type
This pr is a rebase of #3130 to fix commit message and make additional copy & emoji changes.  Core maintainer emoji changed to 🔧 as the original screwdriver emoji was added relatively recently and wouldn't show on all browsers / operating systems.
Taken from original pr #3130 :
Would resolve https://github.com/ONEARMY/community-platform/issues/3128 if merged and see diff for minor copyrwrite updates to make it easier for users to understand what you're explaining
Happy for maintainers to edit the pull request directly if easier or to split it into multiple pull requests if needed
Closes #3128
---
Thanks for the contribution! We try to make sure all PRs are reviewed ahead of our monthly maintainers …
> fix(docs): start contributing emoji & copy updates (fix pr 3130)

- src/utils/helpers.test.ts
- src/utils/helpers.ts
PR Checklist
PR Type
Fix the sort by comments for research items.
this happened because the sort tried to sort on the count as a string and not number
Closes #3135 
---
> fix(research): fix sort by comments

- src/pages/Question/QuestionListing.tsx
PR Checklist
PR Type
Added username and date to the question listing
Closes #3134 
---
> feat(question): add username and date to question listing

- packages/cypress/src/integration/common.spec.ts
- packages/cypress/src/integration/research/follow.spec.ts
PR Checklist
PR Type
Attempted improvements to a couple of the flaky tests that sometimes fail and thus block a PR/release.
> chore: improve flaky tests

- src/pages/Research/Content/EditUpdate/index.tsx
PR Checklist
PR Type
Fixes edit research step.
Happens because it tries to validate permissions for the active research item before it loads.
Closes #3153
> fix: edit research step

- src/pages/Patreon/Patreon.tsx
- src/pages/UserSettings/SettingsPage.tsx
PR Checklist
PR Type
fixes a regression introduced in the [react router v6 upgrade](https://github.com/ONEARMY/community-platform/pull/3069/files#diff-9bd14857524cac55f2458432800e60e67b5056dddeca9857127f413a3c9232b9) which was causing a whitescreen on patreon redirect
Closes #
--- …
> fix(patreon): fix router regression

- src/pages/common/SortFilterHeader/SortFilterHeader.tsx
- src/stores/Howto/howto.store.tsx
- src/stores/Research/research.store.tsx
- src/stores/common/FilterSorterDecorator/FilterSorterDecorator.ts
PR Checklist
PR Type
This pr introduces a 'Most Relevant' search option so that when searching for a how-to / research the results are displayed ranked based on their search score.  Issue raised as a website problem on discord.
https://discord.com/channels/586676777334865928/1192524295172264086/1192524295172264086
Closes #
---
If you need more immediate feedback you can try reaching out on Discord in the [Community Platform …
> feat: improve search result ordering

- package.json
- src/common/Form/ImageInput/ImageConverter.tsx
- yarn.lock
PR Checklist
PR Type
Upload entire images, do not do any downsampling on uploaded image content.
> fix: remove image compression from uploads

- packages/cypress/src/integration/profile.spec.ts
- src/models/user.models.tsx
- src/pages/User/content/SpaceProfile.tsx
- src/pages/User/impact/Impact.tsx
- src/pages/User/impact/constants.ts
PR Checklist
PR Type
For PP. As we're importing impact data to spaces profiles, we're giving them ~10 days to see and update their data before it's viewable by everyone. 
**This PR should be merged and released in Janurary - date TBC.**
> Change default display for impact

- src/pages/UserSettings/SettingsPage.tsx
PR Checklist
PR Type
Removes the beta tester wrapper from the impact data settings component
> feat: remove auth wrapper from impact setting

- packages/cypress/src/integration/research/read.spec.ts
- packages/cypress/src/integration/research/write.spec.ts
- src/models/research.models.tsx
- src/pages/Research/Content/Common/Research.form.tsx
- src/pages/Research/Content/ResearchArticle.tsx
- src/pages/Research/Content/ResearchDescription.tsx
- src/pages/Research/Content/ResearchList.tsx
- src/pages/Research/Content/ResearchListItem.tsx
- src/pages/Research/labels.ts
- src/pages/common/SortFilterHeader/SortFilterHeader.tsx
- src/stores/Research/research.store.tsx
- src/stores/common/FilterSorterDecorator/FilterSorterDecorator.ts
- src/utils/helpers.ts
PR Checklist
PR Type
Introduces the research status field and corresponding research list filter for research status.
Also some minor bug fixes to solve type errors on the research store.
Closes #
---
> feat: add research status to research

- src/pages/common/SortFilterHeader/SortFilterHeader.tsx
- src/stores/Research/research.store.tsx
PR Checklist
PR Type
Tidies up some type casting implemented as part of the research status work
Closes #
---
> refactor: remove unnecessary research related type casts

- .circleci/config.yml
PR Checklist
PR Type
Closes #
---
> chore(ci): remove Slack notifications as this is no longer primary chat tool

- packages/cypress/src/integration/profile.spec.ts
- src/pages/User/content/SpaceProfile.tsx
PR Checklist
PR Type
Enables all logged in users to view and complete the contact form (if the workspace has opted-in).
> feat: remove beta tester wrapper from contact display

- src/pages/UserSettings/SettingsPage.tsx
PR Checklist
PR Type
A minor improvement to the user experience of the settings page, especially for users on slower connections/devices.
> feat: add initial loading condition to settings page

- packages/components/src/FollowButton/FollowButton.tsx
- packages/cypress/src/integration/research/follow.spec.ts
PR Checklist
PR Type
This seems to get the cypress test for the follow button on research articles back to a point where the test is flaky rather than failing.
> Fix: Follow button test

- functions/src/emulator/seed/content-generate.ts
- packages/cypress/src/integration/notifications.spec.ts
- src/models/user.models.tsx
- src/pages/Howto/Content/Howto/HowToComments/HowToComments.tsx
- src/pages/common/Header/getFormattedNotifications.tsx
- src/stores/Howto/howto.store.test.ts
- src/stores/Howto/howto.store.tsx
- src/stores/Research/research.store.test.ts
- src/stores/Research/research.store.tsx
- src/stores/User/notifications.store.test.tsx
- src/stores/User/notifications.store.ts
PR Checklist
- [ x ] - Commit [messages are descriptive](https://github.com/ONEARMY/community-platform/blob/master/CONTRIBUTING.md#--commit-style-guide), it will be used in our [Release Notes](https://github.com/ONEARMY/community-platform/releases/)
PR Type
- [ x ] New feature (non-breaking change which adds functionality)
The notification message specifies the research topic that the person has posted an update, commented, or found useful.  Messages are based on suggestions that were being discussed.
Closes #2922
If the PR is working as intended it'll be merged and included in the next platform release, if not changes will be requested and re-reviewed …
> feat: more information in Follower notifications

- package.json
- packages/cypress/package.json
- packages/cypress/src/integration/SignUp.spec.ts
- packages/cypress/src/support/db/firebase.ts
- packages/security-rules/package.json
- shared/messages.ts
- src/pages/SignUp/SignUp.tsx
- src/stores/User/user.store.test.tsx
- src/stores/User/user.store.ts
- src/utils/firebase.ts
- yarn.lock
PR Checklist
PR Type
Upgrades firebase 
- chore(deps): upgrade to firebase@9
- chore(cypress): install firebase dependency
- refactor: firebase switch to modular usage for auth
Following recommended process: https://firebase.google.com/docs/web/modular-upgrade
Additional Issues will be created to track the following process:
> chore(deps): upgrade Firebase to v9

- packages/cypress/src/integration/profile.spec.ts
- src/pages/User/content/SpaceProfile.tsx
- src/pages/User/impact/Impact.tsx
PR Checklist
PR Type
Displays impact data for all! To be released on Thursday 18th.
> feat(impact): show impact to all

- package.json
- src/pages/Maps/Content/Controls/Controls.tsx
- yarn.lock
PR Checklist
PR Type
This package was needed only for v4/v5 of react-router
> chore: remove react-router-hash-link

- package.json
- yarn.lock
PR Checklist
PR Type
We were using a version from 6 years ago. So maybe this will fix the issue where `/how-to` page doesn't load sometimes, on dev,
https://github.com/dexie/Dexie.js/releases/tag/v3.0.0 they say there are no api breaking changes.
> chore: update dexie to v3

- package.json
- src/pages/Research/Content/ResearchListItem.tsx
- src/pages/Research/Content/ResearchUpdate.test.tsx
- src/pages/Research/Content/ResearchUpdate.tsx
- src/pages/common/ContentAuthorTimestamp/ContentAuthorTimestamp.tsx
- src/pages/common/UserNameTag/UserNameTag.tsx
- src/utils/date.ts
- src/utils/filters.ts
- yarn.lock
PR Checklist
PR Type
Updates date-fns to the latest version.
> chore: update date-fns

- src/pages/Question/QuestionListing.tsx
- src/pages/Question/QuestionPage.tsx
- src/pages/Question/question.routes.test.tsx
- src/stores/Question/question.store.tsx
PR Checklist
PR Type
- Moves edit button for question so that the placement is consistent with existing modules.
- Makes clickable area of question list item larger.
- Fixes infinite loading spinner if no question items.
- Updates no questions text slightly.
Closes #
--- …
> feat: minor question module tweaks

- .gitignore
- functions/src/emailNotifications/createSubmissionEmails.spec.ts
- functions/src/emailNotifications/createSubmissionEmails.ts
- functions/src/emailNotifications/utils.test.ts
- functions/src/emailNotifications/utils.ts
- src/utils/helpers.ts
PR Checklist
PR Type
Tidy-up from #3167
> chore(messaging): isBlockedFromMessaging follow up

- packages/components/src/CommentItem/CommentItem.tsx
- packages/components/src/ConfirmModal/ConfirmModal.tsx
- packages/components/src/CreateComment/CreateComment.stories.tsx
- packages/components/src/CreateComment/CreateComment.test.tsx
- packages/components/src/CreateComment/CreateComment.tsx
- packages/components/src/EditComment/EditComment.tsx
- src/models/comment.model.ts
- src/models/discussion.models.tsx
- src/pages/Question/QuestionComments.tsx
- src/pages/Question/QuestionPage.tsx
- src/pages/Question/question.routes.test.tsx
- src/pages/Research/Content/ResearchComments/ResearchComments.tsx
Building on the work originally in #3100, this adds support for creating, editing and removing comments on Question content items.
PR Checklist
> feat: question discussion add/edit comments

- src/pages/Question/QuestionPage.tsx
PR Checklist
PR Type
CSS update for making QuestionPage component narrower by setting max-width to 1000px.
Also removed useless padding to match simi
Similar to what was already existing in ResearchArticle component.
Closes #3220
> fix(questionPage): added maxWidth to page container element

- src/pages/common/SortFilterHeader/SortFilterHeader.tsx
- src/stores/Howto/howto.store.tsx
- src/stores/Question/question.store.tsx
- src/stores/Research/research.store.tsx
- src/stores/common/FilterSorterDecorator/FilterSorterDecorator.ts
PR Checklist
PR Type
Most relevant sort option only present if search value entered.  If search value deleted then it will return to the sort option chosen before the search value was entered.
Closes #
---
> feat: most relevant sort option only present if search value entered

- src/pages/User/content/SpaceProfile.tsx
PR Checklist
PR Type
Closes #3243
> fix: introduce gap between columns

- package.json
- packages/components/package.json
PR Checklist
PR Type
Removes the coverage output, this is preferable when working in [TDD pattern](https://scaledagileframework.com/test-driven-development/) with `yarn test`, it reduces the output to only show test results.
> chore(ci): split coverage out to only run in CI

- src/pages/Question/QuestionPage.tsx
- src/pages/Question/question.routes.test.tsx
PR Checklist
PR Type
Adds the content statistics:
Closes #2961
> feat: add content statistics to questions

- .circleci/config.yml
- functions/package.json
- packages/components/.gitignore
- packages/components/package.json
PR Checklist
PR Type
Closes #
---
> test: introduce junit output for component and (serverless) functions

- src/stores/databaseV2/clients/dexie.tsx
- src/stores/databaseV2/clients/firestore.tsx
- src/stores/databaseV2/utils/getQueryOptions.ts
PR Checklist
PR Type
Small refactor to introduce helper function rather than passing constants around.
> chore: refactor database clients

- packages/components/src/CommentContainer/CommentContainer.test.tsx
PR Type
I'm hoping this stops all the failing CI unit test flows.
> chore: fix flaky component test

- src/common/Form/ImageInput.field.tsx
- src/common/Form/ImageInput/DeleteImage.tsx
- src/common/Form/ImageInput/ImageConverterList.tsx
- src/common/Form/ImageInput/ImageInput.tsx
- src/common/Form/ImageInput/ImageInputWrapper.tsx
- src/common/Form/ImageInput/getPresentFiles.ts
- src/common/Form/ImageInput/setSrc.ts
- src/common/Form/ImageInput/types.ts
PR Checklist
PR Type
To aid #3270, I've tidied up `ImageInput` which I found very difficult to follow and understand. Further ideas for refactoring this greatly appreciated.
> chore: refactor image input field

- packages/cypress/package.json
- yarn.lock
PR Checklist
PR Type
Closes #
---
> chore(deps): upgrade cypress@13.6.6

- packages/components/src/CreateReply/CreateReply.test.tsx
- packages/components/src/CreateReply/CreateReply.tsx
PR Checklist
PR Type
Clears the reply field after submission.
Closes #3262
> fix: clear create reply field after submit

- src/common/Alerts/AlertProfileVerification.tsx
- src/common/Error/handlers/ChunkLoadError.tsx
- src/pages/SignUp/SignUpMessage.tsx
- src/utils/helpers.test.ts
- src/utils/helpers.ts
PR Checklist
PR Type
Adds a little util to get the support email address with the project instance appended at the end.
Closes #3309
> feat: get support email that is project specific

- src/pages/Question/QuestionPage.tsx
- src/pages/Question/question.routes.test.tsx
- src/stores/Question/question.store.tsx
- src/stores/common/incrementDocViewCount.tsx
PR Checklist
PR Type
As [flagged here](https://github.com/ONEARMY/community-platform/pull/3252#issuecomment-1925308469) by 🦅 👁️ @davehakkens, adds view tracking to Question items.
> feat: question add views counter

- packages/components/src/NotificationItem/NotificationItem.tsx
- src/models/discussion.models.tsx
- src/pages/Question/QuestionComments.tsx
- src/stores/Discussions/discussion.store.test.ts
- src/stores/Discussions/discussionEvents.ts
- src/stores/Discussions/discussions.store.tsx
- src/stores/User/notifications.store.ts
PR Checklist
PR Type
Adds a notification trigger for top level and nested comments in discussions.
Closes #3259
https://github.com/ONEARMY/community-platform/assets/16688508/f4c60171-5fd5-40ce-823e-fc9d1076ad6f
> Feat(discussion): add notifications

- packages/components/src/ContentStatistics/ContentStatistics.tsx
- packages/components/src/IconCountWithTooltip/IconCountWithTooltip.stories.tsx
- packages/components/src/IconCountWithTooltip/IconCountWithTooltip.test.tsx
- packages/components/src/IconCountWithTooltip/IconCountWithTooltip.tsx
- packages/components/src/index.ts
- packages/cypress/src/integration/research/read.spec.ts
- src/pages/Question/QuestionListing.tsx
- src/pages/Research/Content/ResearchListItem.tsx
PR Checklist
PR Type
-  [ ] Developer experience (improves developer workflows for contributing to the project)
Adds comment and useful count on Question listing.
> feat: question listing show comments/useful count

- packages/cypress/src/integration/settings.spec.ts
- src/pages/UserSettings/content/formSections/AccountSettings.section.tsx
- src/pages/UserSettings/content/formSections/ChangeEmail.form.tsx
- src/pages/UserSettings/content/formSections/ChangePassword.form.tsx
- src/pages/UserSettings/labels.ts
- src/stores/User/user.store.ts
PR Checklist
PR Type
I used the change to tidy up the forms in align with approaches I've taken on other forms (form messaging, labels, etc). I'm betting the way I've written the cypress test will become a pain. Would be delighted with ideas for a better approach.
Closes #3320 
Email:
https://github.com/ONEARMY/community-platform/assets/16688508/f62d31b8-03e5-44fd-905f-849ac973cec6
Password:
https://github.com/ONEARMY/community-platform/assets/16688508/84526e18-f4dc-49dc-9c8b-2495918a4df6
> fix: account settings forms

- packages/components/src/IconCountWithTooltip/IconCountWithTooltip.tsx
PR Checklist
PR Type
Research:
Questions:
> fix: spacing issue in icon count with tooltip

- src/pages/SignUp/SignUpMessage.tsx
As it's possible for users to request a new email verfication email, it doesn't need to be quite as easy to contact us...
> feat: drop email link from signup message

- packages/components/src/IconCountWithTooltip/IconCountWithTooltip.tsx
PR Checklist
PR Type
Closes #
---
> fix: undo commit 6722df9 to fix prod release

- packages/components/src/IconCountWithTooltip/IconCountWithTooltip.tsx
A redo of #3326 after a weird production release issue.
> fix: redo fix of tooltip spacing issue

- src/config/config.ts
- src/pages/User/content/SpaceProfile.tsx
- src/pages/UserSettings/SettingsPage.tsx
PR Checklist
PR Type
The impact feature for Precious Plastic was incorrectly also showing on the Fixing Fashion site. This PR corrects that.
> fix: add wrapper to impact to only show on pp

- packages/cypress/src/integration/profile.spec.ts
- packages/cypress/src/integration/settings.spec.ts
Fixes the tests I should have changed in #3338.
> fix: cypress tests from pp impact wrapper change

- src/pages/Question/Content/Common/QuestionForm.tsx
- src/pages/Question/question.routes.test.tsx
If you save a draft question, or worst, have a published question you then revert to drafts, it's currently not possible to find your question again! Ideally the UI allows for draft questions to be found easily but it doesn't right now so I'm removing the save draft button until this design challenge is solved.
> feat: drop draft question state

- src/pages/Howto/Content/HowtoList/HowToCard.tsx
> fix: show moderation state on how to card

- packages/components/src/FieldTextarea/FieldTextarea.stories.tsx
- packages/components/src/FieldTextarea/FieldTextarea.tsx
- src/pages/Question/Content/Common/FormFields/QuestionCategory.field.tsx
- src/pages/Question/Content/Common/FormFields/QuestionDescription.field.tsx
- src/pages/Question/Content/Common/FormFields/QuestionTags.field.tsx
- src/pages/Question/Content/Common/FormFields/QuestionTitle.field.tsx
- src/pages/Question/Content/Common/FormFields/index.ts
- src/pages/Question/Content/Common/QuestionForm.tsx
- src/pages/Question/labels.ts
- src/pages/Question/question.routes.test.tsx
PR Checklist
PR Type
Mainly a tidy-up but also includes text and form size updates.
> Feat(questions): refactor form field wrapper and update UI

- packages/components/src/Tag/Tag.tsx
- packages/components/src/TagList/TagList.stories.tsx
- packages/components/src/TagList/TagList.test.tsx
- packages/components/src/TagList/TagList.tsx
- packages/components/src/index.ts
- src/common/Tags/TagsList.test.tsx
- src/common/Tags/TagsList.tsx
- src/models/question.models.tsx
- src/pages/Question/QuestionPage.tsx
PR Checklist
PR Type
1. Displays tags and categories on the question page.
2. Tidies up the layout on question page (e.g. use flex more consistently)
3. Creates two(!) lays for TagsList, UI layer in the component library and common component to do the store call (which should then be used across the other content types too.
> Feat(questions): Add missing UI elements to page

- packages/components/src/CommentContainer/CommentContainer.tsx
- packages/components/src/CommentItem/CommentItem.stories.tsx
- packages/components/src/CommentItem/CommentItem.tsx
- packages/components/src/CommentList/CommentList.stories.tsx
- packages/components/src/CommentList/CommentList.test.tsx
- packages/components/src/CommentList/CommentList.tsx
- packages/components/src/DiscussionContainer/DiscussionContainer.tsx
- packages/components/src/EditComment/EditComment.stories.tsx
- packages/components/src/EditComment/EditComment.test.tsx
- packages/components/src/EditComment/EditComment.tsx
> feat(discussion): update labels for editing discussion items

- src/pages/Research/Content/ResearchArticle.tsx
- src/pages/Research/Content/ResearchListItem.tsx
- src/stores/common/FilterSorterDecorator/FilterSorterDecorator.ts
- src/utils/helpers.test.ts
- src/utils/helpers.ts
PR Checklist
PR Type
- **refactor: rename helper**
- **fix: load comment count from new property**
- **refactor: use general helper for loading comment count**
> fix: use total comment prop

- src/stores/common/mentions/index.ts
PR Checklist
PR Type
In summary, this patch fixes a bug by ensuring that the changeUserReferenceToPlainText function can handle cases where the text parameter is not provided or is undefined, preventing potential errors in the code that could occur due to undefined values.
> fix: handle undefined val

- src/pages/Question/QuestionComments.tsx
- src/pages/Question/QuestionDiscussion.tsx
- src/pages/Question/QuestionPage.tsx
- src/pages/Question/question.routes.test.tsx
- src/stores/Discussions/discussion.store.test.ts
- src/stores/Discussions/discussions.store.tsx
- src/utils/helpers.ts
PR Checklist
PR Type
Does some tidy-up and fixes a couple of bugs. No 404. Notifications. Discussion component responsible for getting discussion for faster loading.
> Chore: Tidy-up Question page responsibilities

- src/pages/Question/QuestionPage.tsx
- src/pages/Question/question.routes.test.tsx
- src/stores/Question/question.store.test.tsx
- src/stores/Question/question.store.tsx
- src/stores/common/toggleDocSubscriberStatusByUserName.ts
- src/stores/common/toggleDocUsefulByUser.ts
PR Checklist
PR Type
Useful and follow buttons state was not correctly updating on screen for the user.  Refactoring / fixes made to correct this.
Closes #
---
> fix: question useful and follow toggles

- firestore.indexes.json
PR Checklist
PR Type
Closes #
---
> fix: remove field name bug

- src/pages/Question/QuestionListItem.tsx
- src/pages/Question/question.routes.test.tsx
PR Checklist
PR Type
Adds the display of a question image to the list if present.
> feat: add image display to question list item

- packages/cypress/src/integration/questions/read.spec.ts
- shared/mocks/data/questions.ts
- src/pages/Question/QuestionPage.tsx
Adds the clickable link component to question description.
> feat: add clickable links to question description

- src/pages/Question/QuestionListItem.tsx
PR Checklist
PR Type
This drops the image list element of #3397 that got merged in today(!) but keeps the change which makes the item more clickable as that issue came through in user testing.
> feat: drop image on question item list display

- packages/cypress/src/integration/howto/read.spec.ts
- packages/cypress/src/integration/questions/write.spec.ts
- src/pages/Question/Content/Common/FormFields/QuestionCategory.field.tsx
- src/pages/Question/QuestionFilterHeader.tsx
- src/pages/Question/question.routes.test.tsx
- src/pages/common/Category/CategoriesSelectV2.tsx
PR Checklist
PR Type
Not sure at which points this category select for questions was working, but it is definitely now and have a test to check.
> fix: questions form category select

- src/models/research.models.tsx
- src/stores/Question/question.store.tsx
- src/stores/Research/research.store.tsx
- src/stores/common/toggleDocUsefulByUser.ts
- src/utils/searchHelper.test.ts
- src/utils/searchHelper.ts
PR Checklist
PR Type
Introduces `keywords`, `totalUpdates` and `totalUsefulVotes` fields so we can filter/sort directly on the database.
Very similar to the work done for the questions search.
Also adds the username to the searchable words and improves keywords method to ignore special characters.
The main difference from questions is that we now have existing items to migrate. @thisislawatts any advice on that?
Pre-work for #3405
> feat: add keywords, totalUpdates and totalUsefulVotes fields to research

- src/stores/Question/question.store.test.tsx
- src/stores/Question/question.store.tsx
PR Checklist
PR Type
Removes question store code that was fetching all questions when that's no longer necessary.
This also removes unnecessary tests as the question fetching is already tested on question.service.test.ts file.
> fix: question store was still fetching all questions

- packages/components/src/CreateComment/CreateComment.tsx
- packages/components/src/CreateReply/CreateReply.stories.tsx
- packages/components/src/CreateReply/CreateReply.test.tsx
- packages/components/src/CreateReply/CreateReply.tsx
- src/pages/Research/Content/ResearchComments.tsx
- src/stores/Research/research.store.test.ts
- src/stores/Research/research.store.tsx
PR Checklist
PR Type
Adds support for Nested Comments (or replies) on Research content
> feat: support nested comments on Research comments

- src/stores/Discussions/discussions.store.tsx
- src/stores/Message/message.store.tsx
- src/stores/Question/question.store.tsx
PR Checklist
PR Type
Having lots of things observable is causing unvaluable downloading of documents. Plus calling all records in certain stores is totally unnecessary.
> Feat: Start dropping observability

- src/models/howto.models.tsx
- src/stores/Howto/howto.store.tsx
PR Checklist
PR Type
Groundwork for a future howto search refactor.
The migration can be executed after merging this.
Note: totalUsefulVotes is already being updated for howtos since #3406
> feat: add keywords & totalComments to howtos

- src/pages/Howto/Content/Howto/Howto.test.tsx
- src/pages/Howto/Content/Howto/HowtoDescription/HowtoDescription.tsx
- src/pages/Question/QuestionPage.tsx
- src/pages/Question/question.routes.test.tsx
- src/pages/Research/Content/ResearchArticle.test.tsx
- src/pages/Research/Content/ResearchDescription.tsx
- src/stores/Howto/howto.store.test.ts
- src/stores/Howto/howto.store.tsx
- src/stores/Question/question.store.test.tsx
- src/stores/Question/question.store.tsx
- src/stores/Research/research.store.test.ts
- src/stores/Research/research.store.tsx
- src/stores/RootStore.tsx
- src/stores/common/incrementDocViewCount.tsx
- src/utils/helpers.ts
- src/utils/incrementViewCount.test.ts
- src/utils/incrementViewCount.ts
PR Checklist
PR Type
Calls to increment the total views of a document required a read of the document every time. This removes that read and doesn't require the updated views for the document view. It also wraps these calls in a single util wrapper for a consistent implementation (which was missing on questions). Also, unnessary setting of data was happening.
> Refactor: increment counts

- packages/cypress/src/integration/questions/write.spec.ts
- src/pages/Research/Content/Common/Research.form.tsx
- src/stores/Howto/howto.store.tsx
- src/stores/Question/question.store.test.tsx
- src/stores/Question/question.store.tsx
- src/stores/Research/research.store.tsx
- src/stores/common/__mocks__/module.store.ts
- src/stores/common/module.store.test.tsx
- src/stores/common/module.store.ts
PR Checklist
PR Type
1) Moves slug setting related responsibilities to module store.
2) Add previous slugs to questions.
3) Tidies up a little.
Closes #3325 #3359
---
> Refactor: Slugs

- packages/cypress/src/integration/howto/read.spec.ts
A quick fix to get the CI tests passing for an important fix we need to get out.
> chore: temporarily comment out image gallery feat test

- packages/cypress/src/integration/SignUp.spec.ts
- packages/cypress/src/integration/howto/write.spec.ts
- packages/cypress/src/integration/notificationBanner.spec.ts
- packages/cypress/src/integration/research/write.spec.ts
- packages/cypress/src/integration/settings.spec.ts
- packages/cypress/src/integration/unsubscribe.spec.ts
- packages/cypress/src/support/hooks.ts
- packages/cypress/src/utils/TestUtils.ts
- src/pages/Unsubscribe/Unsubscribe.test.tsx
- src/pages/Unsubscribe/Unsubscribe.tsx
PR Checklist
PR Type
Following the issue https://github.com/ONEARMY/community-platform/issues/3475
- It was removed unnecessary `cy.wait` then it can save some test running time
- move `cy.deleteCurrentUser` to `beforeEach` instead of after as best practice
- Removed duplicate `generateId` code as best practice
Closes #
--- …
> refactor: e2e best practice #3475

- .all-contributorsrc
- README.md
- packages/cypress/src/integration/SignUp.spec.ts
- packages/cypress/src/integration/howto/write.spec.ts
- packages/cypress/src/integration/notificationBanner.spec.ts
- packages/cypress/src/integration/research/write.spec.ts
- packages/cypress/src/integration/settings.spec.ts
- packages/cypress/src/integration/unsubscribe.spec.ts
- packages/cypress/src/support/hooks.ts
- packages/cypress/src/utils/TestUtils.ts
- src/pages/Unsubscribe/Unsubscribe.test.tsx
- src/pages/Unsubscribe/Unsubscribe.tsx
- src/stores/Maps/maps.store.ts
- src/stores/common/module.store.ts
- src/stores/databaseV2/CollectionReference.ts
- src/stores/databaseV2/types/AbstractDatabaseClient.ts
- src/stores/databaseV2/types/index.d.ts
There was an annoying merge conflict between the release candidate and the current production branch. This branch rebases the release PRs on top of production manually.
(Now I'm co-author on everything, you're welcome.)
> Fix: Conflicts for release

- packages/cypress/src/integration/notificationBanner.spec.ts
- shared/mocks/data/users.ts
PR Checklist
PR Type
Looking into failing e2e tests.
* Update the authId on the seeded user account to match AuthID of account in test Project
> test: update authId to match auth id

- packages/documentation/docs/Maintainers/Rollback.md
PR Checklist
PR Type
Introduces documentation for rollback process.
> docs: outline steps for rollback

- packages/components/src/ResearchEditorOverview/ResearchEditorOverview.tsx
- packages/components/src/ResearchEditorOverview/__snapshots__/ResearchEditorOverview.test.tsx.snap
- src/pages/Research/Content/Common/PostingGuidelines.tsx
- src/pages/Research/Content/Common/Research.form.tsx
- src/pages/Research/Content/Common/ResearchUpdate.form.tsx
- src/pages/Research/Content/Common/SubmitStatus.tsx
- src/pages/Research/Content/ResearchDescription.tsx
- src/pages/Research/Content/ResearchList.tsx
- src/pages/Research/Content/ResearchUpdate.tsx
Refactoring upload submit modal to remove some duplication
PR Checklist
PR Type
This PR update some Headings components to a specific html heading tag from the default h2. There is some debate to have to some choices. Like for the upload status modal, I chose "p" but h2 or h3 could be valid. 
Helps to close #3424 
---
If you need more immediate feedback you can try reaching out on Discord in the [Community Platform …
> feat(seo): Update headings for research section

- src/pages/policy/PrivacyPolicy.tsx
- src/pages/policy/TermsPolicy.tsx
PR Checklist
PR Type
- [?] Bug fix (non-breaking change which fixes an issue)
- [?] New feature (non-breaking change which adds functionality)
This PR update h2 tags to h1 for the two policy pages. 
@benfurber I have hesitation of the correct tag for the `Updated 20th January 2020` part of the terms page.
Maybe  the [\<time />](https://www.codecademy.com/resources/docs/html/semantic-html/time) tag is more adequate ?
Help to closes #3424
---
If you need more immediate feedback you can …
> feat(seo): Update headings for policy pages

- src/pages/Howto/labels.ts
- src/pages/Question/labels.ts
- src/pages/Research/labels.ts
> fix: content search labels

- src/pages/Howto/Content/Common/Howto.form.tsx
- src/pages/Howto/Content/Common/HowtoFieldStep.tsx
- src/pages/Howto/Content/Common/HowtoFieldStepsContainer.tsx
- src/pages/Howto/Content/Common/PostingGuidelines.tsx
- src/pages/Howto/Content/Common/SubmitStatus.tsx
- src/pages/Howto/Content/Howto/HowtoDescription/HowtoDescription.tsx
- src/pages/Howto/Content/Howto/Step/Step.tsx
- src/pages/Howto/Content/HowtoList/HowToCard.tsx
- src/pages/Howto/Content/HowtoList/HowtoList.tsx
PR Checklist
PR Type
- [?] Bug fix (non-breaking change which fixes an issue)
- [?] New feature (non-breaking change which adds functionality)
This PR update some Headings components in the Howto module to a specific html heading tag from the default h2 to h1, h2 or p.
Help to closes #3424
--- …
> feat(seo): update headings for Howto Module

- firebase.json
- firestore.rules
PR Checklist
PR Type
Adds a reference to the rules configuration so that it will be deployed as part of the roll out process. Currently Firestore security rules are being manually configured. 
Here is the documentation around this property:
https://firebase.google.com/docs/cli#the_firebasejson_file
> feat: deploy firestore rules

- firestore.indexes.json
- src/models/common.models.tsx
- src/pages/Research/Content/ResearchList.tsx
- src/pages/Research/labels.ts
- src/pages/Research/research.service.test.ts
- src/pages/Research/research.service.ts
- src/pages/common/Drafts/DraftButton.test.tsx
- src/pages/common/Drafts/DraftButton.tsx
- src/pages/common/Drafts/useDrafts.tsx
- src/pages/common/labels.ts
PR Checklist
PR Type
- Ensures only accepted research items appear on the list.
- Adds a new section to display the user's non-accepted research items.
Closes #3503
https://github.com/ONEARMY/community-platform/assets/8073622/ad6b5aa5-2a26-413a-87c8-4c7c1105e191
> feat: research draft list

- packages/components/src/ArticleCallToAction/ArticleCallToAction.stories.tsx
- packages/components/src/UsefulStatsButton/UsefulStatsButton.stories.tsx
- packages/components/src/UsefulStatsButton/UsefulStatsButton.tsx
- packages/components/src/UserEngagementWrapper/UserEngagementWrapper.stories.tsx
- src/pages/Howto/Content/Howto/Howto.tsx
- src/pages/Howto/Content/Howto/HowtoDescription/HowtoDescription.tsx
- src/pages/Research/Content/ResearchArticle.tsx
- src/pages/Research/Content/ResearchDescription.tsx
PR Checklist
PR Type
Fixes useful vote click spam by awaiting for the action to complete.
Closes #
> fix: useful button click spam

- firestore.rules
PR Checklist
PR Type
Closes #
---
> fix(security-rules): unblock v3 categories

- packages/components/src/Breadcrumbs/BreadcrumbsItem.tsx
- packages/cypress/src/integration/howto/comments.spec.ts
- packages/cypress/src/integration/howto/read.spec.ts
- packages/cypress/src/integration/questions/read.spec.ts
- packages/cypress/src/integration/research/read.spec.ts
- packages/cypress/src/integration/research/write.spec.ts
- shared/mocks/data/howtos.ts
- shared/mocks/data/research.ts
- shared/mocks/data/researchCategories.ts
PR Checklist
PR Type
Adding basic e2e tests for breadcrumbs.
> test: add for breadcrumbs

- packages/cypress/cypress.config.ts
PR Checklist
PR Type
- refactoring
The Boolean was changed in this commit https://github.com/ONEARMY/community-platform/commit/a998fd80c34a552dd90362d2eb5c4e8e53e96812 but the comment was not removed.
remove outdated comment
> refactor: remove outdated comment

- packages/components/src/NotificationList/NotificationList.stories.tsx
- packages/components/src/NotificationList/NotificationList.tsx
- packages/components/src/index.ts
- src/pages/common/Header/Header.tsx
- src/pages/common/Header/Menu/Notifications/NotificationsDesktop.tsx
- src/pages/common/Header/Menu/Notifications/NotificationsMobile.tsx
- src/pages/common/Header/getFormattedNotifications.tsx
- src/stores/User/notifications.store.ts
PR Checklist
PR Type
Fixes an infinite loop when the notifications tab is open.
A bit of code cleanup.
Closes #3592
> fix: notifications infinite loop

- packages/cypress/src/integration/research/read.spec.ts
PR Checklist
PR Type
- chore
Fix typo.
> chore: add closing bracket

- packages/cypress/src/integration/questions/write.spec.ts
- src/common/Form/types.ts
- src/common/Tags/TagsList.tsx
- src/models/question.models.tsx
- src/pages/Question/Content/Common/FormFields/QuestionTitle.field.tsx
- src/pages/Question/Content/Common/QuestionForm.tsx
- src/pages/Question/question.routes.test.tsx
- src/pages/Research/Content/Common/Research.form.tsx
- src/pages/Research/Content/Common/ResearchUpdate.form.tsx
- src/stores/Question/question.store.test.tsx
- src/stores/Question/question.store.tsx
- src/stores/common/module.store.ts
- src/test/factories/Question.ts
- src/utils/validators.ts
PR Checklist
PR Type
Addes a UI form check and store check for the uniqueness of question titles.
Closes #3573
> feat: add unique title check to questions

- packages/cypress/src/integration/howto/write.spec.ts
- packages/cypress/src/support/CustomAssertations.ts
- src/pages/Howto/Content/Common/Howto.form.tsx
PR Checklist
PR Type
Editing an already accepted Howto no longer reverts it to awaiting-moderation.
Closes #3613
> chore: do not require approval on an already accepted howto

- package.json
PR Checklist
PR Type
- chore
Remove outdated script.
commit where healthcheck.js was introduced: https://github.com/ONEARMY/community-platform/commit/916451e7763b1fea9d2bf069374c0bd94c2429bf
commit where healthcheck.js was deleted: https://github.com/ONEARMY/community-platform/commit/b42eff056b664faf483c51487a0e17741048a08a
> chore: remove outdated healthcheck script

- packages/components/src/Tag/Tag.tsx
- packages/components/src/TagList/TagList.tsx
PR Checklist
PR Type
Issue on prod - whole questions not displayed because of a weird tag issue.
## Image
[This on prod](https://community.preciousplastic.com/questions/any-active-precious-plastic-team-in-barcelona--) (currently with a spinner), now fine locally with this fix:
> fix: filter out undefined tags in list

- firestore.indexes.json
- src/pages/Howto/howto.service.ts
- src/pages/Research/Content/ResearchListItem.tsx
- src/pages/Research/research.service.ts
PR Checklist
PR Type
Changes Howtos and Research Items to filter by `_contentModifiedTimestamp` instead of `_modified`.
Also updates the Research listing display.
Closes #3558
> fix: search by modified

- functions/src/emailNotifications/createNotificationEmails.spec.ts
PR Checklist
PR Type
Following issue #2795, adds asserts based on the content of the email. 
Please tell me if too many assertions were added. I only added a check for presence of links, but no check on the number of occurrences. I can add it if useful.
Closes #2795
/
> test(functions): improve testing of notification email content (#2795)

- src/pages/Research/Content/ResearchListItem.tsx
PR Checklist
PR Type
Prevents an error when `_contentModifiedTimestamp` is undefined
Closes #
> fix: research modified timestamp

- packages/cypress/src/integration/questions/discussions.spec.ts
- shared/mocks/data/discussions.ts
- src/pages/Question/question.routes.test.tsx
- src/stores/Discussions/discussions.store.tsx
- vite.config.ts
PR Checklist
PR Type
Fixes the issue with how mentions are displayed in comments/replies.
> fix: display of mentions in discussion comments

- src/pages/Question/question.routes.test.tsx
> test: change routes test timeout to 15 seconds

- src/stores/Maps/filter.ts
PR Checklist
PR Type
Filters by member if no filters and website is precious plastic
Closes #3555
> fix: hide member mappins for precious plastic

- firestore.indexes.json
PR Checklist
PR Type
Some search combinations were not working
> fix: firestore indexes

- src/pages/Research/Content/ResearchFilterHeader.tsx
- src/pages/Research/Content/ResearchList.tsx
PR Checklist
PR Type
default research sort should be last updated
Closes #3662
---
> fix(research): change default sort to last updated

- src/pages/User/impact/Impact.test.tsx
- src/pages/User/impact/ImpactItem.test.tsx
- src/pages/UserSettings/content/formSections/Impact/impactQuestions.ts
- src/pages/UserSettings/content/formSections/Impact/utils.test.ts
PR Checklist
PR Type
chang '$' to 'USD' (finishing off https://github.com/ONEARMY/community-platform/pull/3315)
Closes #
---
> fix(impact): change $ to USD

- functions/package.json
- functions/src/Integrations/firebase-slack.ts
- yarn.lock
PR Checklist
PR Type
see slack webhook docs: https://api.slack.com/messaging/webhooks
Closes #3617
---
> chore(functions): remove request dependency

- packages/components/src/ButtonShowReplies/ButtonShowReplies.tsx
PR Checklist
PR Type
This PR updates the "Show Replies" button functionality. It enhances the user experience by making the button more intuitive and responsive, ensuring that replies are displayed or hidden correctly when the button is clicked.
Closes #3655
--- …
> fix: the reply button UI

- packages/components/src/CommentItem/CommentItem.tsx
PR Checklist
PR Type
Decrease the margin-top to the `comment-text`
Closes https://github.com/ONEARMY/community-platform/issues/3650
> feat: decrease margin top comment

- packages/cypress/src/integration/howto/read.spec.ts
- shared/mocks/data/howtos.ts
- shared/mocks/data/messages.ts
- shared/mocks/data/tags.ts
- src/stores/Howto/howto.store.tsx
- src/stores/Tags/tags.store.tsx
PR Checklist
PR Type
We've got a high risk flaky test:
This PR does the bare minimum to reduce that flakiness.
> test: fix flacky tag expectation

- packages/components/src/UserStatistics/UserStatistics.tsx
- src/pages/User/content/MemberProfile.tsx
PR Checklist
PR Type
Fixing a few spacing issues on the profile page - a recent regression.
Before: 
After:
> fix: spacing on profile

- packages/components/src/Icon/Icon.tsx
- src/common/Form/ImageInput/ImageInput.tsx
PR Checklist
PR Type
Fixes submit on image upload.
Fixes icon size.
Closes #3691
> fix: image input & icon

- functions/src/Integrations/firebase-discord.ts
- functions/src/Integrations/firebase-slack.ts
- functions/src/Integrations/index.ts
feature
Make message in Discord when a new Research Update is created.
Doesn't close, but for: https://github.com/ONEARMY/community-platform/issues/3533
demo:
https://www.youtube.com/watch?v=LD1Rj0OrHDg
> Add research update webhook

- scripts/postBuild.ts
PR Type
cleanup code
Description
Code cleanup and fixes one of the meta tags from being incorrect.
related to, but does not fully fix (I think) https://github.com/ONEARMY/community-platform/issues/3633
It might be easier to review this one commit by commit.
example output, to know I didn't break anything:
```
yarn run build
export REACT_APP_PLATFORM_THEME=project-kamp
yarn run build:post
(node:40156) ExperimentalWarning: `--experimental-loader` may be removed in the future; instead use `register()`:
--import 'data:text/javascript,import { register } from "node:module"; import { pathToFileURL } from "node:url"; register("ts-node/esm", pathToFileURL("./"));'
(Use `node --trace-warnings ...` to show where the warning was created)
Writing configuration into the global window object...
The …
```
> 3633 meta tags 1

- functions/emulator/Dockerfile
PR Type
chore
Add healthcheck to backend docker container.
> chore: add healthcheck to backend emulator

- src/pages/Research/research.routes.test.tsx
> fix: research test

- functions/src/emailNotifications/templates/index.ts
PR Checklist
PR Type
Fixes error getting email templates that prevented sending emails.
> fix: send emails

- src/pages/Research/Content/ResearchList.tsx
PR Checklist
PR Type
Always displays drafts for PP users.
Closes #3713
> fix: research drafts

- packages/components/src/Button/Button.tsx
- src/pages/UserSettings/content/formSections/Focus.section.tsx
PR Checklist
PR Type
Fixes guidelines button
Closes #
> fix: default-button

- packages/components/src/CommentItem/CommentItem.tsx
PR Checklist
PR Type
it improves the date display in comment section.
Closes #3653
---
> fix: improve date display

- packages/components/src/CommentItem/CommentItem.stories.tsx
- packages/components/src/CommentItem/CommentItem.tsx
PR Checklist
PR Type
- Add default avatar to the CommentItem when creatorImage is not defined.
- Align avatar horizontally as per the screenshot in this issue
- Add storybook story
Closes #3654
---
> fix: add default avatar to CommentItem

- src/pages/Research/research.routes.test.tsx
PR Checklist
PR Type
For a bit of time (probably since the vite upgrade) the research route test(s) have been flaky, looking for expectation that isn't ready as the component is still loading.
> test: fix async error in route tests

- packages/components/src/DiscussionContainer/DiscussionContainer.test.tsx
- src/common/ScrollToTop.test.tsx
- src/logger/index.ts
- src/pages/Howto/Content/Howto/Howto.test.tsx
- src/pages/Question/question.routes.test.tsx
- src/pages/Research/Content/ResearchArticle.test.tsx
- src/pages/UserSettings/content/formSections/UserProfile.test.tsx
- src/stores/Discussions/discussion.store.test.ts
- src/stores/Question/question.store.tsx
PR Checklist
PR Type
Resolved all instances of the warning "Warning: An update to observerComponent inside a test was not wrapped in act(...)" by properly wrapping relevant updates in act() functions.
Configured the application logger to suppress logging when running in the test environment, ensuring cleaner test outputs and improved test performance.
Closes #3303 
--- …
> fix: handle jest console warnings

- src/pages/Question/QuestionListItem.tsx
- src/pages/Question/QuestionListing.tsx
- src/pages/Research/Content/ResearchList.tsx
- src/pages/Research/Content/ResearchListItem.tsx
- src/pages/common/UserNameTag/UserNameTag.tsx
PR Checklist
PR Type
- Fixed the nested anchor tag issue by placing the main link around the title inside the `<h2>` tag inside each card, following the pseudo-content approach recommended in  [Inclusive Components](https://inclusive-components.design/cards/).
- Additionally, wrapped the list of cards in a `<ul>` element and set the as property of each card to `li` to improve accessibility.
Closes #3278 
---
If you need more immediate feedback you can try reaching out on Discord in the [Community …
> fix: nested anchor tags in ResearchListItem

- functions/src/Integrations/firebase-discord.test.ts
- functions/src/Integrations/firebase-discord.ts
PR Type
chore
Description
improve unit test
> chore: improve unit testing interface

- src/pages/UserSettings/content/formSections/UserProfile.section.tsx
PR Checklist
PR Type
Quick fix to a test failure that's blocking a release.
> fix: showing form notifications

- packages/cypress/src/integration/howto/write.spec.ts
- packages/cypress/src/integration/research/write.spec.ts
- packages/cypress/src/support/commandsUi.ts
PR Checklist
PR Type
- Add `fillIntroTitle` to `commandUI.ts` will reduce duplicate code
> [e2e]: Create commandUi fillIntroTitle

- src/pages/Question/Content/Common/FormFields/QuestionTitle.field.tsx
- src/pages/Research/research.routes.test.tsx
- src/utils/validators.test.ts
- src/utils/validators.ts
PR Checklist
PR Type
Add a new validator ( endsWithQuestionMark ) that validates the value allowing only one question mark at the end. Also, it modifies the composeValidator function to return multiple error messages at once.
Closes #3604 
---
> [feat]: Add question mark validation to question title form

- src/pages/Research/Content/EditUpdate/index.tsx
Clicking edit on a research update gives an error page to the user.
Works as expected :)
Closes #3771
> fix: research update edit

- packages/components/src/Alert/Alert.stories.tsx
- packages/components/src/ArticleCallToAction/ArticleCallToAction.stories.tsx
- packages/components/src/BlockedRoute/BlockedRoute.stories.tsx
- packages/components/src/Breadcrumbs/Breadcrumbs.stories.tsx
- packages/components/src/CommentItem/CommentItem.stories.tsx
- packages/components/src/CommentList/CommentList.stories.tsx
- packages/components/src/ConfirmModal/ConfirmModal.stories.tsx
- packages/components/src/ContentStatistics/ContentStatistics.stories.tsx
- packages/components/src/CreateComment/CreateComment.stories.tsx
- packages/components/src/CreateReply/CreateReply.stories.tsx
- packages/components/src/DiscussionContainer/DiscussionContainer.stories.tsx
- packages/components/src/DiscussionTitle/DiscussionTitle.stories.tsx
- packages/components/src/EditComment/EditComment.stories.tsx
- packages/components/src/Heading/Heading.stories.tsx
- packages/components/src/HeroBanner/HeroBanner.stories.tsx
- packages/components/src/ImageGallery/ImageGallery.stories.tsx
- packages/components/src/Input/Input.stories.tsx
- packages/components/src/Loader/Loader.stories.tsx
- packages/components/src/MapMemberCard/MapMemberCard.stories.tsx
- packages/components/src/Modal/Modal.stories.tsx
- packages/components/src/MoreContainer/MoreContainer.stories.tsx
- packages/components/src/NotificationList/NotificationList.stories.tsx
- packages/components/src/ResearchEditorOverview/ResearchEditorOverview.stories.tsx
- packages/components/src/Select/Select.stories.tsx
- packages/components/src/SiteFooter/SiteFooter.stories.tsx
- packages/components/src/TextNotification/TextNotification.stories.tsx
- packages/components/src/Textarea/Textarea.stories.tsx
- packages/components/src/UserEngagementWrapper/UserEngagementWrapper.stories.tsx
- packages/components/src/UserStatistics/UserStatistics.stories.tsx
What type and range of components we have can be hard to find.
Adds sections to the component library so it's easier to find different types of stuff.
> chore: add sections to component library

- packages/components/src/CommentList/CommentList.test.tsx
- packages/components/src/CommentList/CommentList.tsx
Shows 5 comments at a time.
Shows 10 comments at a time. (Discussion with Dave)
> feat: show more comments by default

- src/pages/UserSettings/content/formSections/UserProfile.section.tsx
> fix: show notifications on user profile form

- .cspell.json
- packages/documentation/docs/Deployment/circle-ci.md
> docs: add docs for function variables

- src/pages/Research/Content/ResearchArticle.tsx
> fix: scrolling comments and updates on research

- src/utils/validators.test.ts
- src/utils/validators.ts
Correctly formed questions weren't being saved.
Correctly formed questions are being saved.
The question mark validator was erroring when it was called without a value during the final form validation flow. This ensures that the question mark validator returns and thus enables a positive validation.
> fix: question mark validator on question create

- packages/cypress/src/integration/questions/write.spec.ts
- packages/cypress/src/support/rules.ts
- shared/mocks/data/questions.ts
- src/pages/Question/Content/Common/FormFields/QuestionCategory.field.tsx
- src/pages/Question/Content/Common/FormFields/QuestionTitle.field.tsx
- src/pages/Question/Content/Common/QuestionForm.tsx
- src/stores/Question/question.store.tsx
- src/stores/databaseV2/clients/DexieClient.ts
- src/utils/getUserCountry.ts
No question create/edit test.
There's a question create/edit test.
> fix: blocked create questions test

- src/pages/Research/constants.ts
implements #3818
Currently the maximum length of description is 1000 characters
Increased the limit to 3000 characters
Closes #
> feat(research): changed max length of research description from 1000 to 3000

- src/common/Form/ImageInput/ImageInputWrapper.tsx
> fix: border to image upload button

- packages/cypress/src/integration/research/write.spec.ts
Very flaky test from #3838
More consistent passing.
> fix: flaky research update test

- packages/components/src/Breadcrumbs/Breadcrumbs.tsx
- packages/components/src/Breadcrumbs/BreadcrumbsItem.tsx
the chevron is not aligned :(
the chevron is aligned :)
> fix: alignment of breadcrumbs chevron

- packages/components/package.json
- packages/components/scripts/newComponent.ts
- packages/components/src/CardList/CardList.tsx
@kimskovhusandersen's fix in #3770 for the new component script
> fix: new component script

- packages/components/src/CardButton/CardButton.tsx
- packages/components/src/FilterList/FilterList.tsx
- server.js
- src/pages/Maps/Maps.client.tsx
- src/pages/Maps/map.service.ts
1. Logged in users triggers a map useEffect to append their pin to the main pins list.
2. Some random prop error around styling.
3. The map api isn't on the approved sources list (related to remix migration).
All the above fixed.
> fix: render issues on new map

- server.js
sentry.io is being blocked
unblocks :)
Closes #
> fix: sentry CSP

- .github/workflows/docs-deploy.yml
- packages/documentation/README.md
- packages/documentation/docs/Docs Contribution/md-style-guide.md
- packages/documentation/docusaurus.config.gh-pages.js
- packages/documentation/docusaurus.config.js
- packages/documentation/package.json
- yarn.lock
Docs do not deploy
Docs deploy
Closes #
> fix: docs deploy referencing deleted config + docusaurus upgrade

- .github/workflows/fly-pr-preview.yml
- fly-preview.toml
PR preview broken
Adds fly.io pr preview
Closes #
> build: add fly preview workflow

- src/pages/Question/QuestionListItem.tsx
- src/pages/Question/QuestionListing.tsx
Closes https://github.com/ONEARMY/community-platform/issues/3900
> chore: update questions ui

- packages/cypress/src/integration/map.spec.ts
using cy.wait
Improvements on map.spec.ts
1. Wait for API call `londonSearch` to make the assertions
> test: refactor cy map 

- src/common/Form/PasswordField.tsx
- src/pages/SignUp/SignUp.tsx
- src/pages/UserSettings/content/sections/ChangeEmail.form.tsx
- src/pages/UserSettings/content/sections/ChangePassword.form.tsx
- src/pages/UserSettings/labels.ts
placeholder shows 'testing'
placeholder shows correct text
Closes #
> fix: signup password placeholder

- .github/workflows/fly-pr-preview.yml
Fly pr preview not working
Adds default environment variables required by dockerfile
Closes #
> feat: add default preview environment variables

- .github/workflows/fly-pr-preview.yml
Typo in variable name
Typo fixed
Closes #
> fix: preview config variable typo

- .github/workflows/fly-pr-preview.yml
References specific release version
Setting to latest tag to reduce need for version changes whilst debugging
Closes #
> feat: set preview action tag to latest

- packages/cypress/package.json
- packages/cypress/src/fixtures/howto.ts
- packages/cypress/src/fixtures/question.ts
- packages/cypress/src/fixtures/research.ts
- packages/cypress/src/integration/howto/discussions.spec.ts
- packages/cypress/src/integration/questions/discussions.spec.ts
- packages/cypress/src/integration/research/discussions.spec.ts
- packages/cypress/src/support/commands.ts
- packages/cypress/src/support/commandsUi.ts
- packages/cypress/src/support/db/firebase.ts
- packages/cypress/src/utils/TestUtils.ts
- shared/models/questions.ts
- shared/models/research.ts
- src/common/DiscussionWrapper.tsx
- yarn.lock
CI is blocked as all the discussion tests are failing.
Adds fixtures and cy commands for the fixtures that create new documents for the discuss tests to then use.
Closes #3939
> fix: discussion tests for ci

- Dockerfile.preview
- fly-preview.toml
Fly config around vm sizing not right
Fly config updated with more suitable values
Closes #
> feat: update preview deploy config

- .github/workflows/fly-pr-preview.yml
- fly-preview.toml
1 cpu which can't be provisioned with 4gb of memory + paris region.
Updated to 2 cpu's and changed to amsterdam region (slightly cheaper)
Closes #
> build: update fly preview cpu and region

- src/pages/Howto/Content/Howto/Howto.tsx
Useful count isn't updated on the Call to Action section.
Updates as expected.
> fix: howto useful count when using the "call to action" section

- src/routes/_.privacy.tsx
- src/routes/_.terms.tsx
terms and privacy pages are rendered client side
terms and privacy pages are rendered server side
Closes #3933 
Closes #3934 
> feat: terms and privacy pages ssr

- packages/components/src/IconCountWithTooltip/IconCountWithTooltip.tsx
Tooltips get confused due to sharing the same id.
https://github.com/ONEARMY/community-platform/pull/3962#discussion_r1818191241
Fixes that by creating a unique id for each one.
Closes #
> fix: tooltip render

- fly-ff.toml
- fly-pk.toml
- fly-pp.toml
Currently using paris (cdg) as our deploy region and both machines for all apps stay running 24/7.
Switches to using amsterdam (ams) as it's slightly cheaper and updates config to test on fixing fashion whether auto suspend for 1 machine works for us to save resources.
Closes #
If you need more immediate feedback you can try reaching out on Discord in the …
> build: update fly deploy region to amsterdam + test auto suspend on fixing fashion app

- packages/components/src/IconCountWithTooltip/IconCountWithTooltip.tsx
- src/pages/Question/QuestionListItem.tsx
- src/pages/Question/QuestionListing.tsx
> fix: #3964 which is erroring locally

- .github/workflows/preview-label-removed.yml
Version number not recognised
Updated to v1
Closes #
> build: update destroy app action version number

- .github/actions/destroy-fly-preview-app/Dockerfile
Set docker file entrypoint permissions to allow execution
Closes #
> build: add action dockerfile permissions update

- .github/actions/destroy-fly-preview-app/entrypoint.sh
- .github/workflows/pr-preview-fly-deploy.yml
- .github/workflows/pr-preview-fly-destroy.yml
- .github/workflows/pr-preview-remove-label.yml
Same workflow was handling pr's that were closed as well as labelled
Separated concerns so that separate workflow handling pr's that are closed and improved naming of workflows
Closes #
> build: pr preview workflow improvements

- src/pages/Howto/Content/Howto/Howto.tsx
- src/pages/Question/QuestionEdit.tsx
- src/pages/Question/QuestionPage.test.tsx
- src/pages/Question/QuestionPage.tsx
- src/pages/Question/question.service.ts
- src/pages/Research/Content/ResearchArticle.tsx
- src/routes/_.questions.$slug._index.tsx
- src/routes/_.questions.$slug.edit.tsx
- src/routes/_.questions.tsx
- src/stores/Question/question.store.test.tsx
- src/stores/Question/question.store.tsx
- src/stores/Research/research.store.test.ts
- src/stores/Research/research.store.tsx
- src/stores/common/toggleDocSubscriberStatusByUserName.ts
Question page is rendered client-side.
Question page is rendered **server-side**.
Closes #3919
> feat: question ssr

- src/common/Form/ImageInput/compressImage.ts
Image quality is too low.
Increases the compression quality.
Closes #
> fix: improve image compression quality

- src/stores/Discussions/discussions.store.tsx
In case of duplicate discussions, returns the one with comments.
This obviously is a bandage fix, will be improved once we move to supabase.
> fix: duplicate discussions

- .gitignore
- src/pages/Research/Content/Common/Research.form.tsx
- src/pages/Research/Content/Common/ResearchUpdate.form.tsx
- src/stores/Research/research.store.tsx
The lock feature is blocking users from updating by overriding with old data.
Removes the lock feature.
Closes #
> fix: research save by removing lock feature

- packages/components/src/CardProfile/CardDetailsMemberProfile.tsx
- packages/components/src/CardProfile/CardDetailsSpaceProfile.tsx
- packages/components/src/PinProfile/PinProfile.tsx
- shared/models/maps.ts
1. Profile images for map load lazy.
2. Fix contact button showing for spaces who haven't opted out.
> feat: quick map pin fixes 

- packages/components/src/MapFilterList/MapFilterList.tsx
- packages/components/src/Username/UserBadge.tsx
- packages/components/src/Username/Username.tsx
- src/pages/Maps/Content/MapView/MapWithList.tsx
- src/pages/Maps/Content/MapView/MapWithListHeader.tsx
- src/pages/Maps/Content/MapView/allMapFilterOptions.ts
- src/pages/Maps/utils/filterPins.test.ts
- src/pages/Maps/utils/filterPins.ts
1. Adds a verified and supporter filter option to the map.
2. Adds a responsive layout to the filter modal display.
> feat: add badge filters to new map

- packages/documentation/docs/Backend Development/firestore-backup.md
No changes to current behavior.
Corrects a grammatical mistake in the documentation: added missing words for clarity in the "Configuring Permissions" section.
> Fixed a grammatical error in the documentation.

- src/routes/_.how-to.$slug._index.tsx
- src/routes/_.questions.$slug._index.tsx
- src/routes/_.research.$slug._index.tsx
- src/routes/_.u.$id._index.tsx
Adds a hydration fallback to ssr pages.
Closes #4015
> fix: hydration on ssr pages

- .github/workflows/pr-preview-fly-deploy.yml
- src/pages/common/CommentsV2/CommentItemV2.tsx
> chore: test preview

- .env
Clearer notes about the .env file variables - I've been confused myself recently
> chore: add consistent notes for .env variables

- src/pages/UserSettings/content/fields/CustomRadio.field.tsx
- src/pages/UserSettings/content/sections/Focus.section.tsx
> fix: settings SVGs on mobile

- src/pages/common/CommentsV2/CommentSectionV2.tsx
Always display highlighted comment
Closes #
> feat: ensure highlighted comment is visible

- packages/cypress/src/integration/howto/discussions.spec.ts
- packages/cypress/src/integration/map.spec.ts
- shared/mocks/data/discussions.ts
A how-to discussion test and a map test were recently commented out because they were failing on ci.
Slightly edited tests are back in.
> ci: return howto and discussion e2e specs

- src/routes/api.comments.count.ts
Filters deleted comments counts from question comment count.
Closes #
> fix: question comment counts filter out deleted comments

- src/pages/common/CommentsV2/CreateCommentV2.css
- src/pages/common/CommentsV2/CreateCommentV2.tsx
> feat: bring comment ui improvements to comments v2 components

- packages/cypress/src/integration/howto/read.spec.ts
- packages/cypress/src/integration/map.spec.ts
- packages/cypress/src/integration/questions/read.spec.ts
- packages/cypress/src/integration/research/read.spec.ts
- src/routes/_.library._index.tsx
- src/routes/_.questions._index.tsx
The library and question index pages weren't having their page titles updated.
Fixed. Plus tests added to prevent regression.
> fix: add missing page title updates

- src/pages/Research/Content/ResearchArticle.tsx
When navigating between research articles, the research updates do not change.
Closes #
> fix: rendering research updates on navigation

- shared/models/user.ts
- src/pages/User/impact/ImpactField.tsx
- src/pages/User/impact/ImpactItem.tsx
- src/pages/User/impact/constants.ts
- src/pages/UserSettings/SettingsPageImpact.test.tsx
- src/pages/UserSettings/content/fields/ImpactQuestion.field.tsx
- src/pages/UserSettings/content/fields/ImpactYear.field.tsx
- src/pages/UserSettings/content/impactQuestions.ts
- src/pages/UserSettings/content/sections/ImpactYear.section.tsx
- src/pages/UserSettings/utils.test.ts
Adds 2024 to the impact years and does a few minor design tweaks.
Closes #4055
> feat: quick wins to release PP impact 2024

- packages/components/src/MapFilterList/MapFilterList.tsx
- packages/components/src/Modal/Modal.tsx
- src/pages/Maps/Content/MapView/MapView.tsx
1. fix: empty map on certain mobile scenarios
2. fix: max height sizing of modals on mobile
> fix: map ux for mobile

- src/pages/Maps/Content/MapView/MapView.tsx
- src/pages/common/Header/Menu/Notifications/NotificationsDesktop.tsx
> fix: zIndex ordering of map icons

- .github/workflows/pr-preview-fly-deploy.yml
> fix: supabase cli version

- .circleci/config.yml
> fix: supabase deploy version

- .github/pull_request_template.md
- .github/workflows/pr-preview-fly-deploy.yml
> chore: remove supabase schema sync on preview branches

- functions/src/supabaseSync/index.ts
- src/routes/api.discussions.$sourceId.comments.$id.ts
- src/routes/api.discussions.$sourceId.comments.ts
- src/routes/api.questions.$id.ts
- src/routes/api.questions.ts
- src/routes/api.subscribers.$contentType.$contentId.ts
- src/routes/api.useful.$contentType.$contentId.ts
> fix: duplicate profiles

- .circleci/config.yml
- shared/index.ts
> fix: firebase deploy

- src/routes/_.questions.$slug._index.tsx
> fix: question view counts

- src/pages/Maps/Content/MapView/MapView.tsx
The background of the map when zoomed out does not match the map.
The map background is changed to match the map.
Closes #4113
> fix: change map background color

- src/routes/_.update-password.tsx
> fix: weird update password bug

- README.md
- docs/supabase.md
> docs: updated getting started instructions

- functions/src/emailNotifications/createModerationEmails.spec.ts
- functions/src/emailNotifications/templates/map-pin-needs-improvements.html
- functions/src/emailNotifications/templates/map-pin-rejected.html
- packages/components/src/DisplayDate/DisplayDate.test.tsx
Map pin needs improvement emails include the feedback and the right PP profile guidelines.
> fix: map pin email templates

- packages/components/src/Breadcrumbs/BreadcrumbsItem.tsx
- packages/components/src/CommentBody/CommentBody.tsx
- packages/components/src/CommentDisplay/CommentDisplay.tsx
- packages/components/src/CreateComment/CreateComment.tsx
- packages/components/src/DiscussionContainer/DiscussionContainer.tsx
- packages/themes/src/common/index.ts
- src/pages/Library/Content/List/LibraryCard.tsx
- src/pages/Library/Content/List/LibraryList.tsx
- src/pages/Library/Content/Page/Library.tsx
- src/pages/Library/Content/Page/LibraryDescription.tsx
- src/pages/Library/Content/Page/LibraryDiscussion.tsx
- src/pages/Library/Content/Page/LibraryStep.tsx
- src/pages/Question/QuestionListing.tsx
- src/pages/Question/QuestionPage.tsx
- src/pages/Research/Content/ResearchArticle.test.tsx
- src/pages/Research/Content/ResearchArticlePage.tsx
- src/pages/Research/Content/ResearchDescription.tsx
- src/pages/Research/Content/ResearchListItem.tsx
- src/pages/Research/Content/ResearchUpdate.tsx
- src/pages/common/Breadcrumbs/Breadcrumbs.tsx
- src/pages/common/CommentsSupabase/CommentItemSupabase.tsx
- src/pages/common/CommentsSupabase/CreateCommentSupabase.tsx
- src/pages/common/Layout/ListHeader.tsx
- src/pages/common/Layout/Main.tsx
- src/routes/_.research.$slug._index.tsx
> feat: pages with comments more mobile friendly

- package.json
- packages/cypress/scripts/start.mts
- packages/cypress/src/integration/profile.spec.ts
- packages/cypress/src/integration/settings.spec.ts
- src/.server/templates/Layout.tsx
- src/.server/templates/RecieverMessage.tsx
- src/pages/User/contact/UserContactFieldMessage.tsx
- src/pages/User/contact/UserContactFieldName.tsx
- src/pages/User/contact/UserContactForm.test.tsx
- src/pages/User/contact/UserContactForm.tsx
- src/pages/UserSettings/SettingsPageUserProfile.tsx
- src/pages/UserSettings/content/sections/PublicContact.section.tsx
- src/routes/api.messages.tsx
- src/services/messageService.ts
- supabase/functions/send-email/_templates/layout.tsx
- yarn.lock
1. Updated the email template
2. Got a pattern between the API/FE that displays the errors (when they happen)
> feat: update user experience of contact form

- src/.server/templates/RecieverMessage.tsx
- src/routes/api.messages.tsx
> fix: name field use on message email

- src/pages/Library/Content/Page/LibraryStep.tsx
> fix: flex for library steps

- src/.server/templates/Layout.tsx
> fix: yet another email template typo

- src/pages/User/content/ProfileDetails.tsx
- src/pages/User/content/UserProfile.tsx
> fix: UserStatistics spacing on profiles

- src/.server/templates/RecieverMessage.tsx
- src/routes/api.messages.tsx
Users being told to email themselves
Being told to email the right person now.
> fix: messaging email fields

- packages/components/src/UserStatistics/UserStatistics.tsx
> UI changes for UserStatistica #4098(6,7)

- CONTRIBUTING.md
Supabase was not mentioned in contributing.md
Added link and fixed emulator link
Closes #
> chore(docs): Add supabase to CONTRIBUTING.md

- public/robots.txt
- src/routes/[robots.txt].tsx
robots.txt was allowing every route. 
this change ensures only active modules are crawled.
Closes #
> feat: serve robots.txt based on the active modules

- src/routes/api.discussions.$sourceType.$sourceId.comments.ts
> fix: sorting comments from oldest to newest

- src/pages/Library/Content/Page/LibraryDownloads.tsx
> fix: download library files

- src/pages/Research/Content/ResearchDescription.tsx
> fix: hide research cover image on article page

- server.js
> fix: hsts condition

- docs/supabase.md
Added instructions to use online supabase instance for testing purposes.
> docs: Add online supabase instance instructions

- packages/cypress/src/integration/news/write.spec.ts
- packages/cypress/src/integration/questions/write.spec.ts
- packages/cypress/src/integration/research/write.spec.ts
- packages/cypress/src/support/commands.ts
- src/pages/Question/QuestionPage.tsx
- src/pages/common/CommentsSupabase/CollapsableCommentSection.tsx
- src/routes/api.news.ts
- src/routes/api.subscribers.$contentType.$contentId.subscribed.ts
- src/routes/api.subscribers.$contentType.$contentId.ts
> feat: follow discussion button behind auth wrapper

- packages/components/src/UserStatistics/UserStatistics.tsx
- packages/cypress/src/integration/profile.spec.ts
- src/pages/User/content/ProfileDetails.tsx
- src/pages/User/content/UserCreatedDocuments.test.tsx
- src/pages/User/content/UserCreatedDocuments.tsx
- src/pages/User/content/UserCreatedDocumentsItem.tsx
- src/pages/User/content/UserProfile.tsx
- src/pages/User/types.ts
- src/routes/_.u.$id._index.tsx
- src/services/questionService.server.test.ts
- src/services/questionService.server.ts
- supabase/migrations/20250523104253_20250523_add-get-user-questions.sql
Contributions on profile page does not show users questions + useful votes.
Contributions on profile page shows users questions + useful votes.
Closes https://github.com/ONEARMY/community-platform/issues/4211 …
> 4211 add questions to contributions

- packages/cypress/src/integration/research/write.spec.ts
- src/routes/api.research.$id.updates.$updateId.ts
- src/routes/api.research.$id.updates.ts
- src/routes/api.research.ts
- src/services/notificationsService.server.ts
- src/services/subscribersService.server.ts
> fix: old notifications for research update

- src/routes/_.email-confirmation.tsx
- src/routes/_.sign-up-message.tsx
- src/routes/_.update-password.tsx
Reset password token is exchanged right when the page loads. Making subsequent refreshes no longer work due to expired links.
- Reset password token is exchanged only after submitting the form with a new passwoord.
also:
- Better error handling and other minor improvements to email confirmation page.
- Fixed display of characters like '+' on the signup message page.
Closes #
> feat: improve reset password and sign-up flow

- shared/models/common.ts
- src/common/Form/FormWrapper.tsx
- src/pages/Research/Content/Common/ResearchUpdateForm.tsx
> fix: spamming research update submit button

- packages/cypress/src/integration/research/list.spec.ts
- shared/mocks/data/research.ts
- src/pages/Research/Content/ResearchArticle.test.tsx
- src/pages/Research/Content/ResearchArticlePage.tsx
- src/pages/Research/Content/ResearchDescription.tsx
- src/routes/api.research.$id.updates.ts
- supabase/migrations/20250605115351_research-latest-updated.sql
> fix: research update sort

- packages/components/src/Banner/Banner.tsx
- packages/components/src/CreateReply/CreateReply.test.tsx
Hey! Fixed errors 
packages/components/src/Banner/Banner.tsx
`specificed` - `specified`
packages/components/src/CreateReply/CreateReply.test.tsx
`sucessful` - `successful`
> fix spelling errors

- src/pages/Library/Content/Common/LibraryStep.field.tsx
- src/pages/Library/Content/Common/LibraryStepsContainer.field.tsx
Fixes an issue where images and videos were not correctly validated.
Closes #
> fix: library form step image validation

- src/routes/_.update-password.tsx
- supabase/functions/send-email/_templates/reset-password.tsx
> fix: refactor reset password flow

- src/routes/api.projects.$id.ts
- src/services/libraryService.server.ts
can't delete steps
is able to delete steps.
> fix: delete steps

- packages/cypress/src/integration/library/write.spec.ts
- packages/cypress/src/integration/news/write.spec.ts
- packages/cypress/src/integration/questions/write.spec.ts
- packages/cypress/src/integration/research/write.spec.ts
- src/common/Form/ErrorsContainer.test.tsx
- src/common/Form/ErrorsContainer.tsx
- src/common/Form/FormWrapper.tsx
- src/pages/Library/Content/Common/Library.form.tsx
- src/pages/Library/Content/Common/LibraryTags.field.tsx
- src/pages/Library/Content/utils/transformLibraryErrors.ts
- src/pages/News/Content/Common/FormFields/NewsBodyField.tsx
- src/pages/News/Content/Common/NewsForm.tsx
- src/pages/Question/Content/Common/QuestionForm.tsx
- src/pages/Research/Content/Common/ResearchForm.tsx
- src/pages/Research/Content/Common/ResearchUpdateForm.tsx
- src/pages/Research/labels.ts
- src/pages/UserSettings/content/SettingsFormNotifications.tsx
Backend form validation only - unclear errors sometimes.
Client side validation
> feat: client side validation to all content forms

- src/services/researchService.server.ts
Authors couldn't change the status of their research.
Closes #
> fix: complete research by author

- src/common/FollowButtonAction.tsx
- src/pages/Library/Content/Page/LibraryDescription.tsx
- src/pages/Library/Content/Page/ProjectPage.tsx
- src/pages/News/NewsPage.tsx
- src/pages/Question/QuestionPage.tsx
- src/pages/Research/Content/ResearchDescription.tsx
- src/pages/common/CommentsSupabase/CollapsableCommentSection.tsx
- src/pages/common/CommentsSupabase/CommentItemSupabase.tsx
- src/pages/common/CommentsSupabase/CommentSectionSupabase.tsx
> feat: add follow button for all comment sections

- shared/models/notificationsPreferences.ts
- src/routes/api.notifications-preferences-via-email.$userCode.ts
- src/routes/api.notifications-preferences.ts
- src/services/notificationEmailService.server.ts
- src/services/notificationsPreferencesService.server.ts
- src/services/notificationsPreferencesService.ts
- src/services/notificationsPreferencesViaEmailService.ts
- src/test/factories/dbNotification.ts
- src/test/factories/notificationsPreferences.ts
- src/test/routes/api.notifications-preferences.test.ts
- src/test/services/notificationEmailService.server.test.ts
- src/test/services/notificationsPreferencesService.server.test.ts
- src/test/services/notificationsPreferencesService.test.ts
- src/test/services/notificationsPreferencesViaEmailService.test.ts
- src/test/utils/supabaseClientMock.ts
Unit tests provided for the recent notifications work. Heavily reliant on Claude for this.
> test: add unit tests

- .github/workflows/pr-preview-fly-destroy.yml
- supabase/functions/send-email/deno.lock
> fix: destroy fly preview apps on PR close

- supabase/functions/send-email/_templates/email-change-new.tsx
- supabase/functions/send-email/_templates/instant-notification-email.tsx
- supabase/functions/send-email/_templates/layout.tsx
- supabase/functions/send-email/_templates/magic-link.tsx
- supabase/functions/send-email/_templates/moderation-email.tsx
- supabase/functions/send-email/_templates/reset-password.tsx
- supabase/functions/send-email/_templates/sign-up.tsx
1. Removed the preferences update info on services emails and reworded slightly.
2. Added GA tracking params.
> feat: update email template links/footer

- packages/cypress/src/integration/research/write.spec.ts
- src/routes/api.research.$id.updates.$updateId.ts
- src/routes/api.research.$id.updates.ts
- src/services/broadcastCoordinationService.server.ts
- src/test/services/broadcastCoordinationService.server.ts
Quick renaming for clarity. Should of been in the previous PR.
> chore: rename broadcast service for clarity

- packages/cypress/src/integration/news/write.spec.ts
- packages/cypress/src/integration/questions/write.spec.ts
- src/pages/News/NewsListItem.tsx
- src/routes/api.news.$id.ts
Specs currently failing as drafts often haven't saved before moved on to the next expectation (that needs them to have been saved). Plus user/auth info often hasn't loaded in time for a save action.
> test: drafts save before next expectation

- src/pages/common/CommentsSupabase/CommentItemSupabase.tsx
> feat: switch not-following reply wording to action

- packages/cypress/src/integration/common.spec.ts
- src/routes/_.forbidden.tsx
- src/routes/_.library.$slug.edit.tsx
- src/routes/_.news.$slug.edit.tsx
- src/routes/_.news.create.tsx
- src/routes/_.questions.$slug.edit.tsx
- src/routes/_.research.$slug.edit-update.$updateId.tsx
- src/routes/_.research.$slug.edit.tsx
- src/routes/_.research.$slug.new-update.tsx
- src/routes/_.research.create.tsx
Unhelpful:
Default when not given a page:
When given a page:
Closes #4377
> feat: update forbidden page
