src/pages/Howto/Content/Howto/Step/elements.js

* add word wrap to StepDescription style to avoid text go outside the container
@mattia-io @BenGamma

#224  fix - prevent long step text to go outside container 

---

src/pages/Home/Home.tsx
src/pages/Howto/Howto.tsx
src/pages/index.tsx

The case when the root url was called was out of the page.map(). The Header was indeed not render with it.
I added the `/` as a proper page const `HOME_PAGE` and the boolean prop `exact` to `IPageMeta` interface.
Now if a page will need an exact path, add `exact: true` when declaring the PageMeta object. Then, all the requests for a deeper url will fallback into a 404.

Fix homepage navigation display

---

src/components/Editor/common/firebase.ts
src/pages/Howto/Content/CreateHowto/CreateHowto.tsx
src/pages/Howto/Content/Howto/Howto.tsx
src/stores/Events/events.store.tsx
src/stores/Howto/howto.store.tsx
src/stores/Tags/tags.store.tsx
src/stores/User/user.store.ts
src/stores/_Template/template.store.tsx
src/stores/database.tsx
src/utils/firebase.ts
src/utils/user-migration.ts

- rename direct calls to the firebase database as `afs` instead of `db` to support new middle db layer
- initial database class with static methods to get docs and collections, first making a quick return from the local cache and then checking server for updates

Fix/73   database queries

---

src/components/Icons/index.tsx
src/pages/Discussions/PostView/PostView.tsx
src/pages/common/Avatar/index.tsx

I created an Avatar component with the prop `userEmail`. The prop is not mandatory so if you just use the avatar component without prop, it will display a placeholder user Icon. In a close futur this placeholder should be a proper image.
As a quick solution I added an `avatar` field in the users collection in firebase with a link to our github avatar.
I added the field by hand for chris and I, there is probably a better way to do it.
TODO :
* automatically add the field for new created user.
* add the avatar to the `/profile` section with the ability to modify it
* decide where to save the avatar. To begin I think that firebase storage would be ok, but it's open for discussion

351 create avatar component

---

src/components/Auth/AuthWrapper.tsx
src/pages/Howto/Content/HowtoList/HowtoList.tsx
src/pages/Howto/Howto.tsx
src/pages/common/AuthRoute.tsx

Created a new `AuthRoute` component that replaces the standard `Route` component for any routes where we only want to allow logged in users access (like how-to create). Includes an optional redirect to send the user to if not signed in
Also created a new `AuthWrapper` component that stops the render of child components if user not logged in (like the 'create how-to' button).
Have testing and working as intended so shouldn't take much review, however @BenGamma you might be interested in taking a quick look so that you can see how it's been implemented.
Closes #457

Add auth nav guards and component hide wrapper

---

src/components/Layout/PageContainer.tsx
src/pages/PageList.tsx
src/pages/index.tsx

Not sure if this maps a lot of sense to do it this way, but I can imagine some pages want to have a "cover" format. I'm not sure on the right words to use, or whether you want to achieve it this way, but just an idea. The main use case is for something like Maps where you want it to cover the whole width of the page, and not be boxed into the container size.

feat(container): pageWidth characteristics on page containers

---

src/components/ImageInput/ImageConverter.tsx
src/components/ImageInput/ImageInput.tsx

Resolves issue #512 by removing the option buttons for image compression, and defaults image upload to "low" setting with max width of 640. Compression rate and final file size are still shown.
Also prevent flash of unstyled content (FOUC) when loading/replacing image.

(512) Feature: remove compression option for image upload

---

src/pages/Howto/Content/Howto/Step/ImageGallery.tsx

I additionally added `cursor: pointer` as the Image has now an on click interaction.

Add max-width and lightbox for images on how-to page

---

src/stores/Howto/howto.store.tsx
src/utils/filters.ts

small changes to split util function, remove additional check and shorten filter code

add filter util function, tidy howto filter code

---

src/pages/Events/Content/EventsList/EventsList.tsx
src/pages/Events/Events.tsx
src/pages/Howto/Content/HowtoList/HowtoList.tsx
src/stores/Events/events.store.tsx
src/stores/Howto/howto.store.tsx
src/stores/common/module.store.ts

* Rename the method `filteredHowto` in howto.store to `filteredCollectionByTags` and moved to the module.store to allow event.store to access it.
* Add the `SelectTags` component in event list
* Base the event list render() on `filteredEvents` value instead of `upcomingEvents`
Closes #557

557 events filtering by tags

---

src/components/ImageInput/ImageInput.tsx

Using `.concat` to update the compressed images so we don't add empty files to the array.

Stopping the first file being empty when returning compressed images

---

.storybook/webpack.config.js
src/components/Heading/heading.stories.tsx
src/components/Heading/index.tsx
src/components/Text/text.stories.tsx
src/utils/knobs.ts

✅ Add Text component to storybook
✅ Add Heading component to storybook
* Was fixed an issue to start storybook, do not necesary upgrade storybook, just adapt the `webpack.config`
* Was fixed something  related with the definition of `fontSize` using a prop (medium, small, large) that I think was a typo in heading component (but I not sure if that was something intentional in any case it can be reversed)
* I made a factory to handle the Knops using a default props objects (let me know if is useful or not)

#437 add text & heading component to storybook 

---

cypress.json
cypress/support/commands.ts

Should hopefully fix issue of first test fail. On local machine all tests now appear to pass when localhost is slow to load the platform.

extend timeout and add base route to all tests

---

cypress/integration/events.spec.ts
src/components/LocationSearch/LocationSearch.tsx
src/pages/Events/Content/EventsCreate/EventsCreate.tsx
src/pages/Events/Content/EventsList/EventsList.tsx

- Setup 
- Testing in progress

Event test

---

cypress/integration/how_to.spec.ts

Simply call same delete method at end of how-to test to avoid some of the current race condition issues
(note - could also be put directly after creation)

delete generated how-tos at end of test

---

package.json
src/components/Button/index.tsx
src/components/FileInfo/FileInfo.tsx
src/components/Form/ImageInput.field.tsx
src/components/Form/elements.ts
src/components/ImageInput/ImageConverter.tsx
src/components/ImageInput/ImageInput.tsx
src/models/howto.models.tsx
src/pages/Howto/Content/Common/Howto.form.tsx
src/pages/Howto/Content/Common/HowtoStep.form.tsx
src/pages/Howto/Content/Howto/HowtoDescription/HowtoDescription.tsx
src/pages/Howto/Content/Howto/Step/ImageGallery.tsx
src/stores/Howto/howto.store.tsx
yarn.lock

Reverts ONEARMY/community-platform#691 because found a critical bug on how-to edit.
To reproduce :
If you edit a step with 3 images and remove images n°2, the app crashes on save. Needs investigate.

Revert "593 max image upload"

---

cypress/integration/howto/write.spec.ts
cypress/support/commands.ts
cypress/support/custom-assertions.ts
cypress/support/firestore.ts
cypress/support/index.ts
package.json
yarn.lock

Added cy.queryDocuments to query documents from firebase
Added eqHowto and eqHowtoStep to verify a howto

Verify created/edited howtos

---

.travis.yml

I think this should make things work better.
By including branches we can still run build on both PRs and branch push, but only when either the branch is master/production, or the PR targets master/production (I hope...)

only run scripts on PRs targetting master and production

---

src/components/LocationSearch/LocationSearch.tsx

The dropdown closes when clicking away from the field now. I wonder about implementing the second requirement from the issue though -- 'ESC' as a way of closing the dropdown. Is it still necessary to add even though clicking away works?

Fixes #678: close dropdown on click away in events

---

src/pages/Settings/content/formSections/MapPin.section.tsx

**Previous Behaviour**
The custom icons float around when the zoom level changes, since the anchoring wasn't correct. 
**Fix**
Changed the anchoring to be in the bottom-centre of the icon so they visually stick to the proper place.
**Side note**
Interestingly, it turns out that Algolia's places search returns incorrect lat-lng coordinates for some addresses. E.g. `401 West Georgia Street, Vancouver` is off by quite a bit. This looks like an issue on Algolia's side. E.g. looking up `401 West Georgia Street, Vancouver` [returns wrong coordinates on the actual Algolia page](https://community.algolia.com/places/), which is strange because they're supposed to be pulling from Open Street Maps, which [actually returns the right coordinates](https://www.openstreetmap.org/search?query=401%20west%20 …

Fix anchoring for custom markers on Settings page

---

src/pages/Howto/Content/Common/Howto.form.tsx
src/pages/Howto/Content/Common/SubmitStatus.tsx
src/stores/Howto/howto.store.tsx

Fixes #734: added a warning about unsaved changes

---

src/components/Avatar/index.tsx
src/mocks/user_pp.mock.tsx
src/models/user_pp.models.tsx
src/pages/Maps/Content/View/Popup.tsx
src/pages/Maps/Content/View/Sprites.tsx
src/pages/User/content/UserPage/UserPage.tsx
src/pages/User/workspace/Workspace.tsx
src/pages/common/Header/Menu/Profile/Profile.tsx
src/stores/Maps/maps.groupings.ts

closes #775 
I added the fallback image and restructured the way workspace icons are retrieved. This way, the non-decorated icons are no longer based in components related to the map, which makes choosing between the two types of workspace icons in other parts of the app easier.

User badge fallback image

---

src/stores/databaseV2/clients/dexie.tsx
src/stores/databaseV2/utils/db.utils.ts

@BenGamma 
This should fix issues with caching data that has been deleted. 
**Done**
- Add methods to allow clearing of cached db. This is currently implemented within an error handler due to the complex nature of updating cached databases. All cached dbs have a version number, when adding a new version you are supposed to also keep the old version alongside notes to tell dexie how to upgrade. Whilst this is very useful to allow incremental upgrades and changes to database structures, it can quickly get messy if you have made numerous changes to the database over time and can't be sure what version everybody currently has in their web browsers. 
The error handler implemented catches the case when a newly versioned database is created but explicit guidance hasn't been set for how to …

add dexie cache-busting methods

---

src/stores/Howto/howto.store.tsx

Fix for #756 I found the problem. In howto.store.tsx, line 129, when an image is deleted, the object in the stepImages variable is set to null, then that array gets iterated on in uploadCollectionBatch() and the function tries to access properties on null. I added a filter to remove falsey values from the stepImages array. As I’m not very familiar with the codebase yet, I am open to suggestions as to solve this differently if there is a better way.

Fixed howto submit after deleting step image

---

src/components/ExternalEmbed/ExternalEmbed.tsx

Closes #832
Combines with PR on academy site (https://github.com/ONEARMY/academy/pull/40)
Adds listener for postmessage to respond to link clicks and open in a new tab.

add academy link click message support

---

src/pages/Settings/content/formSections/MapPin.section.tsx

Temporary fix to #739.
Display the following notice under the pin location selector in user settings :
`We are aware that location search may result in an inaccurate
position of your pin. If it happend, choose the closest location
to you. Pro tip : you can write your precise address in your
profile description & help find a fix here`

add notice for non precise location search value

---

functions/src/Integrations/firebase-discord.ts
functions/src/Integrations/firebase-slack.ts

Very little update on the messages posted by the webhooks, to fit the markdown used by each platform. Because yes they don't use the same 🤦‍♂

update messages posted for discord & slack webhooks

---

src/pages/admin/Admin.tsx
src/stores/Admin/admin.store.ts
src/stores/databaseV2/clients/dexie.tsx
src/stores/databaseV2/index.tsx

The added cache fallback methods from PR #872 produced errors when queries were executed on the cache that either:
a) Didn't have a corresponding operation. Basic queries have been created for things like `>`, `==`, `<`, however the firebase custom `array-contains` query has not been created and was throwing an error. This message has been made more clear, and a better catch used to avoid.
b) Didn't have indexes on the fields required to query. By default any searches on dexie can only be performed on fields that are specified in the schema, which didn't include things like `userRoles` or `_authID`. This again is now handled more gracefully.
Additionally, both errors were being thrown on launch from the admin store. As the admin store isn't required for most users I've changed the init …

add catch to cachDB fallback, defer admin store init

---

src/components/Analytics/index.tsx
src/components/GoogleAnalytics/index.tsx
src/config/config.ts
src/pages/index.tsx

I decided to make a component to do all the analytics instead of using the Analytics store. It still uses `react-ga`. But I found the store to coupled to the frontend and backend and was confusing. So keep it simple and let the frontend and the `<Analytics />` component take care of the FE.

Adding Google Analytics

---

cypress/support/hooks.ts
functions/src/Integrations/firebase-discord.ts
src/models/common.models.tsx
src/stores/Maps/maps.store.ts

Since merge of #920 automated testings build were mysteriously failing, with various errors, always different.
That was linked to the [change of the IModerable interface](https://github.com/ONEARMY/community-platform/pull/920/files) in #920 and the fact that the IndexDB database interfaces cached in the automated browser used by cypress (in my case chromium) was different than the new ones.
In this PR I removed the need of modifiying the interface. We should modify interfaces only in major update cases because it will cause all our user to redownload the datas from db. With approximately 10 000 monthly visitors that will cost a lot of bandwith and more hosting cost too.
In this situation (update a webhook for internal use only), it doesn't appear worth to remove all caching.
Also I added …

Fix pr920 - clear indexDB local cache before automated test

---

src/pages/Howto/Content/Common/PostingGuidelines.tsx
src/pages/index.tsx

Added a few extra points + guidelines URL

Improved how-to guidelines

---

src/pages/Maps/Content/Controls/GroupingFilterDesktop.tsx
src/pages/Maps/Content/Controls/GroupingFilterMobile.tsx
src/stores/Maps/maps.store.ts

Close #901 
I also added the number of pins per filter type on the mobile filter 📱

901 show pins amount map filter

---

src/pages/Maps/Content/View/Popup.tsx
src/pages/Settings/content/formSections/MapPin.section.tsx

- This only sets a limit of characters for people using the endpoint through this frontend
Closes #900

Limit description length for map pins to 70 characters

---

src/components/Tags/TagsSelect.tsx
src/pages/Events/Content/EventsCreate/EventsCreate.tsx
src/pages/Howto/Content/Common/Howto.form.tsx
src/pages/Howto/Content/Common/HowtoStep.form.tsx

925 character limits

---

.gitignore
functions/package.json
functions/tsconfig.json
functions/yarn.lock
src/models/common.models.tsx
tsconfig.json

Latest build on master failing due to config errors with how `functions` shares some type definitions with the main `src`. Not really sure why this has happened now, but it's always been a bit of a fragile system so not hugely surprised.
This attempts fix by:
- update typescript version in functions to match src
- add project references tsconfig support
- add typing build script for project
In the future we can hopefully achieve a better/more-permanent fix via `lerna` and/or `yarn workspaces`

hotfix - tsconfig minor tweaks

---

.github/PULL_REQUEST_TEMPLATE/pull_request_template.md
.github/release-drafter.yml
.github/workflows/release-drafter.yml

PR Type
PR Checklist
Will likely need some fine-tuning, but the idea is to tidy up how PRs and releases are organised. I've added a PR template (used for this PR) to encourage people to be more clear on what they are merging (particularly to remember to close any linked issues, and make sure branch up to date).
Additionally I've included a github workflow action to automatically prepare a draft release from all PRs merged into master. It's setup to automatically list PR titles in the notes, and additionally could  categorise if we choose to tag PRs in a particular way. I still expect the releases will still need to be mostly written by a person, but hopefully this will speed up the process and help make sure nothing is left out
_Closes #_
Example Release Drafter: …

Add PR template and release drafter

---

package.json
src/pages/common/Header/Menu/Logo/Logo.tsx

Minor fix just to properly display the version number on logo hover (tried before using an `alt tag` but should have been a name tag. Also bumped minor version for future release, and updated PR template to show correctly

Show platform version on logo hover

---

package.json
src/pages/Howto/Content/HowtoList/HowtoList.tsx
yarn.lock

PR Type
PR Checklist
It adds a virtual scroll for the HowtoList to reduce initial rendering and only render the needed Howto´s for every visitor. It will render additional Howto´s while rendering, while removing Howto´s which are not in the viewport.
Therefor I added react-virtualized as discussed in the Issue. First I thought react-window would be good enough, but it does not support a Window scroll feature and there for react-virtualized was my choice here.
Closes #493

#493 - Add virtual scroll for HowtoList

---

package.json
src/components/VirtualizedFlex/VirtualizedFlex.tsx
src/pages/Howto/Content/HowtoList/HowtoList.tsx
tsconfig.json
yarn.lock

PR Type
- Code Tidying
PR Checklist
Following #962 (thanks @tudi2d!), some minor code tidying
- swap getter function with regular (as it's used in multiple places it runs the code multiple times)
- simplify row/column calculation methods
- add overscanrowcount property (change default lookahead from 10 rows to 2)
Probably deserves one as really neat how images now only load in as they scrolled past!

Virtual scroll code tidying

---

src/pages/Howto/Content/Common/SubmitStatus.tsx

PR Type
PR Checklist
Adding a close button to the submit how-to modal. It prevent the user to have to reload the page on how-to upload fail, and thus loose all his how-to writing.
Partial fix for #781

feat: close button for submitStatus modal

---

src/pages/Events/Content/EventsCreate/EventsCreate.tsx
src/pages/Settings/SettingsPage.tsx
src/pages/Settings/content/formSections/Fields/Link.field.tsx
src/pages/User/content/UserPage/ProfileLink.tsx
src/pages/User/content/UserPage/UserPage.tsx
src/utils/validators.ts
tsconfig.json

PR Type
PR Checklist
- [x - PR title descriptive (can be used in release notes)
- Remove additional workspace type text for regular profiles (closes #818)
- Refactor profile links to own component and remove code duplication (could be further tidied but small improvement for now)
- Add workaround for opening URLs without HTTP prefix (fixes #968)
Closes #818
Closes #968

fix profile double type and links bugs, tidy profile code

---

src/pages/Settings/content/formSections/Fields/Link.field.tsx

PR Type
- [ x ] Bug fix (non-breaking change which fixes an issue)
PR Checklist
- remove link validation for discord IDs
- As described in #970 thread, still one little bug to fix :
> I've spotted a weird behavior in the link validation while doing a last check. See a screencast [here](http://recordit.co/Pphy7TNBU4)
It happend in the case you have an invalid url first, then the validation removes the last char of the input. But I don't get it because we are not striping any character, we are just adding from the existing value 🤔

Fix links validations

---

cypress/integration/common.spec.ts
src/pages/index.tsx

PR Type
PR Checklist
Changes landing page from `/how-to` to `/academy`
Closes #988

redirect root page to /academy instead of /how-to

---

src/pages/Maps/Content/View/Cluster.tsx

PR Type
PR Checklist
Remove cluster groups for every type of pin. Instead add all pins to one cluster group and cluster them together. Additionally the distance for pins to be clustered together was reduced
Closes #1006

Cluster pins of different types in map

---

functions/src/Integrations/firebase-discord.ts
functions/src/Integrations/firebase-slack.ts

Fixes #1008
Notification will be triggered if user reverts to draft and then try to publish after being accepted.
PR Type
PR Checklist
Keeps accepted status after edit avoiding messages to disscord
Closes #1008

Avoid notification when user edits pin or howto

---

functions/src/Integrations/firebase-discord.ts
functions/src/Integrations/firebase-slack.ts

There was a mistake in 252df324af4ff4fb40ccbc119f6084887f9cbb4b, firebase syntax was used instead of firestore.
Avoid notification when user edits pin or howto and it was previuosly accepted.
Notification will be triggered if user reverts to draft and then try to publish after being accepted.
Note: will trigger disscord message, maybe we could add field in DB to know it has been accepted before.... Would it brake frontend??
PR Type
PR Checklist
_Closes #1008

Avoid notification when user edits pin or howto and it was previuosly accepted. #1008

---

functions/src/Integrations/user-triggers.ts
functions/src/index.ts
src/components/HowToCard/HowToCard.tsx
src/mocks/howto.mock.tsx
src/models/howto.models.tsx
src/pages/Howto/Content/Howto/HowtoDescription/HowtoDescription.tsx
src/stores/Howto/howto.store.tsx

Display of flags for HowTos (List and detail) implemented
TODO: Create firestore trigger to update when user changes location

Fix #972 Add country flags at username

---

functions/src/Integrations/user-triggers.ts

Remove missing underscore (_) from _creatorCountry
Added const on firestore function declaration
PR Type
PR Checklist
Typo fix, part of flag disaplay
Closes #972

Fix #972 Add country flags at username - Fix deployment

---

src/pages/Howto/Content/Howto/HowtoDescription/HowtoDescription.tsx

PR Type
PR Checklist
Replace the CSS rotate with transform: rotate(...) to support every browser.
Closes #1042

Fix rotation of arrow icon for HowTo descriptions

---

src/pages/Howto/Content/Howto/Step/Step.tsx

PR Type
PR Checklist
This replaces an unnecessary Flex Wrapper with a normal Box component. This way there is no different behavior cross browsers for the width of the flex items.
Closes #1054

Fix flexbox cross-browser issue for step images

---

cypress/integration/howto/write.spec.ts
src/pages/Howto/Content/Common/Comparisons.tsx
src/pages/Howto/Content/Common/Howto.form.test.tsx
src/pages/Howto/Content/Common/Howto.form.tsx
src/pages/Howto/Content/Common/HowtoStep.form.tsx

PR Type
PR Checklist
Only show the confirm dialog (prompt) when a value is changed inside the howto edit/create page
#766

#766 Show prompt only if form value changed

---

.github/labels.yml
.github/pr-labeller.config.yml
.github/workflows/pr-labeller.yml

PR Type
PR Checklist
Add github action to automatically label PRs depending on what files have changed to help with reviews.
_Closes #_

Add pr labeller action

---

package.json
src/components/Tooltip/index.tsx
src/pages/Howto/Content/Howto/HowtoDescription/HowtoDescription.tsx
yarn.lock

PR Type
PR Checklist
As discussed on #1096, I am adding a proper tooltip when a not logged in user clicks the `useful` button. I added the [react-tooltip](https://github.com/wwayne/react-tooltip/) library to the project, rather than [react-popper](https://github.com/popperjs/react-popper/), which was suggested by @chrismclarke. The reasoning of the choice is mainly because `react-popper` provides only a usePopper hook that works with the use of the `ref` attribute, which was not clear to me in this case. Apart from that, it has more stars on GitHub and a smoother API for React development overall.
The tooltip is triggered with a `click` or `focus` event, and hidden with a `mouseleave` or `blur` event. Find a demo below.
_Closes #1096_

Add useful button tooltip

---

cypress/integration/howto/read.spec.ts
package.json
src/common/errors.ts
src/components/SearchInput/index.tsx
src/index.tsx
src/pages/Howto/Content/HowtoList/HowtoList.tsx
src/pages/Research/Content/ResearchItemDetail.tsx
src/stores/Howto/howto.store.tsx
yarn.lock

PR Type
PR Checklist
As suggested on #1088, adding client-side searching for how-tos using [Fuse](https://github.com/krisk/Fuse/). I added a `SearchInput` component that only renders the search field, and I did the searching logic on the howto store. After filtering the howtos by tags, if there is something typed in the search field the function will perform a Fuse search and return the search-sorted howtos.
On the first commit I also removed some warnings React was throwing for no apparent reason, screenshot below.
Also, I updated an integration test which was selecting the how-to tag selector by the input tag. It now selects the first input, as there are now two.
Note on Fuse - the current weights for the how-to search are:
```
0.5 - Title
0.3 - Description
0.15 - Steps titles
0.05 - …
```

Add how-to client side searching

---

src/components/SearchInput/index.tsx
src/pages/Howto/Content/HowtoList/HowtoList.tsx
src/stores/Howto/howto.store.tsx

PR Type
PR Checklist
As discussed in #1100, adding the feature to update the URL query string when the search field is altered. I also implemented the same logic for tags selecting. Everything was done using the JavaScript URL API, so mapping spaces and special characters to encoded values is already working by default. 
Note: as tags are identified by the unique ID, the URL gets a little noisy with the params. If you guys think this is not desirable, I can revert this part.
_Closes #1100_
(Demo is a bit slow cuz of my machine)

Add query params updating on search howtos

---

functions/src/userUpdates/backupUser.ts
functions/src/userUpdates/index.ts
src/stores/User/user.store.ts

PR Type
PR Checklist
A login now updates the user's last active status to the current time, as discussed in #984. The update is done in the `userSignedIn` method in the store. I tested with a custom pin and the last active info is updating correctly now.
Also, in order to not backup a user every time he logs in, I added a shallow comparator on a previous and updated user, to check if `lastActive` is the only field updated. This hasn't been tested though as I'm not sure how to test the backup function and see the backup data. If the test is desirable I'd be happy to test it, just will need some directions.
_Closes #984_

Fix user last active updating

---

src/components/EventCard/EventCard.tsx
src/components/HowToCard/HowToCard.tsx
src/components/ModerationStatusText/index.tsx
src/components/Research/ResearchListItem.tsx
src/models/user.models.tsx
src/pages/Howto/Content/Howto/HowtoDescription/HowtoDescription.tsx
src/pages/PageList.tsx
src/pages/Research/Content/ResearchDescription.tsx
src/pages/Research/index.tsx
src/pages/admin/Admin.tsx
src/pages/admin/content/AdminBetaTesters.tsx
src/pages/common/Header/Menu/MenuDesktop.tsx
src/pages/common/Header/Menu/MenuMobile/MenuMobilePanel.tsx
src/stores/Admin/admin.store.ts

PR Type
PR Checklist
With this update, the research module page becomes visible in the production site, but only for users that have the `beta-tester` role. I added a `requiredRole` attribute to the `IPageMeta`, so pages using this attribute will have a rendered link in the menu only for users who have the required role.
Also added an admin page to manage beta tester users.
Also, minor changes to clarify prop names from my last PR (https://github.com/ONEARMY/community-platform/pull/1116#discussion_r607033140).
_Closes #1118_

Research module live, but only for specific users

---

cypress/support/hooks.ts
firebase.json

PR Checklist
PR Type
Deployed functions include typing references compiled from the main src code, which requires precompile for linting to pass. As this is done in the build phase assume fine to skip the lint phase (lint errors should still appear locally). Additionally requires a full yarn install of all workspaces so the src typings can be compiled successfully
Also added a fix for flaky tests where DB seed/tear-down does not always resolve correctly.
Closes #
---
If the PR is working as intended it'll be merged and included in the next platform release, if not changes will be …

build fixes - functions linting

---

src/components/Comment/CommentHeader.tsx

PR Checklist
PR Type
Linked username in comments to user profile.
Closes [#1157](https://github.com/ONEARMY/community-platform/issues/1157)
https://user-images.githubusercontent.com/35103888/121354255-ff124c80-c92e-11eb-9563-8d4160801445.mp4

Linked username in comments to user profile

---

src/pages/Maps/Content/View/index.tsx
src/pages/Maps/Maps.tsx
src/stores/Maps/maps.store.ts

PR Checklist
PR Type
When mappins load they should retrieve details from db (including verified badge), except some legacy mappins already have details hardcoded and so were skipping this step. This PR fixes the behaviour (force always to look at db and ignore hardcoded data), as well as some minor code tidying. 
Closes #
---

fix map pin detail

---

src/components/Comment/CommentTextArea.tsx

PR Checklist
PR Type
- Turn the `login` text to a link to the sign-in page
Closes
**Before:**
**After:**
---

add link to login from comments

---

yarn.lock

PR Checklist
PR Type
Generate a new yarn lock file as I noticed other PRs raised against this repo fail at dependency install step currently.
Not to sure about the _why_ here, I don't work with Yarn too much currently. From what I understand it looks like the current immutable lock file can not be used (🤯) and instead requires a new lock file to be generated. So I have done just that without any meaningful context on how this will affect things as a _lot_ of dependencies have changed.
Let's see what Circle thinks…

fix: yarn install script

---

package.json
src/common/errors.ts
src/config/config.ts
yarn.lock

PR Checklist
PR Type
The implementation should support
Sentry credentials being supplied via the
environment.
This allows us to use seperate Sentry projects
for individual installs and eventually remove
the credentials from our codebase entirely
instead moving this key to be supplied via
CI environment variables.
For example, we may want a dedicated
Sentry project for monitoring the health of 
the ProjectKamp installation.
In addition to this change we are adding
support for Sentry's concept of environments.
We are using the `siteVariant` to acheive this.
This allows us to filter the errors and understand
how our production environment is performing compared
to our various staging and development environment.

feat: load sentry credentials from environment

---

src/assets/images/menu-current.svg
src/pages/common/Header/Menu/MenuDesktop.tsx

PR Checklist
PR Type
Moving towards making the platform easier to re-theme this updates the menu link background to use CSS masks instead of relying on a hardcoded hex value in the SVG. This means that updating the colour value in the theme file will be used as the highlight color. 
The attached screenshot demostrates how the menu highlight will now align with the base colour defined within `styled.theme.tsx`

fix: use css mask to make background color dynamic

---

src/components/Comment/CommentHeader.tsx
src/components/Form/Select.field.tsx
src/components/Form/elements.ts
src/components/ImageGallery/index.tsx
src/components/ImageInput/ImageConverter.tsx
src/components/ProfileModal/ProfileModal.tsx
src/components/Text/index.tsx
src/pages/Howto/Content/Howto/HowtoDescription/HowtoDescription.tsx
src/pages/Howto/Content/Howto/HowtoDescription/HowtoUsefulStats.tsx
src/pages/Research/Content/ResearchDescription.tsx
src/pages/User/content/UserPage/UserPage.tsx
src/pages/common/Header/Menu/MenuMobile/MenuMobilePanel.tsx
src/themes/styled.theme.tsx

PR Checklist
PR Type
Updates any colour references to use the primary theme file. Where there was a super close match I used an existing color, otherwise opted to move the hex code into the primary theme file.

fix: only load colours from primary theme file

---

src/components/ProfileModal/ProfileModal.tsx
src/pages/common/Header/Menu/MenuMobile/MenuMobileLink.tsx
src/pages/common/Header/Menu/Profile/Profile.tsx

PR Checklist
PR Type
A recent change moved the colour definition
out of the SVG into a CSS file using CSS masks. We missed
the usage of the SVG within the mobile navigation.
Before:
After:

fix: regression in background colour

---

.circleci/config.yml

This reverts the recent changes which removed the e2e from the `production` branch pipelines.

test: reinstate loads of time consuming tests

---

.circleci/config.yml
src/config/config.ts

PR Checklist
PR Type
At the moment the version is taken from the `package.json` version field. This is manually updated during the release process. However we don't want to rely on such a manual process for our development environments, no deployment to a development environment needs to be mapped to a releaseable artefact.
Development environments are intended to represent the HEAD state of our default branch. So instead of using a value that looks like a [semantic version](https://semver.org/), we can load a SHA value which references a specific point in the project history.  
Hovering over the logo will give you something like this instead:
**Note:** This will only affect the development environments and not the production instances. The production instances will continue to use the …

chore: fetch version number from git sha

---

src/pages/Maps/Content/Controls/index.tsx

PR Checklist
PR Type
In the production environment _only_ this
box is incorrectly inheriting the display:flex
property which due to ordering of selectors
in the generated CSS are taking preference
over the media query defined display:none.
This is a guess as I haven't been able to recreate
the behaviour locally.

fix: flex style overriding hidden preference

---

packages/cypress/src/integration/academy.spec.ts
src/components/ExternalEmbed/ExternalEmbed.tsx
src/pages/Academy/Academy.tsx
src/pages/PageList.tsx
src/themes/precious-plastic/index.ts
src/themes/project-kamp/index.ts
src/themes/types.tsx

PR Checklist
PR Type
The PlatformTheme definition has been extended to include a `academyResource` property so that each themed instance can reference its own Academy resource.

feat: support additional academy locations

---

src/pages/common/Header/Menu/MenuMobile/MenuMobileLink.tsx
src/pages/common/Header/Menu/MenuMobile/MenuMobilePanel.tsx
src/stores/Theme/theme.store.tsx
src/themes/precious-plastic/index.ts
src/themes/project-kamp/index.ts
src/themes/types.tsx

PR Checklist
PR Type
Moves the external links out so that they
can be defined at the theme layer.
Attached screen grab demonstrates different navigation items appearing for Project Kamp instance:

feat: moves external links to theme definition

---

.circleci/config.yml
.yarnrc.yml
packages/cypress/package.json

PR Checklist
PR Type
Reverts a configuration change to yarn which prevented the [Storybook](https://storybook.js.org/) instance from booting. Originally reported by @kfern in #1308.
Also introduces a Circle CI job which builds the Storybook site. This is a sanity check to prevent us inadvertently breaking it in the future. It may be interesting to publish to a standalone site at some point but that's something that can wait for another PR.

fix: storybook instance

---

src/pages/Settings/content/formSections/Fields/Link.field.tsx
src/utils/formatters.test.ts
src/utils/formatters.ts

fix: formatting of URL, closes #1256

---

src/components/Auth/AuthWrapper.tsx
src/components/Comment/Comment.tsx
src/components/Comment/CommentTextArea.tsx
src/components/Heading/index.tsx
src/components/Loader/index.tsx
src/components/Tags/TagsSelect.tsx
src/pages/Academy/Academy.tsx
src/pages/Howto/Content/Howto/HowToComments/HowToComments.tsx
src/pages/Research/Content/Common/Research.form.tsx
src/pages/Research/Content/Common/Update.form.tsx
src/pages/Research/Content/EditResearch/index.tsx
src/pages/Research/Content/EditUpdate/index.tsx
src/pages/Research/Content/ResearchItemDetail.tsx
src/pages/Research/research.routes.test.tsx
src/pages/Research/research.routes.tsx
src/stores/common/module.store.ts

PR Checklist
PR Type
Fixes an issue where a user can not edit a Research item, or add an Update to a Research article.
I _think_ it is happening because the paths are being matched from top to bottom, meaning that the `Route` item here is being matched first before the `AuthRoute` wrappers which contains the edit logic.
Steps to recreate:
1. Add new Research item to the site
2. View the new Research item
3. Clicking either the Add Update or Edit button flashes a 404 page before returning to render the Research item

fix: adjust ordering of paths so that auth'd routes take precedent

---

src/pages/Research/research.routes.test.tsx
tsconfig.json

PR Checklist
PR Type
The recently introduced `.toBeInTheDocument` assertation from `@testing-library` caused the type check as part of the functions precompilation to break. 
There are few interesting things here;
* That typecheck includes tests files, there aren't many of them yet, but they shouldn't be scanned as part of this flow.
* This broken change was mergeable into `master` because we do no validation on the functions before we try to deploy them. There is [a PR](https://github.com/ONEARMY/community-platform/pull/1252), which introduces a Circle CI job to validate their correctness. I would need to do some investigation to see if this would have caught the issue.

fix: type definitions for tests

---

firebase.json

PR Checklist
PR Type
Over the last month we've shipped multiple
releases to production, at a far higher
cadence then recent months.
A side effect of this has been observing
multiple "odd" behaviour on the production
deployments which can not be recreated locally.
The primary candidate for causing these issues
is the service worker. The service worker is a
built in component of create react app (CRA).
Interestingly in the CRA documentation when discussing
servic workers they mention:
> they (service workers) can make debugging deployments more challenging.
So as a result I have been hunting out for more information around
other folks encountering this behaviour.
An interesting thread here around the combination of
service workers AND firebase: …

fix: service worker cache headers

---

packages/cypress/src/integration/howto/search.spec.ts
src/pages/Howto/Content/HowtoList/HowtoList.tsx

PR Checklist
PR Type
I added a flush of the search value in the howToStore when the component invokes `componentWillUnmount` and the respective e2e in cypress test.
Closes #1238 
---

[FIX] #1238 howto search cleaning after navigation

---

.eslintrc.json
src/pages/Howto/Content/Common/Howto.form.test.tsx
src/stores/common/__mocks__/module.store.ts

PR Checklist
PR Type
As raised in #1378, the lint rule `@typescript-eslint/no-empty-function` can be a bit annoying when doing things like stubbing/mocking tests. It is possible to work around by adding a disable statement (already been done twice previously), however probably makes sense to just remove it as most use cases are intentional as opposed to true code-quality issues.
An alternative would be to modify to just provide warning, however as these will be thrown as errors during CI build (and for reason above) I think best to just remove.
Closes #
---
If the PR is working as …

chore: remove empty function lint rule

---

package.json
src/config/constants.ts
src/logger/index.ts
yarn.lock

PR Checklist
PR Type
Adds a transport to the pino logger library to
forward your messages to Logflare.
This can be verified locally by adding a `.env` file
with the following values:
```
REACT_APP_LOGFLARE_KEY=<LOG_FLARE_API_KEY>
REACT_APP_LOGFLARE_SOURCE=<LOGFLARE_SOURCE_ID>
```
This is a trial with Logflare, we can easily switch
to another provider at a later date.
See attached screen grab for an example of how a message appears in [Logflare](https://logflare.app/guides/overview)
ℹ️ Before merging this change ensure that environmental variables `REACT_APP_LOGFLARE_KEY` and `REACT_APP_LOGFLARE_SOURCE` have been added for all of the instances we wish to add logging to.

feat: adds logflare drain

---

.github/pull_request_template.md

The project recently switched to use commit messages
to generate the release notes rather than a semi-manual
method based on PR titles.
This change aims to make it easier for contributors to
understand how to address linting failures.
PR Checklist
PR Type

docs: update pr template to link through to commit

---

packages/cypress/src/support/custom-assertions.ts
src/components/ImageInput/ImageConverter.tsx

PR Checklist
PR Type
Fixes #1206, where if multiple images with the same name are uploaded their names collide resulting in only the first one being shown in all instances. It does this by adding a timestamp of the current time in base-16 text with `Date.now().toString(16)`
Closes #1206 
2 of the images on this page were named `mc.jpg` and the other 2 were both named `mc.png`.

fix: add image time stamps to uploaded images

---

functions/package.json
yarn.lock

PR Checklist
PR Type
We were running 0.26.0 released in late 2020,
this updates us to the latest and greatest.
https://sharp.pixelplumbing.com/changelog#v030---dresser
A big advantage of more recent versions is that
they come bundled with prebuilt binaries, removing
need to compile things for MacOS users
https://github.com/lovell/sharp/issues/2460#issuecomment-811046375
Example of the errors seen on MacOS Silicon
```
sharp@npm:0.26.3 couldn't be built successfully (exit code 1, logs can be found here: /private/var/folders/9f/dxvycrwd3533yff0ybdxfb4r0000gn/T/xfs-8786acf4/build.log)
```

chore(deps): upgrade sharp@0.30.x

---

.circleci/config.yml

There is a manual step involved when raising raising and then
merging a PR from `master` into the `production` branch.
As a result this manual step in the CircleCI configuration adds
an unnecessary and duplicative manual process into the release.
PR Checklist
PR Type

chore(ci): remove manual approval step from release pipeline

---

.circleci/config.yml

PR Checklist
PR Type
Description
The Cypress tests are now consistently failing
when running against the Firefox browser. However
driving the browser through the same steps it
is not possible to encounter the same issue.
This _appears_ to be a false positive, however
it is now blocking the production pipeline.
This change aims to remove this blockage so we
can debug this issue around Cypress + Firefox
stability separately.
Failing builds on default branch:
https://app.circleci.com/pipelines/github/ONEARMY/community-platform?branch=master&filter=all

chore(ci): remove firefox e2e tests

---

.circleci/config.yml

PR Checklist
PR Type
Given that we've currently removed firefox testing (see #1522) we might as well put all runners to use to run chrome tests a bit faster. As it happens I think we could still keep if adding back firefox/safari and just run independently on those browsers as a new test run (using parallelism from circleci instead of cypress)
Closes #
Looks like it should shave around 3mins of the tests overall
---
If you need more immediate feedback you can try reaching out on slack in the …

chore: increase number of ci cypress runners

---

firebase.json

PR Checklist
PR Type
After deploying a new iteration of the site a user
can hit an error state due to the service worker
attempting to load a JS file which no longer exists
on the Firebase hosting. This results in a 
broken white page. 
The default caching is 1 hour. However as the JS
bundles include a md5 string they are unique so can
be cached indefinitely. 
The intent of this change is to reduce the number of times
people encounter this white page of death. As each deployment
removes all previous files from the hosting, the aim 
here is for users to be able to load from their own cache.

fix: increase caching for static JS resources

---

package.json
packages/components/package.json
packages/components/src/Icon/Icon.tsx
src/components/Comment/Comment.tsx
yarn.lock

PR Checklist
PR Type
It seems that although we are only using
a limited selection of icons from this package
we are seeing the react-icons bundle at 2.61Mb
Switching to use @react-icons/all-files instead
which seems to offer better tree shaking.
The linked GitHub issue thread suggests that
webpack _should_ be able to optimise the bundle
size. However I think owing to our dependency
on an outdated CRA we are not getting those benefits.
https://github.com/react-icons/react-icons/issues/154
Before: 
After:

chore: reduce react icon bundle size

---

package.json
packages/components/package.json
packages/components/src/Icon/Icon.tsx
src/components/Comment/Comment.tsx
yarn.lock

Testing a revert of ONEARMY/community-platform#1547
Since this change was merged the CircleCI jobs have started failing with a consistent error message:
```
yarn build:components && yarn workspace functions build && yarn workspace functions emulator:test
Usage Error: Couldn't find the node_modules state file - running an install might help (findPackageLocation)
$ yarn run [--inspect] [--inspect-brk] [-T,--top-level] [-B,--binaries-only] <scriptName>
```
https://app.circleci.com/pipelines/github/ONEARMY/community-platform/1688/workflows/7d99b4cf-7267-485b-8e55-eb2684756c81/jobs/8892
Questions:
1. What does that error message from `yarn` really mean?
2. Why was this failure not caught _before_ merging?

Revert "chore: reduce react icon bundle size"

---

firebase.json
src/service-worker.ts

PR Checklist
PR Type
The default behaviour in the platform hosting is to redirect any URLs that don't match an exact file to the main index.html. This is needed for us to handle spa routing for urls like `/howto` within the main app (via the react-router), because there is not /howto.html page). A weird caveat of this is fetching of static resources (like the main build js and CSS files), which firebase defaults to not redirecting IF AND ONLY IF the file exists. So any requests for JS/CSS that does not exist in the server is instead sent a copy of the index.html page, which will be stored in cache and throw an error when accessed. In production this can sometimes mean the user sees a blank white screen and the app won't load until the cache has had time to sort itself out (usually …

chore: prevent redirect of static assets

---

package.json

PR Checklist
PR Type
Change main npm scripts to use concurrently package instead of `&` operator. This allows cli output to be a bit cleaner (distinguish what logs are coming from which process) and allow failure in one process to kill over (e.g. component compile fail stops server instead of just disappearing into the night). 
This is particularly useful for things like start:emulated which needs to run 3 tasks in parallel without outputs getting garbled up along the way
---
If you need more …

chore: make npm scripts use concurrently

---

packages/documentation/docs/Backend Development/firebase-emulators-docker.md
packages/emulators-docker/README.md
packages/emulators-docker/src/start.ts

PR Checklist
PR Type
Adds an additional wait step to ensure functions are built before starting the docker emulator (otherwise will fail to successfully link up the functions code with the emulator)
Adds additional line to docs for clearing cached data
Closes #
Now CLI will show `waiting for functions to be built...` instead of trying to proceed without the functions code (and crashing)

fix: add functions build wait for docker emulator

---

.circleci/config.yml

PR Checklist
PR Type
The Release should be generated _before_ we deploy
our code to the production environments.
We have already merged the code to `production` so
regardless of whether it makes it out to the live sites
it has been released.

chore(ci): adjust order of Release generation

---

src/pages/Settings/content/formSections/AccountSettings.section.tsx
src/pages/Settings/content/formSections/Collection.section.tsx
src/pages/Settings/content/formSections/Expertise.section.tsx
src/pages/Settings/content/formSections/Focus.section.tsx
src/pages/Settings/content/formSections/MemberMapPin.section.tsx
src/pages/Settings/content/formSections/UserInfos.section.tsx
src/pages/Settings/content/formSections/Workspace.section.tsx
src/pages/Settings/content/formSections/WorkspaceMapPin.section.tsx
src/pages/Settings/content/formSections/elements.tsx

PR Checklist
PR Type
The collapsible behaviour on these blocks had a different implementation for each of the sections, so there are two approaches we could take here, either extract or standardise into a reusable component or remove it entirely if the behaviour is not worth the investment.
Before this change the functionality within the Account Settings pane was hidden behind _three_ required user interactions:
1. The user must scroll to the bottom of the page
2. The user must know to and then expand the Account Settings pane
3. The user must click the action they required. 
This change simplifies the interaction for our intreprid user by 33.33333% 
The following screenshot shows how this page renders _without_ the collapsible icon/behaviour.

feat: removes collapsible behaviour from settings

---

src/pages/Howto/Content/Howto/HowtoDescription/HowtoDescription.tsx
src/pages/Howto/Content/Howto/Step/Step.tsx
src/pages/Research/Content/ResearchDescription.tsx
src/pages/Research/Content/ResearchUpdate.tsx

PR Checklist
PR Type
- Implements behaviour proposed in #1619
- Parses in-content links with [react-linkify](https://tasti.github.io/react-linkify/) and adds the `target="_blank"` attribute so they open in a new tab
- Applies to how-to descriptions, how-to steps, research descriptions, and research updates
- Based on [this approach](https://github.com/ONEARMY/community-platform/pull/1639/files#diff-7aab05b5c350e50591b3ebe276a7734835df27cdd7b6e1f8f607576f2023cbddR76) for how-to comments and research comments in #1639
Closes #1619
Examples
- [How-to description and step](http://localhost:3000/how-to/test-links-in-description-and-step)
- [Research description](http://localhost:3000/research/test-test)
- Research update: could you, kind reviewer, test this one? 😅 (I couldn't figure out how)

fix: open links in new tab

---

package.json
packages/cypress/src/integration/settings.spec.ts
src/pages/Settings/SettingsPage.tsx
src/pages/Settings/content/formSections/MemberMapPin.section.tsx
src/pages/Settings/content/formSections/UserInfos.section.tsx
yarn.lock

PR Checklist
PR Type
A SelectField which contains countries from the library countries-list has been added. It's shown by default (showLocationDropdown is set to true in the UserSettings components' state) but when we click the button in the MemberMapPinSection component to add a pin, the toggleLocationDropdown() function (which is passed to the component as a prop so we can modify the parent component's state) is called, disabling the locations dropdown.
Closes #1541
---
If the PR is working as intended it'll be merged and included in the next platform release, if not changes will …

feat: add country dropdown in profile settings

---

.github/workflows/reset-staging-site.yml

PR Checklist
PR Type
We have been seeing some flakey builds in our GitHub actions, the error is usually something like:
```
Error: The process '/opt/hostedtoolcache/node/16.15.1/x64/bin/npx' failed with exit code 127
```
Hoping that bumping to the latest version of the action may help here 🤞🏻

chore(ci): bump action to use latest version of node action

---

src/pages/Settings/content/formSections/Focus.section.tsx
src/themes/fixing-fashion/styles.ts
src/themes/project-kamp/styles.ts

PR Checklist
PR Type
Prevent the Settings page from erroring out
due to missing badges in the current theme :/
This duplicative declaration of member types between
themes and the standalone module points to the
abstraction being wrong here. Requires some
further thought and iteration.
Closes https://github.com/ONEARMY/community-platform/issues/1729

fix: profile settings for fixing fashion

---

src/pages/Maps/Content/Controls/GroupingFilterDesktop.tsx
src/pages/Maps/Content/Controls/GroupingFilterMobile.tsx
src/pages/Maps/Content/Controls/transformSpecialistWorkspaceTypeToWorkspace.tsx

PR Checklist
PR Type
Addresses an issue where specialist workspace types were being incorrectly resolved to a fallback badge.
**Before:**
**After**

fix: badge icons for specialist workshops

---

src/components/FileInfo/FileInfo.tsx
src/models/howto.models.tsx
src/pages/Howto/Content/Howto/HowtoDescription/HowtoDescription.tsx
src/pages/Howto/Content/Howto/HowtoDescription/downloadCooldown.ts
src/pages/Howto/Content/Howto/HowtoDescription/utils.tsx
src/pages/Howto/DownloadExternal/DownloadExternal.tsx
src/stores/Howto/howto.store.tsx

PR Checklist
PR Type
I have added a total downloads counter feature. When the download file button is clicked this increments the total_downloads property of the howto model and also updates state inside of the FileInfo component in order to re-render the newly incremented value. 
BUG: I am also aware that since older howto's don't have a total_downloads property then they currently just show 'downloads' without a value. I didn't implement a conditional check because I was thinking we would update all howto's to have the total_download property if they have an attached file? Or is this feature not going to be retroactive and only affect newly created howto's?
Potential issue with using LocalStorage: a malicious user could find remove the cooldown manually and spam download.

1617-add-download-count-howto

---

.releaserc.json

PR Checklist
PR Type
Originally the releases were generated _after_ the code
had been deployed to a production environment. However
as the number of deployed instances has increased past one,
the question is if code is partially deployed has been released?
Not wishing to get lost down that rabbit hole we opted to declare
code released _before_ it is then deployed to the instances.

chore(ci): generate releases on master(default) branch

---

functions/src/aggregations/common.aggregations.ts

PR Checklist
PR Type
The user badges aggregation keeps failing to seed due to max write issues
The code already batches requests to limit to 500 updates per second, however it may be the case that some updates are counted twice so limiting to 250 instead
Once merged it can be tested by toggling the badge status for any of the users
In the emulator everything already worked before so hard to test, example output below
Closes #
--- …

fix: aggregations limit

---

functions/src/aggregations/user.aggregations.ts

PR Checklist
PR Type
User verified aggregation populates the value from the saved badge field, however some of these are populates as string `"true"` instead of boolean `true`, which then doesn't show up in some filters. See example from screenshots in #1782
This forces a boolean value on the aggregation.
Note - it will only apply to users changed after the fix has been deployed (existing users manually migrated)
Closes #
---
If you need more immediate feedback you can try reaching out on slack in …

fix: populate users_verified as boolean

---

.circleci/config.yml

PR Checklist
PR Type
When builds fail a message is posted to slack. The message tries to tag me but
a) I'm super unresponsive
b) It doesn't tag me correctly
This makes fail notifications try to tag `@channel` instead. Hopefully we will never see this...
---

chore: change slack fail notification mention

---

.github/workflows/pr-preview.yml

PR Checklist
PR Type
Our automation action to deploy previews to firebase seems to be failing, e.g.
https://github.com/ONEARMY/community-platform/runs/6974256199?check_suite_focus=true
The error suggests an issue with how the 3rd-party firebase-hosting-deploy action calls the firebase cli (`firebase-tools`) using npx.
This installs the firebase cli globally instead so that it should be available when the action calls also.
Should be working now, although as the default action relies on pull_request_target it will only use the code from this function after merge into master (I manually forced the action to run for the demo below by changing the trigger to pull_request):
https://github.com/ONEARMY/community-platform/runs/6975113104?check_suite_focus=true
Closes #
_If useful, provide …

fix: update hosting-preview action

---

shared/models/db.ts

PR Checklist
PR Type
The shared db endpoint generator method which includes a check for any prefix stored in sessionStorage (as used by cypress tests), however when running on backend functions the sessionStorage object is not available, so this throws an error. It seems a recent update might have started to check and catch these things, instead of previously running unnoticed.
This pr adds a check for to see if sessionStorage is available before trying to use (via `typeof sessionStorage === 'undefined'`)
Seen in:
https://app.circleci.com/pipelines/github/ONEARMY/community-platform/2669/workflows/afbed966-55a3-4015-a6a3-ed8722699414/jobs/15743
Closes #
---
Thanks for the contribution! We try to make sure all PRs are …

fix: avoid calling sessionStorage from non-browser env

---

packages/cypress/src/integration/howto/write.spec.ts
shared/mocks/data/howtos.ts
src/pages/Howto/Content/Howto/HowtoDescription/HowtoDescription.tsx
src/stores/Howto/howto.store.tsx

PR Checklist
PR Type
I realized that I had forgot to implement a check to stop the counter from being reset when the howto is edited.
Closes #
---

fix: download counter not resetting to 0 on howto edit

---

src/pages/Maps/Content/Controls/transformAvailableFiltersToGroups.tsx

PR Checklist
PR Type
Will not show filters in the map dropdown if there are no items belonging to that group.
Closes [#1775](https://github.com/ONEARMY/community-platform/issues/1775)
**Before**
**After**

fix: do not show map filters if there are no items

---

.circleci/config.yml

PR Checklist
PR Type
Pin CI version of firebase tools to unblock build due to regression seen in firebase tools:
`https://github.com/firebase/firebase-tools/issues/4697`
Closes #
---

fix: pin firebase tools ci version to fix  regression

---

src/pages/Howto/Content/HowtoList/HowtoList.tsx

PR Checklist
PR Type
Fixes padding for heading within how-to.
Closes #1849 
---

fix: reduced how-to heading padding for mobile

---

src/pages/Settings/content/formSections/elements.tsx

PR Checklist
PR Type
This PR adds a css property that allows a SelectField to show its children when exceeding it parent
Closes #1866 
[Video](https://streamtape.com/v/xODO30vG1wTkKLB/2022-08-07_14-33-14.mkv)

fix: add visibility to SelectField child items when exceeding parent

---

functions/src/userUpdates/index.ts

PR Checklist
PR Type
Fixes the bug where updating a country in user profile wouldn't reflect in the comments the user made. The logic runs in a function which triggers from user updates. The function queries for all the howtos, then filters and updates the comments owned by the user. An optimization could be made here by querying directly for the howtos where the user participated, with something involving `array-contains` and the userName, but would require an additional aggregation data structure, as [discussed on Slack](https://onearmy.slack.com/archives/C01CXSDSMC2/p1657933042198259). This can be looked at as an optimization in the future.
Closes #1469

fix(functions): updating user info in howto comments

---

src/pages/Maps/Content/View/index.tsx

PR Checklist
PR Type
This PR adds a verification to hide map zoom controls on mobile/tablets devices, due to its pinch mechanism
Closes #1839

feat: remove map zoom control on mobile/tablet

---

.github/pull_request_template.md

PR Checklist
PR Type
Removes mention of the Slack channel from the PR template, instead directing folks to the Discord channel. 
---

chore: adds link to PR template through to Discord channel

---

src/pages/User/content/SpaceProfile.tsx

PR Checklist
PR Type
User stats in profile can at times overflow outside of its box. This fix prevents that by removing max-width and flexing the box.
Closes #1890
---

fix: added flex to container to prevent overflow of content

---

package.json
src/models/comment.model.ts
src/models/howto.models.tsx
src/models/index.ts
src/models/user.models.tsx
src/stores/Howto/howto.store.test.ts
src/stores/Howto/howto.store.tsx
src/stores/Research/research.store.test.ts
src/stores/Research/research.store.tsx
src/stores/common/__mocks__/module.store.ts
src/test/factories/Comment.ts
src/test/factories/Howto.ts
src/test/factories/ResearchItem.ts
src/test/factories/User.ts
yarn.lock

PR Checklist
PR Type
Recently we introduced an `@mention` feature. This enables users to mention others at multiple places within a Research and Howto article; these are are main description, update description and comments.
This behaviour relies on `addUserReference` having been applied to each of those fields to convert a plain `@mention` string to a user reference ID: `@@{userId:username}`.
Every method which modifies the ResearchItem|HowtoArticle first clones and saves the ResearchItem which means the save object does _not_ have a userReferenceId available. 
I think that there is value in refactoring the internal flow of the store so that we can avoid this rework but first let's fix the immediate bug and introduce some tests to make it safer to refactor the implementation. 
---
Thanks …

fix: user references after updates

---

src/pages/Research/Content/ResearchUpdate.test.tsx
src/pages/Research/Content/ResearchUpdate.tsx

PR Checklist
PR Type
Do not show create and edited datestamps if they show the same value. 
**Before:**  
**After:**

fix: research update, do not show identical created/edited timestamps

---

.eslintrc.json
packages/components/.eslintrc.json
packages/components/package.json
packages/components/src/MapMemberCard/MapMemberCard.stories.tsx
packages/components/src/MapMemberCard/MapMemberCard.tsx
packages/components/src/index.ts
src/pages/Maps/Content/View/Popup.tsx
src/pages/Maps/Content/View/popup.css
yarn.lock

PR Checklist
PR Type
* Refactors the Map Card out to a stateless component `MapMemberCard`
* Adds a loading state which better the dimensions for the loaded state
This first screen recording demonstrates the current behaviour. The card displays a small block containing "loading" before the user data is fetched and displayed. This results in the card being resized which feels a bit janky.
https://user-images.githubusercontent.com/472589/204007419-36eb0cfb-29e5-4e70-8ba6-ba79da3cb497.mov
The second screen recording demonstrates the proposed behaviour. Instead the card's loading state better matches the expected size _after_ the content has loaded. This creates a gentler transition from the loading to loaded state.
https://user-images.githubusercontent.com/472589/204007443-5126e881-20e5-45fc- …

feat: move map card to component

---

package.json
yarn.lock

PR Checklist
PR Type
Removes unused dependency, linkifying text is now handled via [the LinkifyText component](https://onearmy.github.io/community-platform/storybook-static/index.html?path=/story/components-linkifytext--default)

chore(deps): remove unused react-linkify

---

.github/workflows/docker-emulator-build.yml

PR Checklist
PR Type
It looks like some of the recent robot release PRs are failing e.g. #2022.
The release pr is rebuilding the docker seed data image when it shouldn't be (should only build when changed). It appears there is an issue with the indentation on the file that specifies the build triggers (introduced in bc68f6ae7605eace885b27b5e1293a8aa29d0b87). 
https://github.com/ONEARMY/community-platform/actions/runs/3671170395/jobs/6206188896
This pr should fix that and add better rules to try ensure the docker builds only happen on merge into master when seed data changed. Likely follow-up will be needed when next running emulator build to see if there has been a breaking change  within our own code somewhere or just a temporary glitch in the build process (e.g. github/docker error). …

fix: docker emulator build triggers

---

packages/components/src/Button/Button.stories.tsx
packages/components/src/Button/Button.tsx
packages/components/src/CommentList/CommentList.tsx
packages/components/src/MapMemberCard/MapMemberCard.tsx
src/pages/Events/Content/EventsCreate/EventsCreate.tsx
src/pages/Events/EventCard/EventCard.tsx
src/pages/Howto/Content/Common/Howto.form.tsx
src/pages/Howto/Content/Common/HowtoStep.form.tsx
src/pages/Howto/Content/Howto/HowtoDescription/HowtoDescription.tsx
src/pages/Howto/Content/HowtoList/HowtoList.tsx
src/pages/Password/ForgotPassword.tsx
src/pages/Password/ForgotPasswordMessage.tsx
src/pages/Research/Content/Common/Research.form.tsx
src/pages/Research/Content/Common/Update.form.tsx
src/pages/Research/Content/ResearchDescription.tsx
src/pages/Settings/SettingsPage.tsx
src/pages/Settings/content/ProfileDelete.tsx
src/pages/Settings/content/formSections/ChangeEmail.form.tsx
src/pages/Settings/content/formSections/ChangePassword.form.tsx
src/pages/Settings/content/formSections/Fields/Link.field.tsx
src/pages/Settings/content/formSections/Fields/OpeningHoursPicker.field.tsx
src/pages/SignIn/SignIn.tsx
src/pages/SignUp/ResendSignUpMessage.tsx
src/pages/SignUp/SignUp.tsx
src/pages/common/Header/Menu/Profile/ProfileButtonItem.tsx
src/pages/common/Header/Menu/Profile/ProfileButtons.tsx
src/themes/common/button.ts
src/themes/fixing-fashion/styles.ts
src/themes/precious-plastic/styles.ts
src/themes/project-kamp/styles.ts

PR Checklist
PR Type
It was the misalignment of text and icons in the folllowing screengrab that started me down this path. 
* Remove unused `medium` variant in favour of a sensible default complimented by a small and large variant.
* Remove snowflake transform effect from `Create new How-to` button.
* Introduced documentation for all variants within Storybook
Questions:
* Large is not currently being used anywhere, should we just remove it?
* Inconsistent cases, some buttons are lowercased `action` and others are capitalized `Action`. Do we have a clear preference here? 
Closes #

fix: address button inconsistency

---

packages/components/src/SiteFooter/SiteFooter.tsx

PR Checklist
PR Type
All of the instances of Platform are used by a project operating under the banner of One Army. These benefit greatly from the support of patrons. Adding an explicit call to action aims to increase the number of visitors to the Patreon page and drive up number of patrons.  
Before:  
After:

feat: adds link to Patreon in footer

---

src/pages/index.tsx

PR Checklist
PR Type
Drop use of emoji within a button in favour of standard icon followed by text pattern used across the entire platform. 
Before:  
After:  
---

fix: use standard button icon for Discord link

---

packages/components/src/UsefulStatsButton/UsefulStatsButton.tsx

PR Checklist
PR Type
Overrides border colour for subtle button variant when used within Useful stats
**Before:** 
**After:**
---

fix: override blue border of subtle button variant

---

src/pages/Howto/Content/Howto/HowtoDescription/HowtoDescription.tsx

Use new `showIconOnly` property and use margin-left for consistent layout.
(cherry picked from commit 9ddc1c6f624f31fd0d9a388afb2e3f3fa0f068fa)
PR Checklist
PR Type
Rebase of #2065 to fix commitlint issue
Closes #2065
---

fix: adds accessible labels to moderation buttons

---

scripts/envCheck.js

The envcheck was generating output when all
tests pass. Whilst reassuring, this is a distraction
when kicking off new tasks. We should aim for
actionable output and reduce noise where possible.
🕊️
Additional changes:
* Refactor to remove unused `severity` property
* Reduce logic branches within for loop
* Remove indent of documentation URL
PR Checklist
PR Type
Closes #
---
If you need more immediate feedback …

chore: only print output in failure scenario

---

craco.config.ts
src/pages/Howto/Category/CategoriesSelect.tsx
src/pages/Research/research.routes.test.tsx

PR Checklist
PR Type
Adds back a test suite which had previously been disabled.

test: reinstate skipped research.routes test

---

functions/src/emulator/seed/content-generate.ts
packages/components/src/NotificationItem/NotificationItem.tsx
packages/cypress/src/integration/notifications.spec.ts
packages/cypress/src/integration/research/comments.spec.ts
packages/cypress/src/support/custom-assertions.ts
shared/mocks/data/research.ts
src/models/common.models.tsx
src/models/howto.models.tsx
src/models/research.models.tsx
src/models/user.models.tsx
src/pages/Research/Content/ResearchArticle.tsx
src/pages/Research/Content/ResearchComments/ResearchComments.tsx
src/pages/Research/Content/ResearchUpdate.test.tsx
src/pages/Research/Content/ResearchUpdate.tsx
src/pages/Research/Content/helper.test.tsx
src/pages/Research/Content/helper.ts
src/pages/common/Header/Header.tsx
src/pages/common/Header/getFormattedNotifications.test.tsx
src/pages/common/Header/getFormattedNotifications.tsx
src/stores/Howto/howto.store.tsx
src/stores/Research/research.store.test.ts
src/stores/Research/research.store.tsx
src/test/factories/Notification.ts
src/test/factories/ResearchItem.ts

PR Checklist
PR Type
Closes #
---

feat: support mention in Research descriptions, updates and comments

---

functions/src/aggregations/userNotifications.aggregations.ts

PR Checklist
PR Type
Fix minor bug blocking user notifications seed on production
Should test if aggregations populated for user notifications following merge and deployment to dev/production.
Note - this will require having at least 1 user subscribed to notifications and a new notification triggered for initial seeding.
Closes #
---
If you need more immediate feedback you can try reaching out on Discord in the [Community Platform …

fix: user notifications aggregation seed

---

src/modules/admin/pages/adminNotifications.tsx
src/pages/common/Header/getFormattedNotifications.tsx
src/stores/databaseV2/DocReference.tsx

PR Checklist
PR Type
Fix admin panel to display notifications stored in legacy format. They didn't track the `triggeredBy` user in the same way, so for now just marking as "Anonymous". Unclear if any of these notifications exist in production, so for now mostly just to keep the dev site working until we have a better way to clean-up legacy data.
Closes #
**Admin panel now lists pending emails in table**
---
If you need more immediate feedback you can try reaching out on Discord in the [Community …

fix: admin notifications legacy format

---

src/pages/Howto/Content/Howto/HowToComments/HowToComments.tsx

PR Checklist
PR Type
Adjust the margin and width of elements in the HowToComments component so they are consistent 
Closes #2118
---

fix: adjust margin and width of elements in HowToComments

---

src/stores/Howto/howto.store.test.ts
src/stores/Howto/howto.store.tsx
src/stores/Research/research.store.test.ts
src/stores/Research/research.store.tsx
src/test/factories/Howto.ts
src/test/factories/ResearchItem.ts

PR Checklist
PR Type
Fetches howto data from server rather than cache on view. Temporary fix until serverside incrementation is implemented.
Closes #2115

fix: added fetching from server for views

---

packages/components/src/ViewsCounter/ViewsCounter.tsx
packages/cypress/src/integration/howto/read.spec.ts
packages/cypress/src/integration/research/read.spec.ts
shared/mocks/data/research.ts
src/pages/Howto/Content/Howto/HowtoDescription/HowtoDescription.tsx
src/pages/Research/Content/ResearchDescription.tsx

PR Checklist
PR Type
I noticed that this [line](https://github.com/ONEARMY/community-platform/blob/e2727c9ea7ec9c3e149ce9885fc66f9caf138c45/src/pages/Howto/Content/Howto/HowtoDescription/HowtoDescription.tsx#L56) was added, the issue is that now it will set `didInit` to true after a single howto or research is viewed and then the `useEffect` won't run again for other pages until page refresh.  This fixes the issue.

fix: move initialization boolean inside component

---

.eslintrc.json
packages/components/.eslintrc.json
packages/cypress/src/integration/settings.spec.ts
src/models/user.models.tsx
src/pages/Howto/Content/Howto/HowToComments/HowToComments.tsx
src/pages/Research/Content/ResearchComments/ResearchComments.tsx
src/pages/Settings/SettingsPage.tsx
src/pages/Settings/content/formSections/Fields/Link.field.tsx
src/pages/Settings/content/formSections/Fields/ProfileLink.field.tsx
src/pages/Settings/content/formSections/UserInfos.section.tsx

PR Checklist
PR Type
Fixes an issue that occurs when attempting to remove the first list item from Contacts and Links.
Seems to be coming from: https://github.com/ONEARMY/community-platform/blob/master/src/pages/Settings/content/formSections/Fields/Link.field.tsx#L136:L136
Related chatter:
* https://github.com/final-form/react-final-form-arrays/issues/128
* https://github.com/marmelab/react-admin/pull/6763/files
Closes issue reported: 
https://discord.com/channels/586676777334865928/1079116300133072897/1079116300133072897

fix: handle removing first item from Contact and links

---

src/.eslintrc.json
src/common/Error/handler.ts
src/logger/index.ts
src/modules/admin/pages/adminUsers.tsx
src/pages/Maps/Maps.tsx
src/pages/common/UploadedFile/FirebaseFileUploader.tsx
src/serviceWorkerRegistration.ts
src/stores/Admin/admin.store.ts
src/stores/Howto/howto.store.tsx
src/stores/Research/research.store.tsx
src/stores/Theme/theme.store.tsx
src/stores/User/user.store.ts
src/stores/databaseV2/CollectionReference.tsx
src/stores/databaseV2/clients/dexie.tsx
src/utils/firebase.ts

PR Checklist
PR Type
- chore: prevent console log
- chore: code changes to introduce logger instead of using console.log
@AlfonsoGhislieri raised a really useful bit of PR feedback around `console.log`. I propose we adopt automated checks to catch this and free up our reviewers time to concentrate on details not solved with tooling.
--- …

chore: remove usage of console.log in primary SPA

---

packages/components/src/Button/Button.tsx
packages/components/src/CreateComment/CreateComment.tsx
packages/emulators-docker/src/common.ts
shared/messages.ts
src/common/Form/ImageInput/ImageInput.tsx
src/pages/Howto/Content/EditHowto/EditHowto.tsx
src/pages/User/content/UserContactAndLinks.tsx
src/stores/Aggregations/aggregations.store.tsx
src/stores/Howto/howto.store.tsx
src/stores/Maps/maps.store.ts
src/stores/common/module.store.ts
src/utils/helpers.ts

PR Checklist
PR Type
It’s better to always call built in methods from Object.prototype.
For example, foo.hasOwnProperty("bar") should be replaced
with Object.prototype.hasOwnProperty.call(foo, "bar").
Further information:
https://eslint.org/docs/latest/rules/no-irregular-whitespace

chore: refactor to remove use of prototype built ins

---

src/pages/User/content/SpaceProfile.tsx

PR Checklist
PR Type
Adds a 2px black border between space images and information.
**Before:** 
**After:**  
The aim here is to address lack of definition when leading image has a white background, for example: https://community.preciousplastic.com/u/ecopazifico-

fix: add border between image and content

---

src/pages/Howto/Content/Howto/HowtoDescription/HowtoDescription.tsx
src/pages/Research/Content/ResearchDescription.tsx

PR Checklist
PR Type
Use standard Button with icon variant for `Back` button on Research and How-to Description. Introduces standard `arrow-back` icon and spacing. 
**Before:**   
**After:**.

chore: switch to using icon within button component

---

packages/components/src/FieldInput/FieldInput.tsx
src/pages/Howto/Content/Common/Howto.form.tsx

In order to easier see what the limit of characters in the howto creation for the title is, show current and maximum number of characters next to the text area widget.
PR Checklist
PR Type
Introduced the better character length indicator on the title input ui for event
Closes #2015 
https://user-images.githubusercontent.com/4504330/228482191-3b00edd0-66c8-4c90-9dd0-09c8d91cee0a.mp4
--- …

feat(Howto.form): added current character count indicator

---

src/pages/admin/content/AdminTags.tsx

in order to visually distinguish the categories tag I am introducing the separator between the tags
fix #2181
PR Checklist
PR Type
Closes #
---

fix(AdminTags.tsx): change categories separator

---

.circleci/config.yml

Circular dependency test was incorrectly spelt
PR Checklist
PR Type
Minor spelling mistake fixed

chore: fix spelling of CI test

---

.circleci/config.yml
package.json
packages/components/.gitignore
packages/components/package.json
packages/components/vite.config.mts
yarn.lock

PR Checklist
PR Type
Opt into test coverage for jest tests. The aim here would be to integrate with a 3rd party tracking service that allows us to visualise test coverage over time so we can get visibility into this dimension of the code.
Initially I would suggest trying out https://coveralls.io/ as it offers a free plan for open-source projects.
**Edit** Added [🚧 Blocked](https://github.com/ONEARMY/community-platform/labels/%F0%9F%9A%A7%20Blocked) label until one of the maintainers can authorize coveralls.io access to the GitHub repo

chore(ci): track coverage

---

functions/src/emailNotifications/createEmail.ts
functions/src/emailNotifications/index.ts
src/modules/admin/pages/adminNotifications.tsx

PR Checklist
PR Type
this PR creates a button in the admin notifications page that will trigger the create email function to run. this will enable email testing in the development environment.
to do this, i created another firebase function `emailNotifications-sendOnce` that triggers the `createEmail` function through an HTTP call. it requires that the caller be an authorized user with admin permissions.  
we can see emails getting populated in the emails collection locally, but our local emulator env is not integrated with the email extension, so we can't test the full flow until it is deployed.
Closes #
https://user-images.githubusercontent.com/37253846/234773589-07fc2e5c-262a-4f55-b766-8a3a9644fdc3.mov
to try locally follow setup here …

feat(email-notifs): send emails from admin panel for testing

---

packages/themes/src/common/variants.ts
packages/themes/src/fixing-fashion/styles.ts
packages/themes/src/precious-plastic/styles.ts
packages/themes/src/project-kamp/styles.ts
src/pages/Howto/Content/Howto/HowtoDescription/HowtoDescription.tsx

PR Checklist
PR Type
Removes direct use of theme and adds theme aware properties where possible, this does highlight the need to move remove typography in favour of variants in the themes (adding to my TODO).
Also uses breakpoints to set flexDirection dynamically.

refactor: remove direct use of theme in howto description

---

functions/src/emailNotifications/createEmail.ts
src/models/user.models.tsx

PR Checklist
PR Type
another detail i realized we needed...
if an email fails, i don't think we should keep attempting it. the way the pending email aggregation is written, notifications for a user will remain in the pending list until they are marked notified, read, or sent as an email. therefore, i updated the fn to set the `email` field to `'failed'` on error.
i also realized that my update function updated ALL the user's notifs, not just the ones that got sent out in the email... so fixed that
Closes #
---
If the PR is working as intended it'll be merged and included in the next …

fix(email-notifs): update email field to failed on error

---

packages/cypress/src/fixtures/searchResults.ts
packages/cypress/src/integration/events.spec.ts
packages/cypress/src/integration/notificationBanner.spec.ts
packages/cypress/src/integration/settings.spec.ts
packages/cypress/src/support/commands.ts

PR Checklist
PR Type
Makes events test more robust by waiting for url to match rather than a specific set of time (previously set as 3 seconds)
https://www.npmjs.com/package/cypress-wait-until?activeTab=readme could also be an interesting option if this fails
Closes #2287 
--- …

test: make events e2e test more robust by mocking reverse address fetch

---

src/pages/Howto/Content/Common/Howto.form.test.tsx
src/pages/Howto/Content/Common/Howto.form.tsx

PR Checklist
PR Type
Resets the files in the form to an empty array when the re-upload button is clicked, causing problems in #2280 as pointed out by @davehakkens 
This is done using the formApi in react final form (https://final-form.org/docs/final-form/types/FormApi)
Closes #2313
--- …

fix: form values for files reset after reupload click

---

packages/components/src/Button/Button.stories.tsx
packages/themes/src/common/button.ts
src/pages/Research/Content/Common/Research.form.tsx
src/pages/Research/Content/Common/ResearchUpdate.form.tsx
src/pages/Research/Content/EditUpdate/index.tsx
src/pages/Research/Content/ResearchArticle.test.tsx
src/pages/Research/Content/ResearchArticle.tsx
src/pages/Research/Content/ResearchUpdate.tsx
src/stores/Research/research.store.test.ts
src/stores/Research/research.store.tsx

PR Checklist
PR Type
Building on the work in #2206 (please review that one first), this change introduces the ability to "Delete" a Research update.
Closes #
---

feat: adds option to delete ResearchUpdate

---

packages/documentation/docs/Maintainers/Onboarding.md
packages/documentation/docs/Maintainers/Overview.md
packages/documentation/sidebars.js

PR Checklist
PR Type
We propose creating a new documentation section that will outline the roles and responsibilities of the Maintainers. The purpose of this section is to simplify the onboarding process and facilitate knowledge sharing among all Maintainers. Since the project Maintainers are primarily volunteers, we should expect that people will need to take breaks from their responsibilities.
By documenting the processes, we can prevent knowledge silos and ensure that others can take over without issues.

docs: add a maintainers section to the developer documentation

---

packages/themes/src/fixing-fashion/styles.ts
packages/themes/src/precious-plastic/styles.ts
packages/themes/src/project-kamp/styles.ts
packages/themes/src/types/index.ts
src/modules/admin/components/AdminSubheader.tsx
src/modules/admin/index.tsx

PR Checklist
PR Type
Removes direct usage of the theme object, instead accessing it within the `sx` property.

fix: remove use of theme from admin subheader

---

src/pages/Research/Content/ResearchDescription.tsx

PR Checklist
PR Type
Shown follow button for non-logged-in users
To achieve this I didn't allow it to render conditionally so that it can be visible to both logged-in as well as non-logged-in users. 
Also, I have added the tooltip that says "login to follow".
#2337
NA
---

feat: show follow button for non-logged in users

---

codecov.yml

PR Checklist
PR Type
We have been seeing pretty much all status checks from Code cov fail due to coverage being reduced by ~0.5%. Whilst it would be great to have this level of strictness to our checks it is not possible with the current code. To avoid the risk of people [learning to ignore warnings](https://www.atlassian.com/incident-management/on-call/alert-fatigue#What-is-alert-fatigue?) from CodeCov we are going to increase the threshold for the foreseeable future. 
- chore(ci): increase threshold on code cov
- chore(tooling): reduce number of comments from codecov

chore: increase threshold on code cov

---

src/stores/Research/research.store.test.ts
src/stores/Research/research.store.tsx

PR Checklist
PR Type
There was a problem saving issues because the `collaborator` property being sent through to Dexie was still an observable array. This caused an error to be thrown by IndexDB/Dexie. 
This fix forces a plain object to be passed through.
Not addressed by this PR:
* Although an error was thrown by Dexie, the record on Firestore was updated. So when reloading the page the comment would be added as expected. What should the UI do if there is a crash at IndexDB, should it force a page reload to ensure alignment with origin?
---
If the PR is working as intended it'll be merged and included in the next platform release, if not changes …

fix: ensure plain object before save

---

src/stores/Research/research.store.test.ts
src/stores/Research/research.store.tsx

PR Checklist
PR Type
The bug behaviour here is that the Follow button would not show the correct Follow/Following state for some users. 
Reverts to using the `userName` property of User entity. There is some drift across user entities where the `_id` property could contain either the Firestore Auth ID **or** the username. This is something that will need to be addressed separately but is out of scope for this change.
Original implementation:
https://github.com/ONEARMY/community-platform/commit/bc6985ecff43ed87ae1ea9afb0e431aacdb8a357#diff-404a1450ddfbbd25ee32f597e3e8675f7142774a2efa5a730044cdf6ffed0847R234

fix: compare against username property

---

src/pages/Research/Content/Common/SubmitStatus.tsx
src/stores/Research/research.store.tsx

PR Checklist
PR Type
When toggling the Follow/Following status on a Research Article any mentions within the description or Research steps would be broken. This is because when loading data out of the database we need to transform these mentions from an internal to external representation. This is done within the `setActiveResearchItemBySlug` method but elsewhere in the store we were fetching and setting plain DB objects as the activeResearchItem.
- fix: mentions when follow/unfollowing
- chore: refactor to move loading of active item to single function
The original buggy behaviour:
https://github.com/ONEARMY/community-platform/assets/472589/3937ef29-76cd-4c98-bd17-c7437803c82b

fix: interaction between @mention and follow

---

src/pages/User/content/MemberProfile.tsx

PR Checklist
PR Type
Falls back to a blank array for the links property if user doc is missing it. This stops the filter that is part of the MemberProfile component from failing and preventing the profile form loading.
Closes #2396
---

fix: profile load for users without links array

---

package.json
packages/cypress/src/support/commands.ts
packages/cypress/src/support/hooks.ts
src/index.tsx
src/pages/common/ServiceWorkerUpdateNotification/ServiceWorkerUpdateNotification.tsx
src/pages/index.tsx
src/service-worker.ts
src/serviceWorkerRegistration.ts
src/stores/Platform/platform.store.tsx
src/stores/index.tsx
yarn.lock

This reverts commit 545f80481b3ead992603a031bed39bba79310495.
PR Checklist
PR Type
Introduces almost completely empty Service Worker script to remove all functionality. This is necessary because simply deleting the service worker file may not lead to the expected behaviour for all clients. Some browsers may not know that the file is meant to be gone and will continue serving the old service worker from their HTTP cache.

feat: adds empty service-worker ahead of completely removing

---

functions/src/aggregations/common.aggregations.ts
functions/src/aggregations/howto.aggregations.ts
functions/src/aggregations/research.aggregations.ts

PR Checklist
PR Type
Useful aggregation was counting useful from how-to & research that was still awaiting moderation or rejected in the total count.  Updated so that only useful from accepted how-to/research is counted.
Closes #
---

fix: update useful aggregation to only count useful from accepted docs

---

src/pages/Password/ForgotPassword.tsx

PR Checklist
PR Type
Removes direct usage of the theme object, replacing it with the `Label` component that is used on the signup screen
Closes #2295
Seems to be no visual diff to my eyes -
On master:
After:

fix: remove use of theme from forgot password

---

functions/src/Integrations/firebase-discord.ts
functions/src/database/index.ts
functions/src/database/updates.ts
functions/src/emulator/seed/content-generate.ts
functions/src/emulator/seed/users-create.ts
functions/src/index.ts
src/modules/admin/pages/adminDatabase.tsx
src/pages/Howto/Content/Howto/HowtoDescription/HowtoDescription.tsx
src/pages/Research/Content/ResearchDescription.tsx
src/pages/Research/Content/ResearchListItem.tsx
src/stores/Events/events.store.tsx
src/stores/Howto/howto.store.tsx
src/stores/Maps/generatePins.tsx
src/stores/Research/research.store.test.ts
src/stores/Research/research.store.tsx
src/stores/databaseV2/DocReference.tsx
src/stores/databaseV2/types/index.d.ts
src/test/factories/Howto.ts
src/test/factories/ResearchItem.ts
src/test/factories/User.ts

PR Checklist
PR Type
Implements a _lastEditTimestamp property to the document metadata which is only updated when a 'real' update/edit happens on a document.  The platform was using the modified date but as this is updated when someone comments or votes useful etc. it was leading to incorrect/misleading last edit/update dates being shown when viewing how-to's and research.
Closes #
---
If you need more immediate feedback you can …

feat: introduce content modified timestamp

---

packages/components/src/DownloadFiles/DownloadFiles.tsx
packages/components/src/FieldInput/FieldInput.tsx
packages/components/src/FileInformation/FileInformation.tsx
packages/components/src/ModerationStatus/ModerationStatus.tsx
packages/components/src/ResearchEditorOverview/ResearchEditorOverview.tsx
packages/themes/src/common/button.ts
packages/themes/src/fixing-fashion/styles.ts
packages/themes/src/precious-plastic/styles.ts
packages/themes/src/project-kamp/styles.ts
packages/themes/src/types/index.ts
src/modules/admin/pages/adminApprovals.tsx
src/pages/common/Header/Menu/MenuDesktop.tsx
src/pages/common/Header/Menu/MenuMobile/MenuMobileLink.tsx

PR Checklist
PR Type
When I was looking through the application, I noticed that we use a color variable called yellow, which has 2 statuses: base and hover. Looking at the styles for each project, I came to the conclusion that this name is for the facade (it's not always yellow). I also looked in the documentation to see if this yellow appears as something "standard".
I changed the name from yellow to accents, and I changed it everywhere I found it used. Thus, it will be easy for the developer to understand the role of color.

refactor: rename "yellow" variable to "accent"

---

src/common/Form/ImageInput/ImageInput.tsx

PR Checklist
PR Type
Implements the refactoring in #2285.
However, in converting the styled-components code to theme UI, I am not sure whether there is a better way of reusing styles, aside from defining a the base style object, then spreading it into the `sx` props.
Closes #2285
TODO, but the before/after looks the same to me. I could not get the overlay to activate because dropzone wouldn't work in dev mode.
Before
After
---
If you need more immediate feedback you can try reaching out on Discord …

[refactor] Remove direct usage of Theme from "ImageInput.tsx"

---

src/pages/User/content/SpaceProfile.tsx

PR Checklist
PR Type
Space profile research count was using the user stats research figure.  As this has been removed/deprecated the profile would not load and get stuck into an error loop.  This pr switches the research count to the object returned from the user created docs function.
Closes #
--- …

fix: space profile research count bug

---

src/pages/Settings/UserSettings.test.tsx
src/pages/Settings/content/formSections/UserInfos.section.tsx

PR Checklist
PR Type
Member profiles should allow 1 photo to be uploaded and space profiles should allow multiple.  The behaviour had been reversed on the platform.  This pr resets the functionality back to the requirement.
Closes #
---

fix: number of profile images shown on member / spaces profiles

---

src/pages/User/content/UserCreatedDocumentsItem.tsx

PR Checklist
PR Type
Fixes alignment of useful badge when viewing the how-to and research items from member / space profile.
Closes #
---

fix: member / space profile useful alignment to end of row

---

src/stores/User/notifications.store.test.tsx
src/stores/User/notifications.store.ts

PR Checklist
PR Type
It has been noticed duplicate users are getting reintroduced into the system and the 'wrong' users are in some cases the only ones getting updated. This was first noticed in the notifications records saved for the user records being different. As a result all uses of the user _id are being switched for userName so that if duplicates are created that it's definitely the user record that has an _id that matches the username that receives updates.  This pr:
- Switches use of user._id to user._userName in the notifications store.
- Fixes 'notifications' typos
Closes #
---
Thanks for the contribution! We try to make sure all PRs are reviewed ahead of a monthly dev call (first Monday of the month, open to …

fix: switch notification store to use username instead of userid

---

.circleci/config.yml

PR Checklist
PR Type
Historically whenever we remove a function from a deployed instance of the Platform, this requires manual action to be taken. The `firebase deploy` command requires an interactive input to remove functions, the change here is hoping to automate this 🤞🏻

chore: ci workaround for deploying functions

---

packages/components/src/UsefulStatsButton/UsefulStatsButton.tsx

PR Checklist
PR Type
This pr:
- Refactors the useful button to remove the use of the ExternalLink component if the user is logged out.
- Implements a history.push if the user is logged out that redirects to sign-in.
The reason for this change is so that the sign in doesn't open in another page and therefore after sign-in they land back on the page they started on.
Closes #2536 
---
If you need more immediate feedback you can try …

refactor: useful button to use history.push rather than external link

---

firebase.json

PR Checklist
PR Type
At the moment the serverless functions are
only available via a hard to discover URL this
means they can not be found at a root relative path.
This change exposes them via a temporary URL for testing.
Opinions welcome on whether this should eventually be
exposed via a name spaced URI such as `/api/logging`.

feat: expose logging method via routing

---

.github/workflows/pr-stale.yml

PR Checklist
PR Type
Adopt https://github.com/actions/stale to handle administration on very old PRs. The intent for this change is that this automation runs with debug out only and **does not** generate any comments on PRs. I want to trial it for a month and see how it goes before making public.
Although I would flag that with the current level of maintainer time available it is unlikely we will see any PRs reach the 45 day threshold.

chore: add Github action to triage stale issues

---

functions/src/aggregations/common.aggregations.ts
functions/src/aggregations/userNotifications.aggregations.spec.ts

PR Checklist
PR Type
this fixes a regression caused by https://github.com/ONEARMY/community-platform/pull/2344. We were accidentally dropping user notification aggregation updates, which prevented emails from being sent out.
i tested this fix by deploying the userNotification agg function to dev and confirming data was being populated in the `user_notifications` collection following new notifications. 
suggestions for improvement: this `functions/src/aggregations/common.aggregations.ts` file has become a little bloated with code that is not "common" to all aggregations. i think moving calculations for useful counting to the individual aggregation process functions would keep this a bit neater and easier to debug. i can draft an issue for this after lunch :) 
Closes #2547 
---
Thanks for …

fix(aggregations): fix user notification aggregation

---

package.json
yarn.lock

PR Checklist
PR Type
Removes unused `react-tooltip` dependency which is only used in the components workspace.

chore(deps): drop unused react-tooltip

---

functions/src/emailNotifications/index.ts

PR Checklist
PR Type
@davehakkens noticed emails were not being sent daily. looked into the logs and saw:
which, sadly, isn't caught by our error handling (💔) because it occurs within firebase i presume. might be possible to set up an alert to the webhook from functions logs?
i can't find any super obvious memory drain here.. let me know if you see anything I'm missing. if not, seems reasonable to increase the memory usage. testing on dev, 512 seems to do the trick. 
this won't cost us anything extra - as of now we stay well within the 2mil free function invocations per month (https://cloud.google.com/functions/pricing)
Closes #
---
Thanks for the contribution! We try to make sure all PRs are reviewed ahead of a monthly …

fix: increase memory limit

---

packages/cypress/src/integration/howto/write.spec.ts
src/pages/Howto/Content/Common/Howto.form.test.tsx
src/pages/Howto/Content/Common/HowtoStep.form.tsx

PR Checklist
PR Type
The code was ensuring the step description for a how-to was less than 700 characters long, when in actuality we want to make sure it is less than 1000. The message displayed to the user was correct.
- Integration tests were taking forever to type out 1000 characters, so one test has been updated to simply set the textarea value.
Testing: I could not figure out how to write tests for this. The closest I could get was the below, written in `Howto.form.test.tsx`. I could not get the `getBy___` methods to get anything from any of the steps. I also had trouble debugging. Any help would be much appreciated! Also, is this the right approach to test the validation function? Should we be targeting the `validateDescription` method directly? Or writing a test for …

fix: howto step description length validation

---

packages/components/src/ImageGallery/ImageGallery.tsx

PR Checklist
PR Type
It was noticed that when viewing the photos from a gallery and then clicking the main image to open it full screen it would always open the first image rather than the selected one.
This pr updates the imgIndex when clicking through the thumbnails in the ImageGallery component so that the correct image is opened fullscreen.
Closes #
---
If you need more immediate feedback you can try reaching out on Discord in …

fix: update current imgIndex when clicking through images

---

packages/cypress/src/integration/common.spec.ts

PR Checklist
PR Type
Fixes the flaky test. Clicking the user menu when it is open rapidly closes and then re-opens the menu. In the integration test, there's a sub function that handles clicking on a menu item. If that command is run when the menu is already opens, it attempts to re-open the menu (causing a flicker) then click on a menu item. I believe the flicker causes instability.
- This PR simply clicks on the item, instead of attempting to re-open it, as changing pages does not close the menu.
See stretch goals in the issue description for some additional potential changes
Closes #2657

fix: fixes flaky user menu test

---

src/pages/Howto/Content/Common/Howto.form.test.tsx
src/pages/Howto/Content/Common/Howto.form.tsx
src/pages/Howto/Content/Howto/Howto.test.tsx
src/pages/Research/Content/Common/ResearchUpdate.form.tsx
src/pages/Research/research.routes.test.tsx
src/pages/Settings/UserSettings.test.tsx

PR Checklist
PR Type
- Fixes all the errors related to tests.
- Act errors
- In tests, it appears that any async code or code that causes side-effects in the wrapper factories (i.e. anything inside the render function) will cause an act error, as all these changes must be settled before we're testing what the user experiences. This includes the dom, state, etc.
- My initial suspicion that act could be removed was not correct
- form decorator errors
- memoizing decorator function definitions prevents each render from re defining those functions, and prevents a test error that was complaining that: `form decorators should not change from one render to the next as new values will be ignored`
- duplicate key errors
- in one place in the app we had duplicate keys assigned to 2 child elements …

chore: fixes tests so there are no more errors

---

packages/components/src/__mocks__/AuthWrapper.mock.tsx
src/common/AuthWrapper.tsx
src/pages/common/AuthRoute.tsx

PR Checklist
PR Type
Removes unused `additionalAdmin` prop, described as: _Optional additional user IDs that have admin rights (e.g. content creators_

chore: refactor to remove unused additional admin prop

---

functions/src/userUpdates/index.ts
src/pages/Maps/Maps.tsx
src/stores/Maps/maps.store.ts

PR Checklist
PR Type
This pr:
- Filters out any pins that have the _deleted property set to true from displaying on the map
- Prevents direct browsing to the pin map card by entering the username directly in the url
- Adds a user update process that sets the _deleted property on map pins if a user has their _deleted property set to true
- Manual data cleansing also performed to ensure that all map pins for deleted users and user records that no longer exist have the _deleted flag set to true
Closes #772 
---
If the PR is working as intended it'll be merged and included in the next …

feat: hide deleted pins + delete pins when user deleted

---

src/pages/Research/Content/ResearchListItem.tsx

PR Checklist
PR Type
Filters out draft or deleted items when counting total number of updates.
Tests need to be added to verify this behaviour, waiting for #2620 to be merged as that refactors a lot of tests and components.

fix: filter out draft/deleted research updates on listing view

---

src/stores/User/user.store.test.tsx
src/stores/User/user.store.ts

PR Checklist
PR Type
Fixes an issue where in a specific scenario `getUserProfile` will return `undefined` rather than a user profile. This prevents a user from being able to log in. 
The specific problem scenario is that there are 2 or more user records associated with the same `authID`. The `authID` property is a unique identifier which represents a [Firebase Auth user identity](https://firebase.google.com/docs/auth/). The existence of 2 user records points to a bug elsewhere which needs to resolving but this is a hotfix to unblock users.

fix: handle situation where multiple User records exist

---

functions/src/emulator/seed/content-generate.ts
packages/cypress/src/integration/howto/write.spec.ts
src/models/howto.models.tsx
src/pages/Howto/Content/Common/Howto.form.tsx
src/pages/Howto/Content/Common/HowtoStep.form.tsx
src/pages/Howto/Content/Howto/Howto.tsx
src/pages/Howto/Content/Howto/HowtoDescription/HowtoDescription.tsx
src/pages/Howto/Content/Howto/Step/Step.tsx
src/pages/Howto/Content/HowtoList/HowToCard.tsx
src/pages/Research/Content/Common/Research.form.tsx
src/stores/Howto/howto.store.test.ts
src/stores/Howto/howto.store.tsx
src/stores/common/mentions/index.ts
src/test/factories/Howto.ts
src/utils/validators.test.ts
src/utils/validators.ts

PR Checklist
PR Type
This allows users to save a draft how-to with (at a minimum) a title provided. The smallest UI change has been done to enable this. But a lot of store changes were required for this to happen smoothly.
Closes #2540

feat: allow draft how-to save without form validation

---

src/models/user.models.tsx
src/pages/Settings/SettingsPage.tsx
src/stores/User/notifications.store.test.tsx
src/stores/User/notifications.store.ts
src/stores/User/user.store.test.tsx
src/stores/User/user.store.ts
src/stores/common/__mocks__/module.store.ts

PR Checklist
PR Type
This pr:
- Aims to reduce the number of operations that set the full document when updating the user profile.  The reason for this is to remove the number of possible causes of 'duplicate' user docs being created.
- It also introduces two additional properties to the user profile to track when and why a user profile doc was created.  These will be used to help determine the cause of the duplicate records being created and then be removed again at a later date.
- Prevents user docs being returned by the getUserProfile function if the authId and Id are the same
I would suggest reviewing each commit separately as should make more sense that way.
Closes #
---
Thanks for the contribution! We try to make …

refactor: improve updates around user profile

---

src/pages/Research/Content/ResearchArticle.test.tsx
src/pages/Research/Content/ResearchArticle.tsx
src/pages/Research/research.routes.test.tsx
src/stores/Research/research.store.tsx

PR Checklist
PR Type
The problem is that the comments were being looked up via a pointer
reference on an array of Research Updates. This look up would be inaccurate
when there are updates in the array which are not visible
due to their `status=draft`. The result is
that items would be loaded off of the wrong ResearchUpdate.
As the comment list is available on the Research Update document
there is no need to look it up. Instead it can be passed through
and formatted.

fix: research comments not showing

---

src/pages/Howto/Content/Common/Howto.form.tsx

PR Checklist
PR Type
By reseting the form values to the values submitted, this fixes the howto form from incorrectly warning the user about unsaved changes.
Closes #2317

fix: howto unsaved changes warning after submit

---

src/pages/common/SortFilterHeader/SortFilterHeader.tsx

PR Checklist
PR Type
Fix `/how-to` search component label. Previously it was `Search for a How,to`, this was caused by additional`.split('-')` at the end of a function to turn the first letter of strings into uppercase, which lead to an array that was never joined by a proper separator again. I fixed this by removing the `.split` and using the helper function `capitalizeFirstLetter` to achieve the desired resut.
I also added types to the props of `SortFilterHeader` component and organized the imports of the same file.
Closes #2664
---
If the PR is working as intended it'll be merged and included in the next platform release, if not changes will be …

fix: /how-to search component label

---

src/pages/Howto/Content/Common/Howto.form.tsx
src/pages/Howto/Content/Common/HowtoStep.form.tsx
src/pages/Research/Content/Common/Research.form.tsx

PR Checklist
PR Type
Removes word repetitions on forms `HowTo`, `HowToStep` and `Research`. Also slightly improves labels semantic.
Closes #2666 
> I don't have screenshots as of now but will provide asap.
---

fix: remove word repetitions on forms HowTo, HowToStep and Research

---

src/common/Form/ImageInput/ImageInput.tsx
src/pages/Howto/Content/Common/HowtoStep.form.tsx

PR Checklist
PR Type
It passes down the uploaded image props to the edit steps form so that they now appear to users after they leave the page.
Closes #2701

fix: Show uploaded images on how to edit screen

---

packages/cypress/src/integration/howto/write.spec.ts
packages/cypress/src/integration/research/read.spec.ts
shared/mocks/data/howtos.ts
shared/mocks/data/research.ts
src/pages/Research/Content/Common/ResearchUpdate.form.test.tsx
src/stores/common/module.store.ts
src/utils/validators.ts

PR Checklist
PR Type
Adds a check on previousSlugs on title validation.
Closes #2315 
---

Fix #2315 - Possible to reuse previous slugs causing old links to break

---

src/pages/Research/Content/ResearchComments/ResearchComments.tsx

PR Checklist
PR Type
Replacing the research comments box margin with paddings, so there is no white margin around the section.
Closes #2681 
---

fix: replace margins with paddings in research comments box section

---

src/models/research.models.tsx
src/stores/Research/research.store.tsx
src/stores/common/FilterSorterDecorator/FilterSorterDecorator.ts
src/stores/common/FilterSorterDecorator/FitlerSorterDecorator.test.ts

PR Checklist
PR Type
Pins any research created by a user to the top of the research list if they have a moderation status of:
- rejected
- awaiting-moderation
- draft
Closes #2550 
---

feat: filter research list by moderation status

---

src/pages/Howto/Content/Common/HowtoFieldStep.tsx
src/pages/Howto/labels.ts

PR Type
_Simple fix to embed labels in how-to, to make things more clear_
closes #2557 
https://user-images.githubusercontent.com/37253846/264488684-dd99ffb2-01de-4abc-b2c3-a9ab06ebefae.png
---

fix: change embed images/video labels to one line

---

src/stores/common/FilterSorterDecorator/FilterSorterDecorator.ts
src/stores/common/FilterSorterDecorator/FitlerSorterDecorator.test.ts

PR Checklist
PR Type
Prevents the shifting of items in the research/howto lists if they have values equal to that of another item. Previously if equal item b would always go before item a, causing the lists to constanly change. 
Issue was observed in #2752
Closes #
--- …

fix: keep items in research/howto list in place if equal to another

---

packages/components/src/FieldInput/FieldInput.tsx
packages/components/src/FieldTextarea/FieldTextarea.tsx
packages/cypress/src/integration/howto/write.spec.ts
src/pages/Howto/Content/Common/HowtoFieldDescription.tsx
src/pages/Howto/Content/Common/HowtoFieldStep.tsx
src/pages/Howto/Content/Common/HowtoFieldTitle.tsx

PR Checklist
PR Type
Trim trailing whitespace from text fields in How-Tos
Closes #2635 
---

feat: trim trailing whitespace in HowTo text fields

---

packages/cypress/src/integration/howto/write.spec.ts
packages/cypress/src/support/CustomAssertations.ts

PR Checklist
PR Type
In the tests that create and edit howtos, adds a step to select the category in addition to the other fields and then asserts on the final category.
Closes #2743 
Run locally, tests are succeeding:
But if `selectCategory` is commented out, they fail:
The error in the first test is a little odd, as category is not set (just mentioning in case a different sort of assertion would be better):
---
If you need more immediate feedback you can try reaching out on Discord in the …

test: adds e2e testing of howto category

---

functions/src/alerting/errorAlerting.ts
functions/src/index.ts

PR Checklist
PR Type
working on the new email stuff, i realized that functions are not running in the local emulator environment. they fail to compile with this error:
```
[emulators] ⬢  functions: Failed to load function definition from source: FirebaseError: Failed to load function definition from source: Failed to generate manifest from function source: Error: Cannot find module '@google-cloud/logging'
[emulators] Require stack:
[emulators] - /app/functions/dist/index.js
[emulators] - /app/functions/dist/node_modules/firebase-functions/lib/runtime/loader.js
[emulators] - /app/functions/dist/node_modules/firebase-functions/lib/bin/firebase-functions.js
[emulators] 
```
there seems to be an issue with the google cloud logging locally that we don't encounter in prod. by disabling local …

fix: fix errors running functions locally

---

functions/src/aggregations/research.aggregations.ts
packages/components/src/BlockedRoute/BlockedRoute.stories.tsx
packages/components/src/BlockedRoute/BlockedRoute.tsx
packages/components/src/index.ts
packages/cypress/src/integration/howto/write.spec.ts
packages/cypress/src/integration/profile.spec.ts
packages/cypress/src/integration/research/write.spec.ts
src/models/research.models.tsx
src/pages/Research/Content/Common/Research.form.tsx
src/pages/Research/Content/Common/ResearchUpdate.form.tsx
src/pages/Research/Content/EditResearch/index.tsx
src/pages/Research/Content/EditUpdate/index.tsx
src/pages/Research/research.routes.test.tsx
src/pages/common/AuthRoute.tsx
src/stores/Research/research.store.tsx

PR Checklist
PR Type
Introduces the concept of `locking` for Research editors. It is now possible for multiple users to be able to access a Research article or Research Update. This is great but introduces the potential for multiple users to overwrite each others changes. 
This PR attempts to minimise this risk by introducing the concept of locking a document. A document is marked as locked when the edit form is locked. The document is then marked as unlocked when the edit form is unloaded.
Closes #2144
Locked screen when attempting to access Research if another user is working on it. 
**How to validate**
1. You will need two users (A + B) with edit access to the same Research Article. 
2. User A opens the Research article in edit mode
3. User B attempts to edit the Research article
4. …

feat: lock research to multiple editor access

---

functions/src/emailNotifications/__snapshots__/createModerationEmails.spec.ts.snap
functions/src/emailNotifications/__snapshots__/createSubmissionEmails.spec.ts.snap
functions/src/emailNotifications/constants.ts
functions/src/emailNotifications/createModerationEmails.spec.ts
functions/src/emailNotifications/createModerationEmails.ts
functions/src/emailNotifications/createSubmissionEmails.spec.ts
functions/src/emailNotifications/createSubmissionEmails.ts
functions/src/emailNotifications/development/entry-server.mjs
functions/src/emailNotifications/index.ts
functions/src/emailNotifications/templates.ts
functions/src/emailNotifications/templates/how-to-rejected.html
functions/src/emailNotifications/templates/index.ts
functions/src/emailNotifications/templates/map-pin-rejected.html

PR Checklist
PR Type
when creating submission emails, i did not consider the case where a user re-submits a previously rejected (or needs improvements, or draft) how to or map pin. these should also trigger submission emails.
i also snuck in two other changes:
1. move the handler functions out of the index file and into the domain-specific files to consolidate to the logic, as done in #2688 
2. update the PP signoff, as requested in feedback
Closes #
---
If the PR is working as intended it'll be merged and included in the next platform release, if not changes will be requested and …

fix(emails): send submission emails on re-submitted resources

---

src/stores/Maps/maps.store.test.ts
src/stores/Maps/maps.store.ts

PR Checklist
PR Type
in #2521 we decided to maintain moderation status for accepted map pins. however, we should still require moderation for all non-accepted map pins that get updated (not just rejected) as well as map pins that are updated to be a different type. 
Closes #2817
---

fix: reset map pin moderation on update for non-members

---

src/pages/Howto/Category/CategoriesSelect.tsx
src/pages/common/SortFilterHeader/SortFilterHeader.tsx

Updated sort options to show random only on select
PR Checklist
PR Type
- Updated filter and sort inputs to hide currently selected
- Updated sort options to show random only on select
Closes #
https://github.com/ONEARMY/community-platform/issues/2804
--- …

Updated filter and sort inputs

---

codecov.yml

PR Checklist
PR Type
Disable patch status checks which often result in failure. There is probably a better way to configure this but will defer to future me or someone else to dig into it further.
https://docs.codecov.com/docs/commit-status#disabling-a-status

chore: disable codecov/patch status

---

package.json
src/pages/Howto/Content/HowtoList/HowToCard.tsx
src/pages/Research/Content/ResearchListItem.tsx
yarn.lock

PR Checklist
PR Type
Switch to native lazy loading attribute. Removing react-lazy-load-image-component in favor of loading="lazy" makes sense for simplicity, readability, performance, and maintenance reasons. It has widespread support in modern browsers.

fix(deps): switch to using native lazy loading image

---

functions/package.json
yarn.lock

PR Checklist
PR Type
Attempts to upgrade `firebase-tools` to address:
```
Error: HTTP Error: 403, Firebase Extensions Terms of Service Private API has not been used in project 174193431763 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/firebaseextensionstos-pa.googleapis.com/overview?project=174193431763 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.
```
https://app.circleci.com/pipelines/github/ONEARMY/community-platform/6557/workflows/8c08ccbe-008f-435a-9280-1f8b90bea8b3/jobs/52465
I believe it is fixed in: https://github.com/firebase/firebase-tools/releases/tag/v12.4.5
> Added better messages for API permissions failures that direct the user to the URL to enable the …

fix(functions): upgrade firebase-tools@12.4.5

---

src/pages/Research/Content/ResearchList.tsx
src/stores/Research/research.store.tsx

PR Checklist
PR Type
I added loader in research page for initial fetching. 
My solution also can be ported to other stores which have `this.allDocs$.subscribe((docs: IResearch.ItemDB[])` method for fetching data.
Closes #2808

feat(platform): add loader to research page

---

src/stores/User/user.store.test.tsx
src/stores/User/user.store.ts

PR Checklist
PR Type
When changing user type, for example from Workspace to Member, the `workspaceType` field stayed and affected the map filtering system.
added validation for user type and removing the `workspaceType` field if it's not needed.
Closes #2798
---

fix(maps): delete workspaceType if not a workspace

---

functions/src/emailNotifications/development/entry-server.mjs
functions/src/emailNotifications/templates.ts
functions/src/emailNotifications/templates/map-pin-approval.html
functions/src/emailNotifications/templates/map-pin-needs-improvements.html

PR Checklist
PR Type
feedback from @sigolenej that the bullet was not needed in the map pin feedback email, as at the moment the feedback is just submitted as one blob of text. convo [here](https://discord.com/channels/586676777334865928/1156363133905010799/1162239327795945492).
also noticed inconsistencies in the casing of "mappin" and "mapPin". we use both in the codebase, but "mapPin" is more correct IMO and we are using that pattern elsewhere in these functions.
Closes #
---
If you need more …

fix: remove bullet from map pin needs improvement email

---

functions/package.json
packages/security-rules/package.json
yarn.lock

* Fix type mismatch for parametrized function region. (#6205)
* Ignore FIRESTORE_EMULATOR_HOST environment variable on functions deploy. (#6442)
* Added support for enabling, disabling, and displaying Point In Time Recovery enablement state on Firestore databases (#6388)
* Added a --verbosity flag to emulators:* commands that limits what logs are printed (#2859)
* Fixed an issue where params would not be resolved when used to set VPC connector during functions deployment (#6327)
https://github.com/firebase/firebase-tools/releases/tag/v12.7.0
PR Checklist
PR Type
Closes #
---
Thanks for the contribution! We try to make sure all PRs are reviewed ahead of our monthly maintainers call (first Monday of the …

fix(deps): upgrade firebase-tools to 12.7.0

---

src/models/common.models.tsx
src/models/howto.models.tsx
src/pages/Howto/Content/Howto/Howto.test.tsx
src/pages/Howto/Content/Howto/Howto.tsx
src/pages/Howto/Content/Howto/HowtoDescription/HowtoDescription.tsx
src/stores/Howto/howto.store.tsx

PR Checklist
PR Type
- chore: remove accept/deny buttons from how-to description
- fix: load how-to moderation comments from new property
- fix: remove unused moderation methods
Address https://github.com/ONEARMY/community-platform/issues/2876
Also restyles feedback to appear within standard Alert component using the info variant:
Before:
After:

fix: remove moderation from how to

---

src/pages/Howto/Content/Howto/Howto.test.tsx
src/pages/Question/question.routes.test.tsx
src/pages/Research/Content/ResearchArticle.test.tsx
src/pages/Research/Content/ResearchUpdate.test.tsx
src/pages/Research/research.routes.test.tsx

PR Checklist
PR Type
When attempting to move the test suites across to vitest I encountered some odd errors due to a mixture of ThemeProviders being used. Consistently using `@emotion/react` resolved this issue.

chore: use consistent ThemeProvider

---

src/config/config.ts
src/config/constants.ts
src/pages/Howto/Content/HowtoList/HowToCard.tsx
src/utils/cdnImageUrl.test.ts
src/utils/cdnImageUrl.ts

PR Checklist
PR Type
Introduced support for a new environment variable `REACT_APP_CDN_URL`.
This can be used via the `cdnImageUrl` function. It is meant to take a URL pointing to an image in a Firebase Storage bucket and replace the Firebase Storage URL prefix with a CDN URL prefix. If either the CDN URL or the storage bucket name is not available, it simply returns the original URL.
This then supports integration with 3rd party tools such as KeyCDN and Imgix which provide image processing functionality. Previously we had looked at working with a Firebase Extension for this but it threw some odd errors under test so abandoned that implementation.

feat: add helper for loading images from CDN

---

src/stores/Howto/howto.store.test.ts
src/stores/Howto/howto.store.tsx

PR Checklist
PR Type
Fix for broken logic in the shared method `updateHowtoItem`, which assumed that previousSlugs would always be present as a well formed array.

fix: howto updates if document is missing `previousSlugs` property

---

src/pages/UserSettings/content/formSections/Fields/CustomRadio.field.tsx
src/pages/UserSettings/content/formSections/Focus.section.tsx

PR Checklist
PR Type
Changes the minimum width of the repeated grid item so it will initially auto-fill all 5 items in one row. When downsizing the screen width it will act responsively.
Also I noticed that the text-align of the grid items below the images were not always centred. I therefore also removed the 'left' value from the text-align array.
Closes #2993
Before:
https://github.com/ONEARMY/community-platform/assets/131855633/08c4bff8-ec6c-4305-9738-b9058a824f66
After:
https://github.com/ONEARMY/community-platform/assets/131855633/c94a71db-3f9b-4e0e-afb1-5a93089b2fdb
If the PR is working as intended it'll be merged and included in the next platform …

fix: focus alignment

---

src/pages/common/Header/Menu/MenuMobile/MenuMobilePanel.tsx
src/pages/common/Header/Menu/Notifications/NotificationsDesktop.tsx
src/pages/common/Header/Menu/Profile/Profile.tsx
src/pages/common/Header/Menu/Profile/ProfileButtonItem.tsx
src/pages/common/Header/Menu/Profile/ProfileButtons.tsx
src/pages/common/Header/Menu/Profile/profile.css
src/stores/User/user.store.ts

PR Checklist
PR Type
Prevents menu items jumping around as the User state is loaded. Instead starts with blank placeholder element, which then presents LogIn/Join buttons when logged in or our state is determined.
Before:
https://github.com/ONEARMY/community-platform/assets/472589/c96e05e5-95d0-4de9-8201-3cf1469eb5e3
After: 
https://github.com/ONEARMY/community-platform/assets/472589/2b9ed243-26d5-4792-aa94-75ff1c36d65e

fix: prevent header layout shift on login

---

packages/cypress/src/integration/profile.spec.ts
shared/mocks/data/users.ts
src/models/user.models.tsx
src/pages/User/content/SpaceProfile.tsx
src/pages/User/impact/Impact.test.tsx
src/pages/User/impact/Impact.tsx
src/pages/User/impact/ImpactEmoji.tsx
src/pages/User/impact/ImpactField.tsx
src/pages/User/impact/ImpactItem.tsx
src/pages/User/impact/ImpactMissing.tsx
src/pages/User/impact/constants.ts
src/pages/User/impact/labels.ts
src/utils/helpers.test.ts
src/utils/helpers.ts

PR Checklist
PR Type
This adds the large majority of the display for the impact data on workshop profiles.  
Missing: 
* As the tab layout changes haven't been implemented, the backgrounds are inverted in this.
* As no settings exist yet, the display of the tab is hidden unless impact data has been manually added to the database.
* As no settings exist yet, link to add impact data isn't present.
* TEMPORARILY: The links to the 2022 and 2021 impact reports - can I have these please.
A large part of #3001.

feat: add display of impact data

---

packages/cypress/src/integration/settings.spec.ts
shared/mocks/data/users.ts
src/models/user.models.tsx
src/pages/User/contact/UserContactError.tsx
src/pages/User/impact/Impact.test.tsx
src/pages/User/impact/Impact.tsx
src/pages/User/impact/ImpactEmoji.tsx
src/pages/User/impact/ImpactField.tsx
src/pages/User/impact/ImpactItem.tsx
src/pages/User/impact/ImpactMissing.tsx
src/pages/User/impact/labels.ts
src/pages/UserSettings/SettingsPage.tsx
src/pages/UserSettings/content/formSections/Impact/Impact.section.tsx
src/pages/UserSettings/content/formSections/Impact/ImpactQuestion.field.tsx
src/pages/UserSettings/content/formSections/Impact/ImpactYear.field.tsx
src/pages/UserSettings/content/formSections/Impact/ImpactYear.section.tsx
src/pages/UserSettings/content/formSections/Impact/ImpactYearDisplay.field.tsx
src/pages/UserSettings/content/formSections/Impact/impactQuestions.ts
src/pages/UserSettings/content/formSections/Impact/utils.test.ts
src/pages/UserSettings/content/formSections/Impact/utils.ts
src/pages/UserSettings/content/formSections/SettingsErrors.tsx
src/pages/UserSettings/labels.ts
src/stores/User/user.store.ts

PR Checklist
PR Type
This adds a form to the workspace user settings page enabling users to create and update their impact data.
Closes #3018 
https://github.com/ONEARMY/community-platform/assets/16688508/59bbfac3-c7c3-4e6a-bf13-a4124c3869e2

feat: add user setting to update impact

---

packages/cypress/src/integration/settings.spec.ts
shared/mocks/data/users.ts
src/models/user.models.tsx
src/pages/User/impact/Impact.test.tsx
src/pages/User/impact/ImpactEmoji.tsx
src/pages/User/impact/ImpactField.test.tsx
src/pages/User/impact/ImpactField.tsx
src/pages/User/impact/ImpactItem.tsx
src/pages/UserSettings/content/formSections/Impact/ImpactQuestion.field.tsx
src/pages/UserSettings/content/formSections/Impact/ImpactYear.field.tsx
src/pages/UserSettings/content/formSections/Impact/ImpactYear.section.tsx
src/pages/UserSettings/content/formSections/Impact/ImpactYearDisplay.field.tsx
src/pages/UserSettings/content/formSections/Impact/impactQuestions.ts
src/pages/UserSettings/content/formSections/Impact/utils.test.ts
src/pages/UserSettings/content/formSections/Impact/utils.ts

PR Checklist
PR Type
Previously, fields for impact data was being stored that was about presentation only and thus wrongly tied presentation to stored data (like a label) that might easily need changing.

feat: change to save only minimal impact fields

---

src/models/user.models.tsx
src/pages/User/impact/Impact.test.tsx
src/pages/User/impact/Impact.tsx
src/pages/User/impact/ImpactItem.tsx
src/pages/User/impact/ImpactMissing.tsx
src/pages/User/impact/constants.ts
src/pages/User/impact/labels.ts

PR Checklist
PR Type
This ensures that if:
1. A user adds impact data but chooses to hide all the fields, an appropriate message displays.
2. A user adds impact data and then deletes it, the missing data message displays.

Update messages on impact data display

---

src/pages/UserSettings/content/formSections/Focus.section.test.tsx
src/pages/UserSettings/content/formSections/Focus.section.tsx

PR Checklist
PR Type
Feature: Improve display of member focus #3056
FocusSection component is hidden if user has less than two activities
Closes #3056
---

feat: hide member focus section if less than two activities

---

src/pages/Question/index.tsx
src/pages/Research/index.tsx
src/stores/common/module.store.ts

PR Checklist
PR Type
As part of adopting https://www.npmjs.com/package/eslint-plugin-react-hooks in https://github.com/ONEARMY/community-platform/pull/3105, I am merging a subset of fixes declared here:
https://app.circleci.com/pipelines/github/ONEARMY/community-platform/7387/workflows/c97aaa26-c1bd-4640-92ff-419d76beee96/jobs/62234
> The react-hooks/exhaustive-deps rule in the ESLint plugin is beneficial as it ensures that all dependencies of React hooks like useEffect, useMemo, and useCallback are correctly specified. This rule helps prevent bugs related to missing dependencies, which can cause unexpected behavior in React components. By enforcing a comprehensive check on the dependencies array, it aids in maintaining the functional integrity and performance of React components, …

chore: refactor remove use of hooks in ModuleStore class

---

packages/components/src/CommentItem/CommentItem.tsx

PR Checklist
PR Type
This is a very small but valuable change to move around the comment header area (and a little tidying). Moves the edit/delete actions to the top right and the date/edit info to the top left next to the username. A part of the updated comments design.

feat: restructure comment header

---

scripts/installClean.ts
scripts/package.json
yarn.lock

PR Checklist
PR Type
Updates usage of rimraf to match [changes introduced in v4 release](https://github.com/isaacs/rimraf?tab=readme-ov-file#v3-to-v4)
```bash
node/src/index.ts:859
return new TSError(diagnosticText, diagnosticCodes, diagnostics);
^
TSError: ⨯ Unable to compile TypeScript:
installClean.ts:39:47 - error TS2554: Expected 1-2 arguments, but got 3.
rimraf(folderPath, { disableGlob: true }, (err) => {
if (err) {
...
}
})
```
Originally introduced: https://github.com/ONEARMY/community-platform/pull/3036

fix(scripts): update usage of rimraf in install scripts

---

packages/cypress/src/integration/profile.spec.ts
src/pages/User/impact/Impact.test.tsx
src/pages/User/impact/ImpactMissing.tsx

PR Checklist
PR Type
Previously, users were seeing the 'edit your impact' information on other users profile pages when they should have just got the 'see all the impact data' information.

fix: logic for showing page owner impact info

---

src/pages/User/content/SpaceProfile.tsx
src/pages/User/user.routes.test.tsx

PR Checklist
PR Type
Introduce tests for rendering User profile pages, introducing edge case where User has no Cover Images uploaded. Adds graceful fallback for this scenario.
Note the screengrabs below are for two different users, this is due to the bug being visible in prod (before) then fixed locally in (after).
Before:
After:

fix: handle empty images

---

packages/documentation/docs/Install.md
src/utils/cdnImageUrl.test.ts
src/utils/cdnImageUrl.ts

PR Checklist
PR Type
This PR fixes an issue where the application would fail to load if the REACT_APP_CDN_URL environment variable was misconfigured. The fix will handle trailing slashes being provided as part of the configured value.

fix: handle misconfigured `REACT_APP_CDN_URL` param

---

.circleci/config.yml

PR Checklist
PR Type
This step introduces a ~40sec blocker to running the code linting step.
We should not need to prime our caches in this way.

chore(ci): remove cache warmup step

---

src/pages/UserSettings/SettingsPage.tsx
src/pages/UserSettings/content/formSections/PatreonIntegration.test.tsx
src/pages/UserSettings/content/formSections/PatreonIntegration.tsx

PR Checklist
PR Type
it seems like we should have a message for people who a) connect with patreon but b) are not an active supporter
added some thorough tests for this component
removed beta wrapper - ready to release! 
Closes #
@davehakkens let me know if you like the looks of this?
--- …

feat(patreon): add message for patreon users who do not support the project

---

src/pages/Research/Content/ResearchListItem.tsx
src/stores/common/FilterSorterDecorator/FilterSorterDecorator.test.ts
src/stores/common/FilterSorterDecorator/FilterSorterDecorator.ts
src/stores/common/FilterSorterDecorator/FitlerSorterDecorator.test.ts
src/utils/helpers.test.ts
src/utils/helpers.ts

- feat: add Latest Comments, and Least Comments to FilterSorterDecorator
- feat: add sorting by latest comment and by least amount of comments
PR Checklist
PR Type
Update to work done in #3168 to address merge conflicts.

feat add two new filter options

---

src/pages/User/impact/ImpactItem.tsx
src/pages/User/impact/ImpactMissing.test.tsx
src/pages/User/impact/ImpactMissing.tsx
src/pages/User/impact/constants.ts
src/pages/User/impact/labels.ts

PR Checklist
PR Type
PP don't have reports for each impact year, so this adds a simpler display for those years.

feat: add missing impact display when no report

---

package.json
packages/cypress/package.json
packages/security-rules/package.json
yarn.lock

PR Checklist
PR Type
Upgrades firebase to v10, the only breaking changes do not seem related to our use cases.
https://firebase.google.com/support/release-notes/js#version_1000_-_july_6_2023
> Authentication
> * Removed explicit firebase/auth/react-native entry point. The React Native bundle should be automatically picked up by React Native build tools which recognize the react-native fields in package.json (at the top level and in exports). See [Github PR #7138](https://github.com/firebase/firebase-js-sdk/pull/7138).
> * Changed getAuth() in the React Native bundle to default to importing AsyncStorage from @react-native-async-storage/async-storage instead of from the react-native core package (which has recently removed it). See [Github PR …

chore(deps): upgrade to firebase@10

---

src/pages/UserSettings/SettingsPage.tsx
src/stores/User/user.store.test.tsx
src/stores/User/user.store.ts

PR Checklist
PR Type
There have been issues around the impact data not appearing to persist after a user saves it. The biggest reason for this is when a user updates the impact data and then saves their profile, the impact data was being overwritten by the old impact data state being stored.

fix: user settings so that impact isn't overwritten

---

functions/src/emailNotifications/utils.test.ts
functions/src/emailNotifications/utils.ts

PR Checklist
PR Type
`isUserAllowedToMessage` was wrongly using the firebase doc uid (which turns out to be the `_authID`) to search for users.
IF ALL OK WITH WHOEVER REVIEWS, PLEASE MERGE AND RELEASE STRAIGHT AWAY.

fix: allowed message check with right id type

---

packages/components/src/TabbedContent/TabbedContent.tsx

PR Checklist
PR Type
* Removes margin from left side of first tab item
* Reduces borderRadius to match enclosing Box
**Before:** 
**After:**

fix(components): remove margin from first tab

---

functions/src/emailNotifications/__snapshots__/createNotificationEmails.spec.ts.snap
functions/src/emailNotifications/createNotificationEmails.spec.ts
functions/src/emailNotifications/utils.ts
functions/src/emulator/seed/content-generate.ts
packages/components/src/NotificationItem/NotificationItem.stories.tsx
packages/components/src/NotificationList/NotificationList.stories.tsx
packages/cypress/src/integration/notifications.spec.ts
shared/models/notifications.ts
src/pages/Howto/Content/Howto/HowToComments/HowToComments.tsx
src/pages/common/Header/getFormattedNotifications.tsx
src/stores/Howto/howto.store.test.ts
src/stores/Howto/howto.store.tsx
src/stores/Research/research.store.test.ts
src/stores/Research/research.store.tsx

PR Checklist
PR Type
In preparation for #3259 which will require a new comment notification to be added, this adds a new generic comment notification type and moves research/how tos over to it.
(The top one is a how-to, the second and third is research)

feat(notifications): add generic comment notification

---

.circleci/config.yml

As we're now defining the database indexes programmatically, we need the already deployed indexes to not complain with every fresh deployment.

chore: add force command for indexes deploy

---

functions/src/emailNotifications/development/entry-server.mjs
package.json
src/stores/User/user.store.test.tsx
src/test/factories/Comment.ts
src/test/factories/Discussion.ts
src/test/factories/Howto.ts
src/test/factories/MapPin.ts
src/test/factories/Notification.ts
src/test/factories/Question.ts
src/test/factories/ResearchItem.ts
src/test/factories/User.ts
yarn.lock

PR Checklist
PR Type
Update Faker JS from 7.6.0 to 8.4.1, 7.6.0 was clouding up the unit test logs with warnings about methods being depreciated.
This PR updates FakerJS to the latest version, and changes all the deprecated methods to use the new ones. Removing the slew of warnings when running tests.
Here's a comparison between yarn test:unit outputs
[after_faker_upgrade_yarn_unit.txt](https://github.com/ONEARMY/community-platform/files/14808966/after_faker_upgrade_yarn_unit.txt)
[before_faker_upgrade_yarn_unit.txt](https://github.com/ONEARMY/community-platform/files/14808967/before_faker_upgrade_yarn_unit.txt)

chore: update faker-js

---

functions/src/aggregations/common.aggregations.ts
functions/src/aggregations/userNotifications.aggregations.spec.ts
functions/src/aggregations/userNotifications.aggregations.ts

This reverts commit 9f7362782fc76df13885d2051bf86151c0146100.
PR Checklist
PR Type
Over March 10-11th there was a sharp rise (100% on Precious Plastic and 200% on Project Kamp) of daily firestore reads and writes. While there are a few possible changes from this period, this one is easy to revert and impacts both platforms so worth experimenting with.

fix: revert "refactor user notification tests"

---

packages/components/src/DiscussionContainer/transformToStructuredComments.ts
src/stores/Research/research.store.tsx
tsconfig.json

PR Checklist
PR Type
In certain circumstances, Discussion comments may already exist on a Research data object if it has been loaded from the a local data cache. This will result in duplicate comments appearing. This is a side affect of our hard to reason with state management. We should to refactor to perform a clean fetch. 
---
If you need more immediate feedback you can try reaching out on Discord in the [Community Platform `development` channel](https://discord.com/channels/586676777334865928/9387817 …

fix: remove duplicate comments

---

packages/components/src/ImageGallery/ImageGallery.stories.tsx
packages/components/src/ImageGallery/ImageGallery.test.tsx
packages/components/src/ImageGallery/ImageGallery.tsx

- **chore(ci): persist deps to cache**
- **fix: hide thumbnails for single image**
PR Checklist
PR Type
Hide thumbnail navigation on ImageGallery if there is only one image present. See link for lots of thumbnails providing no value: https://community.projectkamp.com/research/can-we-setup-a-screw-system-for-a-community
Before:
After:

fix: hide thumbnail for single image

---

src/pages/Howto/Content/Howto/HowtoDescription/HowtoDescription.tsx

PR Checklist
PR Type
- some images shown in the **HowTo** section were not the full height of the div, leaving a white space ('bar') at the bottom of the div
- it looks like the problem was that the `AspectImage` component auto-generates 3 divs and an img tag; one of the divs had a style of `position: relative` which was causing the image to not fill the enclosing outer div.
- the solution was to use an `Image` component instead of `AspectImage`, and to build the 3 divs manually in the code with required styling to recreate an `AspectImage` but without the trouble-causing style.
Closes #3407 
- image not fully filling the div
**before**
**after**
**image**
- image that is 'very portrait'
**before**
**after**
**image**
- image that is 'very landscape'
**before**
**after**
**image**
- image …

fix: replace AspectImage with Image and Boxes

---

functions/src/aggregations/common.aggregations.ts
functions/src/aggregations/userNotifications.aggregations.spec.ts
functions/src/aggregations/userNotifications.aggregations.ts

This reverts commit 851e368d0f0db538236c16de84401dbcad1bf6ba which was itself a revert of 9f7362782fc76df13885d2051bf86151c0146100.
Now confident it wasn't having any impact on DB calls.

Fix: un-revert "refactor user notification tests"

---

packages/components/src/CommentItem/CommentItem.tsx
packages/components/src/EditComment/EditComment.tsx
packages/cypress/src/integration/questions/read.spec.ts
src/pages/Question/QuestionDiscussion.tsx

PR Checklist
PR Type
While discussion items for questions could be updated or deleted, the display of the page didn't update automatically. This fixes that.
Closes #3385
https://github.com/ONEARMY/community-platform/assets/16688508/f1dbe160-a0dc-4092-a911-6729787b7f31

fix: questions discussion actions updating display

---

functions/src/userUpdates/index.ts

PR Checklist
PR Type
This removes the old function that updates research comments when a user changes their location details. No longer needed as research uses discussions now.

chore: drop old research comments update

---

functions/src/models.ts
functions/src/userUpdates/hasKeyDetailsChanged.test.ts
functions/src/userUpdates/hasKeyDetailsChanged.ts
functions/src/userUpdates/index.test.ts
functions/src/userUpdates/index.ts
functions/src/userUpdates/updateDiscussionComments.test.ts
functions/src/userUpdates/updateDiscussionComments.ts
shared/mocks/data/discussions.ts
src/models/discussion.models.tsx
src/stores/Discussions/discussion.store.test.ts
src/stores/Discussions/discussions.store.tsx
src/test/factories/Discussion.ts

PR Checklist
PR Type
Right now, if a user changes various details, that change won't be reflected on already created discussion comments.
https://github.com/ONEARMY/community-platform/assets/16688508/6842f130-5279-4925-88ae-743c219f3cd8
https://github.com/ONEARMY/community-platform/assets/16688508/dc6922b5-2d48-469e-bdba-ef4f00d3331e

Feat: Function to update discussions when user details change

---

packages/cypress/src/integration/questions/write.spec.ts
src/stores/databaseV2/DatabaseV2.ts

PR Checklist
PR Type
Fix regression introduced in #3281 where the cache db was accidentally disabled, meaning that all data needs to be consistently loaded from server and significant increase into firestore read ops.
Closes #
**Before**
When viewed on the dev or production sites, there is no cache db listed in the devtools application tab
**After**
Cache db should now populate correctly, reducing the number of subsequent requests made to firebase
---
If you need more immediate feedback you can try …

fix: restore cache db

---

src/pages/Maps/Maps.tsx
src/stores/Maps/maps.store.ts
src/stores/databaseV2/types/index.d.ts

PR Checklist
PR Type
Removes streaming from map pins. Should reduce database reads.
BUT, even though is better, this is solution also doesn't scale with an increasing number of users and pins.
we should evaluate some kind of caching, maybe a cloud function?
Closes #

feat: remove map streaming

---

src/stores/Maps/maps.store.ts

PR Checklist
PR Type
Revert changes in #3466 to allow caching of map pins (see comment in PR for details)
Unfortunately the `getWhere` query always executes against server, whereas the `stream` query includes ability to cache results and retrieve from cache
Closes #
--- …

fix: map pin caching

---

src/stores/Maps/maps.store.ts
src/stores/common/module.store.ts
src/stores/databaseV2/CollectionReference.ts
src/stores/databaseV2/types/AbstractDatabaseClient.ts
src/stores/databaseV2/types/index.d.ts

PR Checklist
PR Type
To follow on from discussions raised in #3472:
- Rename the db collection `stream` method to `syncLocally` and update comments to better reflect how the action uses local caching to minimise server requests
- Update default `syncLocally` behavior to stop streaming from server after first response, and provide a `keepAlive` option that can be used to override if required
- Update debug logging to better track start/end and total docs from sync methods
- Tidy map pin sync method to remove previous workaround in favour of new general method
- Tidy abstractDB interfaces to provide separate entries for DBs that support streaming vs not
**Breaking (?)**
- There might be some user functionality that depends on live update streaming which is no longer supported (e.g. updated …

refactor: server collection sync

---

src/pages/common/Breadcrumbs/Breadcrumbs.tsx

Fixes the issue with breadcrumbs going to category label rather than id. As it's a live thing and annoying for users, I'll do e2e tests in a follow-up PR.

fix: breadcrumb paths use category ids

---

src/pages/UserSettings/SettingsPage.tsx
src/pages/UserSettings/content/PostingGuidelines.tsx
src/pages/UserSettings/content/formSections/AccountSettings.section.tsx
src/pages/UserSettings/content/formSections/ChangeEmail.form.tsx
src/pages/UserSettings/content/formSections/ChangePassword.form.tsx
src/pages/UserSettings/content/formSections/Collection.section.tsx
src/pages/UserSettings/content/formSections/EmailNotifications.section.tsx
src/pages/UserSettings/content/formSections/Expertise.section.tsx
src/pages/UserSettings/content/formSections/Focus.section.tsx
src/pages/UserSettings/content/formSections/Impact/Impact.section.tsx
src/pages/UserSettings/content/formSections/Impact/ImpactYear.section.tsx
src/pages/UserSettings/content/formSections/MemberMapPin.section.tsx
src/pages/UserSettings/content/formSections/PatreonIntegration.tsx
src/pages/UserSettings/content/formSections/PublicContact.section.tsx
src/pages/UserSettings/content/formSections/UserInfos.section.tsx
src/pages/UserSettings/content/formSections/Workspace.section.tsx
src/pages/UserSettings/content/formSections/WorkspaceMapPin.section.tsx
src/pages/UserSettings/labels.ts

PR Checklist
PR Type
- [?] Bug fix (non-breaking change which fixes an issue)
- [?] New feature (non-breaking change which adds functionality)
This PR update all Heading tags in the User settings sections and forms to specific html heading tags from the default h2 to h1, h2 or h3. It should respect a correct hierarchical structure. To sum up, all sections have a confirmed h2, and every other heading in the card is now a h3 and the title of the page is now a h1.
Helps to close #3424
---
If the PR is working as intended it'll be merged and included in the next platform release, if not changes will be requested and re-reviewed once …

feat(seo): update headings for user settings form

---

.circleci/config.yml
firestore.rules
packages/security-rules/README.md
packages/security-rules/package.json
packages/security-rules/tests/general.spec.ts
packages/security-rules/vite.config.mts

PR Checklist
PR Type
In preparation for reviewing the permissions around each collection
we need to split the matches out to target an individual collection.
This allows us to apply rules in a granular fashion, based on the
following documented behaviour from Firestore:
> It's possible for a document to match more than one match
> statement. In the case where multiple allow expressions
> match a request, the access is allowed if any of the
> conditions is true.
https://firebase.google.com/docs/firestore/security/rules-structure#version-1

refactor: split rules out to granular matching

---

packages/components/src/Breadcrumbs/Breadcrumbs.tsx

chore: tidy up breadcrumb spacing

---

packages/cypress/src/integration/profile.spec.ts
packages/cypress/src/integration/research/write.spec.ts
packages/cypress/src/integration/settings.spec.ts
packages/cypress/src/utils/TestUtils.ts
src/pages/Research/Content/ResearchArticle.tsx
src/pages/Research/Content/ResearchList.tsx
src/pages/Research/research.routes.tsx

PR Checklist
PR Type
This allows any logged in user on Precious Plastic only to create their own research. The create research button is there for all with the standard link to login if they aren't already.

feat: enable research creation on pp

---

src/pages/User/contact/UserContactForm.tsx
src/pages/User/content/MemberProfile.tsx
src/pages/User/content/SpaceProfile.tsx
src/pages/User/content/UserCreatedDocuments.tsx
src/pages/User/content/UserCreatedDocumentsItem.tsx
src/pages/User/impact/ImpactItem.tsx

PR Checklist
PR Type
- [?] Bug fix (non-breaking change which fixes an issue)
- [?] New feature (non-breaking change which adds functionality)
This PR update all Heading tags in the User (members and others) profile to specific html heading tags from the default h2 to h1, h2 or h3. It should respect a correct hierarchical structure. To sum up, all tabs are now confirmed h2, and every other heading in the card is now a h3 and the name of the user is now a h1.
Helps to close #3424
---
If the PR is working as intended it'll be merged and included in the next platform …

feat(seo): update headings for user profiles

---

CONTRIBUTING.md

PR Checklist
PR Type
- chore
Fixes a broken link.
Steps to reproduce:
1. Go to https://github.com/ONEARMY/community-platform/blob/master/CONTRIBUTING.md
2. Click on Deployment in the Summary section
3. Be confused you aren't redirected.
Going to this link: https://github.com/ONEARMY/community-platform/blob/master/CONTRIBUTING.md#--deployments goes directly to the section, so I've changed it.

chore: make clicking on link work

---

src/pages/common/Header/Menu/MenuDesktop.tsx

PR Checklist
PR Type
Displays the "blob" for the active navigation.
@davehakkens is not going crazy (yet!).
The cause was the router migration 6 months ago.
Solution found [here](https://stackoverflow.com/a/73508812)
Closes #3605

fix: display the active nav blob again

---

.circleci/config.yml

PR Checklist
PR Type
Adds yarn caching step to setup command.
Findings:
- adding `- *save_yarn_cache` to the setup command improves each execution of `yarn install` by ~1min
- but ideally it would reduce to 0
- current theory why it's not 0 is that `yarn install` is different for each workspace
I see two ways to improve further:
1. have a dynamic cache key and path for each workspace (quick win, not sure it's possible)
2. migrate the solution to use a monorepo tool (nx or turborepo) where there is only 1 package.json with all the dependencies
Closes #3596

fix: add ci cache step

---

packages/cypress/src/support/rules.ts

PR Checklist
PR Type
We've started to get a cypress test failure during teardown for when firebase can't find a document (normally a user record) to 'update'. It's unrelated to the test suite so adding an expection.
Closes #3572

test: exception for when firebase can't find doc

---

functions/src/userUpdates/hasKeyDetailsChanged.test.ts
functions/src/userUpdates/hasKeyDetailsChanged.ts
functions/src/userUpdates/updateDiscussionComments.test.ts
functions/src/userUpdates/updateDiscussionComments.ts
packages/components/src/CommentItem/CommentItem.stories.tsx
packages/components/src/CommentItem/CommentItem.test.tsx
packages/components/src/CommentItem/CommentItem.tsx
packages/components/src/CommentItem/types.ts
packages/components/src/CommentList/CommentList.stories.tsx
packages/components/src/CommentList/CommentList.test.tsx
packages/components/src/CommentList/CommentList.tsx
packages/components/src/CreateComment/CreateComment.tsx
packages/components/src/DiscussionContainer/DiscussionContainer.stories.tsx
packages/components/src/DiscussionContainer/DiscussionContainer.tsx
packages/components/src/DiscussionTitle/DiscussionTitle.tsx
packages/components/src/utils.ts
packages/cypress/src/integration/questions/discussions.spec.ts
shared/mocks/data/discussions.ts
src/common/DiscussionWrapper.tsx
src/models/discussion.models.tsx
src/models/user.models.tsx
src/stores/Discussions/discussions.store.tsx

PR Checklist
PR Type
Add option user profile image to comments (and tidies up various responsive layout stuff).

feat(discussions): add avatars

---

.circleci/config.yml

PR Type
Sorting out the CI chromatic step as it's currently blocking deployment. This adds chromatic as a proper seperate step in the ci pipeline after the e2e complete.

fix: chromatic as separate ci step

---

src/pages/Question/Content/Common/QuestionForm.tsx
src/stores/Question/question.store.tsx

PR Checklist
PR Type
Even after #3600 got merged in, it's happened again that a user has submitted duplicate questions (just this time changing the title to do it...). I did some more testing and it turns out that the submitting button isn't instantly disabled if you're on a low connection (I set to poor-3G for testing), thus maybe giving the user the view that the submission request has been handled. 
This change ensures the button is more quickly set.

fix: question form submitting not instantly set

---

packages/cypress/src/integration/SignUp.spec.ts
packages/cypress/src/integration/common.spec.ts
packages/cypress/src/integration/howto/read.spec.ts
packages/cypress/src/integration/howto/search.spec.ts
packages/cypress/src/integration/howto/write.spec.ts
packages/cypress/src/integration/notifications.spec.ts
packages/cypress/src/integration/profile.spec.ts
packages/cypress/src/integration/questions/write.spec.ts
packages/cypress/src/integration/research/follow.spec.ts
packages/cypress/src/integration/research/read.spec.ts
packages/cypress/src/integration/research/write.spec.ts
packages/cypress/src/integration/settings.spec.ts
packages/cypress/src/integration/unsubscribe.spec.ts
packages/cypress/src/support/commandsUi.ts

PR Checklist
PR Type
This MR is an improvement in some asserts as they used `.should('exist')` instead of `.should('be.visible')`. When you use `should('exist')` cypress checks if the element exists in DOM, then cypress will NOT check if the element is visible.

refactor: cy change shouldExist to beVisible

---

packages/components/src/ButtonShowReplies/ButtonShowReplies.stories.tsx
packages/components/src/ButtonShowReplies/ButtonShowReplies.tsx
packages/components/src/CommentItem/CommentItem.stories.tsx
packages/components/src/CommentItem/CommentItem.tsx
packages/components/src/CommentItem/types.ts
packages/components/src/CommentList/CommentList.stories.tsx
packages/components/src/CommentList/CommentList.tsx
packages/components/src/CreateComment/CreateComment.tsx
packages/components/src/CreateReply/CreateReply.tsx
packages/components/src/DiscussionContainer/DiscussionContainer.tsx
packages/components/src/DiscussionTitle/DiscussionTitle.stories.tsx
packages/components/src/DiscussionTitle/DiscussionTitle.test.tsx
packages/components/src/DiscussionTitle/DiscussionTitle.tsx
packages/components/src/EditComment/EditComment.tsx
packages/cypress/src/integration/howto/discussions.spec.ts
packages/cypress/src/integration/questions/discussions.spec.ts
packages/cypress/src/integration/research/discussions.spec.ts
src/common/DiscussionWrapper.tsx
src/models/discussion.models.tsx
src/models/question.models.tsx
src/pages/Question/QuestionPage.tsx
src/stores/Discussions/discussion.store.test.ts
src/stores/Discussions/discussionEvents.ts
src/stores/Discussions/discussions.store.tsx
src/utils/filterNonDeletedComments.test.ts
src/utils/filterNonDeletedComments.ts
src/utils/nonDeletedCommentsCount.test.ts
src/utils/nonDeletedCommentsCount.ts

PR Checklist
PR Type
Still show the nest comments (replies) when a parent comment is deleted. 
Closes #
https://github.com/ONEARMY/community-platform/assets/16688508/02b19d97-57ce-447b-92eb-963e9f22718b

feat: still display replies for deleted comment

---

packages/cypress/src/integration/howto/read.spec.ts
packages/cypress/src/integration/howto/seo.spec.ts
packages/cypress/src/integration/profile.spec.ts
packages/cypress/src/integration/questions/read.spec.ts
packages/cypress/src/integration/research/read.spec.ts
packages/cypress/src/support/commands.ts
shared/mocks/data/questions.ts
shared/mocks/data/research.ts
src/config/constants.ts
src/models/question.models.tsx
src/pages/Howto/Content/Howto/Howto.tsx
src/pages/PageList.tsx
src/pages/Question/QuestionPage.tsx
src/pages/Research/Content/ResearchArticle.tsx
src/pages/User/content/UserProfile.tsx
src/utils/seo.tsx

PR Checklist
PR Type
By not doing this before we've probably been missing out on traffic...
From --> To
Research --> Research - [Community Name]
[Research Title] --> [Research Title] - Research - [Community Name]
How-tos --> How-tos - [Community Name]
[How-to Title] --> [How-to Title] - How-to - [Community Name]
Questions --> Questions - [Community Name]
[Question Title] --> [Question Title] - Question - [Community Name]
Profile --> [Username] - Profile -  [Community Name]
Plus this sets social tags of questions correctly.
Closes #3409

feat: update page titles

---

functions/src/Integrations/firebase-discord.ts

PR Type
- bug fix (probably)
Well, I realized I originally copied the format of the slack webhook, which is different than the discord one. I didn't test it with an actual Discord channel though. (lol)

chore: make format match other discord webhooks

---

src/pages/Research/Content/Common/ResearchUpdate.form.tsx
src/pages/Research/Content/CreateResearch/Form/DescriptionField.tsx
src/pages/Research/Content/CreateResearch/Form/FilesFields.tsx
src/pages/Research/Content/CreateResearch/Form/MediaFields.tsx
src/pages/Research/Content/CreateResearch/Form/TitleField.tsx

…r an update
PR Checklist
PR Type
This PR introduces several components to encapsulate fields of the research update form. This should allow easier futur changes but also easier identification of duplication for input fields between how to and research.

refactor(research): extract several components to simplify the form

---

.circleci/config.yml

Current error on CircleCI for storybook:
```
Usage Error: Couldn't find a script named "storybook:chromatic".
$ yarn run [--inspect] [--inspect-brk] [-T,--top-level] [-B,--binaries-only] <scriptName> ...
Exited with code exit status 1
```
Had changed command in #3689 but not the ci script.

chore: change circle storybook command

---

functions/src/Integrations/firebase-discord.ts

PR Type
bug fix, kinda
Dave said to wrap the url in <> to avoid previews, which I originally didn't do.
Here is how it is currently: https://discord.com/channels/586676777334865928/599259846767935519/1255595823690158141
see the "Things to keep in mind" section, in this ticket: https://github.com/ONEARMY/community-platform/issues/3533

chore: disable url preview

---

packages/cypress/src/integration/howto/write.spec.ts
src/pages/Howto/Content/Common/SubmitStatus.tsx

PR Checklist
PR Type
- Add `data-cy` to close icon on Uploading How to modal
- Add condition on the e2e test file in case the Uploading How to modal is being displayed to close it
The submit modal is sometimes displayed when the user clicks the add step this is causing the flaky test. As you can see in [this execution](https://cloud.cypress.io/projects/4s5zgo/runs/5959/test-results/f4388e91-8408-4267-ae54-fb5c9c98d73a/replay?actions=%5B%5D&att=1&browsers=%5B%5D&groups=%5B%5D&isFlaky=%5B%5D&modificationDateRange=%7B%22startDate%22%3A%221970-01-01%22%2C%22endDate%22%3A%222038-01-19%22%7D&orderBy=EXECUTION_ORDER&oses=%5B%5D&specs=%5B%5D&statuses=%5B%7B%22value%22%3A%22FAILED%22%2C%22label%22%3A%22FAILED%22%7D%5D&testingTypesEnum=%5B%5D&ts=1720510477618.5017) (you can skip until the end of …

[e2e] Fix to Write HowTo flaky

---

packages/cypress/src/integration/howto/read.spec.ts
src/common/DownloadWithDonationAsk.test.tsx
src/common/DownloadWithDonationAsk.tsx

PR Checklist
PR Type
This PR displays to any logged-in users, not only beta testers anymore, the "pay as you can" modal whenever they click a download button.
Closes #3726
---

feat(platform): remove beta wrapper for 'pay as you can' feature

---

src/stores/Discussions/discussionEvents.ts
src/stores/Howto/howto.store.tsx
src/stores/Question/question.store.tsx
src/stores/Research/research.store.tsx
src/stores/Research/researchEvents.ts
src/stores/common/toggleDocSubscriberStatusByUserName.ts
src/stores/databaseV2/DocReference.ts

We had a recent issue with discussion document updates being lost because the store wasn't using the saved version to perform the update on.
This picks off the remaining uses on the app of getting a document from the cache rather than the server. So now`doc.get('server')` is always used.

fix: always getting server version of document

---

src/common/DiscussionWrapper.tsx

Wrong comment count shown on button to show/hide discussion.
The button now uses the util to check for deleted comments.

fix: research show discussion comment count

---

src/pages/User/content/MemberProfile.tsx
src/pages/User/content/SpaceProfile.tsx
src/pages/User/content/UserProfile.tsx

A suggestion from Dalibor was to add a profile update button to users on their own profile. It also does a responsive tidy-up to the display of the profile type icon on space profiles.

Feat: add edit profile button to profile

---

functions/src/Integrations/firebase-discord.ts
packages/cypress/src/integration/research/discussions.spec.ts
packages/cypress/src/integration/research/read.spec.ts
src/pages/Research/Content/ResearchArticle.tsx
src/pages/Research/Content/ResearchUpdate.tsx
src/stores/Discussions/discussions.store.tsx

Anchors are present on research articles but link to the wrong update.
Fixes now by scrolling to the right update and the discord webhook links to that update anchor.

feat: fix and use research update anchors

---

functions/src/emailNotifications/createSubmissionEmails.spec.ts
functions/src/emailNotifications/createSubmissionEmails.ts

The final step to create emails from messages involves updating the message doc to know that the message has been sent. This was done through a 'set()' command.
The message is now changed through an update command, which is safer.

chore: change notification after send to update

---

src/models/discussion.models.tsx
src/stores/Discussions/discussions.store.tsx

Adding comments fails when the discussion contributorIds array is undefined.
Unsure how contributorIds could be null though. Couldn't replicate locally.
Comments can be added.
Closes #3804

fix: adding contributorId when contributorIds is undefined

---

src/App.tsx

A user reported this issue when clicking onto a how-to:
[From reading this](https://github.com/vitejs/vite/issues/11804), a possible reason for the issue is that our prod hosting provider deletes the old js files that the new build links to.
My fix causes a page level refresh (to get the most up to date js files) when that error occurs.

fix: prod users seeing a dynamic import error

---

scripts/postBuild.ts

Adds a meta tag to the head of the html rendered file upon checking if the environment is NOT production based on an environment variable
fix #3777
Closes #

fix(platform): add conditional meta tag to post build

---

packages/components/src/SettingsFormWrapper/SettingsFormTab.tsx
packages/cypress/src/integration/settings.spec.ts
src/pages/UserSettings/SettingsPage.tsx
src/pages/UserSettings/content/formSections/EmailNotifications.section.tsx
src/pages/UserSettings/content/formSections/SettingsMapPin.section.tsx
src/pages/UserSettings/content/formSections/SettingsNotifications.section.tsx
src/pages/UserSettings/content/formSections/UserProfile.section.tsx
src/pages/UserSettings/labels.ts
src/stores/Maps/maps.store.test.ts
src/stores/Maps/maps.store.ts
src/stores/User/user.store.ts

Email notification nested in the user profile tab.
In it's own tab with own store method.

feat: move email notification setting to own tab

---

functions/src/userUpdates/hasKeyDetailsChanged.test.ts
functions/src/userUpdates/hasKeyDetailsChanged.ts
functions/src/userUpdates/updateDiscussionComments.ts

Comments not updating `creatorImage` when `userImage` is updated.
https://github.com/user-attachments/assets/356e96b6-8ada-4b4a-bf77-5a67a732c149
Comments updating `creatorImage` when `userImage` is updated.
https://github.com/user-attachments/assets/25f60506-f5ff-49ef-a0e4-21afa9f3d3a7

fix: content updating when userImage changes

---

packages/components/src/TabbedContent/TabbedContent.stories.tsx
packages/components/src/TabbedContent/TabbedContent.tsx

On small screens:
A more graceful display on small screens.

fix: responsive design of tabs on profile

---

packages/components/src/CreateComment/CreateComment.tsx
packages/components/src/DiscussionContainer/DiscussionContainer.stories.tsx
packages/components/src/DiscussionContainer/DiscussionContainer.tsx
src/common/DiscussionWrapper.tsx
src/common/HideDiscussionContainer.tsx
src/stores/Discussions/discussionEvents.ts
src/stores/Discussions/discussions.store.tsx

Adding comments is very slow (13 seconds in a particular case!).
Due to notifications, the more contributors it has, the worse it gets!
Lack of loading indicators makes it worse.
Does not await discussion metadata updates and user notifications.
Locally it reduces the time from 4s to 1s.
1 second should be constant now, so for prod it would reduce from 13s to 1s.
Closes #

fix: improve comments performance

---

shared/mocks/data/research.ts
src/models/research.models.tsx
src/stores/Discussions/discussionEvents.test.ts
src/stores/Discussions/discussionEvents.ts
src/test/factories/ResearchItem.ts

While the typing for research updates stats that status is a required field... The actual prod data says different, so my last fix didn't work as old research updates on PK don't have the status set.

fix: discussion count on research updates

---

CONTRIBUTING.md

The CONTRIBUTING.md link to the firebase emulator page is leading to a 404 page (`https://docs.platform.onearmy.earth/Backend%20Development/firebase-emulator`)
Changed the link from to `https://docs.platform.onearmy.earth/Backend%20Development/firebase-emulators-docker`
Closes #3821
If you need more immediate feedback you can try reaching out on Discord in the [Community Platform `development` channel](https://discord.com/channels/586676777334865928/93878172701 …

fix(docs): fix CONTRIBUTING.md backend emulator link

---

src/models/user.models.tsx
src/pages/UserSettings/SettingsPageNotifications.test.tsx
src/pages/UserSettings/SettingsPageNotifications.tsx
src/pages/UserSettings/content/sections/EmailNotifications.section.tsx
src/stores/User/user.store.test.tsx
src/stores/User/user.store.ts

An admin was recently confused that they weren't recieving notification emails. It turns out they'd been unsubscribed at somepoint. But there's no way they could have known this from their user settings.
As in our functions, if an unsubscribe token is present then that overrides the notification frequency preference. Now this is shown to the user by displaying the requency as 'never' and clearing `unsubscribeToken` if changed from never.

feat: show unsubscribed on notification setting

---

packages/cypress/src/integration/common.spec.ts
src/pages/common/StickyButton.tsx

The page url given to the link to the feedback form was set on the first path viewed by the user. It was updated on refresh but not normal navigation around the site.

fix: page link given to feedback button

---

functions/src/emailNotifications/constants.ts

The PK email template currently links to a now deleted (for whatever reason) asset library. 
I've uploaded the same image directly to the firebase image store so this new url shouldn't change.

fix: email link to PK header image

---

shared/mocks/data/discussions.ts
src/stores/Discussions/discussion.store.test.ts
src/stores/Discussions/discussions.store.tsx
src/stores/User/notifications.store.test.tsx
src/stores/User/notifications.store.ts
src/test/factories/Discussion.ts
src/utils/getDiscussionContributorsToNotify.test.ts
src/utils/getDiscussionContributorsToNotify.ts

When a new discussion item is added, only the "comment parent" is notificied (content creator for comments, comment creator for replies). Plus for research, the research collaborators are notified. Therefore in most instances a new comment notifies only one person.
Now all users who have participated in the discussion will be notified...

feat: send notification to discussion contributors

---

functions/src/Integrations/firebase-discord.test.ts
functions/src/Integrations/firebase-discord.ts

Saving a research article as a draft triggers the discord webhook
Saving a research article as a draft does not trigger the discord webhook
Closes #3740

fix: saving a research article as a draft does not trigger webhook

---

packages/components/assets/icons/step.svg
packages/components/src/CardList/CardList.stories.tsx
packages/components/src/CardList/CardList.tsx
packages/components/src/Icon/Icon.tsx
packages/components/src/Icon/svgs.tsx
packages/cypress/src/integration/map.spec.ts
src/pages/Maps/Content/Controls/Controls.tsx
src/pages/Maps/Content/MapView/MapWithList.tsx
src/pages/Maps/Content/NewMapBanner.tsx
src/pages/Maps/Maps.tsx

No new map at mobile/tablet viewports.
1. Map at mobile/tablet viewports (with button).
2. Quick loading indicator.
3. Updated map icon on banner.

feat: add responsive views for new map

---

packages/components/src/CardListItem/CardDetailsMemberProfile.tsx
packages/components/src/CardListItem/CardDetailsSpaceProfile.tsx
packages/components/src/CardListItem/types.ts
shared/models/maps.ts
src/models/maps.models.tsx
src/pages/Maps/map.service.ts

Slow loading on prod of the workspace cover images for the map pin list.
Using the CDN smaller versions of the images should speed things up.

feat: use cdn images for map pin calls

---

packages/components/src/ButtonShowReplies/ButtonShowReplies.tsx
packages/components/src/CommentItem/CommentItem.tsx
packages/themes/src/common/button.ts
src/common/HideDiscussionContainer.tsx

- Edit and Delete comment buttons use outlined variant
- Edit and Delete comment buttons increase the spacing between the username and the comment text
Edit and Delete comment buttons use subtle variant:
on hover:
Updated  [button.ts](https://github.com/ONEARMY/community-platform/compare/master...onim-at:3651-comment-button?expand=1#diff-55ca3b7df8d945246670eada2c5f2cd5061d1ee57aafacd6c1374495054f53dd) subtle variant to be consistent with the changes done in #3675 
Updated [HideDiscussionContainer.tsx](https://github.com/ONEARMY/community-platform/compare/master...onim-at:3651-comment-button?expand=1#diff-6663f7705972fd1b641a8cd254882f3c09a31c1d3b37d167bd8a78472ea3ff34) to avoid regression due to the button component changes
Comment with edit …

fix: make edit and delete comment button subtle

---

packages/cypress/src/integration/research/write.spec.ts
src/pages/Research/Content/Common/ResearchUpdate.form.tsx
src/pages/Research/Content/ResearchArticle.tsx
src/pages/Research/Content/ResearchUpdate.tsx

It wasn't clear sometimes to research creators that there updates had been saved as drafts.
1. Clearly shows an update is draft on display page.
2. Re-order the buttons that that it's a little harder to accidently set an update back to draft.

feat: show clearly when research update is draft

---

packages/components/src/DonationRequest/DonationRequest.tsx
packages/components/src/DonationRequestModal/DonationRequestModal.tsx

Users with lower screen resolutions or smaller laptops are experiencing difficulties locating the download button. 
Download button is always displayed at the bottom of the screen, regardless of the content length.
Also added a thin scrollbar and increased the modal width for mobile.
Closes #3847

fix: always display download button

---

functions/src/Integrations/firebase-discord.test.ts
functions/src/Integrations/firebase-discord.ts
functions/src/models.ts

The notification script wouldn't trigger if a new research update was changed to draft.

fix: notification not being sent for new updates which go from draft to published

---

packages/cypress/src/integration/map.spec.ts

The cypress map test currently relies on an external (to this repo) api with a version of our dev data on. So as new/existing engineers get involved the number of map pins goes up and the test starts failing. The API is being replaced shortly (and will be part of this repo) so I'm temporarily removing the result total related expectations until that happens.

fix: temp reduction in map spec coverage

---

packages/components/src/CardProfile/CardDetailsMemberProfile.tsx
packages/components/src/CardProfile/CardDetailsSpaceProfile.tsx
packages/components/src/CardProfile/CardProfile.tsx
packages/components/src/PinProfile/PinProfile.tsx

Adding back in the regular profile link for usernames on the map pin, was removed for the list cards.

feat: set map pins to have profile link

---

.circleci/config.yml

"Approve Production deployment" step is showing even when it's not the master branch.
fixes that :)

fix: do not show deployment approval unless it's the default branch

---

.github/workflows/fly-pr-preview.yml

Old pr preview workflow no longer works since moving to fly.io
Implements pr preview workflow using fly.io
Closes #

build: add fly preview workflow

---

.github/workflows/fly-pr-preview.yml

Fly preview workflow fails because GitHub organisation isn't lowercase 🙄 
Set non default app name that is all lower case
Closes #

build: add app name to fly preview workflow

---

packages/components/assets/icons/chevron-down.svg
packages/components/assets/icons/chevron-up.svg
packages/components/src/ButtonShowReplies/ButtonShowReplies.stories.tsx
packages/components/src/ButtonShowReplies/ButtonShowReplies.test.tsx
packages/components/src/ButtonShowReplies/ButtonShowReplies.tsx
packages/components/src/CommentList/CommentList.test.tsx
packages/components/src/CommentList/CommentList.tsx
packages/components/src/ContentStatistics/ContentStatistics.test.tsx
packages/components/src/DiscussionContainer/DiscussionContainer.test.tsx
packages/components/src/Icon/Icon.tsx
packages/components/src/Icon/svgs.tsx

The reply button text is too long and the icon is too thick
<details> 
</details>
The reply button text is updated to not include the username and the icon has been changed to a chevron
<details> 
</details>
Closes #3652 

feat: update reply to comment button text and icon

---

src/styles/leaflet.css

The zoom controls for the new map are currently the default design.
The zoom controls were updated with the correct design.
Closes #3872  

feat: update design of zoom controls on new map

---

src/common/Alerts/AlertProfileVerification.tsx

fix: alert profile icon positioning

---

src/stores/Research/research.store.tsx

Re publishing or updating a research reset its total comments count to 0
The total comments count is not reset on Publish/Draft
Note: this PR does not fix the researches already affected by the bug. The correct count value will be displayed when a new comment or update is posted
Closes #3905 …

bug: setting as draft a published research does not reset the total comment count

---

packages/cypress/.eslintrc.json

You can merge in Jest tests that are exclusive (IE using `describe.only`). 
An ESLint error will be thrown if any exclusive test is added. I chose to go with error because I can't think of a super good reason why this should ever be allowed.
Closes #3873

fix: adding eslint rule for no exclusive tests

---

.github/workflows/fly-pr-preview.yml

Uses fly preview workflow action which doesn't support build secrets
Switches to custom forked action which allows build secrets
Closes #

feat: switch to custom github action with build secrets

---

.github/workflows/fly-pr-preview.yml

Doesn't run due to missing release number
Should run with release number added
Closes #

fix: add release number to action path

---

.github/workflows/fly-pr-preview.yml
Dockerfile.preview

Sending secrets in GitHub workflow
As using new dockerfile with limited hardcoded env variables no need to send all variables as build secrets
Closes #

feat: remove sending of secrets from github workflow

---

.github/workflows/fly-pr-preview.yml

Preview workflow only triggered on addition of preview label.
Triggers on close of pull request to tidy up fly deployment.
Closes #

feat: trigger preview workflow on pull request closure

---

src/pages/Howto/Content/Common/HowtoButtonDraft.tsx
src/pages/Howto/labels.ts
src/pages/Research/Content/Common/Research.form.tsx

We currently show "Revert to draft" as the button CTA for How-tos and Research posts that are still in Draft mode.
We remove the "Revert to draft" CTA entirely. All draft posts will always just have a "Save as draft" CTA, which makes sense.
https://github.com/user-attachments/assets/2ca986ee-5d9e-497a-8201-f93e6217675c
Closes #3910 …

fix: remove revert to draft state

---

.github/workflows/fly-pr-preview.yml
.github/workflows/preview-label-removed.yml

Currently closing or merging a pr will destroy the fly.io preview app, however the label remains in place and as a result when the pr is included in a release the updates trigger another preview deploy.
Introduces 2 improvements:
1. when a pr is closed the label is automatically removed preventing any further updates triggering an inadvertent deploy.
2. when the preview label is removed a workflow is triggered to destroy the fly.io app
Closes #
If you need …

build: remove preview label if pr closed + destroy fly.io preview app if label removed

---

.github/actions/destroy-fly-preview-app/Dockerfile
.github/actions/destroy-fly-preview-app/action.yml
.github/actions/destroy-fly-preview-app/entrypoint.sh
.github/workflows/preview-label-removed.yml

Adds local action to destroy fly preview apps
Closes #

build: add local fly preview destroy app action

---

src/common/Form/FileInput.field.tsx
src/common/Form/FileInput/FileInput.tsx
src/common/Form/FileInput/UppyConfigAdmin.ts
src/pages/Howto/Content/Common/HowtoFieldFileUpload.tsx
src/pages/Research/Content/Common/ResearchUpdate.form.test.tsx
src/pages/Research/Content/CreateResearch/Form/FilesFields.tsx

All humans using the platform have a 50mb file upload limit
Humans that have an admin account can upload up to 300mb files.
Closes #

feat: add 300mb file upload limit for admins

---

src/stores/Discussions/discussion.store.test.ts
src/stores/Discussions/discussions.store.tsx

Discussions are being duplicated which causes comments to not show. There should only be 1 discussion per sourceId.
Ensure that even with duplicated discussions, it shows the correct one.
Change that might prevent this duplication in the first place.
Closes #

fix: discussion duplication

---

packages/components/src/MapFilterList/MapFilterList.stories.tsx
packages/components/src/MapFilterList/MapFilterList.tsx
packages/components/src/MapFilterList/MapFilterListItem.tsx
packages/components/src/MapFilterList/MapFilterListWrapper.tsx
packages/components/src/ProfileTagsList/ProfileTagsList.tsx
packages/cypress/src/integration/map.spec.ts
packages/cypress/src/integration/settings.spec.ts
packages/cypress/src/support/db/endpoints.ts
src/pages/Maps/Content/Controls/transformAvailableFiltersToGroups.tsx
src/pages/Maps/Content/MapView/MapWithList.tsx
src/pages/Maps/Content/MapView/MapWithListHeader.tsx
src/pages/Maps/Maps.client.tsx
src/pages/Maps/utils/filterPins.test.ts
src/pages/Maps/utils/filterPins.ts
src/stores/Maps/filter.test.ts
src/stores/Maps/filter.ts
src/stores/Maps/maps.store.ts
src/styles/leaflet.css
src/test/factories/MapPin.ts

So far...
https://github.com/user-attachments/assets/c9586170-44a6-41ad-944e-a7cad954f4ad

feat: add tags to map filters

---

.github/ISSUE_TEMPLATE/build-new-component.md
packages/documentation/docs/Backend Development/integrations.md
packages/documentation/docs/Install.md
types/readme.md

This pull request contains changes to improve clarity, correctness and structure.
**Description correction:**
Corrected "descritpion" to "description".
Corrected "platform and and generate" to "platform and generate".
The phrase "Firebase CLI tools]" — the opening square bracket before "Firebase CLI tools" was missing, corrected.
The phrase "Create an application]" — again, the opening square bracket before "Create an application" was missing, corrected.
Corrected "typescript" to "TypeScript".
Please review the changes and let me know if any additional changes are needed.

fix: typos in documentation files

---

BOUNTIES.md
docs/supabase.md

I reviewed the entire repository, no more typos found in docs. 
Hope this helps streamline the project!
Best regards,
Bilogweb3

chore: correct typos docs

---

packages/components/src/CardButton/CardButton.tsx
packages/components/src/CategoryVerticalList/CategoryVerticalList.tsx
packages/components/src/MemberTypeVerticalList/MemberTypeVerticalList.client.tsx
packages/components/src/VerticalList/Arrows.tsx
packages/components/src/VerticalList/styles.css

Minor styling tweaks for vertical scroll lists
Final part of #4003

feat: tweak active styling of card buttons

---

src/pages/Question/QuestionListing.tsx

Loading more comment counts was resetting the previous page comment counts.
Closes #

fix: question comment counts reseting on pagination

---

.circleci/config.yml

fix: missing slash for circle ci argument

---

packages/cypress/src/integration/map.spec.ts
src/pages/Maps/Content/MapView/ButtonZoomIn.tsx
src/pages/Maps/Content/MapView/MapContainer.tsx
src/pages/Maps/Content/MapView/MapList.tsx
src/pages/Maps/Content/MapView/MapView.tsx

1. Drops the zoom out/show globe button as it was already getting annoying to maintain.
2. Updates the zoom in/to user location button to make it clear when a user has already denied a location request.

feat: update zoom buttons

---

packages/components/src/MemberBadge/MemberBadge.tsx
src/pages/common/Header/Menu/Profile/Profile.tsx

The cursor is unchanged when hovering over the MemberBadge component
The cursor changes to pointer when hovering over the MemberBadge component
Closes #

fix: add "cursor: pointer" to MemberBadge component

---

packages/cypress/src/integration/research/list.spec.ts
src/pages/Research/Content/Common/ResearchCategorySelect.tsx
src/pages/Research/Content/ResearchList.tsx
src/pages/Research/research.service.test.ts
src/pages/Research/research.service.ts
src/routes/api.research.categories.ts
src/routes/api.research.drafts.count.ts
src/routes/api.research.ts

Fetching of research articles is being done directly with Firestore
Fetching of research articles have moved to a Remix backend API
Closes #3924 

Create API for research search

---

packages/components/src/ImageGallery/ImageGallery.tsx
packages/components/src/ImageGalleryThumbnail/ImageGalleryThumbnail.stories.tsx
packages/components/src/ImageGalleryThumbnail/ImageGalleryThumbnail.test.tsx
packages/components/src/ImageGalleryThumbnail/ImageGalleryThumbnail.tsx
packages/components/src/MapFilterList/MapFilterList.tsx
packages/components/src/MemberTypeVerticalList/MemberTypeVerticalList.client.tsx

Feature (adds functionality)
Images loading in are displayed while they are uncompleted. 
When Images load in, there is now the Applications Load Spinner.
No
Closes #3462
I've decided to move the Loadingspinner logic for the thumbnails into their own component, for a couple of reasons:
1. Keep the ImageGallery state as small as possible (to prevent rerenders)
2. Prevent rerender data loss, when images load at the exact same time (which is the main Reason)
3. Make the ImageGallery tighter
`packages/components/src/MapFilterList/MapFilterList.tsx` and `packages/components/src/MemberTypeVerticalList/MemberTypeVerticalList.client.tsx` I've only noticed now. I'm guessing they got in while linting/formatting (`yarn format && yarn lint`).

feat: Add loading state to ImageGallery (#3462)

---

packages/components/src/DownloadButton/DownloadButton.stories.tsx
packages/components/src/DownloadButton/DownloadButton.tsx
packages/components/src/DownloadStaticFile/DownloadStaticFile.stories.tsx
packages/components/src/DownloadStaticFile/DownloadStaticFile.tsx
packages/components/src/DownloadWithDonationAsk/DownloadWithDonationAsk.stories.tsx
packages/components/src/DownloadWithDonationAsk/DownloadWithDonationAsk.test.tsx
packages/components/src/DownloadWithDonationAsk/DownloadWithDonationAsk.tsx
packages/cypress/src/integration/library/write.spec.ts
packages/cypress/src/integration/questions/write.spec.ts
packages/cypress/src/integration/research/write.spec.ts
src/common/Alerts/Alerts.tsx
src/common/DownloadWrapper.tsx
src/common/UserAction.test.tsx
src/common/UserAction.tsx
src/pages/Library/Content/List/LibraryListHeader.tsx
src/pages/Library/Content/Page/LibraryDescription.tsx
src/pages/Library/Content/Page/LibraryDownloads.tsx
src/pages/Library/labels.ts
src/pages/Question/QuestionListHeader.tsx
src/pages/Question/labels.ts
src/pages/Research/Content/ResearchListHeader.tsx
src/pages/Research/Content/ResearchUpdate.tsx
src/pages/Research/labels.ts
src/pages/User/contact/UserContactForm.tsx
src/pages/User/content/SpaceProfile.tsx
src/pages/common/CommentsV2/CreateCommentV2.tsx

A little util component to wrap around actions logged in user can do. Useful prep for #4044.
Reduces components that access the user store.
One small user change:
Closes #4079

feat: add user action component

---

packages/components/src/Username/Username.tsx
packages/documentation/docs/Testing/overview.md

https://github.com/ONEARMY/community-platform/issues/4101
This PR truncates the Username when is longer than the limit of the page.
It also adds a Tooltip for users to see the username when it's truncated.
Closes #4101

fix: truncate username when too long

---

packages/cypress/src/support/commandsUi.ts
shared/models/user.ts
src/pages/UserSettings/SettingsPageUserProfile.tsx
src/pages/UserSettings/content/fields/ProfileLink.field.tsx
src/pages/UserSettings/content/sections/UserInfos.section.tsx
src/pages/UserSettings/labels.ts
src/services/userService.server.ts
src/stores/User/user.store.ts
src/utils/isProfileComplete.test.ts
src/utils/isProfileComplete.ts

* Links no longer a required field when a user fills in their profile.
* Empty/no links no longer a variable when showing the incomplete profile banner.

feat: drop links as a required user field

---

packages/cypress/src/integration/SignUp.spec.ts
packages/cypress/src/support/seedAccounts.ts
packages/cypress/src/utils/TestUtils.ts

Resend is now sending out all the test emails from the cypress tests and we don't want to be changed for them! 
So changing all the future test accounts to use the [email address that have for testing](https://resend.com/changelog/sending-test-emails)

test: change domain for test emails

---

packages/cypress/src/integration/library/write.spec.ts
packages/cypress/src/integration/questions/discussions.spec.ts
packages/cypress/src/integration/questions/write.spec.ts
packages/cypress/src/integration/research/write.spec.ts
packages/cypress/src/integration/settings.spec.ts
packages/cypress/src/support/commandsUi.ts
packages/themes/src/common/button.ts
src/common/UserAction.test.tsx
src/common/UserAction.tsx
src/pages/Library/Content/List/LibraryListHeader.tsx
src/pages/Library/labels.ts
src/pages/Question/QuestionListHeader.tsx
src/pages/Question/labels.ts
src/pages/Research/Content/CreateResearch/index.tsx
src/pages/Research/Content/ResearchListHeader.tsx
src/pages/Research/labels.ts
src/pages/User/content/ProfileContact.tsx
src/pages/UserSettings/SettingsPageUserProfile.tsx
src/pages/common/CommentsSupabase/CreateCommentSupabase.tsx
src/routes/_.library.create.tsx
src/routes/_.questions.create.tsx
src/routes/_.research.create.tsx
src/stores/User/user.store.ts

Users can basically do anything.
Users need to complete their profile before adding projects, research, questions or comments on questions.
Note: can still add comments on projects/research due to how much code is in the component library and I'm accepting that debt as we'll be removing those components (and using the question comment components) soon.

feat: block actions from incomplete profiles

---

.github/workflows/codeql-analysis.yml

Hey ! GitHub‑hosted runners now use Node 20, so checkout v4 is required
This PR updates all workflows to actions/checkout@v4 , no functional changes expected

ci: bump actions/checkout to v4

---

supabase/migrations/20250512170000_research_sorting.sql

Research sorting by 'LastUpdated' uses modified_at of research.
Now considers created_at value of it's research updates.

fix: research sorting

---

src/pages/User/content/ProfileDetails.tsx

There's `user.badges.verified` and `user.verified` - which should be the same

fix: old data for verified at top user level

---

.github/workflows/reset-staging-site.yml

Bumps setup-node to v4 for future-proofing against runner updates. Workflows compile the same. Reference: https://github.com/actions/setup-node/releases/tag/v4.0.0

CI: migrate workflows to setup-node v4

---

packages/cypress/src/integration/news/write.spec.ts
packages/cypress/src/integration/questions/write.spec.ts

**Description:**  
This pull request fixes a typo in the Cypress integration test files for both news and questions. The word "visiable" has been corrected to "visible" in the step descriptions to improve clarity and maintain consistency throughout the test suite. No functional changes were made; this is a documentation/description update only.

Fix Typo: Correct "visiable" to "visible" in Cypress Integration Tests

---

src/common/FollowButtonAction.tsx
src/pages/common/CommentsSupabase/CommentItemSupabase.tsx

fix: hide comment thread subscribe icon

---

shared/models/profile.ts
src/test/factories/supabaseNotification.ts
src/test/models/profiles.test.ts

There's a lot going on in `NotificationDisplay.fromNotification()`. So no unit test coverage was a problem.

test: notification display unit tests

---

packages/cypress/src/integration/research/write.spec.ts
packages/cypress/src/support/commands.ts
shared/models/research.ts
src/routes/api.research.$id.updates.$updateId.ts
src/routes/api.research.$id.updates.ts
src/services/notificationSupabaseService.server.ts
src/services/notificationsCoordinationService.server.ts
src/services/notificationsService.server.ts
src/test/factories/ResearchItem.ts
src/test/factories/profile.ts
src/test/services/notificationsCoordinationService.server.ts

Previously, notifications wouldn't be sent for research updates that were initially saved as drafts, they are now - with improved unit tests.

feat: update notifications for non-drafts

---

packages/components/src/DownloadButton/DownloadButton.stories.tsx
packages/components/src/DownloadButton/DownloadButton.tsx
packages/components/src/DownloadStaticFile/DownloadStaticFile.tsx
packages/components/src/DownloadWithDonationAsk/DownloadWithDonationAsk.stories.tsx
packages/components/src/DownloadWithDonationAsk/DownloadWithDonationAsk.test.tsx
packages/components/src/DownloadWithDonationAsk/DownloadWithDonationAsk.tsx
src/common/DownloadWrapper.test.tsx
src/common/DownloadWrapper.tsx

The download count is total, but displayed in each file/link
Now it displays a total count at the bottom of the File/Link list
Closes #4332

Bug: Moving the DownloadCounter to the parent component + stories changed

---

packages/cypress/src/integration/news/write.spec.ts
src/routes/api.news.$id.ts

Atm, sometimes e2e tests are failing because a page doesn't have all the user/profile/auth information it needs after 15 seconds(!) This is worst on the news create/edit test for an unclear reason. As big profile changes are on the horizon, I'm temporarily commenting out the news test to ensure CI can pass and release.

test: temporily drop news create

---

supabase/functions/send-email/_templates/layout.tsx

For notification emails:
Service emails say: "This is a service email" instead.

feat: email footer service message or preferences

---

packages/components/src/FieldMarkdown/style.css

In the /news/create path, when tag select is open, is hidden by the rich text editor, As described in #4356
New stacking context is created in the FieldMarkdown component, preventing from hiding the selection menu. Also, keeping the sitcky functionality for the tools of the editor.
Closes #4356  …

fix: create stacking context for markdown editor

---

src/pages/Library/Content/List/LibraryListHeader.tsx
src/pages/Question/QuestionListHeader.tsx

When typing into the search box, if you type again after the initial fetch, it would overwrite your new search with the previous values. I was able to replicate by throttling the network dev tools.
Now it will keep the new type input and re-fetch as needed.
Closes #4387

fix: questions page: prevent input from resetting when typing

---

packages/components/src/ProfileBadgeContentLabel/ProfileBadgeContentLabel.stories.tsx
packages/components/src/ProfileBadgeContentLabel/ProfileBadgeContentLabel.tsx
packages/components/src/index.ts
packages/components/src/utils.ts
packages/cypress/src/integration/news/write.spec.ts
packages/cypress/src/support/commandsUi.ts
seed.ts
shared/models/news.ts
src/pages/News/Content/Common/NewsForm.tsx
src/pages/News/NewsListItem.tsx
src/pages/News/NewsPage.tsx
src/pages/News/labels.ts
src/pages/common/FormFields/ProfileBadgeField.tsx
src/routes/_.news.$slug._index.tsx
src/routes/api.news.$id.ts
src/routes/api.news.ts
src/routes/api.profile-badges.ts
src/services/newsService.server.ts
src/services/newsService.ts
src/services/profileBadgeService.ts
src/services/profileService.server.ts
src/test/factories/News.ts
supabase/migrations/20250819103736_add_badge_id_to_news.sql

Add the option on news for the content creator to limit view access of a news article to logged in users (profiles) which have the defined profile badge.
If news has a badge, it is also displayed to the corresponding users (and admins) in the list view.

feat: add badge only news

---

packages/components/src/Banner/Banner.tsx
packages/components/src/EditComment/EditComment.stories.tsx
packages/components/src/EditComment/EditComment.test.tsx
packages/components/src/EditComment/EditComment.tsx
src/pages/common/CommentsSupabase/CommentItemSupabase.tsx
src/pages/common/CommentsSupabase/CommentReplySupabase.tsx
src/pages/common/CommentsSupabase/CommentSectionSupabase.tsx
src/routes/api.discussions.$sourceId.comments.$id.ts

Currently the research discussion tests are the mostly likely to fail and have been blocking a release all day. To understand why I've added the display of comment errors which should help visibility.

feat: show errors when edit comment issue
