ONEARMY/community-platform

src/config/config.ts

last changes to production site ci pipelines and config, closes #39

remove console logs

---

src/pages/index.tsx

split router to support subdomin rendering of a single component 

---

functions/package.json
functions/src/imageConverter.ts
functions/src/index.ts
functions/yarn.lock

@chrismclarke I don't have the contents of the functions/config directory, so I can't deploy the function. Are you able to deploy this? I've fixed all linting errors so it should just deploy. Also, feel free to just send me the config on slack and I'll push and test it from here.

feat(functions): adding image converter support

---

src/utils/UserMigration/.gitignore
src/utils/UserMigration/README.md
src/utils/UserMigration/package.json
src/utils/UserMigration/src/index.ts
src/utils/UserMigration/tsconfig.json
src/utils/UserMigration/yarn.lock
src/utils/user-migration.ts

Lots of different functions to support user migration. Includes
- login component functions to crosscheck user against legacy data and attempt migration
- password validation algorithms
- separate functions to handle temporary conversion of legacy csv data to json, and import into database
closes #138

#138   user migration

---

config/enzyme.js
package.json
src/pages/Discussions/ListRow/ListRow.spec.tsx
src/pages/Discussions/ListRow/ListRow.tsx
yarn.lock

Moment.js was added in this PR: https://github.com/OneArmyWorld/onearmy/pull/231. I exchanged it for a `date-fns` implementation and added a test. @chrismclarke let me know when you add the design document and then I'll add an entry for using `date-fns` when you're doing date calculations.

Remove moment.js

---

package.json

i updated package.json in #master. please let me know whether you want the other PRs for all the other branches. My main branch is module-discussion, for which i do another PR

Updated react and types/react to 16.7

---

src/components/Dev/DevNotice.tsx
src/config/config.ts
src/pages/index.tsx

add site variant for config

---

src/utils/firebase.ts

remove custom config

---

src/pages/Discussions/PostCreate/index.tsx

missed from last pr, merging automatically

rename db to afs

---

src/pages/index.tsx

remove tools on production site

---

src/mocks/discussions.mock.tsx
src/mocks/user.mock.tsx
src/models/user.models.tsx
src/pages/SignUp/index.tsx
src/pages/common/User/Form.tsx
src/pages/common/User/Template.tsx
src/stores/User/user.store.ts
src/utils/helpers.ts
src/utils/user-migration.ts

done:
- legacy_id and legacy_registered marked as not required (I do not know if its needed for new users(?))
- creating entry in Authentication and users/<email> on submit
still todo:
- email verification (now user is automaticly logged in after sign up)
- handling error while sign up proccess (delete create entry in Authentication?)
- handle additional fieds in form (avatar, nickname itd..)
- add some tests

sign up user on form submit

---

package.json
src/pages/Discussions/PostList/List.tsx
src/pages/Discussions/PostList/ListRow/elements.js
src/pages/Discussions/PostList/ListRow/index.tsx
src/pages/Discussions/PostList/elements.js
src/pages/Discussions/PostList/fields.tsx
src/pages/Discussions/PostList/index.tsx
src/pages/Discussions/common/columns.ts
src/pages/Discussions/common/compare.ts
src/pages/Discussions/common/filters.ts
src/pages/Discussions/common/format.ts
src/pages/Discussions/common/handler.ts
src/pages/Discussions/common/index.ts
src/pages/Discussions/common/types.ts

@TODOS: 
- apply filter system
- create missing pages when clicking on certain list columns as avatar, comments, tags
- search
- integrate server paging
- default avatar

Minimal implementation with devextreme-reactive/react

---

src/pages/Howto/Content/Howto/HowtoDescription/elements.js

object-fit will do the work in any situations with with broken proportions

#361 fixed cover-image display on how-to

---

src/stores/Discussions/discussions.store.tsx

Fix discussion post save appear to be broken

---

src/pages/Home/Action.tsx

I didn't have this error before merging.. sorrry

fix actionCode type

---

README.md

Rewrote the "Why One Army" paragraph to fix grammatical errors and improve readability

Edited README.md for readability

---

CONTRIBUTING.md

Feel free to include or remove whichever bits you like. I reckon this is looking like a pretty neat introduction to Onearmy and should get people stoked and inspired to contribute 👏 🤙

Fix some typos and simplify some of the language

---

CONTRIBUTING.md

Looking forward to getting into the project! Have discovered a couple of typos in the meanwhile :)

fix spelling typos in CONTRIBUTING.md

---

src/components/Heading/index.tsx
src/components/Text/index.tsx
src/index.css
src/index.tsx
src/themes/app.globalStyle.js
src/themes/styled.theme.tsx
yarn.lock

- Define system font as main font-family
- Create Text component based on Rebass `Text` with custom size props `large`, `medium`, `small`, `superSmall`
- Extend existing `Heading` from new created `Text`component.
- remove useless index.css
Close #431

431 create text components

---

package.json
src/components/Button/index.tsx
src/components/Icons/index.tsx
src/pages/Howto/Content/HowtoList/HowtoList.tsx
src/pages/common/Header/CommunityHeader/CommunityHeader.tsx
src/pages/common/Header/CommunityHeader/elements.js
src/pages/common/Header/Header.tsx
src/pages/common/Login/Login.tsx
src/pages/index.tsx
src/themes/styled.theme.tsx
yarn.lock

* Update Navbar
* Global UI
* Create signUp Button
* Update breadcrumb
* Start using rebass grid instead of Material-UI for How-to list page

Navbar update wip remove mui

---

src/pages/Howto/Content/Howto/HowtoDescription/HowtoDescription.tsx

This PR is for [this](https://github.com/OneArmyWorld/onearmy/issues/458) Issue

Add durationSincePosted function in HowToDescription

---

src/components/FileInput/UppyConfig.ts

That's what append when you create a PR too fast 😅

fix upload file restriction

---

src/pages/Howto/Content/Howto/Howto.tsx
src/pages/Howto/Content/Howto/Step/Step.tsx
src/pages/common/Header/CommunityHeader/CommunityHeader.tsx
src/themes/styled.theme.tsx

fix padding - add top bar notice

---

src/models/howto.models.tsx
src/pages/Howto/Content/CreateHowto/CreateHowto.tsx
src/pages/Howto/Content/CreateHowto/Step/Step.tsx
src/pages/Howto/Content/Howto/HowtoDescription/HowtoDescription.tsx
src/pages/Howto/Content/Howto/Step/Step.tsx

I'll like some feedback on my code.

Image Caption Feature Added

---

src/pages/Howto/Content/Howto/Step/ImageGallery.tsx
src/pages/Howto/Content/Howto/Step/Step.tsx

Based on @tudi2d work in #534 
I added the caption and ability to navigate between multiple images in the lightbox.
Thanks for the work @tudi2d !

495 improve images display

---

src/pages/Howto/Content/Howto/Howto.tsx
src/pages/Howto/Content/HowtoList/HowtoList.tsx
src/pages/Howto/Howto.tsx
src/stores/Howto/howto.store.tsx

In howtoList, added the TagsSelect component and allow the sorting of the howtos by tags.

How to sorting by tags

---

.travis.yml

test against Nodejs 9,10,11,12 so we know issues in the next version and see if we can move from 8 to 11

Add Build matrix to CI

---

src/components/LocationSearch/LocationSearch.tsx
src/pages/Events/Content/EventsList/EventsList.tsx
src/stores/Events/events.store.tsx
src/stores/Howto/howto.store.tsx
src/stores/common/module.store.ts

* LocationSearch component to event list page to allow filtering by location (still need some UI modifications, will be done in 0.6 release)
* add method `onClear` as props to LocationSearch component to listen to onclear event on field.
close #558

558 filter events by location

---

CONTRIBUTING.md
cypress.json
cypress/integration/academy.spec.ts
cypress/integration/events.spec.ts
cypress/integration/how_to.spec.ts
cypress/integration/map.spec.ts
cypress/integration/sign-in.spec.ts
cypress/integration/sign-up.spec.ts
cypress/page-objects/academy-page.ts
cypress/page-objects/events-page.ts
cypress/page-objects/how-to-page.ts
cypress/page-objects/map-page.ts
cypress/page-objects/sign-in-page.ts
cypress/page-objects/sign-up-page.ts
cypress/page-objects/sign-up-success-page.ts
src/pages/SignUp/SignUpMessage.tsx

In response to #266,
moving cy.visit() of  page to test: So we can have in the page constructor some asserts that the page was loaded correctly 
testing sign up and sing in: the features that can not fail

testing sign up

---

cypress.json
cypress/integration/how_to.spec.ts
cypress/tsconfig.json
src/components/HowToCard/HowToCard.tsx
src/components/Tags/TagsSelect.tsx
src/pages/Howto/Content/Howto/Howto.tsx
src/pages/Howto/Content/Howto/HowtoDescription/HowtoDescription.tsx
src/pages/Howto/Content/Howto/Step/Step.tsx
src/pages/Howto/Content/HowtoList/HowtoList.tsx
yarn.lock

Added following tests for the How-to page

Added some tests for How-to page

---

.travis.yml

Cypress tests are designed to run against a dedicated testing environment, not prod/staging

Skip tests for the production deployment

---

CONTRIBUTING.md
cypress/integration/bugs.spec.ts
cypress/integration/how_to.spec.ts
cypress/support/commands.ts

- Added cy.step - make test descriptions visually clearer
- Added cy.uploadFiles - upload multiple files into <input type="field"/>

Refactored testing code

---

src/pages/common/Login/Login.tsx

fix sign-in child redirect

---

cypress/integration/sign-in.spec.ts
cypress/utils/test-utils.ts
src/pages/SignIn/SignIn.tsx

Test steps:
- Open /sign-in as an anonymous
- Click on Don't have account
- Check if the sign-up page is opened
- Click on /sign-in again
- Type correct email, password
- Click login
- Check if a user is redirected to the home page

Added tests for the Sign-in page

---

src/stores/User/user.store.ts

Fix/632   user signup confirmation email

---

package.json

Just a small fix to allow me to install packages

Fix invalid package name during "npm i"

---

cypress/integration/bugs.spec.ts
cypress/integration/how_to.spec.ts
cypress/page-objects/how-to-page.ts
cypress/support/commands.ts
src/stores/common/module.store.ts

- Fix the issue preventing recognition of duplicate how-to
- Update the how-to spec to add more helper methods (less code duplication)
- Update spec to check for duplicate how-tos
- Rewrite spec to create how-to
closes #658

Fix/658   duplicate titles how to

---

src/pages/Howto/Content/HowtoList/HowtoList.tsx

Fixes #639: wrong msg when there are no how-tos

---

src/components/Form/elements.ts

Fixes #617: remore extra button border

---

cypress/integration/bugs.spec.ts
cypress/integration/how_to.spec.ts

#665 test steps, specially expect, were not reliable because expect doesn't wait for a component to load. The solution is cy command

Fixed the build pipeline

---

src/components/ProfileModal/ProfileModal.tsx
src/pages/common/Header/Profile/Profile.tsx

Spent some time on this one figuring everything out, but it finally works hahah :joy:  
There's probably a better way to position the modal as I left it positioned absolutely with top/right pixel attributes, but I couldn't come up with one. Can be made into another issue if it malfunctions :ok_hand: 
closes #628 :tada:

Fixes #628: Updated user menu modal

---

src/pages/common/Login/Login.tsx
src/themes/styled.theme.tsx

Fixes #620: changed navbar button colors to match the mock-up

---

src/components/Tags/TagsSelect.tsx
src/pages/Events/Content/EventsList/EventsList.tsx
src/pages/Howto/Content/HowtoList/HowtoList.tsx

Fixes #615: hide event tags with zero results

---

src/components/EventCard/EventCard.tsx
src/components/Tags/TagDisplay/TagDisplay.tsx
src/components/Text/index.tsx
src/utils/helpers.ts

Fixed the date output and the styling on the tags.

667 tags overlapping

---

src/stores/Howto/howto.store.tsx

Fixes #627: sort how-tos chronologically

---

package.json
src/components/Notification/TextNotification.tsx
src/pages/Settings/SettingsPage.tsx
src/pages/Settings/Template.tsx
src/pages/Settings/content/formSections/Focus.section.tsx

closes #746 
I dissallowed focus change for now, will fix in next minor release.

746 improve form values handling

---

src/pages/PageList.tsx

Forgot to add the map to the pageList 😅

add map section to production pageList

---

cypress/integration/common.spec.ts
cypress/integration/settings.spec.ts
src/components/Form/Fields.tsx
src/stores/User/user.store.ts

Benj cypress test

---

src/stores/Maps/maps.store.ts

Fixed pin description bug

---

src/pages/Maps/Content/View/Popup.tsx

closes #697 
In order to test, substitute `heroImageUrl` with an empty string

Added fallback image

---

src/components/DevHelpers/DevHelpers.tsx
src/pages/Maps/Content/Controls/GroupingFilter.tsx
src/pages/SignIn/SignIn.tsx
src/themes/styled.theme.tsx

Small text updates, nothing much to worry about !

wording update

---

src/pages/Maps/Content/View/Cluster.tsx

Minor change to way points are clustered, remove spider map

change map zoom algorithm (less clustering)

---

src/pages/Settings/content/PostingGuidelines.tsx
src/pages/Settings/content/formSections/Focus.section.tsx

update settings guidelines text & focus section button

---

src/pages/Maps/Content/View/Cluster.tsx

Reduce cluster and display more pins. Might change back later if more pins are added.

Improved cluster

---

src/pages/Howto/Content/Howto/HowtoDescription/HowtoDescription.tsx

How-to plural dates fix

---

src/pages/Howto/Content/Howto/Step/Step.tsx

Fix padding on how-to steps' numbers

---

cypress/integration/settings.spec.ts
src/pages/Settings/SettingsPage.tsx
src/pages/Settings/content/PostingGuidelines.tsx
src/pages/Settings/content/formSections/Collection.section.tsx
src/pages/Settings/content/formSections/Expertise.section.tsx
src/pages/Settings/content/formSections/Fields/CustomCheckbox.field.tsx
src/pages/Settings/content/formSections/Fields/CustomRadio.field.tsx
src/pages/Settings/content/formSections/Fields/Link.field.tsx
src/pages/Settings/content/formSections/Fields/OpeningHoursPicker.field.tsx
src/pages/Settings/content/formSections/Focus.section.tsx
src/pages/Settings/content/formSections/Workspace.section.tsx
src/pages/Settings/content/formSections/elements.tsx
src/pages/SignIn/SignIn.tsx
src/pages/index.tsx
src/themes/styled.theme.tsx

Integration of the /settings page for mobile.
Closes #820

820 mobile settings page

---

src/pages/User/content/UserPage/UserPage.tsx
src/utils/helpers.ts

Fix profile types typography

---

src/pages/Howto/Content/Howto/Step/Step.tsx
src/pages/Howto/Content/HowtoList/HowtoList.tsx

Fix how-to typo

---

src/components/Form/Select.field.tsx
src/pages/Events/Content/EventsList/EventsList.tsx
src/pages/Howto/Content/HowtoList/HowtoList.tsx
src/pages/Maps/Content/View/index.tsx

835 fix events mobile display

---

cypress/fixtures/seed/howtos.json
cypress/integration/howto/read.spec.ts
src/pages/Maps/Content/Controls/index.tsx
src/pages/Maps/Content/View/index.tsx
src/pages/Maps/Maps.tsx

Remove hash map when closing popup

---

cypress/integration/settings.spec.ts
cypress/support/custom-assertions.ts
functions/src/Integrations/firebase-slack.ts
src/components/FileInfo/FileDetails.tsx
src/components/FileInfo/FileInfo.tsx
src/components/FileInput/FileInput.tsx
src/mocks/user_pp.mock.tsx
src/models/user.models.tsx
src/models/user_pp.models.tsx
src/pages/Howto/Content/Howto/HowtoDescription/HowtoDescription.tsx
src/pages/Howto/Content/Howto/Step/Step.tsx
src/pages/Howto/Content/HowtoList/HowtoList.tsx
src/pages/Settings/Template.tsx
src/pages/Settings/content/formSections/UserInfos.section.tsx
src/pages/User/content/UserPage/UserPage.tsx
src/pages/common/Header/Header.tsx
src/pages/common/Header/Menu/Logo/Logo.tsx
src/stores/Events/events.store.tsx
src/stores/Maps/maps.store.ts
src/utils/helpers.ts

multiples fixes, closes #845 #843 #841 #828 #776 
Also fix a bug from moderation system, to display moderation buttons on map card and events.
See commits message for descriptions

mutiple fixes

---

functions/src/Integrations/firebase-discord.ts
functions/src/config/config.ts
functions/src/index.ts

Rules for notifications are as follows:
Ready for moderation -> slack
Accepted by moderator -> discord

Added discord webhooks and updated url for pin, now referencing own map

---

src/pages/Howto/Content/Howto/Step/ImageGallery.tsx
src/pages/Howto/Content/Howto/Step/Step.tsx

798 how to

---

src/pages/PageList.tsx

remove header height in academy container

---

cypress/integration/howto/read.spec.ts
src/pages/Howto/Content/Howto/HowtoDescription/HowtoDescription.tsx

based on #905, I just added some quick styles.

895 link username to profile

---

cypress/integration/howto/read.spec.ts
src/pages/Howto/Content/Howto/HowtoDescription/HowtoDescription.tsx

Based on #906 
I added check to display edit date only if different from created & updated a few styles

894 add publication date

---

cypress/integration/howto/read.spec.ts
src/pages/Howto/Content/Howto/HowtoDescription/HowtoDescription.tsx

Add 'HowTo' publication date

---

cypress/integration/common.spec.ts
src/pages/index.tsx

Update feedback button for survey banner

comment feedback button for survey banner

---

src/stores/Howto/howto.store.tsx

filter howto list by _created field instead of _modified

---

functions/src/Integrations/firebase-discord.ts

Disable embed page in message for discord webhooks

---

src/components/Tags/TagsSelect.tsx
src/pages/Events/Content/EventsCreate/EventsCreate.tsx
src/pages/Howto/Content/Common/Howto.form.tsx
src/pages/Howto/Content/Common/HowtoStep.form.tsx

Set character limits for user input fields

---

cypress/integration/settings.spec.ts
src/pages/Howto/Content/Common/Howto.form.tsx
src/pages/Settings/SettingsPage.tsx
src/pages/Settings/content/formSections/UserInfos.section.tsx

899 slideshow profile image

---

src/pages/Settings/SettingsPage.tsx
src/pages/Settings/content/formSections/UserInfos.section.tsx

Fix a bug introduce with #930 when no cover image was uploaded, it will only add 1 cover image.

fix case for empty coverImage profile

---

src/pages/Settings/content/formSections/UserInfos.section.tsx

Mention it needs to be in english. Saves moderation mails

Change text for profile desciption

---

src/pages/Howto/Content/Common/Howto.form.tsx
src/pages/Howto/Content/Common/HowtoStep.form.tsx

939 move steps how to

---

src/stores/Howto/howto.store.tsx

retain creator howto ownership

---

src/pages/User/content/UserPage/UserPage.tsx

PR Type
PR Checklist
Swap order of flag and username in the user profile.
_Closes #973_

973 display flag before username in user profile

---

src/pages/Settings/content/formSections/Fields/Link.field.tsx

PR Type
PR Checklist
Format link on blur to lower case in the user settings.
Closes #986

Format link in user settings to lower case

---

src/components/VirtualizedFlex/VirtualizedFlex.tsx
src/pages/Howto/Content/Howto/HowtoDescription/HowtoDescription.tsx
src/utils/helpers.ts

PR Type
PR Checklist
Fix display of icons in HowTo on mobile screens.
Closes #967

Algin icons vertical on mobile

---

.travis.yml
functions/package.json
src/pages/Events/Events.tsx
src/pages/Home/Home.tsx
src/pages/Howto/Howto.tsx
src/pages/Maps/Content/View/Cluster.tsx
src/pages/Maps/Maps.tsx
src/pages/admin/Admin.tsx

PR Type
PR Checklist
Reverts #1010 to fix the deployment
Closes #1011

Revert deployment to last commit

---

src/pages/Howto/Content/Common/FormSettings.tsx

PR Type
PR Checklist
Adds the following additional time options to the how-to form
- < 1 hour
- < 5 hours
- < 10 hours
- < 1 day
Closes #1023

feat: Adds more time options to how-to form

---

src/components/HowToCard/HowToCard.tsx
src/components/Icons/FlagIcon/FlagIcon.tsx
src/pages/Howto/Content/Howto/HowtoDescription/HowtoDescription.tsx

PR Type
PR Checklist
Improve styling of howto flags

Fix style of HowTo flags

---

functions/src/Integrations/user-stats.ts

fix type & lint errors in user-stats.ts

---

functions/src/Integrations/user-stats.ts

PR Type
PR Checklist
Previous user stats algorithm was inefficent and would lead to unpredicted result due to being based on promisses, when querySnapshot already have *size* property.
To identify if full stats computation was needed user.stats was used instead of user.data().stats leading to inefficiently computing all stats every time.

Feat/974 Improve stats computation efficiency

---

community-platform.iml
debug.log
src/pages/Howto/Content/Howto/Howto.tsx
src/pages/SignIn/SignIn.tsx

PR Type
PR Checklist
Closes #676
Closes #651

#676 Received a broken How-to page #651 sign-in page accessible to logged-in users

---

src/pages/User/content/UserPage/ProfileLink.tsx
src/pages/User/content/UserPage/UserPage.tsx

PR Type
PR Checklist
Show social media icon on profile page
Closes #1062

Fix social media icon on profile page

---

src/pages/Maps/Content/Controls/index.tsx

PR Type
PR Checklist
Enable Following "My pin" link on map
Closes #1048

Fix "My pin" link on map

---

src/pages/Maps/Content/View/Popup.tsx

PR Type
PR Checklist
_Closes #796_

#796 Map profile card issues

---

functions/src/userUpdates/index.ts

PR Type
PR Checklist
- Minor update to change order backend functions backup user
_Closes #_

Minor fix to user backup function

---

src/pages/Settings/content/PostingGuidelines.tsx
src/pages/Settings/content/formSections/MapPin.section.tsx

PR Type
PR Checklist
Text edits to the profile page to comply with Community Program
Closes #1121

#1121 Change Profile tips 

---

src/pages/Settings/content/formSections/MapPin.section.tsx

for issue https://github.com/ONEARMY/community-platform/issues/1122
PR Type
PR Checklist
Add notification in profile settings for verification program
_Closes #1122

Added notification

---

src/pages/Research/Content/Common/Update.form.tsx
src/pages/Settings/content/formSections/MapPin.section.tsx

PR Type
PR Checklist
- Change Url for Community program in profile
- Increase text length for research module

Change Url + text length

---

src/components/FileInput/UppyConfig.ts

PR Type
PR Checklist
Increase max upload file size from 5MB to 50MB
_Closes #_

increase max upload file size (5MB -> 50MB)

---

.github/pull_request_template.md
scripts/maintenance/reset-staging-site.ts

PR Type
PR Checklist
_Closes #_

add stats to staging site reset

---

src/components/Auth/AuthWrapper.tsx
src/pages/Events/Events.tsx
src/pages/Howto/Howto.tsx
src/pages/Research/index.tsx
src/pages/Research/research.routes.tsx
src/pages/admin/Admin.tsx
src/pages/common/AuthRoute.tsx
src/pages/common/Header/Menu/MenuDesktop.tsx
src/pages/common/Header/Menu/MenuMobile/MenuMobilePanel.tsx

PR Checklist
PR Type
- Remove auth restrictions when developing locally
- Simplify auth-route component to use existing auth-wrapper component
- Remove redirect paths (now that auth route deny shows message instead of redirect)
- Add auth beta tester restrictions to all research paths
- Tidy header and mobile menu bars to use existing auth wrappers
Closes #
---
If you need more immediate feedback you can try reaching out on slack …

Refactor auth routing

---

.travis.yml

PR Checklist
PR Type
- Fix travis file watch limit bug
- Remove travis tests for PRs (now handled by circle-ci)
Closes #
---

Travis ci fixes

---

package.json
src/components/Avatar/index.tsx
src/components/Comment/Comment.tsx
src/components/Comment/CommentHeader.tsx
src/components/Comment/CommentTextArea.tsx
src/components/Comment/EnterComment.tsx
src/pages/Howto/Content/Howto/HowToComments/HowToComments.tsx
src/pages/Howto/Content/Howto/Howto.tsx
yarn.lock

PR Checklist
PR Type
**This is still WIP & will update. Let me know, if you have suggestions**
Add the components & UI for viewing & creating comments for HowTos.
Closes #1127
Design

WIP: Comments UI & components

---

functions/src/userUpdates/index.ts
src/models/howto.models.tsx
src/pages/Howto/Content/Howto/Comment/Comment.tsx
src/pages/Howto/Content/Howto/Howto.tsx
src/stores/Howto/howto.store.tsx

PR Checklist
PR Type
Adding the back-end for comments. Howto's get a new `comments` property, which is an optional array of comments. Each comment has a unique ID, creation timestamp, user ID, user display name, user country flag, and the text.
The howto store gets the `addComment`, `editComment` and `deleteComment` methods. 
The front-end part is setup and ready for work so hopefully @tudi2d can start to work on it as soon as this gets merged (I'll be available on Slack if anything is needed).
Closes #1128

Comments backend

---

BOUNTIES.md
CONTRIBUTING.md

PR Checklist
Add a docs page to outline the bounty system and link from the contributing guidelines

Add bounty docs

---

src/pages/PageList.tsx
src/pages/Research/Content/ResearchList.tsx
src/pages/Research/index.tsx
src/pages/Research/research.routes.tsx
src/stores/Research/research.store.tsx

PR Checklist
PR Type
Allow people to share research pages for public view, by making the main research list and detail pages publically viewable (without a link in the menu). Keep authoring options (create/edit) as beta-tester only
Closes #
---

Add public view for research module (anyone can view, beta-testers can author)

---

functions/package.json
functions/src/exports/api.ts
package.json
yarn.lock

PR Checklist
PR Type
Minor fix for recent update config used for API in backend functions
Closes #
---

deprecate body-parser in api function

---

src/pages/Howto/Content/Howto/HowtoDescription/HowtoDescription.tsx

PR Checklist
PR Type
The image in the how-to will show full div. This will remove the white space on the bottom and make it look pretty 💫

Full div image in how-to introduction

---

src/components/Comment/CommentTextArea.tsx
src/pages/Howto/Content/Howto/HowToComments/HowToComments.tsx
src/stores/Howto/howto.store.tsx

PR Type
PR Checklist
Add a comment by pressing the "Comment" button. Replaces the submit on enter behaviour.
Closes #1170

Add comment button

---

package.json
src/components/Animations/FadeInOut.tsx
src/pages/Howto/Content/Common/Howto.form.tsx
src/pages/common/Header/Header.tsx
yarn.lock

PR Checklist
PR Type
This PR replaces all instances of react-pose, a [deprecated](https://popmotion.io/blog/20200115-pose-is-deprecated/) animation library for a library called framer-motion.
Closes #724

#724 Update react-pose(deprecated) to framer-motion

---

src/components/Auth/AuthWrapper.tsx
src/components/Comment/Comment.tsx
src/components/DevSiteHeader/DevSiteHeader.tsx
src/config/config.ts
src/pages/Howto/Content/Howto/HowToComments/HowToComments.tsx
src/pages/Howto/Content/Howto/Howto.tsx
src/pages/admin/content/AdminBetaTesters.tsx

PR Checklist
PR Type
- Add dev site override so developers can test different user auth roles (e.g admin, beta-tester)
- Update howto comments system so that comments can be seen by all but only created by beta-testers
Closes #
https://user-images.githubusercontent.com/10515065/126243181-eb1fb510-fba2-4e6b-8385-64ad76632dd5.mp4

Add auth system local overrides and comments auth

---

package.json

PR Checklist
PR Type
- Simple app version update to be merged directly into `production` branch so that service worker will update with new config variables that fix a broken URL for uploads.
Closes #
---

Hotfix - upload urls

---

.github/workflows/pr-preview.yml
package.json

PR Checklist
- bump version
Closes #
---

prepare release (1.6.0)

---

package.json

PR Checklist
PR Type
CI Pipeline has wrong analytics code, so need to bump version here to create new build in circle-ci with correct code
Closes #
---

Fix analytics code

---

CODE_OF_CONDUCT.md
CONTRIBUTING.md

PR Checklist
PR Type
Closes #
---

Updated ".world" appended emails in the CONTRIBUTING and CODE_OF_CONDUCT guides

---

.github/pr-labeler.config.yml
.github/workflows/docs-deploy.yml
packages/documentation/docusaurus.config.js
packages/documentation/package.json
packages/documentation/yarn.lock

PR Checklist
PR Type
We currently have various bits of in-progress development documentation saved in the repo. This PR adds scripts to allow us to deploy to github pages in preparation for sharing with developers more generally.
Closes #
---

Add developer docs deployment

---

.github/pr-labeler.config.yml
.github/workflows/docs-deploy.yml
.github/workflows/pr-labeler.yml
packages/documentation/docs/Contributing/bounties.md
packages/documentation/docs/Contributing/docs-contribution.md
packages/documentation/docs/Contributing/intro.md
packages/documentation/docs/Contributing/maintainer.md
packages/documentation/docs/Docs Contribution/md-style-guide.md
packages/documentation/docs/Docs Contribution/running-docs-locally.md
packages/documentation/docs/Frontend Development/overview.md
packages/documentation/docs/Getting Started/recommended-tools.md
packages/documentation/docs/Getting Started/setup.md
packages/documentation/docusaurus.config.gh-pages.js
packages/documentation/docusaurus.config.js
packages/documentation/sidebars.js

PR Checklist
PR Type
- Add various bits of developer documentation
- Add config to support deployment to github pages
Closes #
---

Update developer documentation

---

packages/documentation/docs/Docs Contribution/running-docs-locally.md
packages/documentation/docusaurus.config.gh-pages.js
packages/documentation/docusaurus.config.js

PR Checklist
PR Type
Updates documentation microsite to:
* Include a link through Discord
* Corrects yarn cmd to kick off docusaurus locally 🦖

docs: add discord server link and fix server start command

---

src/components/Comment/Comment.tsx
src/components/ImageInput/ImageConverter.tsx

PR Checklist
PR Type
Cleans up a few linter violations which were generating warning output. This PR is not expected to cause any functional changes.
**Before**
```bash
Compiled with warnings.
src/components/Comment/Comment.tsx
Line 23:9:  'user' is assigned a value but never used  @typescript-eslint/no-unused-vars
src/components/ImageInput/ImageConverter.tsx
Line 109:11:  'ICompressionOptions' is defined but never used  @typescript-eslint/no-unused-vars
```
**After**
```bash
Compiled successfully!
```
---
If the PR is working as intended it'll be merged and included in the next platform release, if not changes will be requested and re-reviewed once …

chore: clean up warning output from eslint

---

README.md

PR Checklist
PR Type
Update readme to include quicklinks section for onearmy.earth, pp community platform, dev docs and contributing guide 
Closes #
---

Add quicklinks section to readme

---

CONTRIBUTING.md
README.md

PR Checklist
PR Type
- Fix build status badge (for circleci instead of travis)
- Add general git info and discord badges
- Move tech stack badges to contributing
Closes #
**Main Readme Badges**
**Contributing Guide Badges**
---

Docs badges update

---

.circleci/config.yml

PR Checklist
PR Type
*work-in-progress* Throwing stuff at Circle CI until something sticks ;) 
References: 
* https://stackoverflow.com/questions/44046366/increase-javascript-heap-size-in-create-react-app-project

chore: stablise CircleCI builds

---

package.json
yarn.lock

PR Checklist
PR Type
Thanks to the report from @tiefpunkt, this PR introduces the `eslint` as an explicit dev dependency rather than making the assumption has the tool installed on their machine.

chore: adds missing eslint dep

---

.gitpod.yml
README.md

PR Checklist
PR Type
The idea is ephemeral development workspaces in the cloud. I thought I'd try it out and see how it worked :slightly_smiling_face:
A few simple steps:
1. Click the Gitpod: Ready-to-code  link in the README.md
2. Probably sign in/authorize with auth provider of your choice
3. It will spin up a new workspace and run the development server
Get to work.

feat: adds gitpod config

---

.eslintignore

PR Checklist
PR Type
eslint was failing due to more than 500 errors and 7.000
warnings. All of these were coming due to compiled
storybook assets.
Ignoring this directory gets the project back in a healthy
place 🧘
This has no impact on the platform software and is a developer
experience only change.

chore: ignore storybook static assets in eslint

---

.circleci/config.yml
src/pages/Howto/Content/Common/Howto.form.test.tsx

PR Checklist
PR Type
Adds the unit tests so that they are run as part of the CI pipeline, there aren't many of them yet but at least running them here improves visibility of them. Next steps for a separate PR:
1. Add documentation around unit testing
2. Introduce tests to another area of the code base to see what's missing from the testing infrastructure to make it easy to work with.

test: adds unit tests to CI pipeline

---

SECURITY.md
packages/documentation/docs/Security.md
packages/documentation/sidebars.js

PR Checklist
PR Type
Introduces a SECURITY.md file to align with community convention on GitHub.
~Could someone confirm an email address we can use for these reports?~

chore: adds SECURITY.md

---

CONTRIBUTING.md

PR Checklist
PR Type
Tidy up line spacing.
Switch to using titles of remote pages
as the body of the link text, making it
easier to understand the document content.
This change only affects people viewing the GitHub repository.

docs: adjust formatting of resources list

---

packages/documentation/docs/Environmental Impact/environmental-impact.md
packages/documentation/sidebars.js

PR Checklist
PR Type
Moves the documentation from the wiki into the new docs platform.  No other changes being made at this point in time.

docs: migrates environmental impact doc from wiki

---

.circleci/config.yml
.firebaserc

PR Checklist
PR Type
**Aim:** Set up automated deployments to the development instance of https://dev.community.projectkamp.com. This will happen automatically for any changes merged into the `master` branch. This change introduces an additional deployment target into the CircleCI configuration. 
This will _not_ affect any existing deployment pipelines.

chore: adds deployment job for projectkamp instance

---

.circleci/config.yml

PR Checklist
PR Type
Prevent running e2e on production branch.

chore: skip e2e on production

---

.circleci/config.yml

PR Checklist
PR Type
In this following commit we removed e2e tests from the
production deployment as they would be rerunning against the same
code which went through tests as part of `master` branch
https://github.com/ONEARMY/community-platform/commit/0bb9d9fce6b3e10c74ae09ec65ff0e9874a2061c
During this change we missed that the e2e tests were a requirement
for our deployment pipeline to run.

fix: dependency chain for production release

---

firebase.storage.rules

PR Checklist
PR Type
Addresses an issue where logged out users were not able to load image files from fire storage. This change has already been made in the production Firebase project. To avoid a regression the next time we trigger a Release this is being committed into the project.

fix: correct read permissions

---

.circleci/config.yml

PR Checklist
PR Type
Increases Resource class in CircleCI to address memory issues affecting build step.

chore: increase CircleCI resource class

---

.circleci/config.yml
.firebaserc

PR Checklist
PR Type
Extends the CI pipeline so that it deploys to the Project Kamp production instance as well as community.preciousplastic.com each time we make a Release.

chore: adds project kamp production target

---

.github/pull_request_template.md

docs: extend pr template to include developer experience option

---

.circleci/config.yml

PR Checklist
PR Type
Similar to our e2e tests, we don't want to run these again on `production` as the code will be the same as what was in `master`,

chore: skip unit tests on the production branch

---

.circleci/config.yml

PR Checklist
PR Type
Closes #
---

chore: add debug output

---

src/common/errors.ts
src/stores/User/user.store.ts

PR Checklist
PR Type
The Sentry alert that is triggered as a result
of this log is not actionable nor does
anyone seem to concerned about. So we should
probably remove it ¯\_(ツ)_/¯

fix: remove unhelpful logging

---

package.json

PR Checklist
PR Type
Bump version for production release
Closes #
---

chore: update version (1.6.2)

---

package.json
src/common/ErrorBoundary.tsx
yarn.lock

PR Checklist
PR Type
Change had meant to include with review for #1246 to revert changes to sentry. Will merge now to fix master build
Closes #
---

chore: revert back sentry/browser to sentry/react

---

.github/pull_request_template.md
packages/documentation/docs/Security.md

PR Checklist
PR Type
Applies automated formatting to markdown files. This is available with the command `yarn format`

chore: apply formatting

---

.circleci/config.yml
.env
src/modules/index.test.ts
src/modules/index.ts
src/pages/PageList.tsx
src/pages/Research/index.tsx
src/pages/common/Header/Header.tsx
src/pages/common/Header/Menu/MenuDesktop.tsx
src/pages/common/Header/Menu/MenuMobile/MenuMobilePanel.tsx
src/pages/index.tsx

PR Checklist
PR Type
Introduces a mechanism for selectively loading modules based on environmental variables. This can be done with a comma separated list of modules defined on the `REACT_APP_SUPPORTED_MODULES` environment variable.
This check takes priority over any role based permission checks. 
The available modules are defined as:
```ts
export enum MODULE {
CORE = 'core', // This is enabled on all installations
HOWTO = 'howto',
MAP = 'map',
EVENTS = 'events',
RESEARCH = 'research',
ACADEMY = 'academy',
USER = 'user',
}
```

feat: conditional module loading

---

.github/workflows/pr-preview.yml

PR Checklist
PR Type
Updates the GitHub workflow which deploys a preview version of the site so that it uses the same version of Node as our core project. This is part of an investigation into failing tests affecting this PR:
https://github.com/ONEARMY/community-platform/pull/1300

chore: switch to align with project node-version

---

.env
.gitignore
package.json
scripts/package.json
scripts/prepare-public-directory.ts
src/templates/index.html.mst
src/templates/manifest.json.mst
yarn.lock

PR Checklist
PR Type
This change introduces a build step that will build HTML using ENV variables. This allows us to add a custom title and description for the separate instances. This is important to ensure the search engine results pages show helpful content.
This step happens first, **outside** of the existing Create React App lifecycle.
Extracted from #1255

feat: generate HTML wrapper based on ENV vars

---

.circleci/config.yml

PR Checklist
PR Type
Use `CIRCLE_SHA1` from the provided environmental variables
https://circleci.com/docs/2.0/env-vars/#built-in-environment-variables
This is a follow up to https://github.com/ONEARMY/community-platform/pull/1293 as it doesn't seem to be working correctly.

chore: switch to use CircleCI provided var

---

.circleci/config.yml

PR Checklist
PR Type
The e2e suite has already run on the code
when the changes were merged into the
master branch. Merging to production
should only perform the deployment task.

test: remove e2e from production workflow

---

src/modules/index.test.ts
src/modules/index.ts

PR Checklist
PR Type
Closes #
---

fix: default all modules to enabled

---

src/pages/Settings/SettingsPage.tsx

PR Checklist
PR Type
The User Profile section has quite a lot of information
which is tied to specifics of the original Precious Plastic
deployment. The change here is a quick fix rather than
a long term solution.
Ideally the concept of user focus' can be removed from the
code and made into an extensible object either in configuration
or a database.

fix: hide user profile section

---

functions/package.json

PR Checklist
PR Type
Closes #
---

fix: broken functions build

---

src/components/ImageGallery/index.tsx

PR Checklist
PR Type
Adds in a explicit import for the CSS styles of this 3rd party library.

fix: lightbox styles not loading

---

src/themes/project-kamp/index.ts

fix: academy url for projectkamp

---

src/components/Avatar/index.tsx
src/pages/User/workspace/Workspace.test.ts
src/pages/User/workspace/Workspace.tsx

PR Checklist
PR Type
Correctly load "clean" image _only_ for small instances of the avatar component.

fix: badge url for larger avatar

---

src/components/ExternalEmbed/ExternalEmbed.tsx
src/pages/Academy/Academy.test.tsx
src/pages/Academy/Academy.tsx
src/themes/project-kamp/index.ts

PR Checklist
PR Type
* Correct base path for Project Kamp academy instance
* Improve path parsing

fix: academy URL for project kamp

---

src/pages/User/content/UserPage/UserPage.tsx
src/themes/app.globalStyles.ts

PR Checklist
PR Type
Corrects position of slideshow arrows for Profile page

fix: user page slideshow arrows

---

public/index.html
scripts/post-cra-build.ts

PR Checklist
PR Type
Adds a custom description used by Search engines and social networks when sharing links to the site.

feat: introduce customised description

---

.circleci/config.yml

docs: include production url in circle CI job name

---

src/pages/Howto/Content/Common/Howto.form.tsx
src/pages/Howto/Content/Common/HowtoStep.form.tsx
src/pages/Howto/constants.ts

PR Checklist
PR Type
Increases the number of characters that can be provided for the initial description and individual steps of a Howto article. 
Originally raised as part of:
https://feedback.preciousplastic.com/suggestions/202757/longer-character-limit-for-howto-steps

feat: increase supported length of text

---

.circleci/config.yml

PR Checklist
PR Type
The unit tests are very quick but reliable
if they fail we do not have a candidate which
can progress to our slower and more expensive
e2e test suite.
The main benefit of this change is to save spending
CircleCI credits running e2e tests.

test: require Unit tests for e2e

---

src/pages/Research/research.routes.test.tsx

PR Checklist
PR Type
This test has been flaking a little bit in Circle
recently. Looking at the resource usage the small
Docker resource is running at 100% CPU. We have
also been introducing _more_ unit tests into the
platform.
This is an experiment to see if this stabilises
the tests, but it may be we need to consider either:
* Increasing the resource for running tests
* Dig into jest configuration inherited from create
react app to identify optimisations.

test: increase timeout

---

.circleci/config.yml

test: correct sha ref in circle CI

---

src/components/LocationSearch/LocationSearch.tsx
src/pages/Events/Content/EventsList/EventsList.tsx
src/pages/Maps/Content/Controls/index.tsx
src/pages/Settings/content/formSections/MapPin.section.tsx

PR Checklist
PR Type
We are looking to better understand how users
are interacting with Location Search so that
we can understand how best to move forward
with finding a replacement for Algolia Places.
Ref: https://github.com/ONEARMY/community-platform/issues/1177

feat: introduce GA event tracking event around location search

---

src/components/ExternalEmbed/ExternalEmbed.tsx

fix: URL rewriting for Academy content

---

packages/cypress/src/integration/settings.spec.ts
src/mocks/Selectors.tsx

PR Checklist
PR Type
The old forums are hard to find and Discord profile links are equally hard to find.

feat: drop discord and forum as contact method

---

src/stores/Maps/filter.test.ts
src/stores/Maps/filter.ts
src/stores/Maps/maps.store.ts

fix: ignore deleted in filter counts

---

src/pages/User/content/UserPage/UserPage.tsx

fix: do not display discord or forum links

---

packages/cypress/package.json
yarn.lock

PR Checklist
PR Type
Bumps Cypress up to the latest version, full changelog available here:
https://docs.cypress.io/guides/references/changelog#9-0-0
If we trust our test suite then everything looks ✅

test: upgrade cypress to 9.2.0

---

src/pages/User/content/UserPage/UserPage.tsx

PR Checklist
PR Type
Non discord/forum links will now show in the user profile

fix: incorrect filtering of social links

---

src/pages/Settings/SettingsPage.tsx

PR Checklist
PR Type
The map pin only make sense if the Map
module is available on the current installation.
Closes #1381

fix: do not show mappin in user profile

---

packages/cypress/src/integration/howto/read.spec.ts
packages/cypress/src/integration/sign-in.spec.ts
packages/cypress/src/utils/test-utils.ts
src/components/Comment/CommentTextArea.tsx
src/pages/Howto/Content/Howto/HowToComments/HowToComments.tsx

PR Checklist
PR Type
Comments are now available on How To articles for any logged in user of the site. This feature has been available for a little while to users with the `beta-tester` role.

feat: release comments to all users

---

src/components/Comment/Comment.tsx
src/pages/Howto/Content/Howto/HowToComments/HowToComments.tsx

PR Checklist
PR Type
Introduces [Google Analytics events](https://developers.google.com/analytics/devguides/collection/analyticsjs/events) to track key interactions with the Comments feature.

feat: track interaction with comment events

---

src/pages/Research/research.routes.test.tsx

PR Checklist
PR Type
Closes #
---

test: increase timeout due to slow ci resource

---

packages/cypress/src/integration/howto/read.spec.ts

PR Checklist
PR Type
Relax assertations around comment test.

test: relax assertations

---

src/pages/Events/Content/EventsList/EventsList.tsx
src/pages/Research/Content/ResearchList.tsx

fix: consistent vertical padding for section heading

---

src/components/SiteFooter/SiteFooter.tsx
src/pages/Research/Content/Common/Research.form.tsx

PR Checklist
PR Type
Closes #
---

Small edits - Increase character limit research and change URL footer

---

.github/workflows/merge-to-production.yml

chore: label automatically generated PRs

---

functions/src/dev/index.ts
functions/src/index.ts

PR Checklist
PR Type
The dev API is a set of hacky/temporary functions used for working with local emulator. As they are not intended for use in production commenting out until we have better means of separating. 
Closes #
---

chore: BREAKING CHANGE remove dev api

---

packages/documentation/docs/Install.md

Documentation around Firebase configuration required to deploy new instance

📚 docs: deploying a new instance

---

.circleci/config.yml
.releaserc.json
package.json
yarn.lock

PR Checklist
PR Type
Automatically generate GitHub releases and Changelog each time code is successfully deployed to the production environment.

chore: automated release notes

---

.circleci/config.yml

chore(ci): reduce resources for linting step

---

commitlint.format.ts

PR Checklist
PR Type
Before: 
```
✖   type may not be empty
```
After: 
```
Initial commit
✖   type may not be empty
```

chore: commit lint error messages

---

.circleci/config.yml

PR Checklist
PR Type
Closes #
---

chore(ci): reduce overhead for release job

---

src/pages/Settings/content/formSections/AccountSettings.section.tsx
src/pages/Settings/content/formSections/ChangeEmail.form.tsx
src/stores/User/user.store.ts

PR Checklist
PR Type
added email change functionality
#1414 
https://user-images.githubusercontent.com/42969746/151713218-7ab6c025-f288-4ce0-bc91-bdd0624cada9.mp4
---

feat: change email functionality

---

.circleci/config.yml
functions/package.json
tsconfig.src-types.json
yarn.lock

PR Checklist
PR Type
Addresses an issue introduced from updating Typescript. Also adds a CI check to catch this before merging to `master`

chore(ci): adds job to build functions

---

src/pages/Maps/Content/Controls/GroupingFilterDesktop.tsx

PR Checklist
PR Type
Fix scroll bar style for grouping filter desktop component
Closes #1436
---

style: update grouping filter desktop overlow

---

src/pages/Research/Content/Common/Research.form.tsx

Increase the max length of characters for a research introduction. 
PR Checklist
PR Type

feat: increases max length for a Research introduction

---

package.json
src/components/FileInput/FileInput.tsx
src/components/FileInput/UppyConfig.ts
yarn.lock

PR Checklist
PR Type
We use uppy to handle file picker during howto upload. The version we are using is quite outdated, and [throws various errors](https://app.circleci.com/pipelines/github/ONEARMY/community-platform/1302/workflows/dd62746d-054e-400a-9261-01984b6b5252/jobs/6235) when trying to install (uses version of preact that seems to have issues with other platform deps)
Includes a few code updates to handle [uppy breaking changes](https://github.com/transloadit/uppy/blob/main/CHANGELOG.md#%EF%B8%8F-breaking-changes)
Closes #
Updated uploader working when testing locally
https://user-images.githubusercontent.com/10515065/152082014-b3264f0c-42d5-4a28-a947-89c10f130bc1.mp4
Uppy as source of errors seen
---
Thanks for the contribution! We try to make sure all PRs are reviewed ahead of a …

chore: update uppy 1 to 2

---

packages/documentation/docs/Frontend Development/modules.md
packages/documentation/sidebars.js

PR Checklist
PR Type
Provides documentation to outline steps required to add new modules to the platform.
This follows pr proposed in #1394 to add a new testing module, which in turn was intended to facilitate testing code from #1393
Closes #1394
---

docs: add frontend module docs

---

.circleci/config.yml

PR Checklist
PR Type
Closes #
---

chore(ci): reinstate commit linting

---

.circleci/config.yml

PR Checklist
PR Type
Closes #
---

chore(ci): remove lint commits from production

---

.circleci/config.yml

PR Checklist
PR Type
The ability to validate the serverless functions build
is now covered under the 'Cloud Function tests' job

chore(ci): remove duplicate check functions job

---

package.json

PR Checklist
PR Type
The CI pipeline will lint commits to ccheck for well formatted
messages. At the time of writing these commits are being automatically
lifted into generating our release notes.

chore: add script to make linting commits easier

---

.eslintrc.json
src/stores/databaseV2/AbstractDatabase.ts
src/stores/databaseV2/CollectionReference.tsx
src/stores/databaseV2/DocReference.tsx
src/stores/databaseV2/clients/dexie.tsx
src/stores/databaseV2/clients/firestore.tsx
src/stores/databaseV2/clients/rtdb.tsx
src/stores/databaseV2/index.tsx
src/stores/databaseV2/types/AbstractDBClient.ts
src/stores/databaseV2/types/index.d.ts

PR Checklist
PR Type
* Adds an eslint rule to check for this behaviour
* Switch to interface for `AbstractDBClient` which better reflects
its usage
* Refactor AbstractDatabase to align with Abstract class conventions

chore: move classes into their own files

---

CONTRIBUTING.md
packages/documentation/docs/Install.md

PR Checklist
PR Type
Applies automated formatting to all of our Markdown files using `prettier`, this is a precursor to adding automated linting to our codebase.

chore(docs): format markdown

---

README.md

After 2 years it's time to go @BenGamma. You go out there in the world and farm the best vegetables you can.
PR Checklist
PR Type
Update Readme

docs:  update readme with luke 🍉

---

functions/src/models.ts
functions/src/stats/index.ts
src/models/howto.models.tsx
src/pages/Howto/Content/Howto/Howto.tsx
src/pages/Howto/Content/Howto/HowtoDescription/HowtoDescription.tsx
src/pages/Howto/Content/Howto/HowtoDescription/HowtoUsefulStats.tsx
src/pages/Howto/Content/HowtoList/HowToCard.tsx
src/pages/Howto/Content/HowtoList/HowtoList.tsx
src/stores/Howto/howto.store.tsx
src/stores/User/user.store.ts

Author: danitrod <danitrod@outlook.com>
PR Checklist
PR Type
Rebase of #1204 to fix commit lint
Review changes:
- add howto stats aggregation bindings
- replace previous howto stats with aggregation
This throws out most of the old system for collating total counters as now handled by more general aggregations method (and the counts seemed to be drifting off wildly - worst case I could see one howto with 32 upvotes from 6 users)
A couple minor caveats/notes
- The counter would appear on top of tags in cases where the tags overflowed, and so I've wrapped the tags to spread across multiple lines instead. This means some howtos are longer than others
- When liking a howto there is a delay before the aggregation is updated on the server (usually 1-2s), and also the update is not reflected on …

feat: add useful count to howto card

---

.circleci/config.yml

chore(ci): inject SHA at appropriate step

---

src/components/DiscordLink/DiscordLink.tsx

Closes #1498
PR Checklist
PR Type
Closes #1498
Before:
After:

fix: remove #feedback from global Discord link

---

src/pages/User/content/MemberProfile.tsx

PR Checklist
PR Type
**Before:**  
**After:**

fix: ensure consistent column size for member profile

---

src/components/Comment/Comment.tsx
src/models/research.models.tsx
src/pages/Howto/Content/Howto/HowToComments/HowToComments.tsx
src/pages/Research/Content/ResearchComments/ResearchComments.tsx
src/pages/Research/Content/Update.tsx
src/stores/Research/research.store.tsx

PR Checklist
PR Type
Closes https://github.com/ONEARMY/community-platform/issues/1363
---

feat: add comments to research module

---

src/pages/Howto/Content/HowtoList/HowtoList.tsx
src/stores/Aggregations/aggregations.store.tsx
src/stores/User/user.store.ts
src/stores/common/module.store.ts
src/stores/index.tsx

PR Checklist
PR Type
Creates a common aggregations store that can be used to populate aggregation data (previously required explicit db calls)
The methods try to safeguard against multiple subscriptions being called against the same aggregation endpoint, and also try to find a balance between keeping aggregation data fresh (subscribing to specific endpoints and streaming updates) vs leaving open longer than necessary (excessive requests and memory leaks).
This improves on previous implementation by:
- Avoiding direct db calls from components/stores
- Reducing number of calls made to keep data fresh (e.g. component mount hook)
- Correctly update data in cases where function side-effects take time (e.g. going back to howto list after vote, but before vote count updated)
Closes #
_If useful, …

Feat: aggregations store

---

.circleci/config.yml

chore(ci): remove ON HOLD notification

---

firebase.json

fix: adjust glob for static js files

---

src/components/Comment/Comment.tsx
src/components/CommentList/CommentList.tsx
src/components/FormEditComment/FormEditComment.tsx
src/pages/Howto/Content/Howto/HowToComments/HowToComments.tsx
src/pages/Research/Content/ResearchComments/ResearchComments.tsx

PR Checklist
PR Type
Switching out the custom edit/delete buttons to use standard `Button` components from the UI library. 
Before:
After:
Additionally, refactor implementation of Howto and Research to share a common CommentList component between both location. No functional changes anticipated as part of this.

fix: refactor comment component

---

package.json
packages/components/package.json
packages/components/src/Icon/Icon.tsx
yarn.lock

PR Checklist
PR Type
The last PR we raised to make this change ultimately broke the `Cloud Tests` CI job for reasons which are not immediately obvious. This is an attempt to re-apply that change. 
* [Original PR #1547](https://github.com/ONEARMY/community-platform/pull/1547/files)
* [A broken build](https://app.circleci.com/pipelines/github/ONEARMY/community-platform/1683/workflows/6c4fc148-2cf7-4e7d-a2f3-73d929b23514/jobs/8863) on our default branch after #1547 was merged.

chore: reduce react icons size (again)

---

.releaserc.json

chore(ci): skip v2 release

---

package.json
yarn.lock

chore: deps ugprade commitlint

---

.circleci/config.yml

chore: enable github releases

---

yarn.lock

chore(deps): update caniuse

---

packages/documentation/yarn.lock

chore(docs): relock dependencies

---

src/pages/User/content/MemberProfile.tsx
src/pages/User/content/SpaceProfile.tsx

PR Checklist
PR Type
Add username to profiles
Closes #1407

feat: add username to profiles

---

packages/documentation/docs/Install.md

docs: clarify setup steps and order for new Platform deployment

---

.yarnrc.yml

PR Checklist
PR Type
Replaces https://github.com/ONEARMY/community-platform/pull/1569

chore: suppress unactionable log messages

---

src/pages/Research/Content/ResearchArticle.tsx
src/pages/Research/Content/ResearchComments/ResearchComments.tsx
src/pages/Research/Content/ResearchUpdate.tsx
src/pages/Research/research.routes.tsx

PR Checklist
PR Type
Fixes a layout issue within ResearchComments
Before:
After:

chore: rename individual Research article component

---

src/pages/Research/Content/ResearchUpdate.tsx

feat: make research comments available to all users

---

src/pages/common/Header/Menu/Profile/Profile.tsx

PR Checklist
PR Type
Before:  
After:

fix: alignment of user badge

---

src/models/research.models.tsx
src/pages/Research/Content/ResearchArticle.tsx
src/pages/Research/Content/ResearchDescription.tsx
src/stores/Howto/howto.store.tsx
src/stores/Research/research.store.tsx
src/utils/getUserCountry.test.ts
src/utils/getUserCountry.ts

PR Checklist
PR Type
add country flag to research username
Closes #1406
https://user-images.githubusercontent.com/42969746/160299344-8fc08324-3f92-43af-b598-2640f8073841.png
---

feat: add country flag to research username

---

src/pages/Research/Content/ResearchComments/ResearchComments.tsx

…sers
PR Checklist
PR Type
Add CTA to log in to Research Comments section for logged-out users
Closes #1591

feat: add cta to log in to research comments section for logged-out

---

.circleci/config.yml
CONTRIBUTING.md
src/pages/User/content/MemberProfile.tsx
src/pages/User/content/SpaceProfile.tsx
src/pages/common/Header/Menu/Profile/Profile.tsx

PR Checklist
PR Type
Add a new step to the CI pipeline which verifies that there are no code formatting or issues. The aim of this change is to remove a round of maintainer feedback from PR review cycles and instead defer to automated tooling to flag these issues.

chore(ci): lint code style and formatting

---

packages/components/README.md
packages/components/package.json

PR Checklist
PR Type
Introduces documentation for the new components package.
For the reviewer, does this documentation help you understand:
1. Why we have this package?
2. What is in this package?
3. How to get started with the library

docs: introduces overview of Components package

---

src/pages/Research/Content/ResearchArticle.tsx
src/pages/Research/Content/ResearchDescription.tsx
src/stores/Howto/howto.store.tsx
src/stores/Research/research.store.tsx
src/utils/getUserCountry.test.ts
src/utils/getUserCountry.ts

PR Checklist
PR Type
Run code formatter to un-break build
Closes #
---

chore: format code

---

functions/src/aggregations/common.aggregations.ts
functions/src/aggregations/user.aggregations.ts
functions/src/models.ts
functions/src/stats/index.ts
functions/src/stats/migration.ts
src/models/index.ts
src/models/research.models.tsx
src/models/user.models.tsx
src/pages/Research/Content/ResearchArticle.tsx
src/pages/Research/Content/ResearchDescription.tsx
src/pages/Research/Content/ResearchList.tsx
src/pages/Research/Content/ResearchUsefulStats.tsx
src/stores/Aggregations/aggregations.store.tsx
src/stores/Research/research.store.tsx
src/stores/User/user.store.ts

Co-authored-by: mmortar
PR Checklist
PR Type
Currently testing is quite tricky because it relies on aggregations that are not run on the preview site (side issue), and the local emulators still need work to properly link up different testing profiles (various draft prs open).
But see screenshots below as check that database is at least updating something (!). I've also wrapped in a `beta-tester` flag to make it easier to test once deployed to staging site and production
Rebase of  #1432 to fix linting
Closes #1405
---
If the PR is working as intended it'll be merged and included in the next platform release, if not changes will be requested and …

feat: add useful button to research module

---

packages/cypress/src/integration/howto/read.spec.ts
packages/cypress/src/integration/notificationBanner.spec.ts
src/components/NotificationBanner/NotificationBanner.tsx
src/pages/Research/Content/ResearchArticle.tsx
src/pages/Research/Content/ResearchDescription.tsx
src/pages/User/content/MemberProfile.tsx
src/pages/User/content/SpaceProfile.tsx
src/pages/common/Header/Menu/Profile/Profile.tsx
src/pages/index.tsx
src/stores/Howto/howto.store.tsx
src/stores/Research/research.store.tsx
src/utils/getUserCountry.test.ts
src/utils/getUserCountry.ts

PR Checklist
PR Type
add banner for users with incomplete profile
Closes #1588

feat: add banner for users with incomplete profile

---

src/components/Badge/Badge.tsx

PR Checklist
- [ x ] - Commit [messages are descriptive](https://github.com/ONEARMY/community-platform/blob/master/CONTRIBUTING.md#--commit-style-guide), it will be used in our [Release Notes](https://github.com/ONEARMY/community-platform/releases/)
- [ x ] - Latest `master` branch merged
PR Type
- [ x ] Bug fix (non-breaking change which fixes an issue)
The badge on the profile now changes with the theme. 
Closes #1571

fix: change member icon PK instance

---

.github/workflows/docs-deploy.yml
packages/documentation/.gitignore
packages/documentation/package.json
packages/documentation/sidebars.js
yarn.lock

PR Checklist
PR Type
Update docs deployment workflow to also build component storybook and embed as a static asset (with external link provided)
Closes #
Tested locally with manual file copy, not tested with github actions
https://user-images.githubusercontent.com/10515065/165565162-e6f5f3cd-53f2-4a71-8923-01afb85c47c4.mp4
---

feat: add component storybook to docs

---

packages/documentation/yarn.lock

PR Checklist
PR Type
Update yarn lock to try fix broken docs install command
Closes #
---

chore: update yarn lock

---

.circleci/config.yml

chore(ci): only deploy fixing fashion from master

---

packages/documentation/docs/Backend Development/firebase-emulators-docker.md
packages/documentation/docs/Backend Development/firebase-emulators.md

PR Checklist
PR Type
Some of the doc links point to other places in the repo, which doesn't work when viewing docs online. So those links have been changed to point to the files on github instead
Closes #
---

chore: fix doc links

---

package.json
src/components/CommentList/CommentList.tsx
src/components/GoogleAnalytics/index.tsx
src/pages/Howto/Content/Howto/HowToComments/HowToComments.tsx
src/pages/Research/Content/ResearchComments/ResearchComments.tsx
yarn.lock

PR Checklist
PR Type
Update react-ga package which handles google analytics to add support for GA v4
Closes #
Testing with an external v4 tag and all looks to be working as expected

chore: update react-ga to v4

---

package.json
yarn.lock

PR Checklist
PR Type
Minor dev fix to pin 3rd party @svgr/webpack to v5 as required for platform build (accidentally getting hoisted as v6)
Closes #
---

chore: fix dep resolution

---

src/components/Comment/Comment.tsx
src/components/Comment/CommentTextArea.tsx
src/components/Comment/constants.ts
src/stores/Howto/howto.store.tsx
src/stores/Research/research.store.tsx

PR Checklist
PR Type
Increase character limit in Research and Howtos comment
Closes #1626

feat: increase character limit comment

---

packages/components/README.md
packages/components/scripts/new-component.ts
packages/components/scripts/templates/{componentName}.stories.mdx.mst

PR Checklist
PR Type
Fixes minor issue when adding template via generator
- `react template literals are accidentally escaped because  mustache still interprets a triple curly brace `{{{componentName}}}` syntax, so added a space
- No case restriction is applied to componentName but react throws errors if not pascal case
I also added a note to readme for recommended vscode extension as it took me ages to realise the `mdx` had issues in without the markup
Closes #
---
If the PR is working as intended it'll be merged and included in the next platform release, if not changes will be …

fix: component template

---

packages/components/.storybook/main.js
packages/components/package.json
packages/components/src/__mocks__/AuthWrapper.mock.tsx
src/components/Comment/Comment.stories.mdx
src/components/Comment/Comment.tsx
src/components/Comment/CommentHeader.tsx
src/models/howto.models.tsx
src/pages/Howto/Content/Howto/Howto.tsx
src/pages/Research/Content/ResearchArticle.tsx
src/pages/Research/Content/ResearchUpdate.tsx
src/stores/Howto/howto.store.tsx
src/stores/Research/research.store.tsx
yarn.lock

PR Checklist
PR Type
People are sharing useful links in our comments but at the moment it's hard to interact with them because they are plain text. This means you have to manually copy and paste before you can view them. 
Example from: https://community.projectkamp.com/research/can-we-drink-the-water-from-the-land
This PR wraps all user generated comments in the [Linkify](https://www.npmjs.com/package/react-linkify) react component which we use elsewhere within the Platform. This means that things which look like links will become links! 
**Before:**
**After:**
Additionally this PR refactors the way that Comments data is passed through the components so that we can reduce the amount of external state that these components know about.

feat: support links in Comment content

---

package.json

chore: align colours and namespaces when using concurrently

---

.circleci/config.yml

chore: only release on master

---

src/components/Typography.tsx

PR Checklist
PR Type
This component is empty and does nothing. It should be removed.

chore: drop empty component

---

.github/workflows/docs-deploy.yml

PR Checklist
PR Type
Redeploy documentation after changes have been made to documentation **or** components package.

chore: expand job trigger to include components

---

CONTRIBUTING.md
packages/documentation/docs/Getting Started/setup.md

docs: make yarn v3 requirement explicit

---

src/models/maps.models.tsx
src/models/user_pp.models.tsx
src/modules/profile/index.ts

fix: use relative imports to ensure loading outside of root tsconfig.json

---

README.md

chore: remove contributors from spell check

---

packages/components/src/Icon/ExternalUrl.tsx
packages/components/src/Icon/Icon.tsx
packages/components/src/Icon/types.ts
packages/cypress/src/integration/howto/write.spec.ts
src/models/howto.models.tsx
src/pages/Howto/Content/Common/Howto.form.tsx
src/pages/Howto/Content/Howto/HowtoDescription/HowtoDescription.tsx
src/pages/Howto/DownloadExternal/DownloadExternal.tsx
src/stores/Howto/howto.store.tsx
src/utils/validators.ts

PR Checklist
PR Type
This PR adds an option for how-to writer to include a link, for example to Dropbox, where they can put additional files.
Closes [#1609](https://github.com/ONEARMY/community-platform/issues/1609)
https://user-images.githubusercontent.com/35103888/168448833-a34f20d1-1e07-4474-b6cf-3f11f4337968.mp4

feat: howto file download link

---

packages/components/src/Icon/ExternalUrl.tsx
packages/components/src/Icon/Icon.tsx
packages/components/src/Icon/types.ts
packages/cypress/src/integration/howto/write.spec.ts
src/models/howto.models.tsx
src/pages/Howto/Content/Common/Howto.form.tsx
src/pages/Howto/Content/Howto/HowtoDescription/HowtoDescription.tsx
src/pages/Howto/DownloadExternal/DownloadExternal.tsx
src/stores/Howto/howto.store.tsx
src/utils/validators.ts

PR Checklist
PR Type
Closes #
---

chore: lift changes into new branch

---

.github/pull_request_template.md

PR Checklist
PR Type
We now enforce branches being update to date in GitHub, this checkbox now duplicates prompts provided by the GitHub product.

docs: remove unnecessary checkbox

---

src/pages/Events/Content/EventsCreate/EventsCreate.tsx

PR Checklist
PR Type
Fixes squashed layout. Closes https://github.com/ONEARMY/community-platform/issues/1656
Reference:  https://github.com/ONEARMY/community-platform/pull/1658

fix: create event page layout

---

packages/cypress/src/integration/events.spec.ts

PR Checklist
PR Type
Adress brittle test case which featured hardcoded date value

test: create new event 2 days from now

---

src/themes/fixing-fashion/styles.ts
src/themes/types.tsx

PR Checklist
PR Type
Correctly declares form styles for Fixing Fashion

fix: form style declaration

---

src/themes/fixing-fashion/index.ts

PR Checklist
PR Type
Note, there is a duplicate header component which is coming from the [Fixing Fashion Academy repo](github.com/onearmy/fixing-fashion-academy), this will need to be removed as part of the migration to the Platform.
Closes https://github.com/ONEARMY/community-platform/issues/1732

fix: load academy content for Fixing Fashion

---

src/pages/Settings/content/formSections/Focus.section.tsx
src/themes/fixing-fashion/styles.ts
src/themes/types.tsx

PR Checklist
PR Type
Sets up types which match the expectations of the application code.

chore: introduce stricter types around badge definition

---

packages/components/src/MemberBadge/MemberBadge.stories.tsx
packages/components/src/MemberBadge/MemberBadge.tsx
src/pages/Maps/Content/Controls/GroupingFilterDesktop.tsx
src/stores/Maps/maps.groupings.ts
src/themes/fixing-fashion/styles.ts

Closes https://github.com/ONEARMY/community-platform/issues/1731
PR Checklist
PR Type
Closes #1731

fix: add support for ff member types on map

---

.circleci/config.yml

PR Checklist
PR Type
Closes #
---

chore(ci): notify slack around deployments

---

src/pages/Maps/Content/Controls/Controls.tsx
src/pages/Maps/Content/Controls/GroupingFilterDesktop.tsx
src/pages/Maps/Content/Controls/GroupingFilterMobile.tsx
src/pages/Maps/Content/Controls/transformAvailableFiltersToGroups.tsx
src/pages/Maps/Content/index.ts
src/pages/Maps/Maps.tsx
src/stores/Maps/filter.test.ts
src/stores/Maps/filter.ts
src/stores/Maps/maps.store.ts

PR Checklist
PR Type
Closes #1197

feat: add verified option to map dropdown

---

packages/documentation/docs/Backend Development/integrations.md

PR Checklist
PR Type
Adds more information about how to work with the firebase environment configuration

docs: provide concrete examples of using firebase config

---

src/pages/Research/Content/ResearchUpdate.tsx

PR Checklist
PR Type
Fixing Edit button position in ResearchUpdate component.
Closes #1776
Fixed button

fix: fix research update edit button position

---

.circleci/config.yml

PR Checklist
PR Type
Enable notifications to slack for dev deployments
Closes #
---

chore: add slack notifications for dev deployments

---

src/pages/common/Header/Header.tsx

PR Checklist
PR Type
Release the Notifications feature to all members of the Platform. 
Notifications is a helpful capability which lets a member know if someone has marked a post they authored as useful or commented on a Research or How-to article.

feat: activity notifications available to all users

---

src/pages/common/Header/Header.tsx

fix: split is logged in check from is User module available

---

README.md

PR Checklist
PR Type
Corrects heading for Contributors section and links through to the https://allcontributors.org/ tool we're using.

docs: change from core team to contributors heading

---

packages/documentation/docs/Install.md

PR Checklist
PR Type
Closes #
---

docs: adds detail around support module configuration

---

functions/src/seo/sitemap/sitemapGenerate.ts

PR Checklist
PR Type
Closes #
---

fix: seo sitemap how-to typo

---

src/models/research.models.tsx
src/pages/Research/Content/ResearchArticle.tsx
src/stores/Research/research.store.tsx

PR Checklist
PR Type
Add SEO tags for research article. Uses title and description from main research item, and then attempts to retrieve whatever is the first image of the most recent update as the shared image
Closes #
Seo previews won't work until after deploy, however this is how they should look, e.g.
https://onearmy-next--pr1827-feat-research-seo-n8wtg1ad.web.app/research/test-notifications-comments-again
Metadata (copied into metatags.io)
Metadata (generated on site)
---
If you need more …

feat: add seo tags for research items

---

functions/src/seo/index.ts

PR Checklist
PR Type
Closes #
---

chore(functions): add additional logging to inspect config

---

functions/src/seo/index.ts

PR Checklist
PR Type
Closes #
---

fix: lint format seorender function

---

.circleci/config.yml

PR Checklist
PR Type
Revert changes made in #1819 as the issue should now be fixed in the latest firebase tools
(expect global install to install `11.2.1`)
Closes #
---

chore: revert downgrade of ci firebase-tools

---

packages/documentation/docs/Install.md

PR Checklist
PR Type
Add small update to install docs to mention some permissions issues. 
Note - keeping the docs fully up-to-date with the permissions required is a bit cumbersome as firebase makes changes reasonably frequently and depends on a lot of other factors such as functions being deployed and whether CI environment or not. So for now just adding some broad notes.
Closes #
---
If you need more immediate feedback you can …

docs: update troubleshooting permissions

---

src/pages/User/content/UserStats.tsx

PR Checklist
PR Type
Forces location icon to black rather than the inherited blue.
Closes #1845

fix: location icon color fix

---

src/pages/common/Header/Menu/MenuMobile/MenuMobilePanel.tsx

PR Checklist
PR Type
Removes bazar and global site links from mobile menu.
Closes #1848 
---

fix: removed external links from mobile menu.

---

src/pages/SignUp/SignUpMessage.tsx

Closes #1867
PR Checklist
PR Type
Changed Button "Home" to "Complete your profile" and updated Link to  "/settings"
Closes #1867 
---

fix: change button on sign up message page

---

src/pages/Settings/content/formSections/Fields/Link.field.tsx

PR Checklist
PR Type
Fixes contacts & links layout on mobile.
Closes #1842 
https://user-images.githubusercontent.com/17976252/183895091-c80d0660-c791-4ef2-a6fa-4ffda197fc87.mov
---

fix: contacts & links layout

---

src/pages/Settings/content/ProfileDelete.tsx

PR Checklist
PR Type
Removes unnecessary brackets from Account Settings
Closes #1843
Not required
---

fix: removed brackets

---

src/pages/SignIn/SignIn.tsx

PR Checklist
PR Type
Move the reset email message below sign-up and reset links for a better UI experience
Closes #1840
---

fix: fix alignment of reset email sent message

---

src/pages/SignUp/SignUp.tsx

PR Checklist
PR Type
Fix alignment of the terms and privacy consent checkbox and label and makes the label clickable.
Closes #1877
---

fix: fix alignment of sign-up checkbox

---

src/pages/Settings/content/formSections/Fields/CustomRadio.field.tsx
src/pages/Settings/content/formSections/Focus.section.tsx

PR Checklist
PR Type
Activity grid within settings.
Closes #1841 
https://user-images.githubusercontent.com/17976252/184071371-8e1b1ad2-c2c2-45b5-b469-bacd5b451c09.mp4
---

fix: activity grid within settings

---

src/pages/Settings/SettingsPage.tsx

PR Checklist
PR Type
Fixes "settings" height for mobile devices.
Closes #1844 
https://user-images.githubusercontent.com/17976252/184066472-5b423e87-f7b8-4827-bb12-46758507cf2d.mov
---

fix: settings height for mobile devices

---

src/components/StyledLinkify/StyledLinkify.tsx
src/pages/Howto/Content/Howto/HowtoDescription/HowtoDescription.tsx
src/pages/Howto/Content/Howto/Step/Step.tsx
src/pages/Research/Content/ResearchDescription.tsx
src/pages/Research/Content/ResearchUpdate.tsx

PR Checklist
PR Type
Link styles for research & how-to articles.
Closes #1846 
---

Fixes link styles for research and how-to articles

---

src/pages/common/Header/Menu/ProfileModal/ProfileModal.tsx

PR Checklist
PR Type
Fixes menu items' active states within the user menu.
Closes #1897 #1898
---

fix: user menu items

---

packages/components/.storybook/main.js
packages/components/.storybook/manager.js
packages/components/.storybook/preview.js
packages/components/README.md
packages/components/package.json
packages/components/scripts/templates/{componentName}.stories.tsx.mst
packages/components/src/Button/Button.stories.tsx
packages/components/src/CommentItem/CommentItem.stories.tsx
packages/components/src/CommentList/CommentList.stories.tsx
packages/components/src/CreateComment/CreateComment.stories.tsx
packages/components/src/EditComment/EditComment.stories.tsx
packages/components/src/ElWithBeforeIcon/ElWithBeforeIcon.stories.tsx
packages/components/src/ExternalLink/ExternalLink.stories.tsx
packages/components/src/FieldDatepicker/FieldDatepicker.stories.tsx
packages/components/src/FieldInput/FieldInput.stories.tsx
packages/components/src/FieldTextarea/FieldTextarea.stories.tsx
packages/components/src/Heading/Heading.stories.tsx
packages/components/src/ImageGallery/ImageGallery.stories.tsx
packages/components/src/Input/Input.stories.tsx
packages/components/src/Loader/Loader.stories.tsx
packages/components/src/MemberBadge/MemberBadge.stories.tsx
packages/components/src/Modal/Modal.stories.tsx
packages/components/src/ModerationStatus/ModerationStatus.stories.tsx
packages/components/src/MoreContainer/MoreContainer.stories.tsx
packages/components/src/NotificationItem/NotificationItem.stories.tsx
packages/components/src/NotificationList/NotificationList.stories.tsx
packages/components/src/SiteFooter/SiteFooter.stories.tsx
packages/components/src/Textarea/Textarea.stories.tsx
packages/components/src/stories.mdx

PR Checklist
PR Type
Closes #
---

fix: storybook improve documentation

---

packages/components/src/Alert/Alert.stories.tsx

docs: add documentation for the Alert component

---

src/themes/fixing-fashion/styles.ts
src/themes/precious-plastic/styles.ts
src/themes/project-kamp/styles.ts

PR Checklist
PR Type
Closes #
---

fix: alert padding horizontal

---

.circleci/config.yml

PR Checklist
PR Type
Closes #
---

chore(ci): update labels to reflect new domains

---

functions/src/models.ts
functions/src/userUpdates/index.ts

PR Checklist
PR Type
[My last PR](https://github.com/ONEARMY/community-platform/pull/1865) only included the fixed functionality for updating user info in howto's, but ignored research modules. This PR adds functionality to update user data in researches whenever it changes.
Also, answering to @thisislawatts' [comment](https://github.com/ONEARMY/community-platform/pull/1865#issuecomment-1208545824) in the last PR, currently I am testing manually as I'm not sure how to write tests for the backend Firebase functions. Do we have any test for those yet? Indeed that some automation would be very welcome for testing this behaviour.
Closes #1469 (already closed but this part was missing)

feat(functions): updating user info in research post & comments

---

packages/components/src/CommentItem/CommentItem.tsx

PR Checklist
PR Type
Fixes ability to edit comments in how-to and research
Closes #1864
---

fix: edit comments

---

src/pages/common/UploadedFile/FirebaseFileUploader.tsx
src/pages/common/UploadedFile/UploadedFile.tsx

PR Checklist
PR Type
Closes #
---

chore: move FirebaseFileUploader relative to reference

---

src/pages/Howto/Content/Common/Howto.form.tsx
src/pages/Research/Content/Common/Research.form.tsx
src/pages/Research/Content/Common/Update.form.tsx
src/pages/Settings/SettingsPage.tsx

PR Checklist
PR Type
Closes #
---

fix: switch to sticky

---

packages/components/src/FileInformation/FileInformation.tsx

PR Checklist
PR Type
Fixes download button margin.
Closes #1916
---

fix: download button margin

---

src/common/ErrorBoundary.tsx

PR Checklist
PR Type
Currently the error handling system is quite basic, on all errors a plain white page is shown with a link to track errors to sentry. This PR restricts the error handling to only trigger logging on production site, and removes the blank white page show
- Decide what would be better to show than blank page. Nothing? (just leave errors in background and assume fine for user to continue? A small popup that lets the user know an error was caught and automatically recorded?)
Closes #
---
If the PR is working as intended it'll be merged and included in the next …

refactor: limit error handler

---

packages/components/src/FileInformation/FileInformation.tsx

PR Checklist
PR Type
Fix: correct text colour on download button.
https://github.com/ONEARMY/community-platform/issues/1937

fix: correct text colour on download button

---

src/components/Form/ImageInput.field.tsx
src/pages/Settings/content/formSections/UserInfos.section.tsx

PR Checklist
PR Type
Fixes the wrapping of the error message
https://github.com/ONEARMY/community-platform/issues/1940
_

fix: error message profile-image upload nowrap

---

src/pages/Research/Content/ResearchList.tsx
src/pages/Research/Content/ResearchListItem.tsx

PR Checklist
PR Type
Closes #1972
---

fix: replace zero with dash on research listing

---

src/pages/User/content/index.tsx

PR Checklist
PR Type
A 'Workspace' type should also show the 'SpaceProfile'. 
https://github.com/ONEARMY/community-platform/issues/1506

fix: member type shows member profile

---

.circleci/config.yml

PR Checklist
PR Type
Closes #
---

chore(ci): remove use of token for Firebase CLI authentication

---

packages/cypress/src/integration/profile.spec.ts
shared/mocks/data/users.ts
src/pages/User/content/SpaceProfile.tsx

PR Checklist
PR Type
Test to make sure that a user with a (work)space profile gets the SpaceProfile shown;
https://github.com/ONEARMY/community-platform/issues/1506

feat: test profile type

---

packages/documentation/docs/Contributing/maintainer.md

PR Checklist
PR Type
Adds documentation aiming to list the various things that should be checked as part of a maintainer offboarding from the project.

docs: add maintainer offboarding checklist

---

packages/components/src/LinkifyText/LinkifyText.stories.tsx
src/stores/Research/research.store.tsx
src/stores/common/mentions/index.test.ts
src/stores/common/mentions/index.ts

PR Checklist
PR Type
Fixes a missing edge case in how we convert userRefence to an `@mention`
Closes #1980

fix: support more username variants

---

.github/workflows/docker-emulator-build.yml
functions/package.json
yarn.lock

PR Checklist
PR Type
Fix deployment fails due to firebase not detecting any functions
https://app.circleci.com/pipelines/github/ONEARMY/community-platform/3269/workflows/5031aa88-d95b-4c9e-9c7d-77a26c18566c/jobs/20426
Downgrades firebase-functions pending fix from firebase
`https://github.com/firebase/firebase-functions/issues/1277`
Closes #
---
If you need more immediate feedback you can try reaching out on Discord in the …

fix: pin firebase-functions to older version

---

src/pages/Howto/Content/HowtoList/HowToCard.tsx
src/pages/Howto/Content/HowtoList/HowtoList.tsx
src/pages/Howto/VirtualizedFlex/VirtualizedFlex.tsx

PR Checklist
PR Type
Fixes how-to grid.
Closes #1850 
---

fix: how-to virtualized grid

---

src/constants.ts

PR Checklist
PR Type
Increase the character limit on comments to 3000.
Closes #2012

feat: increase character limit comments

---

package.json
yarn.lock

chore(deps): remove unused use-debounce

---

src/stores/common/mentions/index.ts

PR Checklist
PR Type
Fixes issue mentioned in #2021 where user profile with underscores in names won't show correctly in mentions
This is due to a minor typo in the regex used to replace names.
Note - this only affects users who both exist and have underscores in the auth id, which is very few. Tested on docker emulators with `demo_beta_tester` user
Closes #
**Fixed user mention**
--- …

fix: mention names with underscores

---

src/pages/Settings/content/formSections/WorkspaceMapPin.section.tsx

PR Checklist
PR Type
* Switch from using adhoc styling to a standard `Alert` component. 
* Add vertical spacing between field labels, ie. _Your workspace location_ and the interactive input element. 
Closes #
---

fix: layout of workspace map pin

---

.circleci/config.yml

PR Checklist
PR Type
- Fix issue where circleci was creating different caches for different pipeline steps and failing to restore for certain scripts
- Add initial cache warmup action to test node_modules install and caching
Closes #
---

chore: circle-ci cache fix

---

.circleci/config.yml

PR Checklist
PR Type
- Fix ci firebase deploy script
Firebase not finding bin from local install (likely more issues with latest yarn update) so fix is to use bin from functions dir, should also speed up the ci a little bit
Closes #
---

fix: update deploy script

---

src/stores/common/mentions/index.test.ts

PR Checklist
PR Type
Adds test for fix #2024
> Fixes issue mentioned in #2021 where user profile with underscores in names won't show correctly in mentions
> This is due to a minor typo in the regex used to replace names.

test: adds test for underscore username edgecase

---

packages/documentation/yarn.lock

PR Checklist
PR Type
Update yarn lock for docs package
Closes #
---

chore: update docs yarn lock

---

src/pages/Maps/Content/Controls/Controls.tsx

PR Checklist
PR Type
Before:  
After:

fix: switch to secondary variant

---

.circleci/config.yml

PR Checklist
PR Type
Seeing intermittent failures owing to resource limits: 
https://app.circleci.com/pipelines/github/ONEARMY/community-platform/3704/workflows/1426e359-0ceb-47c2-8ff5-a5b1e7acc65a/jobs/23958/resources
I propose increasing the memory available in CI as a short term workaround for the problem. Ultimately there needs to be some steps taken to reduce the size/complexity of the application build process. There are a few PRs in flight investigating alternatives to the current build process. See https://github.com/ONEARMY/community-platform/pull/2031

chore(ci): increase memory resources

---

.eslintrc.json
packages/components/src/OsmGeocoding/OsmGeocodingResultsList.tsx

PR Checklist
PR Type
- chore: use theme-ui element to add support for sx prop
- chore: adopt stricter linting check

chore: adopt stricter linting check

---

package.json
yarn.lock

PR Checklist
PR Type
Add `cross-env` to main package.json
Closes #
---

chore: add missing dep

---

package.json
src/pages/Research/research.routes.test.tsx
yarn.lock

PR Checklist
PR Type
CI pipeline failing for unrelated code updates ([example](https://app.circleci.com/pipelines/github/ONEARMY/community-platform/3789/workflows/b43f6ae9-6d04-40ba-a93a-dbad97ab1381/jobs/24793)), using this branch to debug and troubleshoot 
Closes #
--- …

fix: ci pipelines

---

packages/documentation/docs/Docs Contribution/md-style-guide.md

PR Checklist
PR Type
Rebase of #2069
Closes #2069
---

docs: update md guide

---

src/pages/Howto/Content/Howto/HowtoDescription/HowtoDescription.tsx
src/stores/Howto/howto.store.tsx
src/stores/Research/research.store.tsx

PR Checklist
PR Type
Adds missing await that could be causing incrementation to not work properly.

fix: added missing await in dbref set

---

packages/components/src/ViewsCounter/ViewsCounter.stories.tsx
packages/components/src/ViewsCounter/ViewsCounter.tsx

PR Checklist
PR Type
Adds example of ViewsCounter to Storybook
Also refactored component to remove useTheme
Any properties within the `sx` prop
automatically have access to values from
the Theme definition.
Read more:
https://theme-ui.com/sx-prop

chore: document views counter

---

packages/components/src/Username/Username.tsx
src/pages/Howto/Content/Howto/Howto.test.tsx
src/pages/Howto/Content/Howto/HowtoDescription/HowtoDescription.tsx

PR Checklist
PR Type
Adds back the verified badge when viewing a Howto Article.
Before:  
After:  
Closes #2107

fix: adds verified badge to username #2107

---

src/pages/index.tsx

PR Checklist
PR Type
Replaced the expired Discord invite link with new link in Join Our Chat.
Closes #2109
---

fix: changed discord link in join our chat

---

src/pages/Howto/Content/Howto/Howto.test.tsx
src/pages/Howto/Howto.test.tsx

PR Checklist
PR Type
- chore: remove useless comments, an artefact of sketching out tests following [Arrange, Act & Assert pattern](https://automationpanda.com/2020/07/07/arrange-act-assert-a-pattern-for-writing-good-tests/)
- chore: remove empty beforeAll
- test: remove empty test suite

chore: remove useless comments

---

src/pages/Howto/Content/Howto/Howto.test.tsx
src/pages/Howto/Content/Howto/HowtoDescription/HowtoDescription.tsx

PR Checklist
PR Type
Use the correct pluralisation for when displaying the number of steps. 
The Problem:

fix: correct plural of step(s)

---

src/pages/Howto/Content/EditHowto/EditHowto.tsx
src/pages/Howto/Content/Howto/Howto.test.tsx
src/pages/Howto/Content/Howto/Howto.tsx
src/stores/Howto/howto.store.test.ts
src/stores/Howto/howto.store.tsx

PR Checklist
PR Type
Closes #2123

fix: empty active howto when unloading component

---

src/pages/Research/Content/ResearchArticle.tsx

PR Checklist
PR Type
Updates the analytics event so that the action changes depending on whether the Useful vote is being added or removed.

fix: correct action for removing useful mark

---

README.md
packages/documentation/docs/Contributing/bounties.md
packages/documentation/docs/Contributing/start-contributing.md
packages/documentation/docs/Design/our-design-system.md
packages/documentation/docusaurus.config.gh-pages.js
packages/documentation/docusaurus.config.js
src/constants.ts
src/pages/Settings/content/PostingGuidelines.tsx

PR Checklist
PR Type
- docs: update discord link to be consistent
- docs: remove mention of defunct monthly dev call

docs: update discord link

---

packages/components/assets/icons/supporter.svg
packages/components/src/Icon/Icon.stories.tsx
packages/components/src/Icon/Icon.tsx
packages/components/src/Icon/svgs.tsx
packages/components/src/Icon/types.ts
src/common/AlertIncompleteProfile.tsx
src/models/user.models.tsx
src/pages/User/content/MemberProfile.tsx
src/pages/User/content/UserStats.tsx

PR Checklist
PR Type
- docs: adds story showcasing all available icons
- feat: adds supporter badge to space and member profile
To review this locally you will need to set `badges.supporter` to true on your user document. 
Closes #2130

feat: adds supporter badge

---

src/pages/Settings/content/formSections/Collection.section.tsx
src/pages/Settings/content/formSections/Fields/CustomCheckbox.field.tsx
src/pages/Settings/content/formSections/Fields/CustomRadio.field.tsx
src/pages/Settings/content/formSections/Fields/OpeningHoursPicker.field.tsx

PR Checklist
PR Type
* _Plastic types accepted_ sits underneath add opening day button
* Adds green border and off white background for selected item
**Before:**
With plastic type selected
---
**After:**
With plastic type selected

fix: styling problems plastic collection Settings section

---

src/modules/admin/pages/adminUsers.tsx
src/pages/Settings/SettingsPage.tsx
src/pages/Settings/UserBadgeSettings.tsx
src/pages/Settings/UserSettings.test.tsx
src/pages/Settings/UserSettings.tsx
src/pages/Settings/index.tsx
src/pages/User/User.tsx
src/stores/User/user.store.ts

PR Checklist
PR Type
- chore: refactor to introduce UserSettings page
- feat: adds admin panel to edit user badges
Outstanding:
Closes #2131
Following screenshot using the standard `red2` colour token.

feat: admin edit user badges

---

packages/components/src/CommentList/CommentList.tsx
src/common/Analytics/GoogleAnalytics.tsx
src/common/Analytics/index.tsx
src/pages/Howto/Content/Howto/HowToComments/HowToComments.tsx
src/pages/Howto/Content/Howto/Howto.tsx
src/pages/Research/Content/ResearchArticle.tsx
src/pages/Research/Content/ResearchComments/ResearchComments.tsx
src/pages/index.tsx

PR Checklist
PR Type
Refactor analytics, introducing a single point where `react-ga4` is used. The intention here is to make it easier to manage upgrades going forwards and/or migration to an alternative tool. 
* Dropped `react-ga4` as a dependency in packages/components instead using a passed in property.

chore: refactor analytics

---

src/pages/common/DevSiteHeader/DevSiteHeader.tsx

https://eslint.org/docs/latest/rules/no-async-promise-executor
PR Checklist
PR Type
Closes #
---

chore: refactor no async promise executor

---

packages/components/src/CreateComment/CreateComment.tsx
src/pages/Howto/Content/EditHowto/EditHowto.tsx
src/pages/User/content/UserContactAndLinks.tsx

PR Checklist
PR Type
Closes #
---

chore: refactor no-extra-boolean-cast

---

src/stores/User/user.store.ts

> A catch clause that only rethrows the original error is redundant, and has no effect on the runtime behavior of the program. These redundant clauses can be a source of confusion and code bloat, so it’s better to disallow these unnecessary catch clauses.
https://eslint.org/docs/latest/rules/no-useless-catch
PR Checklist
PR Type
Closes #
---
If you need more immediate feedback you can try reaching out on …

chore: refactor no-useless-catch

---

packages/components/src/SiteFooter/SiteFooter.tsx
src/stores/common/mentions/index.ts

PR Checklist
PR Type
Closes #
---

chore: refactor to remove or ignore irregular white space

---

src/pages/admin/content/AdminTags.tsx

PR Checklist
PR Type
Add an autofocus property to input label in admin tag editor
Closes #2017
---

fix (#2017): AdminTag label loosing focus on every input change

---

.github/workflows/docs-deploy.yml

PR Checklist
PR Type
Update docs deploy github action for changes made in #2155
Example failed deployment [action](https://github.com/ONEARMY/community-platform/actions/runs/4532062976/jobs/7982979915)
Tested fix by deploying from this branch as part of [github action](https://github.com/ONEARMY/community-platform/actions/runs/4532115780/jobs/7983098756?pr=2177)
Closes #
---
If you need more immediate feedback you can try reaching …

fix: docs deploy

---

packages/documentation/docs/Frontend Development/overview.md

PR Checklist
PR Type
Location of themes was moved recently, docs related to theming used the old location.
Closes #2185
---

docs: update themes location

---

functions/src/emulator/seed/content-generate.ts
packages/components/src/NotificationItem/NotificationItem.tsx
packages/components/src/NotificationList/NotificationList.stories.tsx
src/models/research.models.tsx
src/models/user.models.tsx
src/pages/Research/Content/ResearchArticle.tsx
src/pages/Research/Content/ResearchDescription.tsx
src/pages/common/Header/getFormattedNotifications.tsx
src/stores/Research/research.store.test.ts
src/stores/Research/research.store.tsx

PR Checklist
PR Type
- feat(components): add support for research_update notification
- feat: follow research article
Outstanding;
Closes #1438
Slight deviation from original designs to align with new Useful button styling.

feat: follow research articles for updates #1438

---

packages/components/.storybook/preview.js
packages/components/package.json
yarn.lock

PR Checklist
PR Type
Restores theming that was broken by #2155 
Before: Theme styling and fonts are not loading. 
After:

docs(components): fix theming in storybook

---

packages/components/src/CommentItem/CommentItem.tsx
packages/components/src/CreateComment/CreateComment.tsx
packages/components/src/MapWithDraggablePin/MapWithDraggablePin.tsx
packages/components/src/OsmGeocoding/OsmGeocoding.tsx
packages/components/src/OsmGeocoding/OsmGeocodingResultsList.tsx
packages/components/src/OsmGeocoding/types.tsx
src/pages/common/Header/Menu/MenuMobile/MenuMobilePanel.tsx
src/pages/common/Header/Menu/Notifications/NotificationsMobile.tsx
src/pages/common/Header/Menu/Profile/Profile.tsx

PR Checklist
PR Type
Using `npx madge --circular --extensions ts,tsx ./` to highlight the circular dependencies. Whilst these are allowed within nodejs they make the code harder to reason with.
This PR addresses the accidental circular dependences, it will not change the Rootstore pattern which encourages circular dependencies.
- chore(components): refactor to remove circular deps
- chore(pages): refactor to resolve circular dep

chore: refactor to remove circular deps

---

packages/components/scripts/templates/{componentName}.tsx.mst

PR Checklist
PR Type
Update the template used by `yarn new-component AnExample`

chore: include component name in prop

---

src/pages/SignUp/ResendSignUpMessage.tsx
src/pages/SignUp/SignUp.tsx
src/pages/SignUp/SignUpMessage.tsx

PR Checklist
PR Type
The intent here is to remove direct use of theming from the SPA and instead use [theme aware components](https://theme-ui.com/theme-spec).

chore: Signup remove direct usage of theming

---

packages/cypress/src/integration/events.spec.ts

PR Checklist
PR Type
This test case is consistently failing in the CI environment but working when run locally or manually stepping through the same actions.

test: skip test which fails consistently only in CI env

---

packages/components/scripts/newComponent.ts
packages/components/scripts/templates/{componentName}.test.tsx.mst

PR Checklist
PR Type
Adds a component test template which includes a failing test. The intention here is to nudge people in the direction of thinking about tests for their components.
---

chore: adds test template to components creation

---

packages/components/src/MapMemberCard/MapMemberCard.stories.tsx
packages/components/src/MapMemberCard/MapMemberCard.tsx
src/models/maps.models.tsx
src/pages/Maps/Content/View/Popup.tsx
src/stores/Maps/generatePins.tsx
src/stores/Maps/maps.store.ts

PR Checklist
PR Type
Lifts the single fix commit (5bd0016011d9bf72aca21849ffe3dfd45e156efd) from #2189 which was reverted due to flakey tests. Current hypothesis is that some of the refactoring PRs introduced test regression.
:sparkles: Fun with Git.
This PR was created by:
1. Turning the single fix commit into a patch, using `git format-patch -1 5bd0016011d9bf72aca21849ffe3dfd45e156efd`, this creates a new `*.patch` file.
2. Checking out a new branch from master and applying the patch using `git apply path-to.patch --verbose`
Replaces https://github.com/ONEARMY/community-platform/pull/2215

fix: pass flag through from User object

---

functions/src/emailNotifications/createEmail.spec.ts
functions/src/emailNotifications/createEmail.ts

PR Checklist
PR Type
noticed things weren't working as expected whilst testing... turns out the return was causing the function to terminate prematurely. switched to continue and added to the test to consider this case.
Closes #
---

fix: create email bug

---

packages/cypress/src/fixtures/searchResults.ts
packages/cypress/src/integration/events.spec.ts
packages/cypress/src/integration/notificationBanner.spec.ts
packages/cypress/src/integration/research/comments.spec.ts
packages/cypress/src/integration/settings.spec.ts
packages/cypress/src/support/CustomAssertations.ts
packages/cypress/src/support/commands.ts

PR Checklist
PR Type
Attempts to fix some of the unreliable tests
Closes #
---

fix: improve test reliability

---

.all-contributorsrc

PR Checklist
PR Type
As noticed in #2227 there is an issue as the bot skips ci in its commit messages but in doing so this breaks the ability to merge as CI is required.

fix: allcontributors doesnt skip ci

---

src/modules/admin/components/AdminSubheader.tsx

PR Checklist
PR Type
Fixes negative margin on right hand edge of admin banner so that it sits tight against the edge of the browser window. 
**Before:** 
**After:** 
---

fix: alignment of admin submenu

---

packages/components/src/UserStatistics/UserStatistics.test.tsx
packages/components/src/UserStatistics/UserStatistics.tsx

PR Checklist
PR Type
Do not show anything if there is not enough information to render the block.
Before:
After:

feat: empty user stats

---

.eslintrc.json
packages/components/src/CommentList/CommentList.tsx
packages/components/src/EditComment/EditComment.tsx
packages/components/src/ElWithBeforeIcon/ElWithBeforeIcon.tsx
packages/components/src/FileInformation/FileInformation.tsx
packages/components/src/Icon/DownloadIcon.tsx
packages/components/src/Icon/ExternalUrl.tsx
packages/components/src/UsefulStatsButton/UsefulStatsButton.tsx
src/modules/admin/components/Table/Table.tsx
src/modules/admin/pages/adminNotifications.tsx
src/modules/admin/pages/adminUsers.tsx
src/pages/Research/Content/ResearchListItem.tsx
src/pages/Research/Content/ResearchUpdate.tsx

PR Checklist
PR Type
Refactor of components to remove React.FC
Closes #2182 
---

refactor: remove React.FC from components

---

src/modules/admin/admin.storeV2.tsx

PR Checklist
PR Type
Removing commented out code in favour of using git. 
>… the main problem is commented code adds confusion with no real benefit. Just rely on your version control system to [keep track](https://youtu.be/dQw4w9WgXcQ) of the code that once was. Let it go.
https://kentcdodds.com/blog/please-dont-commit-commented-out-code

chore: remove commented out code admin store

---

functions/src/emailNotifications/createEmail.ts
functions/src/emailNotifications/pp-template.handlebars

PR Checklist
PR Type
you had suggested switching links based on environment, which i am still open to as a solution, but was having a hard time figuring out how to access env variables from the cloud function and wasn't sure it was worth passing in through the aggregated notifications...
anyway, here's an alternate solution. the templates are stored in the database, so we will have different templates for each environment + project anyway. we can hardcode the URLs as well at the top image and anything else (colors, etc) we might want to add in the future that may differ between projects. 
since this template is purely for version control, i put the prod URLs in, but i can change them to the dev URLs in the pp database (i haven't added templates for the other projects yet, not sure if …

fix(email-notifs): fix links in email template

---

src/pages/Research/Content/ResearchUpdate.tsx

PR Checklist
PR Type
Fixes wront variant having been assigned to research updates in #2260 
Closes #
---

fix: add correct variant

---

packages/documentation/docs/Deployment/circle-ci.md
src/models/common.models.tsx

PR Checklist
PR Type
Closes #
---

chore: remove mention of dropped algolia

---

functions/src/aggregations/userNotifications.aggregations.ts
functions/src/models.ts
shared/models/index.ts
shared/models/notifications.ts
src/models/user.models.tsx
src/pages/Settings/SettingsPage.tsx
src/pages/Settings/Template.tsx
src/pages/Settings/content/formSections/EmailNotifications.section.tsx

PR Checklist
PR Type
removing email notification settings from beta access only in advance of email notification release
also refactored to a functional component while i was in there
tested locally and confirmed that states persist and were being respected by pending email aggregation function
Closes #
--- …

feat(email-notifs): remove email setting from beta

---

functions/src/emailNotifications/createEmail.spec.ts
functions/src/emailNotifications/createEmail.ts
functions/src/emailNotifications/index.ts

PR Checklist
PR Type
adds scheduled functions for all email frequency intervals
updates create email function to accept an interval and apply it as a filter to pending emails
updates the test to account for frequency and other recent changes
Closes #
---
If you need more immediate feedback you can try reaching out on Discord in the [Community Platform `development` channel](https://discord.com/channels/586676777334865928/9387817270 …

feat(email-notifs): add weekly and monthly scheduled functions

---

codecov.yml

chore: do not include documentation in code coverage calc

---

packages/components/src/Username/Username.tsx
src/common/contributorData.ts
src/common/hooks/contributorsData.ts
src/common/hooks/userUsefulCount.ts
src/models/common.models.tsx
src/pages/Research/Content/ResearchArticle.test.tsx
src/pages/Research/Content/ResearchArticle.tsx
src/pages/Research/Content/ResearchUpdate.test.tsx
src/pages/Research/Content/ResearchUpdate.tsx
src/pages/User/content/MemberProfile.tsx
src/pages/User/content/SpaceProfile.tsx
src/test/factories/User.ts

PR Checklist
PR Type
Adds contributors flags to bottom of reseach article and to updates
Closes #2278

fix: add countryflag to research collaborators

---

src/pages/Research/Content/ResearchArticle.test.tsx
src/pages/Research/Content/ResearchArticle.tsx
src/pages/Research/Content/ResearchDescription.tsx

PR Checklist
PR Type
Removes authwrapper from follow / subscribe feature of research and adds event tracking for feature use.
Closes #2274 
---

feat: release research follow / subscribe feature

---

functions/src/emailNotifications/pk-template.handlebars

PR Checklist
PR Type
Adding a new template for project kamp emails (changed image src and links)
Closes #
tested on dev:
---

feat(emails): pk template

---

functions/src/index.ts
functions/src/scheduled/tasks.ts

PR Checklist
PR Type
Losing more than a days worth of data seems unacceptable
with increasing volumes of content being created on the platform.
We should aim to take more care of the data that folks spend
time adding to the site.

chore: switch backup to run daily

---

src/stores/User/user.store.ts

PR Checklist
PR Type
- Removes unused arguments
- Move from variable used once to inlined object

chore: refactor for readability

---

src/pages/Research/Content/ResearchUpdate.test.tsx
src/pages/Settings/UserSettings.test.tsx

PR Checklist
PR Type
Closes #
---

refactor: add getWrapper function to test files

---

src/pages/common/Header/getFormattedNotifications.tsx

PR Checklist
PR Type
Modified research update notification text 
from: [Eike ](https://community.projectkamp.com/u/eike)posted an update to their [research article](https://community.projectkamp.com/research/can-we-turn-invasive-trees-mimosa-into-something-useful)
to: [Eike ](https://community.projectkamp.com/u/eike)posted an update to this [research](https://community.projectkamp.com/research/can-we-turn-invasive-trees-mimosa-into-something-useful) you follow
Closes #2346
NA
If you need more …

feat(platform): modified research update notification text

---

src/pages/Howto/Content/Common/Howto.form.test.tsx
src/pages/Research/Content/ResearchArticle.test.tsx
src/pages/Research/Content/ResearchUpdate.test.tsx
src/pages/Research/research.routes.test.tsx
src/pages/Settings/UserSettings.test.tsx
src/test/utils/themeUtils.ts

PR Checklist
PR Type
Removes directly importing theme in test files and consolidates everything into a single themeUtils file that can be easily modified. 
Closes #
---

refactor: add theme util file for testing

---

CONTRIBUTING.md

PR Checklist
PR Type
* Remove links through to Slack
* Remove links through to legacy wiki
* Re-order document to move first contribution elements higher
* Add links through to new documentation
* Changed CTA for joining the team from individual email to Discord

docs: update contributor documentation

---

src/modules/admin/pages/adminNotifications.tsx

PR Checklist
PR Type
@davehakkens pointed out that it would be more helpful to have the user's name than an id in the admin notifications page
Closes #
---

feat(admin-notifications): use display name rather than id for testing

---

src/modules/admin/components/AdminSubheader.tsx

PR Checklist
PR Type
Fixes bug introduced through #2282

fix: admin v2 nav link

---

packages/components/src/Button/Button.tsx
src/pages/Research/Content/ResearchArticle.test.tsx

PR Checklist
PR Type
- chore: refactor to remove invalid html attribute
- test: remove check for colour
The test for a colour relied on an invalid HTML attribute
appearing on the document. The colour is probably better validated
within the component.

chore: refactor to remove invalid html attribute

---

codecov.yml

PR Checklist
PR Type
The configuration was being silently ignored
as it was not valid. Used the following command
to validate the change made.
```
curl -X POST --data-binary @codecov.yml https://codecov.io/validate
```
This should reduce the number of status failures by increasing the
threshold.

chore: configure codecov with threshold

---

src/pages/Research/Content/ResearchList.tsx

PR Checklist
PR Type
Closes #2291

chore: refactor to remove use of theme

---

packages/components/src/Button/Button.tsx
packages/components/src/ResearchEditorOverview/__snapshots__/ResearchEditorOverview.test.tsx.snap
packages/components/src/ViewsCounter/ViewsCounter.tsx

PR Checklist
PR Type
Fixes small button sizing and tweak to view counter component so that the height and positioning of the element matches buttons.
Closes #2369
---

2369 bug small button height has been increased

---

src/stores/databaseV2/clients/dexie.tsx

PR Checklist
PR Type
Introduces more logs around Dexie transactions for use locally with `REACT_APP_LOG_LEVEL=debug yarn start`

chore: add debug logs to Dexie

---

packages/cypress/src/integration/notifications.spec.ts
src/stores/User/notifications.store.test.tsx
src/stores/User/notifications.store.ts

PR Checklist
PR Type
- fix: persist using correct identifier
- chore: refactor to remove duplication

fix: persist using correct id

---

src/pages/Howto/Content/Howto/HowToComments/HowToComments.tsx
src/pages/Howto/Content/Howto/Howto.tsx
src/pages/Research/Content/ResearchArticle.tsx
src/stores/Howto/howto.store.test.ts
src/stores/Howto/howto.store.tsx
src/stores/Research/research.store.test.ts
src/stores/Research/research.store.tsx

PR Checklist
PR Type
Allows users with the admin role to edit and delete research and howto comments
Closes #2385
---

Feat: admin can delete and edit comments

---

src/pages/Howto/Content/Howto/HowtoDescription/HowtoDescription.tsx

PR Checklist
PR Type
Removes whitespace from right hand side of button.
**Before**
**After**

fix: use icon only variant

---

src/stores/User/user.store.ts

PR Checklist
PR Type
Update document based on its `_id` and not the `_authID`

fix: remove use of _authId

---

src/pages/common/Header/Header.tsx

PR Checklist
PR Type
[[refactor] Remove direct usage of Theme from "Header.tsx"](https://github.com/ONEARMY/community-platform/issues/2312)

refactor: remove direct usage of theme from header component

---

packages/documentation/docs/Contributing/start-contributing.md

PR Checklist
PR Type
Update outline of deployment steps

docs: update outline of deployment steps

---

functions/src/aggregations/common.aggregations.ts
functions/src/aggregations/research.aggregations.ts

PR Checklist
PR Type
Fixes collaborator useful aggregation for research
Closes #
---

fix: collaborator useful aggregation

---

functions/src/aggregations/common.aggregations.ts
src/stores/databaseV2/DocReference.tsx

PR Checklist
PR Type
- Implements a much more efficient aggregation seeding function for total user useful
- Adds additional logging for seed process
- Fixes an issue in the new db update process whereby the metadata was being overwritten on update
Closes #
--- …

refactor/fix: useful aggregation seed improvements & db update metadata overwrite

---

functions/src/aggregations/common.aggregations.ts
src/stores/databaseV2/DocReference.tsx

PR Checklist
PR Type
- Further fix to useful aggregation seed update
- Made doc metadata update property name more explicit
Closes #
---

fix: useful aggregation seed update entry generation
